name: knowledge-pdf-url
version: 0.1.0
description: Ingest a remote PDF into a knowledge base

models:
  - provider: groq
    model: openai/gpt-oss-120b
    api_key: "{{ .env.GROQ_API_KEY }}"
    default: true

embedders:
  - id: openai_default
    provider: openai
    model: text-embedding-3-small
    api_key: "{{ .env.OPENAI_API_KEY }}"
    config:
      dimension: 1536
      batch_size: 64

vector_dbs:
  - id: redis_vectors
    type: redis
    config:
      # dsn: "{{ .env.REDIS_URL }}"
      dimension: 1536
      max_top_k: 200

knowledge_bases:
  - id: pdf_demo
    ingest: on_start
    embedder: openai_default
    vector_db: redis_vectors
    sources:
      - type: url
        urls:
          - "https://arxiv.org/pdf/2312.10997"
    chunking:
      strategy: recursive_text_splitter
      size: 400
      overlap: 40
    retrieval:
      top_k: 5
      min_score: 0.15
      max_tokens: 1200

runtime:
  type: bun
  permissions:
    - --allow-read
    - --allow-net

workflows:
  - source: ./workflows/qa.yaml

autoload:
  enabled: true
  strict: true
  include:
    - "agents/*.yaml"
    - "workflows/*.yaml"
  exclude:
    - "**/*.tmp"
    - "**/*~"
