name: knowledge-pdf-url
version: 0.1.0
description: Ingest a remote PDF into a knowledge base

models:
  - provider: openai
    model: o3
    api_key: "{{ .env.OPENAI_API_KEY }}"
    default: true
    params:
      temperature: 1
      max_tokens: 100000

embedders:
  - id: openai_default
    provider: openai
    model: text-embedding-3-small
    api_key: "{{ .env.OPENAI_API_KEY }}"
    config:
      dimension: 1536
      batch_size: 64

vector_dbs:
  - id: pdf_demo_store
    type: filesystem
    config:
      dimension: 1536
  - id: pgvector_local
    type: pgvector
    config:
      # DSN is optional - if not provided, uses global postgres database config
      # dsn: "{{ .env.PGVECTOR_DSN }}"
      ensure_index: true
      table: knowledge_chunks
      metric: cosine
      dimension: 1536

knowledge_bases:
  - id: pdf_demo
    ingest: on_start
    embedder: openai_default
    vector_db: pgvector_local
    sources:
      - type: pdf_url
        urls:
          - "https://arxiv.org/pdf/2312.10997"
    chunking:
      strategy: recursive_text_splitter
      size: 400
      overlap: 40
    retrieval:
      top_k: 5
      min_score: 0.15
      max_tokens: 1200

runtime:
  type: bun
  entrypoint: "./entrypoint.ts"
  permissions:
    - --allow-read
    - --allow-net

workflows:
  - source: ./workflows/qa.yaml

autoload:
  enabled: true
  strict: true
  include:
    - "agents/*.yaml"
    - "workflows/*.yaml"
  exclude:
    - "**/*.tmp"
    - "**/*~"
