// Generated from:
//   packages/ui/src/tokens.css
//   packages/site/app/global.css
// by scripts/sync-font-size-classes.mjs.
// Do not edit by hand. Run make codegen to refresh.
//
// tailwind-merge reads an unrecognized `text-*` class as a color. Without these
// literals a font-size utility loses to a color utility in the same `cn()` call.
export const fontSizeClasses = [
  "text-accent-glyph",
  "text-agent-metric",
  "text-badge",
  "text-card-title",
  "text-code-block",
  "text-compact-h1",
  "text-detail-h1",
  "text-display-2xl",
  "text-empty-h1",
  "text-eyebrow",
  "text-eyebrow-caps",
  "text-form-hint",
  "text-form-input",
  "text-form-label",
  "text-form-required",
  "text-group-label",
  "text-inline-code",
  "text-item-title",
  "text-kbd",
  "text-kbd--font-weight",
  "text-kpi-compact",
  "text-kpi-value",
  "text-metric-value",
  "text-micro",
  "text-modal-title",
  "text-mono-id",
  "text-pill-group-badge",
  "text-rail-avatar",
  "text-section-head",
  "text-site-api-body",
  "text-site-api-code",
  "text-site-api-heading",
  "text-site-api-subheading",
  "text-site-article-title",
  "text-site-bento-2xl",
  "text-site-bento-lg",
  "text-site-bento-md",
  "text-site-bento-sm",
  "text-site-bento-xl",
  "text-site-bento-xs",
  "text-site-blog-title",
  "text-site-card-title",
  "text-site-category-title",
  "text-site-cta-title",
  "text-site-doc-heading",
  "text-site-doc-lead",
  "text-site-doc-prose",
  "text-site-doc-prose-compact",
  "text-site-doc-subheading",
  "text-site-doc-title",
  "text-site-empty-title",
  "text-site-error-title",
  "text-site-feature-title",
  "text-site-hero",
  "text-site-hero-section",
  "text-site-lead",
  "text-site-page-title",
  "text-site-protocol-title",
  "text-site-quote",
  "text-site-release-title",
  "text-site-section-title",
  "text-site-subheading",
  "text-site-subsection-title",
  "text-small-body",
  "text-transcript-body",
  "text-transcript-caption",
  "text-transcript-message",
  "text-transcript-meta",
  "text-ui-title-lg",
  "text-workspace-avatar",
  "text-ws-name",
];
