version: 2

updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "compozy/maintainers"
    assignees:
      - "compozy/maintainers"
    commit-message:
      prefix: "deps(go)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "security"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore patch releases for development dependencies
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "compozy/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"

  # Docker dependencies (for Dockerfiles)
  - package-ecosystem: "docker"
    directory: "/cluster"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "compozy/maintainers"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "security"

  # NPM for docs/tools (TypeScript projects)
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "compozy/maintainers"
    commit-message:
      prefix: "deps(docs)"
      include: "scope"
    labels:
      - "dependencies"
      - "docs"
      - "npm"
    ignore:
      # Ignore patch releases for development dependencies
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # NPM for tools directory
  - package-ecosystem: "npm"
    directory: "/tools"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "compozy/maintainers"
    commit-message:
      prefix: "deps(tools)"
      include: "scope"
    labels:
      - "dependencies"
      - "tools"
      - "npm"

  # NPM for examples
  - package-ecosystem: "npm"
    directory: "/examples"
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "compozy/maintainers"
    commit-message:
      prefix: "deps(examples)"
      include: "scope"
    labels:
      - "dependencies"
      - "examples"
      - "npm"
