package memory

var memoryEventOps = []string{
	memoryEventWriteCommitted,
	memoryEventWriteRejected,
	memoryEventWriteShadowed,
	memoryEventWriteReindex,
	memoryEventWriteReverted,
	memoryEventRecallExecuted,
	memoryEventRecallSkipped,
	memoryEventRecallSignalDropped,
	memoryEventRecallSignalFailed,
	memoryEventDecisionsSummarized,
	memoryEventDecisionsPruned,
	memoryEventDreamStarted,
	memoryEventDreamPromoted,
	memoryEventDreamFailed,
	memoryEventExtractorStarted,
	memoryEventExtractorCompleted,
	memoryEventExtractorFailed,
	memoryEventExtractorCoalesced,
	memoryEventExtractorDropped,
	memoryEventDailyRotated,
	memoryEventDailyArchived,
	memoryEventDailyRestored,
	memoryEventDailyPurged,
	memoryEventDailyArchivePurged,
	memoryEventProviderEnabled,
	memoryEventProviderDisabled,
	memoryEventProviderCollision,
	memoryEventWorkspaceRelocated,
	memoryEventWorkspaceRecovered,
	memoryEventAgentPurged,
	memoryEventMigrationApplied,
}
