language: "en"
early_access: true

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "AGENTS.md"
      - "**/AGENTS.md"
      - ".cursor/rules/**/*.mdc"

reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true
  profile: "assertive"
  related_prs: false
  tools:
    golangci-lint:
      enabled: true
  path_filters:
    - "!**/*.md"
    - "!**/*.yaml"
    - "!**/*.yml"
    - "!**/*.json"
    - "!**/*.toml"
    - "!**/*.xml"
    - "!**/*.mdc"
    - "!**/*.mdx"
    - "!.cursor/**"
    - "!.git/**"
    - "!.claude/**"
    - "!.vscode/**"
    - "!.taskmaster/**"
    - "!docs/swagger.*"
    - "!**/mock_*.go"
    - "!**/*.pb.go"
    - "!**/*.pb.gw.go"
    - "!**/fixtures/**"
    - "!test/testdata/**"
