plugins = ["prettier-plugin-sh", "prettier-plugin-organize-imports"]
printWidth = 100
singleQuote = false
semi = true
tabWidth = 2
useTabs = false
trailingComma = "es5"
bracketSpacing = true
bracketSameLine = false
arrowParens = "avoid"
endOfLine = "lf"

[[overrides]]
files = ["**/*.md", "**/*.mdx"]

[overrides.options]
proseWrap = "preserve"
printWidth = 80

[[overrides]]
files = ["**/*.json"]

[overrides.options]
printWidth = 120
