package events

const (
	ACPUserMessage             = "user_message"
	ACPSyntheticReentry        = "synthetic_reentry"
	ACPAgentMessage            = "agent_message"
	ACPThought                 = "thought"
	ACPToolCall                = "tool_call"
	ACPToolResult              = "tool_result"
	ACPPlan                    = "plan"
	ACPPermission              = "permission"
	ACPUsage                   = "usage"
	ACPSystem                  = "system"
	ACPRuntimeProgress         = "runtime_progress"
	ACPRuntimeWarning          = "runtime_warning"
	ACPDone                    = "done"
	ACPError                   = "error"
	SessionStopped             = "session_stopped"
	SessionUnhealthy           = "session.unhealthy"
	SessionHung                = "session.hung"
	SessionRecovered           = "session.recovered"
	SessionCompactionFired     = "session.compaction_fired"
	SessionConversationRewound = "session.conversation_rewound"

	TaskCreated                          = "task.created"
	TaskUpdated                          = "task.updated"
	TaskPublished                        = "task.published"
	TaskApproved                         = "task.approved"
	TaskRejected                         = "task.rejected"
	TaskCanceled                         = "task.canceled"
	TaskChildCreated                     = "task.child_created"
	TaskDependencyAdded                  = "task.dependency_added"
	TaskDependencyRemoved                = "task.dependency_removed"
	TaskPaused                           = "task.paused"
	TaskResumed                          = "task.resumed"
	TaskBlockCreated                     = "task.block.created"
	TaskBlockCleared                     = "task.block.cleared"
	TaskBlockExpired                     = "task.block.expired"
	TaskNeedsAttention                   = "task.needs_attention"
	TaskRecovered                        = "task.recovered"
	TaskRunEnqueued                      = "task.run_enqueued"
	TaskRunClaimed                       = "task.run_claimed"
	TaskRunStarting                      = "task.run_starting"
	TaskRunSessionBound                  = "task.run_session_bound"
	TaskRunStarted                       = "task.run_started"
	TaskRunCompleted                     = "task.run_completed"
	TaskRunFailed                        = "task.run_failed"
	TaskRunCanceled                      = "task.run_canceled"
	TaskRunForceStopped                  = "task.run_force_stopped"
	TaskRunRecovered                     = "task.run_recovered"
	TaskRunRejected                      = "task.run_rejected"
	TaskRunLeaseExtended                 = "task.run_lease_extended"
	TaskRunLeaseExpired                  = "task.run_lease_expired"
	TaskRunReleased                      = "task.run_released"
	TaskRunOperatorForcedFail            = "task.run_operator_forced_fail"
	TaskRunOperatorRetry                 = "task.run_operator_retry"
	TaskRunRecoveredFromAttention        = "task.run_recovered_from_attention"
	TaskRunStarved                       = "task.run_starved"
	TaskRunNeedsAttention                = "task.run_needs_attention"
	TaskExecutionProfileUpdated          = "task.execution_profile_updated"
	TaskExecutionProfileDeleted          = "task.execution_profile_deleted"
	TaskRunReviewRequested               = "task.run_review_requested"
	TaskRunReviewBound                   = "task.run_review_bound"
	TaskRunReviewRecorded                = "task.run_review_recorded"
	TaskRunReviewApproved                = "task.run_review_approved"
	TaskRunReviewRejected                = "task.run_review_rejected"
	TaskRunReviewBlocked                 = "task.run_review_blocked"
	TaskRunReviewError                   = "task.run_review_error"
	TaskRunReviewTimeout                 = "task.run_review_timeout"
	TaskRunReviewInvalidOutput           = "task.run_review_invalid_output"
	TaskRunReviewRetryEnqueued           = "task.run_review_retry_enqueued"
	TaskAutoEnqueueTriggered             = "task.auto_enqueue.triggered"
	TaskCompletionHallucinationBlocked   = "task.completion.hallucination_blocked"
	TaskCompletionHallucinationSuspected = "task.completion.hallucination_suspected"
	TaskWakeDelivered                    = "task.wake.delivered"
	TaskWakeSuppressed                   = "task.wake.suppressed"

	SettingsChanged  = "settings.changed"
	RoleFallbackUsed = "role.fallback.used"
	RoleResolveError = "role.resolve.error"

	SkillShadowed   = "skill.shadowed"
	SkillLoadFailed = "skills.load_failed"

	HookDispatchStart    = "hook.dispatch.start"
	HookDispatchComplete = "hook.dispatch.complete"

	CoordinatorSpawned  = "coordinator.spawned"
	CoordinatorDecision = "coordinator.decision"
	CoordinatorStopped  = "coordinator.stopped"
	CoordinatorFailed   = "coordinator.failed"

	HarnessContextResolved         = "harness.context_resolved"
	HarnessSectionSelected         = "harness.section_selected"
	HarnessAugmenterApplied        = "harness.augmenter_applied"
	HarnessAugmenterFailed         = "harness.augmenter_failed"
	HarnessDetachedRunCompleted    = "harness.detached_run_completed"
	HarnessSyntheticReentryEmitted = "harness.synthetic_reentry_emitted"
	HarnessSyntheticReentryDropped = "harness.synthetic_reentry_dropped"

	MemoryWriteCommitted     = "memory.write.committed"
	MemoryWriteRejected      = "memory.write.rejected"
	MemoryWriteShadowed      = "memory.write.shadowed"
	MemoryWriteReindex       = "memory.write.reindex"
	MemoryWriteReverted      = "memory.write.reverted"
	MemoryProviderCollision  = "memory.provider.collision"
	MemoryRecallExecuted     = "memory.recall.executed"
	MemoryRecallSkipped      = "memory.recall.skipped"
	MemoryRecallDropped      = "memory.recall.signal_dropped"
	MemoryRecallFailed       = "memory.recall.signal_update_failed"
	MemoryDecisionsSummary   = "memory.decisions.audit_summarized"
	MemoryDecisionsPruned    = "memory.decisions.pruned"
	MemoryDreamStarted       = "memory.dream.run.started"
	MemoryDreamPromoted      = "memory.dream.run.promoted"
	MemoryDreamFailed        = "memory.dream.run.failed"
	MemoryExtractorStarted   = "memory.extractor.started"
	MemoryExtractorComplete  = "memory.extractor.completed"
	MemoryExtractorFailed    = "memory.extractor.failed"
	MemoryExtractorCoalesced = "memory.extractor.coalesced"
	MemoryExtractorDropped   = "memory.extractor.dropped"
	MemoryDailyRotated       = "memory.daily.rotated"
	MemoryDailyArchived      = "memory.daily.archived"
	MemoryDailyRestored      = "memory.daily.restored"
	MemoryDailyPurged        = "memory.daily.purged"
	MemoryDailyArchivePurged = "memory.daily.archive_purged"
	MemoryProviderEnabled    = "memory.provider.enabled"
	MemoryProviderDisabled   = "memory.provider.disabled"
	MemoryWorkspaceRelocated = "memory.workspace.relocated"
	MemoryWorkspaceRecovered = "memory.workspace.recovered"
	MemoryAgentPurged        = "memory.agent.purged"
	MemoryMigrationApplied   = "memory.migration.applied"

	SchedulerPaused         = "scheduler.paused"
	SchedulerResumed        = "scheduler.resumed"
	SchedulerDrainStarted   = "scheduler.drain_started"
	SchedulerDrainCompleted = "scheduler.drain_completed"

	AutomationSuggestionAccepted  = "automation.suggestion.accepted"
	AutomationSuggestionDismissed = "automation.suggestion.dismissed"

	TranscriptMarkerCreated       = "transcript_marker.created"
	TranscriptMarkerRedacted      = "transcript_marker.redacted"
	SessionTranscriptCacheRebuilt = "session_transcript_cache_rebuilt"
	SessionStreamSnapshotServed   = "session_stream_snapshot_served"
	SessionStreamSubscribed       = "session_stream_subscribed"
	SessionStreamOverflowFallback = "session_stream_overflow_fallback"

	ToolCallStarted          = "tool.call_started"
	ToolCallCompleted        = "tool.call_completed"
	ToolCallFailed           = "tool.call_failed"
	ToolCallDenied           = "tool.call_denied"
	ToolResultTruncated      = "tool.result_truncated"
	ToolApprovalGrantPut     = "tool.approval_grant_put"
	ToolApprovalGrantRevoked = "tool.approval_grant_revoked"

	ProviderAuthRequired          = "provider.auth_required"
	ProviderAuthRecovered         = "provider.auth_recovered"
	ProviderRateLimited           = "provider.rate_limited"
	ProviderPermissionDenied      = "provider.permission_denied"
	ProviderUnavailable           = "provider.unavailable"
	ProviderModelCatalogRefreshed = "provider.model_catalog_refreshed"

	DeadEntityMarked  = "reliability.dead_entity_marked"
	DeadEntityCleared = "reliability.dead_entity_cleared"

	BridgeNotificationSuppressed = "bridge_notification_suppressed"
	NetworkPeerJoined            = "network.peer.joined"
	NetworkPeerLeft              = "network.peer.left"

	NotificationPresetCreated        = "notification.preset_created"
	NotificationPresetUpdated        = "notification.preset_updated"
	NotificationPresetDeleted        = "notification.preset_deleted"
	NotificationPresetDispatchFailed = "notification.preset_dispatch_failed"

	WorktreeCreated             = "worktree.created"
	WorktreeAdopted             = "worktree.adopted"
	WorktreeRemoved             = "worktree.removed"
	WorktreeMissing             = "worktree.missing"
	WorktreeDismissed           = "worktree.dismissed"
	WorktreeCreationCanceled    = "worktree.creation_canceled"
	WorktreeSetupFailed         = "worktree.setup_failed"
	WorktreeStatusRefreshed     = "worktree.status_refreshed"
	WorktreeBranchReclaimed     = "worktree.branch_reclaimed"
	WorktreeExitActionStarted   = "worktree.exit_action_started"
	WorktreeExitActionStep      = "worktree.exit_action_step"
	WorktreeExitActionCompleted = "worktree.exit_action_completed"
	WorktreeExitActionFailed    = "worktree.exit_action_failed"
	WorktreeExitActionCanceled  = "worktree.exit_action_canceled"
)
