package toolmeta

var nativeEntries = map[string]Entry{
	"agh__agent_create":                   nativeEntry("Creating", " ", false, "🤖", "auto"),
	"agh__agent_heartbeat_status":         nativeEntry("Reading", " ", false, "🤖", "auto"),
	"agh__agent_heartbeat_wake":           nativeEntry("Running", " ", false, "🤖", "auto"),
	"agh__automation_jobs_create":         nativeEntry("Creating", " ", false, "⏱️", "auto"),
	"agh__automation_jobs_delete":         nativeEntry("Deleting", " ", false, "⏱️", "auto"),
	"agh__automation_jobs_disable":        nativeEntry("Disabling", " ", false, "⏱️", "auto"),
	"agh__automation_jobs_enable":         nativeEntry("Enabling", " ", false, "⏱️", "auto"),
	"agh__automation_jobs_get":            nativeEntry("Reading", " ", false, "⏱️", "auto"),
	"agh__automation_jobs_history":        nativeEntry("Reading", " ", false, "⏱️", "auto"),
	"agh__automation_jobs_list":           nativeEntry("Reading", " ", false, "⏱️", "auto"),
	"agh__automation_jobs_trigger":        nativeEntry("Running", " ", false, "⏱️", "auto"),
	"agh__automation_jobs_update":         nativeEntry("Updating", " ", false, "⏱️", "auto"),
	"agh__automation_runs_get":            nativeEntry("Reading", " ", false, "⏱️", "auto"),
	"agh__automation_runs_list":           nativeEntry("Reading", " ", false, "⏱️", "auto"),
	"agh__automation_suggestions_accept":  nativeEntry("Creating", " ", false, "⏱️", "auto"),
	"agh__automation_suggestions_dismiss": nativeEntry("Dismissing", " ", false, "⏱️", "auto"),
	"agh__automation_suggestions_list":    nativeEntry("Reading", " ", false, "⏱️", "auto"),
	"agh__automation_triggers_create":     nativeEntry("Creating", " ", false, "⏱️", "auto"),
	"agh__automation_triggers_delete":     nativeEntry("Deleting", " ", false, "⏱️", "auto"),
	"agh__automation_triggers_disable":    nativeEntry("Disabling", " ", false, "⏱️", "auto"),
	"agh__automation_triggers_enable":     nativeEntry("Enabling", " ", false, "⏱️", "auto"),
	"agh__automation_triggers_get":        nativeEntry("Reading", " ", false, "⏱️", "auto"),
	"agh__automation_triggers_history":    nativeEntry("Reading", " ", false, "⏱️", "auto"),
	"agh__automation_triggers_list":       nativeEntry("Reading", " ", false, "⏱️", "auto"),
	"agh__automation_triggers_update":     nativeEntry("Updating", " ", false, "⏱️", "auto"),
	"agh__bridges_list":                   nativeEntry("Reading", " ", false, "🌉", "auto"),
	"agh__bridges_status":                 nativeEntry("Reading", " ", false, "🌉", "auto"),
	"agh__bundles_activate":               nativeEntry("Activating", " ", false, "📦", "auto"),
	"agh__bundles_deactivate":             nativeEntry("Deactivating", " ", false, "📦", "auto"),
	"agh__bundles_info":                   nativeEntry("Reading", " ", false, "📦", "auto"),
	"agh__bundles_list":                   nativeEntry("Reading", " ", false, "📦", "auto"),
	"agh__bundles_status":                 nativeEntry("Reading", " ", false, "📦", "auto"),
	"agh__clarify":                        nativeEntry("Asking", " ", false, "💬", "auto"),
	"agh__config_diff":                    nativeEntry("Reading", " ", false, "⚙️", "auto"),
	"agh__config_get":                     nativeEntry("Reading", " ", false, "⚙️", "auto"),
	"agh__config_list":                    nativeEntry("Reading", " ", false, "⚙️", "auto"),
	"agh__config_path":                    nativeEntry("Reading", " ", false, "⚙️", "auto"),
	"agh__config_set":                     nativeEntry("Updating", " ", false, "⚙️", "auto"),
	"agh__config_show":                    nativeEntry("Reading", " ", true, "⚙️", previewHintNone),
	"agh__config_unset":                   nativeEntry("Removing", " ", false, "⚙️", "auto"),
	"agh__desktop_clients":                nativeEntry("Reading", " ", false, "🪟", "auto"),
	"agh__desktop_create":                 nativeEntry("Creating", " ", false, "🪟", "auto"),
	"agh__desktop_delete":                 nativeEntry("Deleting", " ", false, "🪟", "auto"),
	"agh__desktop_list":                   nativeEntry("Reading", " ", false, "🪟", "auto"),
	"agh__desktop_reorder":                nativeEntry("Reordering", " ", false, "🪟", "auto"),
	"agh__desktop_switch":                 nativeEntry("Switching", " ", false, "🪟", "auto"),
	"agh__desktop_update":                 nativeEntry("Updating", " ", false, "🪟", "auto"),
	"agh__extensions_disable":             nativeEntry("Disabling", " ", false, "🧩", "auto"),
	"agh__extensions_enable":              nativeEntry("Enabling", " ", false, "🧩", "auto"),
	"agh__extensions_info":                nativeEntry("Reading", " ", false, "🧩", "auto"),
	"agh__extensions_install":             nativeEntry("Installing", " ", false, "🧩", "auto"),
	"agh__extensions_list":                nativeEntry("Reading", " ", false, "🧩", "auto"),
	"agh__extensions_remove":              nativeEntry("Removing", " ", false, "🧩", "auto"),
	"agh__extensions_update":              nativeEntry("Updating", " ", false, "🧩", "auto"),
	"agh__goal_get":                       nativeEntry("Reading", " ", false, "🎯", "auto"),
	"agh__goal_report":                    nativeEntry("Reporting", " ", false, "🎯", "auto"),
	"agh__hooks_create":                   nativeEntry("Creating", " ", false, "🪝", "auto"),
	"agh__hooks_delete":                   nativeEntry("Deleting", " ", false, "🪝", "auto"),
	"agh__hooks_disable":                  nativeEntry("Disabling", " ", false, "🪝", "auto"),
	"agh__hooks_enable":                   nativeEntry("Enabling", " ", false, "🪝", "auto"),
	"agh__hooks_events":                   nativeEntry("Reading", " ", false, "🪝", "auto"),
	"agh__hooks_info":                     nativeEntry("Reading", " ", false, "🪝", "auto"),
	"agh__hooks_list":                     nativeEntry("Reading", " ", false, "🪝", "auto"),
	"agh__hooks_runs":                     nativeEntry("Reading", " ", false, "🪝", "auto"),
	"agh__hooks_update":                   nativeEntry("Updating", " ", false, "🪝", "auto"),
	"agh__layout_apply":                   nativeEntry("Applying", " ", false, "🪟", "auto"),
	"agh__layout_arrange":                 nativeEntry("Arranging", " ", false, "🪟", "auto"),
	"agh__layout_balance":                 nativeEntry("Balancing", " ", false, "🪟", "auto"),
	"agh__layout_export":                  nativeEntry("Exporting", " ", false, "🪟", "auto"),
	"agh__layout_get":                     nativeEntry("Reading", " ", false, "🪟", "auto"),
	"agh__layout_preview":                 nativeEntry("Previewing", " ", false, "🪟", "auto"),
	"agh__layout_redo":                    nativeEntry("Redoing", " ", false, "🪟", "auto"),
	"agh__layout_resize":                  nativeEntry("Resizing", " ", false, "🪟", "auto"),
	"agh__layout_undo":                    nativeEntry("Undoing", " ", false, "🪟", "auto"),
	"agh__layout_validate":                nativeEntry("Validating", " ", false, "🪟", "auto"),
	"agh__logs":                           nativeEntry("Reading", " ", false, "📜", previewHintQuery),
	"agh__marketplace_search":             nativeEntry("Searching", " for ", false, "🧩", previewHintQuery),
	"agh__loop_approve":                   nativeEntry("Approving", " ", false, "🔁", "auto"),
	"agh__loop_configure":                 nativeEntry("Updating", " ", false, "🔁", "auto"),
	"agh__loop_create":                    nativeEntry("Creating", " ", false, "🔁", "auto"),
	"agh__loop_delete":                    nativeEntry("Deleting", " ", false, "🔁", "auto"),
	"agh__loop_inspect":                   nativeEntry("Reading", " ", false, "🔁", "auto"),
	"agh__loop_list":                      nativeEntry("Reading", " ", false, "🔁", "auto"),
	"agh__loop_pause":                     nativeEntry("Pausing", " ", false, "🔁", "auto"),
	"agh__loop_resume":                    nativeEntry("Resuming", " ", false, "🔁", "auto"),
	"agh__loop_run":                       nativeEntry("Running", " ", false, "🔁", "auto"),
	"agh__loop_runs":                      nativeEntry("Reading", " ", false, "🔁", "auto"),
	"agh__loop_status":                    nativeEntry("Reading", " ", false, "🔁", "auto"),
	"agh__loop_stop":                      nativeEntry("Stopping", " ", false, "🔁", "auto"),
	"agh__loop_turns":                     nativeEntry("Reading", " ", false, "🔁", "auto"),
	"agh__loop_validate":                  nativeEntry("Validating", " ", false, "🔁", "auto"),
	"agh__mcp_auth_status":                nativeEntry("Reading", " ", true, "🔌", previewHintNone),
	"agh__mcp_status":                     nativeEntry("Reading", " ", false, "🔌", "auto"),
	"agh__memory_admin_history":           nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_daily_list":              nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_decisions_list":          nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_decisions_revert":        nativeEntry("Reverting", " ", false, "🧠", "auto"),
	"agh__memory_decisions_show":          nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_dream_list":              nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_dream_retry":             nativeEntry("Retrying", " ", false, "🧠", "auto"),
	"agh__memory_dream_show":              nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_dream_status":            nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_dream_trigger":           nativeEntry("Running", " ", false, "🧠", "auto"),
	"agh__memory_extractor_drain":         nativeEntry("Running", " ", false, "🧠", "auto"),
	"agh__memory_extractor_failures":      nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_extractor_retry":         nativeEntry("Retrying", " ", false, "🧠", "auto"),
	"agh__memory_extractor_status":        nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_health":                  nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_list":                    nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_note":                    nativeEntry("Saving", " ", false, "🧠", "auto"),
	"agh__memory_promote":                 nativeEntry("Promoting", " ", false, "🧠", "auto"),
	"agh__memory_propose":                 nativeEntry("Proposing", " ", false, "🧠", "auto"),
	"agh__memory_provider_disable":        nativeEntry("Disabling", " ", false, "🧠", "auto"),
	"agh__memory_provider_enable":         nativeEntry("Enabling", " ", false, "🧠", "auto"),
	"agh__memory_provider_get":            nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_provider_list":           nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_provider_select":         nativeEntry("Selecting", " ", false, "🧠", "auto"),
	"agh__memory_recall_trace":            nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_reindex":                 nativeEntry("Reindexing", " ", false, "🧠", "auto"),
	"agh__memory_reload":                  nativeEntry("Reloading", " ", false, "🧠", "auto"),
	"agh__memory_reset":                   nativeEntry("Resetting", " ", false, "🧠", "auto"),
	"agh__memory_scope_show":              nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_search":                  nativeEntry("Searching", " for ", false, "🧠", previewHintQuery),
	"agh__memory_session_ledger":          nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__memory_session_replay":          nativeEntry("Replaying", " ", false, "🧠", "auto"),
	"agh__memory_sessions_prune":          nativeEntry("Pruning", " ", false, "🧠", "auto"),
	"agh__memory_sessions_repair":         nativeEntry("Repairing", " ", false, "🧠", "auto"),
	"agh__memory_show":                    nativeEntry("Reading", " ", false, "🧠", "auto"),
	"agh__network_channel_create":         nativeEntry("Creating", " ", false, "🌐", "auto"),
	"agh__network_channel_update":         nativeEntry("Updating", " ", false, "🌐", "auto"),
	"agh__network_channels":               nativeEntry("Reading", " ", false, "🌐", "auto"),
	"agh__network_direct_messages":        nativeEntry("Reading", " ", false, "🌐", "auto"),
	"agh__network_direct_resolve":         nativeEntry("Resolving", " ", false, "🌐", "auto"),
	"agh__network_directs":                nativeEntry("Reading", " ", false, "🌐", "auto"),
	"agh__network_inbox":                  nativeEntry("Reading", " ", false, "🌐", "auto"),
	"agh__network_mute":                   nativeEntry("Muting", " ", false, "🌐", "auto"),
	"agh__network_peers":                  nativeEntry("Reading", " ", false, "🌐", "auto"),
	"agh__network_send":                   nativeEntry("Sending", " ", false, "🌐", "auto"),
	"agh__network_status":                 nativeEntry("Reading", " ", false, "🌐", "auto"),
	"agh__network_subscribe":              nativeEntry("Subscribing", " ", false, "🌐", "auto"),
	"agh__network_subscriptions":          nativeEntry("Reading", " ", false, "🌐", "auto"),
	"agh__network_thread_messages":        nativeEntry("Reading", " ", false, "🌐", "auto"),
	"agh__network_threads":                nativeEntry("Reading", " ", false, "🌐", "auto"),
	"agh__network_unmute":                 nativeEntry("Unmuting", " ", false, "🌐", "auto"),
	"agh__network_usage":                  nativeEntry("Reading", " ", false, "🌐", "auto"),
	"agh__network_work":                   nativeEntry("Reading", " ", false, "🌐", "auto"),
	"agh__observe_metrics":                nativeEntry("Reading", " ", false, "🔭", "auto"),
	"agh__observe_search":                 nativeEntry("Searching", " for ", false, "🔭", previewHintQuery),
	"agh__provider_models_curate":         nativeEntry("Curating", " ", false, "🤖", "auto"),
	"agh__provider_models_list":           nativeEntry("Reading", " ", false, "🤖", "auto"),
	"agh__provider_models_refresh":        nativeEntry("Refreshing", " ", false, "🤖", "auto"),
	"agh__provider_models_status":         nativeEntry("Reading", " ", false, "🤖", "auto"),
	"agh__resources_info":                 nativeEntry("Reading", " ", false, "📚", "auto"),
	"agh__resources_list":                 nativeEntry("Reading", " ", false, "📚", "auto"),
	"agh__resources_snapshot":             nativeEntry("Reading", " ", false, "📚", "auto"),
	"agh__session_describe":               nativeEntry("Reading", " ", false, "💬", "auto"),
	"agh__session_events":                 nativeEntry("Reading", " ", false, "💬", "auto"),
	"agh__session_health":                 nativeEntry("Reading", " ", false, "💬", "auto"),
	"agh__session_history":                nativeEntry("Reading", " ", false, "💬", "auto"),
	"agh__session_list":                   nativeEntry("Reading", " ", false, "💬", "auto"),
	"agh__session_status":                 nativeEntry("Reading", " ", false, "💬", "auto"),
	"agh__skill_list":                     nativeEntry("Reading", " ", false, "🧰", "auto"),
	"agh__skill_search":                   nativeEntry("Searching", " for ", false, "🧰", previewHintQuery),
	"agh__skill_view":                     nativeEntry("Reading", " ", false, "🧰", "auto"),
	"agh__task_block":                     nativeEntry("Blocking", " ", false, "✅", "auto"),
	"agh__task_blocks":                    nativeEntry("Reading", " ", false, "✅", "auto"),
	"agh__task_cancel":                    nativeEntry("Canceling", " ", false, "✅", "auto"),
	"agh__task_child_create":              nativeEntry("Creating", " ", false, "✅", "auto"),
	"agh__task_create":                    nativeEntry("Creating", " ", false, "✅", "auto"),
	"agh__task_execution_profile_delete":  nativeEntry("Deleting", " ", false, "✅", "auto"),
	"agh__task_execution_profile_get":     nativeEntry("Reading", " ", false, "✅", "auto"),
	"agh__task_execution_profile_set":     nativeEntry("Updating", " ", false, "✅", "auto"),
	"agh__task_fanout_runs":               nativeEntry("Creating", " ", false, "✅", "auto"),
	"agh__task_list":                      nativeEntry("Reading", " ", false, "✅", "auto"),
	"agh__task_notification_delete":       nativeEntry("Deleting", " ", false, "✅", "auto"),
	"agh__task_notification_list":         nativeEntry("Reading", " ", false, "✅", "auto"),
	"agh__task_notification_show":         nativeEntry("Reading", " ", false, "✅", "auto"),
	"agh__task_notification_subscribe":    nativeEntry("Subscribing", " ", false, "✅", "auto"),
	"agh__task_promote_from_thread":       nativeEntry("Promoting", " ", false, "✅", "auto"),
	"agh__task_read":                      nativeEntry("Reading", " ", false, "✅", "auto"),
	"agh__task_recover":                   nativeEntry("Recovering", " ", false, "✅", "auto"),
	"agh__task_run_claim_next":            nativeEntry("Claiming", " ", false, "✅", "auto"),
	"agh__task_run_complete":              nativeEntry("Completing", " ", false, "✅", "auto"),
	"agh__task_run_fail":                  nativeEntry("Reporting failure", " ", false, "✅", "auto"),
	"agh__task_run_heartbeat":             nativeEntry("Renewing", " ", false, "✅", "auto"),
	"agh__task_run_list":                  nativeEntry("Reading", " ", false, "✅", "auto"),
	"agh__task_run_release":               nativeEntry("Releasing", " ", false, "✅", "auto"),
	"agh__task_run_review_list":           nativeEntry("Reading", " ", false, "✅", "auto"),
	"agh__task_run_review_request":        nativeEntry("Requesting review", " ", false, "✅", "auto"),
	"agh__task_run_review_show":           nativeEntry("Reading", " ", false, "✅", "auto"),
	"agh__task_run_review_submit":         nativeEntry("Submitting review", " ", false, "✅", "auto"),
	"agh__task_unblock":                   nativeEntry("Unblocking", " ", false, "✅", "auto"),
	"agh__task_update":                    nativeEntry("Updating", " ", false, "✅", "auto"),
	"agh__tool_approvals_set":             nativeEntry("Setting", " ", false, "🔧", "auto"),
	"agh__tool_approvals_list":            nativeEntry("Reading", " ", false, "🔧", "auto"),
	"agh__tool_approvals_revoke":          nativeEntry("Revoking", " ", false, "🔧", "auto"),
	"agh__tool_artifact_read":             nativeEntry("Reading", " ", false, "🔧", "auto"),
	"agh__tool_info":                      nativeEntry("Reading", " ", false, "🔧", "auto"),
	"agh__tool_list":                      nativeEntry("Reading", " ", false, "🔧", "auto"),
	"agh__tool_search":                    nativeEntry("Searching", " for ", false, "🔧", previewHintQuery),
	"agh__window_close":                   nativeEntry("Closing", " ", false, "🪟", "auto"),
	"agh__window_float":                   nativeEntry("Toggling", " ", false, "🪟", "auto"),
	"agh__window_focus":                   nativeEntry("Focusing", " ", false, "🪟", "auto"),
	"agh__window_list":                    nativeEntry("Reading", " ", false, "🪟", "auto"),
	"agh__window_move":                    nativeEntry("Moving", " ", false, "🪟", "auto"),
	"agh__window_navigate":                nativeEntry("Navigating", " ", false, "🪟", "auto"),
	"agh__window_open":                    nativeEntry("Opening", " ", false, "🪟", "auto"),
	"agh__window_swap":                    nativeEntry("Swapping", " ", false, "🪟", "auto"),
	"agh__window_zoom":                    nativeEntry("Zooming", " ", false, "🪟", "auto"),
	"agh__workspace_describe":             nativeEntry("Reading", " ", false, "🗂️", "auto"),
	"agh__workspace_info":                 nativeEntry("Reading", " ", false, "🗂️", "auto"),
	"agh__workspace_list":                 nativeEntry("Reading", " ", false, "🗂️", "auto"),
}

func nativeEntry(verb string, connector string, dropsPreview bool, emoji string, preview string) Entry {
	return Entry{
		Verb:         verb,
		Connector:    connector,
		DropsPreview: dropsPreview,
		Emoji:        emoji,
		Preview:      preview,
	}
}
