package corecmds

const (
	coreAppAgents         = "agents"
	coreAppBridges        = "bridges"
	coreAppExtensions     = "extensions"
	coreAppJobs           = "jobs"
	coreAppKnowledge      = "knowledge"
	coreAppLoops          = "loops"
	coreAppMarketplace    = "marketplace"
	coreAppTasks          = "tasks"
	coreAppTriggers       = "triggers"
	coreAppVault          = "vault"
	coreNetworkKey        = "network"
	coreSettingsKey       = "settings"
	coreIconGlobe         = "globe"
	coreIconTerminal      = "square-terminal"
	coreIconZap           = "zap"
	coreIconPlus          = "plus"
	coreIconPanelTop      = "panel-top"
	coreIconChevronRight  = "chevron-right"
	coreIconChevronLeft   = "chevron-left"
	coreIconMonitor       = "monitor"
	coreIconCommand       = "command"
	coreSectionShell      = "Shell"
	coreSectionWindow     = "Window"
	coreSectionTabs       = "Tabs"
	coreSectionSessions   = "Sessions"
	coreSectionDesktops   = "Desktops"
	coreSectionWorkspaces = "Workspaces"
	coreSectionLayout     = "Layout"
	coreSectionSettings   = "Settings"
	coreSectionViews      = "Views"
	coreSectionTiling     = "Tiling"
	coreSectionApps       = "Apps"
	coreSectionProfiles   = "Profiles"
)
