resource: task
id: topic-research
name: Single-agent topic research
description: Prompt-driven task that delegates to the research-web agent using cp__call_agent.
type: basic
final: true
timeout: 120s

input:
  type: object
  properties:
    topic:
      type: string
      description: Topic the agent should research.
  required:
    - topic

with:
  topic: "{{ .with.topic }}"

prompt: |
  You must call the cp__call_agent builtin to run the web research agent and pass along the topic.

  Call the tool with:
  {
    "agent_id": "research-web",
    "action_id": "research_topic",
    "with": {
      "topic": "{{ .with.topic }}"
    }
  }

  Return only the agent response text (no additional narration).

outputs:
  summary: "{{ .output }}"
