package windowmanager

var defaultKeymap = map[string]ShortcutBinding{
	shortcutPaletteOpenAction:            {shortcutPaletteOpenChord, "meta+shift+KeyP"},
	shortcutPaletteViewSessionsAction:    {"meta+KeyE"},
	shortcutSessionNewAction:             {"meta+KeyN"},
	shortcutScopeGlobalToggleAction:      {"meta+shift+KeyG"},
	shortcutWindowNavBackAction:          {"meta+BracketLeft"},
	shortcutSessionCycleNextAction:       {"control+shift+ArrowDown"},
	shortcutSessionCyclePreviousAction:   {"control+shift+ArrowUp"},
	shortcutSessionFocusAttentionAction:  {"control+alt+KeyA"},
	shortcutWorkspacePickerAction:        {"meta+shift+KeyO"},
	shortcutWorkspaceCycleNextAction:     {"meta+shift+BracketRight"},
	shortcutWorkspaceCyclePreviousAction: {"meta+shift+BracketLeft"},
	"desktop.switch.1":                   {"control+Digit1"},
	"desktop.switch.2":                   {"control+Digit2"},
	"desktop.switch.3":                   {"control+Digit3"},
	"desktop.switch.4":                   {"control+Digit4"},
	"desktop.switch.5":                   {"control+Digit5"},
	"desktop.switch.6":                   {"control+Digit6"},
	"desktop.switch.7":                   {"control+Digit7"},
	"desktop.switch.8":                   {"control+Digit8"},
	"desktop.switch.9":                   {"control+Digit9"},
	string(CommandDesktopCreate):         {"meta+shift+KeyN"},
	"desktop.overview":                   {"meta+shift+KeyD"},
	"desktop.switch.previous":            {"control+shift+ArrowLeft"},
	"desktop.switch.next":                {"control+shift+ArrowRight"},
	shortcutSidebarToggleAction:          {"meta+KeyB"},
	shortcutWindowFocusLastAction:        {"control+alt+KeyO"},
	string(CommandWindowClose):           {"meta+KeyW"},
	"window.minimize":                    {"meta+KeyM"},
	"window.zoom":                        {"control+alt+KeyZ"},
	"window.toggle_floating":             {"control+alt+KeyF"},
	"window.tile.left":                   {"control+alt+ArrowLeft"},
	"window.tile.right":                  {"control+alt+ArrowRight"},
	shortcutWindowTileTopAction:          {"control+alt+ArrowUp"},
	shortcutWindowTileBottomAction:       {"control+alt+ArrowDown"},
	"window.tile.top-left":               {"control+alt+KeyU"},
	"window.tile.top-right":              {"control+alt+KeyI"},
	"window.tile.bottom-left":            {"control+alt+KeyJ"},
	"window.tile.bottom-right":           {"control+alt+KeyK"},
	"window.tab.new":                     {"meta+KeyT"},
	"window.tab.next":                    {"control+Tab"},
	"window.tab.previous":                {"control+shift+Tab"},
	"window.tab.last":                    {"meta+Digit9"},
	"window.tab.reopen":                  {"meta+shift+KeyT"},
	"window.tab.jump.1":                  {"meta+Digit1"},
	"window.tab.jump.2":                  {"meta+Digit2"},
	"window.tab.jump.3":                  {"meta+Digit3"},
	"window.tab.jump.4":                  {"meta+Digit4"},
	"window.tab.jump.5":                  {"meta+Digit5"},
	"window.tab.jump.6":                  {"meta+Digit6"},
	"window.tab.jump.7":                  {"meta+Digit7"},
	"window.tab.jump.8":                  {"meta+Digit8"},
	"window.focus.left":                  {"control+ArrowLeft"},
	"window.focus.right":                 {"control+ArrowRight"},
	"window.focus.up":                    {"control+ArrowUp"},
	"window.focus.down":                  {"control+ArrowDown"},
	"layout.arrange.two-up":              {},
	"layout.arrange.grid":                {},
	string(CommandLayoutBalance):         {"control+alt+KeyB"},
	string(CommandLayoutUndo):            {"meta+KeyZ"},
	"layout.redo":                        {"meta+shift+KeyZ"},
	shortcutCheatsheetAction:             {"shift+Slash", "meta+Slash"},
}

// DefaultKeymap returns the daemon-owned v2 keymap.
func DefaultKeymap() map[string]ShortcutBinding {
	return CloneShortcutMap(defaultKeymap)
}
