import type { LucideIcon } from "lucide-react";
import {
  Ban,
  Bell,
  Check,
  CircleAlert,
  CircleCheck,
  CircleSlash,
  CopyX,
  Eye,
  GitBranch,
  GitFork,
  Hourglass,
  Minus,
  Pause,
  Pencil,
  Play,
  Radio,
  Redo2,
  RotateCcw,
  Send,
  ShieldAlert,
  TriangleAlert,
  VolumeOff,
  X,
  Zap,
  ZapOff,
} from "lucide-react";

import type { LoopStoryIcon } from "./loop-run-story-types";

export const LOOP_STORY_ICONS: Record<LoopStoryIcon, LucideIcon> = {
  round: Play,
  "check-pass": Check,
  "check-warn": TriangleAlert,
  "node-done": Check,
  "node-failed": X,
  approval: Bell,
  watching: Eye,
  paused: Pause,
  resumed: Play,
  started: Play,
  done: Check,
  "circle-slash": CircleSlash,
  retry: RotateCcw,
  canceled: Ban,
  killed: Zap,
  quarantined: ShieldAlert,
  requeued: Redo2,
  waiting: Hourglass,
  attention: TriangleAlert,
  "attention-silence": VolumeOff,
  "attention-cleared": CircleCheck,
  effect: Send,
  suppressed: CopyX,
  "breaker-open": ZapOff,
  "breaker-closed": Radio,

  "request-opened": TriangleAlert,
  "request-answered": Check,
  "request-expired": CircleAlert,
  "route-taken": GitBranch,
  "route-default": GitBranch,
  pruned: Minus,
  amended: Pencil,
  forked: GitFork,
};
