name: knowledge-quickstart
version: 0.1.0
description: Quickstart knowledge base using local Markdown documents and in-memory vector store

embedders:
  - id: openai_default
    provider: openai
    model: text-embedding-3-small
    api_key: "{{ .env.OPENAI_API_KEY }}"
    config:
      batch_size: 32

vector_dbs:
  - id: in_memory_faststart
    type: in_memory

knowledge_bases:
  - id: quickstart_docs
    embedder: openai_default
    vector_db: in_memory_faststart
    sources:
      - kind: markdown_glob
        glob: "docs/**/*.md"
    chunking:
      strategy: token
      size: 512
      overlap: 64
    retrieval:
      top_k: 5
      min_score: 0.2

agents:
  - id: quickstart_agent
    description: Answers questions using quickstart knowledge base
    model: openai/gpt-4o-mini
    instructions: ./agents/quickstart-agent.md
    knowledge:
      id: quickstart_docs
      retrieval:
        top_k: 3
        max_tokens: 1200

workflows:
  - source: ./workflows/qa.yaml

autoload:
  enabled: true
  strict: true
  include:
    - "workflows/*.yaml"
    - "agents/*.md"
    - "docs/**/*.md"
  exclude:
    - "**/*.tmp"
    - "**/*~"
