package httpapi

import (
	"io/fs"

	"github.com/gin-gonic/gin"
)

func (s *Server) handlerConfig(staticFS fs.FS) *handlerConfig {
	return &handlerConfig{
		sessions:           s.sessions,
		drainController:    s.drainController,
		sessionCatalog:     s.sessionCatalog,
		tasks:              s.tasks,
		network:            s.network,
		networkStore:       s.networkStore,
		networkUsage:       s.networkUsage,
		coordination:       s.coordination,
		observer:           s.observer,
		schemaStreams:      s.schemaStreams,
		resources:          s.resources,
		windowManager:      s.windowManager,
		automation:         s.automation,
		loops:              s.loops,
		bridges:            s.bridges,
		notifications:      s.notifications,
		bundles:            s.bundles,
		supportBundles:     s.supportBundles,
		tools:              s.tools,
		toolArtifacts:      s.toolArtifacts,
		toolsets:           s.toolsets,
		toolApprovals:      s.toolApprovals,
		approvalGrants:     s.approvalGrants,
		clarify:            s.clarify,
		settings:           s.settings,
		settingsRestart:    s.settingsRestart,
		settingsUpdate:     s.settingsUpdate,
		vault:              s.vault,
		workspaces:         s.workspaces,
		onboarding:         s.onboarding,
		agentCatalog:       s.agentCatalog,
		agentSync:          s.agentSync,
		modelCatalog:       s.modelCatalog,
		marketplaceCatalog: s.marketplaceCatalog,
		agentContext:       s.agentContext,
		coordinatorRole:    s.coordinatorRole,
		roles:              s.roles,
		soulAuthoring:      s.soulAuthoring,
		soulHistoryPurger:  s.soulHistoryPurger,
		soulRefresher:      s.soulRefresher,
		heartbeatAuthor:    s.heartbeatAuthor,
		heartbeatPurger:    s.heartbeatPurger,
		heartbeatStatus:    s.heartbeatStatus,
		heartbeatWake:      s.heartbeatWake,
		sessionHealth:      s.sessionHealth,
		wakeEvents:         s.wakeEvents,
		skillsRegistry:     s.skillsRegistry,
		skillResources:     s.skillResources,
		memoryStore:        s.memoryStore,
		dreamTrigger:       s.dreamTrigger,
		memoryExtractor:    s.memoryExtractor,
		memoryProviders:    s.memoryProviders,
		memoryLedger:       s.memoryLedger,
		runtimeMemory:      s.runtimeMemory,
		deadEntities:       s.deadEntities,
		staticFS:           staticFS,
		homePaths:          s.homePaths,
		config:             s.config,
		boundHost:          s.host,
		logger:             s.logger,
		startedAt:          s.startedAt,
		now:                s.now,
		pollInterval:       s.pollInterval,
		agentLoader:        s.agentLoader,
		httpPort:           s.port,
		resourceAuth:       append([]gin.HandlerFunc(nil), s.resourceAuth...),
		extensions:         s.extensions,
	}
}
