export const SESSION_ATTACHMENT_IMAGE_MAX_HEIGHT = 168;
export const SESSION_ATTACHMENT_IMAGE_MAX_WIDTH = 280;
export const SESSION_ATTACHMENT_FILE_HEIGHT = 36;
export const SESSION_ATTACHMENT_GALLERY_GAP = 4;
