@baseUrl = http://localhost:5001/api/v0
@workflowId = agentic

### Run structured workflow
# @name executeWorkflow
POST {{baseUrl}}/workflows/{{workflowId}}/executions
Content-Type: application/json
Accept: application/json

{
  "input": {
    "topic": "Most recent agentic methods and techniques"
  }
}

### Get execution ID from response (use this in subsequent requests)
@execId = {{executeWorkflow.response.body.data.exec_id}}

### -----------------------------------------------------------------------------
### Get specific execution details
### -----------------------------------------------------------------------------
GET {{baseUrl}}/executions/workflows/{{execId}}
Accept: application/json
