package cli

const (
	cliDeletedKey     = "deleted"
	cliCanceledKey    = "canceled"
	cliDeliveryKey    = "delivery"
	cliBindingsKey    = "bindings"
	cliComponentKey   = "component"
	cliEnabledKey     = "enabled"
	cliFormatKey      = "format"
	cliIssuesKey      = "issues"
	cliAgentsKey      = "agents"
	cliItemsKey       = "items"
	cliKindKey        = "kind"
	cliKindValue      = "Kind"
	cliDetailValue    = "Detail"
	cliFormatValue    = "Format"
	cliIssuesValue    = "Issues"
	cliLiveKey        = "live"
	cliLiveValue      = "Live"
	cliDeliveryValue  = "Delivery"
	cliMessageIDValue = "Message ID"
	cliNameValue      = "Name"
	cliRuntimeValue   = "Runtime"
	cliReasonValue    = "Reason"
	cliReleaseValue   = "Release"
	cliRuntimeKey     = "runtime"
	cliInstalledValue = "Installed"
	cliSchemaVersion  = "schema_version"
	cliValidateVerb   = "validate"
	cliConfiguredKey  = "configured"
	cliPinVerb        = "pin"
	cliUnpinVerb      = "unpin"
	agentOutputLabel  = automationAgentValue
	roleOutputLabel   = "Role"
)
