package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/compozy/compozy/internal/setup"
	"github.com/spf13/cobra"
)

func TestSetupHelpShowsSetupFlagsOnly(t *testing.T) {
	t.Parallel()

	output, err := executeRootCommand("setup", "--help")
	if err != nil {
		t.Fatalf("execute setup help: %v", err)
	}

	required := []string{"--agent", "--skill", "--global", "--copy", "--list", "--yes", "--all"}
	for _, snippet := range required {
		if !strings.Contains(output, snippet) {
			t.Fatalf("expected setup help to include %q\noutput:\n%s", snippet, output)
		}
	}

	forbidden := []string{"--provider", "--pr", "--tasks-dir", "--batch-size", "--concurrent"}
	for _, snippet := range forbidden {
		if strings.Contains(output, snippet) {
			t.Fatalf("expected setup help to omit %q\noutput:\n%s", snippet, output)
		}
	}
}

func TestSetupRunYesFailsWithoutDetectedAgents(t *testing.T) {
	t.Parallel()

	state := newSetupCommandState()
	state.listSkills = func() ([]setup.Skill, error) {
		return []setup.Skill{{Name: "cy-create-prd", Description: "Create a PRD"}}, nil
	}
	state.listAgents = func(setup.ResolverOptions) ([]setup.Agent, error) {
		return []setup.Agent{
			{
				Name:           "codex",
				DisplayName:    "Codex",
				ProjectRootDir: ".agents/skills",
				GlobalRootDir:  ".codex/skills",
				Universal:      true,
			},
		}, nil
	}
	state.detectAgents = func(setup.ResolverOptions) ([]setup.Agent, error) {
		return nil, nil
	}
	state.yes = true

	cmd := &cobra.Command{Use: "setup"}
	cmd.SetOut(&bytes.Buffer{})
	cmd.SetErr(&bytes.Buffer{})
	cmd.Flags().Bool("global", false, "global")
	cmd.Flags().Bool("copy", false, "copy")

	err := state.run(cmd, nil)
	if err == nil {
		t.Fatal("expected setup run to fail when no agents are detected")
	}
	if !strings.Contains(err.Error(), "no agents detected") {
		t.Fatalf("expected missing detected agents error, got %v", err)
	}
}

func TestSetupWritesWorkflowREADMEOnProjectInstall(t *testing.T) {
	t.Parallel()

	readmeDir := t.TempDir()
	var writtenPath string

	state := newSetupCommandState()
	state.listSkills = func() ([]setup.Skill, error) {
		return []setup.Skill{{Name: "cy-create-prd", Description: "Create a PRD"}}, nil
	}
	state.listAgents = func(setup.ResolverOptions) ([]setup.Agent, error) {
		return []setup.Agent{
			{
				Name:           "codex",
				DisplayName:    "Codex",
				ProjectRootDir: ".agents/skills",
				GlobalRootDir:  ".codex/skills",
				Universal:      true,
			},
		}, nil
	}
	state.detectAgents = func(setup.ResolverOptions) ([]setup.Agent, error) {
		return []setup.Agent{
			{
				Name:           "codex",
				DisplayName:    "Codex",
				ProjectRootDir: ".agents/skills",
				GlobalRootDir:  ".codex/skills",
				Universal:      true,
			},
		}, nil
	}
	state.install = func(setup.InstallConfig) (*setup.Result, error) {
		return &setup.Result{
			Successful: []setup.SuccessItem{
				{Skill: setup.Skill{Name: "cy-create-prd"}, Agent: setup.Agent{DisplayName: "Codex"}},
			},
		}, nil
	}
	state.writeREADME = func(dir string) error {
		writtenPath = dir
		return setup.WriteWorkflowREADME(filepath.Join(readmeDir, ".compozy"))
	}
	state.yes = true

	cmd := &cobra.Command{Use: "setup"}
	cmd.SetOut(&bytes.Buffer{})
	cmd.SetErr(&bytes.Buffer{})
	cmd.Flags().Bool("global", false, "global")
	cmd.Flags().Bool("copy", false, "copy")

	if err := state.run(cmd, nil); err != nil {
		t.Fatalf("setup run: %v", err)
	}

	if writtenPath == "" {
		t.Fatal("writeREADME was not called")
	}

	readmePath := filepath.Join(readmeDir, ".compozy", "README.md")
	content, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatalf("read README: %v", err)
	}
	if !strings.Contains(string(content), "auto-generated by compozy setup") {
		t.Error("README missing auto-generated header")
	}
}

func TestSetupSkipsREADMEOnGlobalInstall(t *testing.T) {
	t.Parallel()

	readmeCalled := false

	state := newSetupCommandState()
	state.listSkills = func() ([]setup.Skill, error) {
		return []setup.Skill{{Name: "cy-create-prd", Description: "Create a PRD"}}, nil
	}
	state.listAgents = func(setup.ResolverOptions) ([]setup.Agent, error) {
		return []setup.Agent{
			{
				Name:           "codex",
				DisplayName:    "Codex",
				ProjectRootDir: ".agents/skills",
				GlobalRootDir:  ".codex/skills",
				Universal:      true,
			},
		}, nil
	}
	state.detectAgents = func(setup.ResolverOptions) ([]setup.Agent, error) {
		return []setup.Agent{
			{
				Name:           "codex",
				DisplayName:    "Codex",
				ProjectRootDir: ".agents/skills",
				GlobalRootDir:  ".codex/skills",
				Universal:      true,
			},
		}, nil
	}
	state.install = func(setup.InstallConfig) (*setup.Result, error) {
		return &setup.Result{
			Successful: []setup.SuccessItem{
				{Skill: setup.Skill{Name: "cy-create-prd"}, Agent: setup.Agent{DisplayName: "Codex"}},
			},
		}, nil
	}
	state.writeREADME = func(_ string) error {
		readmeCalled = true
		return nil
	}
	state.yes = true
	state.global = true

	cmd := &cobra.Command{Use: "setup"}
	cmd.SetOut(&bytes.Buffer{})
	cmd.SetErr(&bytes.Buffer{})
	cmd.Flags().Bool("global", false, "global")
	cmd.Flags().Bool("copy", false, "copy")
	if err := cmd.Flags().Set("global", "true"); err != nil {
		t.Fatalf("set global flag: %v", err)
	}

	if err := state.run(cmd, nil); err != nil {
		t.Fatalf("setup run: %v", err)
	}

	if readmeCalled {
		t.Error("writeREADME should not be called for global installs")
	}
}
