package loop

const (
	metadataLoopRunIDKey       = "loop_run_id"
	metadataGenerationKey      = "generation"
	metadataNodeIDKey          = "node_id"
	metadataItemIndexKey       = "item_index"
	attentionDependencyFlag    = "dependency_quarantined"
	loopTaskAttentionActorRef  = "loop-coordinator"
	targetBreakerStateOpen     = "open"
	targetBreakerStateHalfOpen = "half_open"
	targetBreakerStateClosed   = "closed"
	namespaceInputsKey         = "inputs"
	namespaceNodesKey          = "nodes"
	namespaceOutputKey         = "output"
	namespaceScoreKey          = "score"
	namespacePreviousKey       = "previous"
	namespaceBestKey           = "best"
	namespaceStatusKey         = "status"
	namespaceFailureKey        = "failure"
	namespaceDispositionKey    = "disposition"
	namespaceOutcomeKey        = "outcome"
	namespaceVerdictsKey       = "verdicts"
	namespaceRouteCausesKey    = "route_causes"
	namespaceBlockingIssuesKey = "blocking_issues"
	namespaceCriteriaKey       = "criteria"
	jsonSchemaItemsKey         = "items"
	transformValueKey          = "value"
)
