package loop

import "github.com/compozy/agh/internal/hooks"

var phaseBWatchEvents = []WatchEventsContract{
	// automation_runs is rowid-cursored and workspace-scoped by joining the run's job/trigger
	// plus loop_run fallback; the run row has no workspace_id column.
	{
		Kind:        hooks.HookAutomationRunCompleted,
		Stream:      watchEventsAutomationStream,
		LedgerTypes: []string{string(hooks.HookAutomationRunCompleted)},
		PayloadFields: []string{
			watchEventsPayloadJobID,
			watchEventsPayloadTriggerID,
			watchEventsPayloadAgentName,
			watchEventsFieldSessionID,
			watchEventsPayloadAttempt,
			watchEventsPayloadDurationMS,
		},
	},
	{
		Kind:        hooks.HookAutomationRunFailed,
		Stream:      watchEventsAutomationStream,
		LedgerTypes: []string{string(hooks.HookAutomationRunFailed)},
		PayloadFields: []string{
			watchEventsPayloadJobID,
			watchEventsPayloadTriggerID,
			watchEventsPayloadAgentName,
			watchEventsFieldSessionID,
			watchEventsPayloadAttempt,
			watchEventsPayloadError,
			watchEventsPayloadWillRetry,
		},
	},
	// network_timeline_log is rowid-cursored and workspace-scoped directly by its workspace_id
	// column; work events reconstruct the co-durable network_work state for the timeline row.
	{
		Kind:        hooks.HookNetworkMessagePersisted,
		Stream:      watchEventsNetworkStream,
		LedgerTypes: []string{string(hooks.HookNetworkMessagePersisted)},
		PayloadFields: []string{
			watchEventsFieldSessionID,
			watchEventsFieldChannel,
			watchEventsPayloadSurface,
			watchEventsPayloadThreadID,
			watchEventsPayloadDirectID,
			watchEventsPayloadMessageID,
			actionKindMetaKey,
			watchEventsPayloadDirection,
			watchEventsFieldWorkID,
			watchEventsPayloadWorkState,
			watchEventsPayloadPeerFrom,
			watchEventsPayloadPeerTo,
			watchEventsPayloadTraceID,
			watchEventsPayloadCausationID,
		},
	},
	{
		Kind:        hooks.HookNetworkThreadOpened,
		Stream:      watchEventsNetworkStream,
		LedgerTypes: []string{string(hooks.HookNetworkThreadOpened)},
		PayloadFields: []string{
			watchEventsFieldSessionID,
			watchEventsFieldChannel,
			watchEventsPayloadSurface,
			watchEventsPayloadThreadID,
			watchEventsPayloadMessageID,
			actionKindMetaKey,
			watchEventsPayloadDirection,
			watchEventsPayloadPeerFrom,
			watchEventsPayloadPeerTo,
		},
	},
	{
		Kind:        hooks.HookNetworkDirectRoomOpened,
		Stream:      watchEventsNetworkStream,
		LedgerTypes: []string{string(hooks.HookNetworkDirectRoomOpened)},
		PayloadFields: []string{
			watchEventsFieldSessionID,
			watchEventsFieldChannel,
			watchEventsPayloadSurface,
			watchEventsPayloadDirectID,
			watchEventsPayloadMessageID,
			actionKindMetaKey,
			watchEventsPayloadDirection,
			watchEventsPayloadPeerFrom,
			watchEventsPayloadPeerTo,
		},
	},
	{
		Kind:        hooks.HookNetworkWorkOpened,
		Stream:      watchEventsNetworkStream,
		LedgerTypes: []string{string(hooks.HookNetworkWorkOpened)},
		PayloadFields: []string{
			watchEventsFieldSessionID,
			watchEventsFieldChannel,
			watchEventsPayloadSurface,
			watchEventsPayloadThreadID,
			watchEventsPayloadDirectID,
			watchEventsPayloadMessageID,
			actionKindMetaKey,
			watchEventsPayloadDirection,
			watchEventsFieldWorkID,
			watchEventsPayloadWorkState,
			watchEventsPayloadPeerFrom,
			watchEventsPayloadPeerTo,
			watchEventsPayloadTraceID,
			watchEventsPayloadCausationID,
		},
	},
	{
		Kind:        hooks.HookNetworkWorkTransitioned,
		Stream:      watchEventsNetworkStream,
		LedgerTypes: []string{string(hooks.HookNetworkWorkTransitioned)},
		PayloadFields: []string{
			watchEventsFieldSessionID,
			watchEventsFieldChannel,
			watchEventsPayloadSurface,
			watchEventsPayloadThreadID,
			watchEventsPayloadDirectID,
			watchEventsPayloadMessageID,
			actionKindMetaKey,
			watchEventsPayloadDirection,
			watchEventsFieldWorkID,
			watchEventsPayloadWorkState,
			watchEventsPayloadPeerFrom,
			watchEventsPayloadPeerTo,
			watchEventsPayloadTraceID,
			watchEventsPayloadCausationID,
		},
	},
	{
		Kind:        hooks.HookNetworkWorkClosed,
		Stream:      watchEventsNetworkStream,
		LedgerTypes: []string{string(hooks.HookNetworkWorkClosed)},
		PayloadFields: []string{
			watchEventsFieldSessionID,
			watchEventsFieldChannel,
			watchEventsPayloadSurface,
			watchEventsPayloadThreadID,
			watchEventsPayloadDirectID,
			watchEventsPayloadMessageID,
			actionKindMetaKey,
			watchEventsPayloadDirection,
			watchEventsFieldWorkID,
			watchEventsPayloadWorkState,
			watchEventsPayloadPeerFrom,
			watchEventsPayloadPeerTo,
			watchEventsPayloadTraceID,
			watchEventsPayloadCausationID,
		},
	},
}
