// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: workflow/cmds.proto

package workflow

import (
	common "github.com/compozy/compozy/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowTriggerCommand struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Metadata      *common.Metadata                `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo            `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowTriggerCommand_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTriggerCommand) Reset() {
	*x = WorkflowTriggerCommand{}
	mi := &file_workflow_cmds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTriggerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTriggerCommand) ProtoMessage() {}

func (x *WorkflowTriggerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTriggerCommand.ProtoReflect.Descriptor instead.
func (*WorkflowTriggerCommand) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowTriggerCommand) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowTriggerCommand) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowTriggerCommand) GetPayload() *WorkflowTriggerCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowExecuteCommand struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Metadata      *common.Metadata                `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo            `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowExecuteCommand_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecuteCommand) Reset() {
	*x = WorkflowExecuteCommand{}
	mi := &file_workflow_cmds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecuteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecuteCommand) ProtoMessage() {}

func (x *WorkflowExecuteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecuteCommand.ProtoReflect.Descriptor instead.
func (*WorkflowExecuteCommand) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowExecuteCommand) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowExecuteCommand) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowExecuteCommand) GetPayload() *WorkflowExecuteCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowPauseCommand struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Metadata      *common.Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo          `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowPauseCommand_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowPauseCommand) Reset() {
	*x = WorkflowPauseCommand{}
	mi := &file_workflow_cmds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowPauseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowPauseCommand) ProtoMessage() {}

func (x *WorkflowPauseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowPauseCommand.ProtoReflect.Descriptor instead.
func (*WorkflowPauseCommand) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowPauseCommand) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowPauseCommand) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowPauseCommand) GetPayload() *WorkflowPauseCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowResumeCommand struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Metadata      *common.Metadata               `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo           `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowResumeCommand_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResumeCommand) Reset() {
	*x = WorkflowResumeCommand{}
	mi := &file_workflow_cmds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResumeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResumeCommand) ProtoMessage() {}

func (x *WorkflowResumeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResumeCommand.ProtoReflect.Descriptor instead.
func (*WorkflowResumeCommand) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowResumeCommand) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowResumeCommand) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowResumeCommand) GetPayload() *WorkflowResumeCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowCancelCommand struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Metadata      *common.Metadata               `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo           `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowCancelCommand_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowCancelCommand) Reset() {
	*x = WorkflowCancelCommand{}
	mi := &file_workflow_cmds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowCancelCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowCancelCommand) ProtoMessage() {}

func (x *WorkflowCancelCommand) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowCancelCommand.ProtoReflect.Descriptor instead.
func (*WorkflowCancelCommand) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowCancelCommand) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowCancelCommand) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowCancelCommand) GetPayload() *WorkflowCancelCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowTriggerCommand_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *structpb.Struct       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTriggerCommand_Payload) Reset() {
	*x = WorkflowTriggerCommand_Payload{}
	mi := &file_workflow_cmds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTriggerCommand_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTriggerCommand_Payload) ProtoMessage() {}

func (x *WorkflowTriggerCommand_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTriggerCommand_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowTriggerCommand_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WorkflowTriggerCommand_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowExecuteCommand_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *structpb.Struct       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecuteCommand_Payload) Reset() {
	*x = WorkflowExecuteCommand_Payload{}
	mi := &file_workflow_cmds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecuteCommand_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecuteCommand_Payload) ProtoMessage() {}

func (x *WorkflowExecuteCommand_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecuteCommand_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowExecuteCommand_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{1, 0}
}

func (x *WorkflowExecuteCommand_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowPauseCommand_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *structpb.Struct       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowPauseCommand_Payload) Reset() {
	*x = WorkflowPauseCommand_Payload{}
	mi := &file_workflow_cmds_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowPauseCommand_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowPauseCommand_Payload) ProtoMessage() {}

func (x *WorkflowPauseCommand_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowPauseCommand_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowPauseCommand_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{2, 0}
}

func (x *WorkflowPauseCommand_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowResumeCommand_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *structpb.Struct       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResumeCommand_Payload) Reset() {
	*x = WorkflowResumeCommand_Payload{}
	mi := &file_workflow_cmds_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResumeCommand_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResumeCommand_Payload) ProtoMessage() {}

func (x *WorkflowResumeCommand_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResumeCommand_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowResumeCommand_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{3, 0}
}

func (x *WorkflowResumeCommand_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowCancelCommand_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *structpb.Struct       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowCancelCommand_Payload) Reset() {
	*x = WorkflowCancelCommand_Payload{}
	mi := &file_workflow_cmds_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowCancelCommand_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowCancelCommand_Payload) ProtoMessage() {}

func (x *WorkflowCancelCommand_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowCancelCommand_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowCancelCommand_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{4, 0}
}

func (x *WorkflowCancelCommand_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_workflow_cmds_proto protoreflect.FileDescriptor

const file_workflow_cmds_proto_rawDesc = "" +
	"\n" +
	"\x13workflow/cmds.proto\x12\bworkflow\x1a\x15common/entities.proto\x1a\x15common/metadata.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfa\x01\n" +
	"\x16WorkflowTriggerCommand\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12B\n" +
	"\apayload\x18\x03 \x01(\v2(.workflow.WorkflowTriggerCommand.PayloadR\apayload\x1a<\n" +
	"\aPayload\x121\n" +
	"\acontext\x18\x01 \x01(\v2\x17.google.protobuf.StructR\acontext\"\xfa\x01\n" +
	"\x16WorkflowExecuteCommand\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12B\n" +
	"\apayload\x18\x03 \x01(\v2(.workflow.WorkflowExecuteCommand.PayloadR\apayload\x1a<\n" +
	"\aPayload\x121\n" +
	"\acontext\x18\x01 \x01(\v2\x17.google.protobuf.StructR\acontext\"\xf6\x01\n" +
	"\x14WorkflowPauseCommand\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12@\n" +
	"\apayload\x18\x03 \x01(\v2&.workflow.WorkflowPauseCommand.PayloadR\apayload\x1a<\n" +
	"\aPayload\x121\n" +
	"\acontext\x18\x01 \x01(\v2\x17.google.protobuf.StructR\acontext\"\xf8\x01\n" +
	"\x15WorkflowResumeCommand\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12A\n" +
	"\apayload\x18\x03 \x01(\v2'.workflow.WorkflowResumeCommand.PayloadR\apayload\x1a<\n" +
	"\aPayload\x121\n" +
	"\acontext\x18\x01 \x01(\v2\x17.google.protobuf.StructR\acontext\"\xf8\x01\n" +
	"\x15WorkflowCancelCommand\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12A\n" +
	"\apayload\x18\x03 \x01(\v2'.workflow.WorkflowCancelCommand.PayloadR\apayload\x1a<\n" +
	"\aPayload\x121\n" +
	"\acontext\x18\x01 \x01(\v2\x17.google.protobuf.StructR\acontextB,Z*github.com/compozy/compozy/pkg/pb/workflowb\x06proto3"

var (
	file_workflow_cmds_proto_rawDescOnce sync.Once
	file_workflow_cmds_proto_rawDescData []byte
)

func file_workflow_cmds_proto_rawDescGZIP() []byte {
	file_workflow_cmds_proto_rawDescOnce.Do(func() {
		file_workflow_cmds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_cmds_proto_rawDesc), len(file_workflow_cmds_proto_rawDesc)))
	})
	return file_workflow_cmds_proto_rawDescData
}

var file_workflow_cmds_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_workflow_cmds_proto_goTypes = []any{
	(*WorkflowTriggerCommand)(nil),         // 0: workflow.WorkflowTriggerCommand
	(*WorkflowExecuteCommand)(nil),         // 1: workflow.WorkflowExecuteCommand
	(*WorkflowPauseCommand)(nil),           // 2: workflow.WorkflowPauseCommand
	(*WorkflowResumeCommand)(nil),          // 3: workflow.WorkflowResumeCommand
	(*WorkflowCancelCommand)(nil),          // 4: workflow.WorkflowCancelCommand
	(*WorkflowTriggerCommand_Payload)(nil), // 5: workflow.WorkflowTriggerCommand.Payload
	(*WorkflowExecuteCommand_Payload)(nil), // 6: workflow.WorkflowExecuteCommand.Payload
	(*WorkflowPauseCommand_Payload)(nil),   // 7: workflow.WorkflowPauseCommand.Payload
	(*WorkflowResumeCommand_Payload)(nil),  // 8: workflow.WorkflowResumeCommand.Payload
	(*WorkflowCancelCommand_Payload)(nil),  // 9: workflow.WorkflowCancelCommand.Payload
	(*common.Metadata)(nil),                // 10: common.Metadata
	(*common.WorkflowInfo)(nil),            // 11: common.WorkflowInfo
	(*structpb.Struct)(nil),                // 12: google.protobuf.Struct
}
var file_workflow_cmds_proto_depIdxs = []int32{
	10, // 0: workflow.WorkflowTriggerCommand.metadata:type_name -> common.Metadata
	11, // 1: workflow.WorkflowTriggerCommand.workflow:type_name -> common.WorkflowInfo
	5,  // 2: workflow.WorkflowTriggerCommand.payload:type_name -> workflow.WorkflowTriggerCommand.Payload
	10, // 3: workflow.WorkflowExecuteCommand.metadata:type_name -> common.Metadata
	11, // 4: workflow.WorkflowExecuteCommand.workflow:type_name -> common.WorkflowInfo
	6,  // 5: workflow.WorkflowExecuteCommand.payload:type_name -> workflow.WorkflowExecuteCommand.Payload
	10, // 6: workflow.WorkflowPauseCommand.metadata:type_name -> common.Metadata
	11, // 7: workflow.WorkflowPauseCommand.workflow:type_name -> common.WorkflowInfo
	7,  // 8: workflow.WorkflowPauseCommand.payload:type_name -> workflow.WorkflowPauseCommand.Payload
	10, // 9: workflow.WorkflowResumeCommand.metadata:type_name -> common.Metadata
	11, // 10: workflow.WorkflowResumeCommand.workflow:type_name -> common.WorkflowInfo
	8,  // 11: workflow.WorkflowResumeCommand.payload:type_name -> workflow.WorkflowResumeCommand.Payload
	10, // 12: workflow.WorkflowCancelCommand.metadata:type_name -> common.Metadata
	11, // 13: workflow.WorkflowCancelCommand.workflow:type_name -> common.WorkflowInfo
	9,  // 14: workflow.WorkflowCancelCommand.payload:type_name -> workflow.WorkflowCancelCommand.Payload
	12, // 15: workflow.WorkflowTriggerCommand.Payload.context:type_name -> google.protobuf.Struct
	12, // 16: workflow.WorkflowExecuteCommand.Payload.context:type_name -> google.protobuf.Struct
	12, // 17: workflow.WorkflowPauseCommand.Payload.context:type_name -> google.protobuf.Struct
	12, // 18: workflow.WorkflowResumeCommand.Payload.context:type_name -> google.protobuf.Struct
	12, // 19: workflow.WorkflowCancelCommand.Payload.context:type_name -> google.protobuf.Struct
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_workflow_cmds_proto_init() }
func file_workflow_cmds_proto_init() {
	if File_workflow_cmds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_cmds_proto_rawDesc), len(file_workflow_cmds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_cmds_proto_goTypes,
		DependencyIndexes: file_workflow_cmds_proto_depIdxs,
		MessageInfos:      file_workflow_cmds_proto_msgTypes,
	}.Build()
	File_workflow_cmds_proto = out.File
	file_workflow_cmds_proto_goTypes = nil
	file_workflow_cmds_proto_depIdxs = nil
}
