// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: workflow/cmds.proto

package workflow

import (
	common "github.com/compozy/compozy/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowTriggerCommand struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Metadata      *common.Metadata                `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo            `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowTriggerCommand_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTriggerCommand) Reset() {
	*x = WorkflowTriggerCommand{}
	mi := &file_workflow_cmds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTriggerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTriggerCommand) ProtoMessage() {}

func (x *WorkflowTriggerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTriggerCommand.ProtoReflect.Descriptor instead.
func (*WorkflowTriggerCommand) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowTriggerCommand) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowTriggerCommand) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowTriggerCommand) GetPayload() *WorkflowTriggerCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowTriggerAsyncCommand struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Metadata      *common.Metadata                     `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo                 `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowTriggerAsyncCommand_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTriggerAsyncCommand) Reset() {
	*x = WorkflowTriggerAsyncCommand{}
	mi := &file_workflow_cmds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTriggerAsyncCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTriggerAsyncCommand) ProtoMessage() {}

func (x *WorkflowTriggerAsyncCommand) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTriggerAsyncCommand.ProtoReflect.Descriptor instead.
func (*WorkflowTriggerAsyncCommand) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowTriggerAsyncCommand) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowTriggerAsyncCommand) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowTriggerAsyncCommand) GetPayload() *WorkflowTriggerAsyncCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowExecuteCommand struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Metadata      *common.Metadata                `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo            `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowExecuteCommand_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecuteCommand) Reset() {
	*x = WorkflowExecuteCommand{}
	mi := &file_workflow_cmds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecuteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecuteCommand) ProtoMessage() {}

func (x *WorkflowExecuteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecuteCommand.ProtoReflect.Descriptor instead.
func (*WorkflowExecuteCommand) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowExecuteCommand) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowExecuteCommand) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowExecuteCommand) GetPayload() *WorkflowExecuteCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowPauseCommand struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Metadata      *common.Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo          `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowPauseCommand_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowPauseCommand) Reset() {
	*x = WorkflowPauseCommand{}
	mi := &file_workflow_cmds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowPauseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowPauseCommand) ProtoMessage() {}

func (x *WorkflowPauseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowPauseCommand.ProtoReflect.Descriptor instead.
func (*WorkflowPauseCommand) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowPauseCommand) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowPauseCommand) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowPauseCommand) GetPayload() *WorkflowPauseCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowResumeCommand struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Metadata      *common.Metadata               `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo           `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowResumeCommand_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResumeCommand) Reset() {
	*x = WorkflowResumeCommand{}
	mi := &file_workflow_cmds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResumeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResumeCommand) ProtoMessage() {}

func (x *WorkflowResumeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResumeCommand.ProtoReflect.Descriptor instead.
func (*WorkflowResumeCommand) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowResumeCommand) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowResumeCommand) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowResumeCommand) GetPayload() *WorkflowResumeCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowCancelCommand struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Metadata      *common.Metadata               `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo           `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowCancelCommand_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowCancelCommand) Reset() {
	*x = WorkflowCancelCommand{}
	mi := &file_workflow_cmds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowCancelCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowCancelCommand) ProtoMessage() {}

func (x *WorkflowCancelCommand) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowCancelCommand.ProtoReflect.Descriptor instead.
func (*WorkflowCancelCommand) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowCancelCommand) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowCancelCommand) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowCancelCommand) GetPayload() *WorkflowCancelCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowTriggerCommand_Payload struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Context       *WorkflowTriggerCommand_Payload_Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTriggerCommand_Payload) Reset() {
	*x = WorkflowTriggerCommand_Payload{}
	mi := &file_workflow_cmds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTriggerCommand_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTriggerCommand_Payload) ProtoMessage() {}

func (x *WorkflowTriggerCommand_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTriggerCommand_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowTriggerCommand_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WorkflowTriggerCommand_Payload) GetContext() *WorkflowTriggerCommand_Payload_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowTriggerCommand_Payload_Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerInput  *structpb.Struct       `protobuf:"bytes,1,opt,name=trigger_input,json=triggerInput,proto3" json:"trigger_input,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTriggerCommand_Payload_Context) Reset() {
	*x = WorkflowTriggerCommand_Payload_Context{}
	mi := &file_workflow_cmds_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTriggerCommand_Payload_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTriggerCommand_Payload_Context) ProtoMessage() {}

func (x *WorkflowTriggerCommand_Payload_Context) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTriggerCommand_Payload_Context.ProtoReflect.Descriptor instead.
func (*WorkflowTriggerCommand_Payload_Context) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *WorkflowTriggerCommand_Payload_Context) GetTriggerInput() *structpb.Struct {
	if x != nil {
		return x.TriggerInput
	}
	return nil
}

func (x *WorkflowTriggerCommand_Payload_Context) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type WorkflowTriggerAsyncCommand_Payload struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Context       *WorkflowTriggerAsyncCommand_Payload_Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTriggerAsyncCommand_Payload) Reset() {
	*x = WorkflowTriggerAsyncCommand_Payload{}
	mi := &file_workflow_cmds_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTriggerAsyncCommand_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTriggerAsyncCommand_Payload) ProtoMessage() {}

func (x *WorkflowTriggerAsyncCommand_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTriggerAsyncCommand_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowTriggerAsyncCommand_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{1, 0}
}

func (x *WorkflowTriggerAsyncCommand_Payload) GetContext() *WorkflowTriggerAsyncCommand_Payload_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowTriggerAsyncCommand_Payload_Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerInput  *structpb.Struct       `protobuf:"bytes,1,opt,name=trigger_input,json=triggerInput,proto3" json:"trigger_input,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTriggerAsyncCommand_Payload_Context) Reset() {
	*x = WorkflowTriggerAsyncCommand_Payload_Context{}
	mi := &file_workflow_cmds_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTriggerAsyncCommand_Payload_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTriggerAsyncCommand_Payload_Context) ProtoMessage() {}

func (x *WorkflowTriggerAsyncCommand_Payload_Context) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTriggerAsyncCommand_Payload_Context.ProtoReflect.Descriptor instead.
func (*WorkflowTriggerAsyncCommand_Payload_Context) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *WorkflowTriggerAsyncCommand_Payload_Context) GetTriggerInput() *structpb.Struct {
	if x != nil {
		return x.TriggerInput
	}
	return nil
}

func (x *WorkflowTriggerAsyncCommand_Payload_Context) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type WorkflowExecuteCommand_Payload struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Context       *WorkflowExecuteCommand_Payload_Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecuteCommand_Payload) Reset() {
	*x = WorkflowExecuteCommand_Payload{}
	mi := &file_workflow_cmds_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecuteCommand_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecuteCommand_Payload) ProtoMessage() {}

func (x *WorkflowExecuteCommand_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecuteCommand_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowExecuteCommand_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{2, 0}
}

func (x *WorkflowExecuteCommand_Payload) GetContext() *WorkflowExecuteCommand_Payload_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowExecuteCommand_Payload_Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialInput  *structpb.Struct       `protobuf:"bytes,1,opt,name=initial_input,json=initialInput,proto3" json:"initial_input,omitempty"`
	ResolvedEnv   map[string]string      `protobuf:"bytes,2,rep,name=resolved_env,json=resolvedEnv,proto3" json:"resolved_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TriggerType   *string                `protobuf:"bytes,3,opt,name=trigger_type,json=triggerType,proto3,oneof" json:"trigger_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecuteCommand_Payload_Context) Reset() {
	*x = WorkflowExecuteCommand_Payload_Context{}
	mi := &file_workflow_cmds_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecuteCommand_Payload_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecuteCommand_Payload_Context) ProtoMessage() {}

func (x *WorkflowExecuteCommand_Payload_Context) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecuteCommand_Payload_Context.ProtoReflect.Descriptor instead.
func (*WorkflowExecuteCommand_Payload_Context) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *WorkflowExecuteCommand_Payload_Context) GetInitialInput() *structpb.Struct {
	if x != nil {
		return x.InitialInput
	}
	return nil
}

func (x *WorkflowExecuteCommand_Payload_Context) GetResolvedEnv() map[string]string {
	if x != nil {
		return x.ResolvedEnv
	}
	return nil
}

func (x *WorkflowExecuteCommand_Payload_Context) GetTriggerType() string {
	if x != nil && x.TriggerType != nil {
		return *x.TriggerType
	}
	return ""
}

type WorkflowPauseCommand_Payload struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Context       *WorkflowPauseCommand_Payload_Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowPauseCommand_Payload) Reset() {
	*x = WorkflowPauseCommand_Payload{}
	mi := &file_workflow_cmds_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowPauseCommand_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowPauseCommand_Payload) ProtoMessage() {}

func (x *WorkflowPauseCommand_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowPauseCommand_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowPauseCommand_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{3, 0}
}

func (x *WorkflowPauseCommand_Payload) GetContext() *WorkflowPauseCommand_Payload_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowPauseCommand_Payload_Context struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Reason              string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	PausedBy            *string                `protobuf:"bytes,2,opt,name=paused_by,json=pausedBy,proto3,oneof" json:"paused_by,omitempty"`
	EstimatedDurationMs *int64                 `protobuf:"varint,3,opt,name=estimated_duration_ms,json=estimatedDurationMs,proto3,oneof" json:"estimated_duration_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WorkflowPauseCommand_Payload_Context) Reset() {
	*x = WorkflowPauseCommand_Payload_Context{}
	mi := &file_workflow_cmds_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowPauseCommand_Payload_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowPauseCommand_Payload_Context) ProtoMessage() {}

func (x *WorkflowPauseCommand_Payload_Context) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowPauseCommand_Payload_Context.ProtoReflect.Descriptor instead.
func (*WorkflowPauseCommand_Payload_Context) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *WorkflowPauseCommand_Payload_Context) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *WorkflowPauseCommand_Payload_Context) GetPausedBy() string {
	if x != nil && x.PausedBy != nil {
		return *x.PausedBy
	}
	return ""
}

func (x *WorkflowPauseCommand_Payload_Context) GetEstimatedDurationMs() int64 {
	if x != nil && x.EstimatedDurationMs != nil {
		return *x.EstimatedDurationMs
	}
	return 0
}

type WorkflowResumeCommand_Payload struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	ResumeData    *structpb.Struct                       `protobuf:"bytes,1,opt,name=resume_data,json=resumeData,proto3,oneof" json:"resume_data,omitempty"`
	Context       *WorkflowResumeCommand_Payload_Context `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResumeCommand_Payload) Reset() {
	*x = WorkflowResumeCommand_Payload{}
	mi := &file_workflow_cmds_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResumeCommand_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResumeCommand_Payload) ProtoMessage() {}

func (x *WorkflowResumeCommand_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResumeCommand_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowResumeCommand_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{4, 0}
}

func (x *WorkflowResumeCommand_Payload) GetResumeData() *structpb.Struct {
	if x != nil {
		return x.ResumeData
	}
	return nil
}

func (x *WorkflowResumeCommand_Payload) GetContext() *WorkflowResumeCommand_Payload_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowResumeCommand_Payload_Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumedBy     *string                `protobuf:"bytes,1,opt,name=resumed_by,json=resumedBy,proto3,oneof" json:"resumed_by,omitempty"`
	ResumedAt     *string                `protobuf:"bytes,2,opt,name=resumed_at,json=resumedAt,proto3,oneof" json:"resumed_at,omitempty"` // ISO8601 timestamp
	Reason        *string                `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResumeCommand_Payload_Context) Reset() {
	*x = WorkflowResumeCommand_Payload_Context{}
	mi := &file_workflow_cmds_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResumeCommand_Payload_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResumeCommand_Payload_Context) ProtoMessage() {}

func (x *WorkflowResumeCommand_Payload_Context) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResumeCommand_Payload_Context.ProtoReflect.Descriptor instead.
func (*WorkflowResumeCommand_Payload_Context) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *WorkflowResumeCommand_Payload_Context) GetResumedBy() string {
	if x != nil && x.ResumedBy != nil {
		return *x.ResumedBy
	}
	return ""
}

func (x *WorkflowResumeCommand_Payload_Context) GetResumedAt() string {
	if x != nil && x.ResumedAt != nil {
		return *x.ResumedAt
	}
	return ""
}

func (x *WorkflowResumeCommand_Payload_Context) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type WorkflowCancelCommand_Payload struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Context       *WorkflowCancelCommand_Payload_Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowCancelCommand_Payload) Reset() {
	*x = WorkflowCancelCommand_Payload{}
	mi := &file_workflow_cmds_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowCancelCommand_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowCancelCommand_Payload) ProtoMessage() {}

func (x *WorkflowCancelCommand_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowCancelCommand_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowCancelCommand_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{5, 0}
}

func (x *WorkflowCancelCommand_Payload) GetContext() *WorkflowCancelCommand_Payload_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowCancelCommand_Payload_Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	CancelledBy   *string                `protobuf:"bytes,2,opt,name=cancelled_by,json=cancelledBy,proto3,oneof" json:"cancelled_by,omitempty"`
	CancelledAt   *string                `protobuf:"bytes,3,opt,name=cancelled_at,json=cancelledAt,proto3,oneof" json:"cancelled_at,omitempty"` // ISO8601 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowCancelCommand_Payload_Context) Reset() {
	*x = WorkflowCancelCommand_Payload_Context{}
	mi := &file_workflow_cmds_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowCancelCommand_Payload_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowCancelCommand_Payload_Context) ProtoMessage() {}

func (x *WorkflowCancelCommand_Payload_Context) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_cmds_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowCancelCommand_Payload_Context.ProtoReflect.Descriptor instead.
func (*WorkflowCancelCommand_Payload_Context) Descriptor() ([]byte, []int) {
	return file_workflow_cmds_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *WorkflowCancelCommand_Payload_Context) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *WorkflowCancelCommand_Payload_Context) GetCancelledBy() string {
	if x != nil && x.CancelledBy != nil {
		return *x.CancelledBy
	}
	return ""
}

func (x *WorkflowCancelCommand_Payload_Context) GetCancelledAt() string {
	if x != nil && x.CancelledAt != nil {
		return *x.CancelledAt
	}
	return ""
}

var File_workflow_cmds_proto protoreflect.FileDescriptor

const file_workflow_cmds_proto_rawDesc = "" +
	"\n" +
	"\x13workflow/cmds.proto\x12\bworkflow\x1a\x15common/metadata.proto\x1a\x15common/entities.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xe3\x03\n" +
	"\x16WorkflowTriggerCommand\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12B\n" +
	"\apayload\x18\x03 \x01(\v2(.workflow.WorkflowTriggerCommand.PayloadR\apayload\x1a\xa4\x02\n" +
	"\aPayload\x12J\n" +
	"\acontext\x18\x01 \x01(\v20.workflow.WorkflowTriggerCommand.Payload.ContextR\acontext\x1a\xcc\x01\n" +
	"\aContext\x12<\n" +
	"\rtrigger_input\x18\x01 \x01(\v2\x17.google.protobuf.StructR\ftriggerInput\x12K\n" +
	"\x03env\x18\x02 \x03(\v29.workflow.WorkflowTriggerCommand.Payload.Context.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x03\n" +
	"\x1bWorkflowTriggerAsyncCommand\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12G\n" +
	"\apayload\x18\x03 \x01(\v2-.workflow.WorkflowTriggerAsyncCommand.PayloadR\apayload\x1a\xae\x02\n" +
	"\aPayload\x12O\n" +
	"\acontext\x18\x01 \x01(\v25.workflow.WorkflowTriggerAsyncCommand.Payload.ContextR\acontext\x1a\xd1\x01\n" +
	"\aContext\x12<\n" +
	"\rtrigger_input\x18\x01 \x01(\v2\x17.google.protobuf.StructR\ftriggerInput\x12P\n" +
	"\x03env\x18\x02 \x03(\v2>.workflow.WorkflowTriggerAsyncCommand.Payload.Context.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x04\n" +
	"\x16WorkflowExecuteCommand\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12B\n" +
	"\apayload\x18\x03 \x01(\v2(.workflow.WorkflowExecuteCommand.PayloadR\apayload\x1a\xfe\x02\n" +
	"\aPayload\x12J\n" +
	"\acontext\x18\x01 \x01(\v20.workflow.WorkflowExecuteCommand.Payload.ContextR\acontext\x1a\xa6\x02\n" +
	"\aContext\x12<\n" +
	"\rinitial_input\x18\x01 \x01(\v2\x17.google.protobuf.StructR\finitialInput\x12d\n" +
	"\fresolved_env\x18\x02 \x03(\v2A.workflow.WorkflowExecuteCommand.Payload.Context.ResolvedEnvEntryR\vresolvedEnv\x12&\n" +
	"\ftrigger_type\x18\x03 \x01(\tH\x00R\vtriggerType\x88\x01\x01\x1a>\n" +
	"\x10ResolvedEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_trigger_type\"\xb5\x03\n" +
	"\x14WorkflowPauseCommand\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12@\n" +
	"\apayload\x18\x03 \x01(\v2&.workflow.WorkflowPauseCommand.PayloadR\apayload\x1a\xfa\x01\n" +
	"\aPayload\x12H\n" +
	"\acontext\x18\x01 \x01(\v2..workflow.WorkflowPauseCommand.Payload.ContextR\acontext\x1a\xa4\x01\n" +
	"\aContext\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12 \n" +
	"\tpaused_by\x18\x02 \x01(\tH\x00R\bpausedBy\x88\x01\x01\x127\n" +
	"\x15estimated_duration_ms\x18\x03 \x01(\x03H\x01R\x13estimatedDurationMs\x88\x01\x01B\f\n" +
	"\n" +
	"_paused_byB\x18\n" +
	"\x16_estimated_duration_ms\"\xfa\x03\n" +
	"\x15WorkflowResumeCommand\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12A\n" +
	"\apayload\x18\x03 \x01(\v2'.workflow.WorkflowResumeCommand.PayloadR\apayload\x1a\xbd\x02\n" +
	"\aPayload\x12=\n" +
	"\vresume_data\x18\x01 \x01(\v2\x17.google.protobuf.StructH\x00R\n" +
	"resumeData\x88\x01\x01\x12I\n" +
	"\acontext\x18\x02 \x01(\v2/.workflow.WorkflowResumeCommand.Payload.ContextR\acontext\x1a\x97\x01\n" +
	"\aContext\x12\"\n" +
	"\n" +
	"resumed_by\x18\x01 \x01(\tH\x00R\tresumedBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"resumed_at\x18\x02 \x01(\tH\x01R\tresumedAt\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tH\x02R\x06reason\x88\x01\x01B\r\n" +
	"\v_resumed_byB\r\n" +
	"\v_resumed_atB\t\n" +
	"\a_reasonB\x0e\n" +
	"\f_resume_data\"\xa7\x03\n" +
	"\x15WorkflowCancelCommand\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12A\n" +
	"\apayload\x18\x03 \x01(\v2'.workflow.WorkflowCancelCommand.PayloadR\apayload\x1a\xea\x01\n" +
	"\aPayload\x12I\n" +
	"\acontext\x18\x01 \x01(\v2/.workflow.WorkflowCancelCommand.Payload.ContextR\acontext\x1a\x93\x01\n" +
	"\aContext\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12&\n" +
	"\fcancelled_by\x18\x02 \x01(\tH\x00R\vcancelledBy\x88\x01\x01\x12&\n" +
	"\fcancelled_at\x18\x03 \x01(\tH\x01R\vcancelledAt\x88\x01\x01B\x0f\n" +
	"\r_cancelled_byB\x0f\n" +
	"\r_cancelled_atB,Z*github.com/compozy/compozy/pkg/pb/workflowb\x06proto3"

var (
	file_workflow_cmds_proto_rawDescOnce sync.Once
	file_workflow_cmds_proto_rawDescData []byte
)

func file_workflow_cmds_proto_rawDescGZIP() []byte {
	file_workflow_cmds_proto_rawDescOnce.Do(func() {
		file_workflow_cmds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_cmds_proto_rawDesc), len(file_workflow_cmds_proto_rawDesc)))
	})
	return file_workflow_cmds_proto_rawDescData
}

var file_workflow_cmds_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_workflow_cmds_proto_goTypes = []any{
	(*WorkflowTriggerCommand)(nil),                 // 0: workflow.WorkflowTriggerCommand
	(*WorkflowTriggerAsyncCommand)(nil),            // 1: workflow.WorkflowTriggerAsyncCommand
	(*WorkflowExecuteCommand)(nil),                 // 2: workflow.WorkflowExecuteCommand
	(*WorkflowPauseCommand)(nil),                   // 3: workflow.WorkflowPauseCommand
	(*WorkflowResumeCommand)(nil),                  // 4: workflow.WorkflowResumeCommand
	(*WorkflowCancelCommand)(nil),                  // 5: workflow.WorkflowCancelCommand
	(*WorkflowTriggerCommand_Payload)(nil),         // 6: workflow.WorkflowTriggerCommand.Payload
	(*WorkflowTriggerCommand_Payload_Context)(nil), // 7: workflow.WorkflowTriggerCommand.Payload.Context
	nil, // 8: workflow.WorkflowTriggerCommand.Payload.Context.EnvEntry
	(*WorkflowTriggerAsyncCommand_Payload)(nil),         // 9: workflow.WorkflowTriggerAsyncCommand.Payload
	(*WorkflowTriggerAsyncCommand_Payload_Context)(nil), // 10: workflow.WorkflowTriggerAsyncCommand.Payload.Context
	nil,                                    // 11: workflow.WorkflowTriggerAsyncCommand.Payload.Context.EnvEntry
	(*WorkflowExecuteCommand_Payload)(nil), // 12: workflow.WorkflowExecuteCommand.Payload
	(*WorkflowExecuteCommand_Payload_Context)(nil), // 13: workflow.WorkflowExecuteCommand.Payload.Context
	nil,                                  // 14: workflow.WorkflowExecuteCommand.Payload.Context.ResolvedEnvEntry
	(*WorkflowPauseCommand_Payload)(nil), // 15: workflow.WorkflowPauseCommand.Payload
	(*WorkflowPauseCommand_Payload_Context)(nil),  // 16: workflow.WorkflowPauseCommand.Payload.Context
	(*WorkflowResumeCommand_Payload)(nil),         // 17: workflow.WorkflowResumeCommand.Payload
	(*WorkflowResumeCommand_Payload_Context)(nil), // 18: workflow.WorkflowResumeCommand.Payload.Context
	(*WorkflowCancelCommand_Payload)(nil),         // 19: workflow.WorkflowCancelCommand.Payload
	(*WorkflowCancelCommand_Payload_Context)(nil), // 20: workflow.WorkflowCancelCommand.Payload.Context
	(*common.Metadata)(nil),                       // 21: common.Metadata
	(*common.WorkflowInfo)(nil),                   // 22: common.WorkflowInfo
	(*structpb.Struct)(nil),                       // 23: google.protobuf.Struct
}
var file_workflow_cmds_proto_depIdxs = []int32{
	21, // 0: workflow.WorkflowTriggerCommand.metadata:type_name -> common.Metadata
	22, // 1: workflow.WorkflowTriggerCommand.workflow:type_name -> common.WorkflowInfo
	6,  // 2: workflow.WorkflowTriggerCommand.payload:type_name -> workflow.WorkflowTriggerCommand.Payload
	21, // 3: workflow.WorkflowTriggerAsyncCommand.metadata:type_name -> common.Metadata
	22, // 4: workflow.WorkflowTriggerAsyncCommand.workflow:type_name -> common.WorkflowInfo
	9,  // 5: workflow.WorkflowTriggerAsyncCommand.payload:type_name -> workflow.WorkflowTriggerAsyncCommand.Payload
	21, // 6: workflow.WorkflowExecuteCommand.metadata:type_name -> common.Metadata
	22, // 7: workflow.WorkflowExecuteCommand.workflow:type_name -> common.WorkflowInfo
	12, // 8: workflow.WorkflowExecuteCommand.payload:type_name -> workflow.WorkflowExecuteCommand.Payload
	21, // 9: workflow.WorkflowPauseCommand.metadata:type_name -> common.Metadata
	22, // 10: workflow.WorkflowPauseCommand.workflow:type_name -> common.WorkflowInfo
	15, // 11: workflow.WorkflowPauseCommand.payload:type_name -> workflow.WorkflowPauseCommand.Payload
	21, // 12: workflow.WorkflowResumeCommand.metadata:type_name -> common.Metadata
	22, // 13: workflow.WorkflowResumeCommand.workflow:type_name -> common.WorkflowInfo
	17, // 14: workflow.WorkflowResumeCommand.payload:type_name -> workflow.WorkflowResumeCommand.Payload
	21, // 15: workflow.WorkflowCancelCommand.metadata:type_name -> common.Metadata
	22, // 16: workflow.WorkflowCancelCommand.workflow:type_name -> common.WorkflowInfo
	19, // 17: workflow.WorkflowCancelCommand.payload:type_name -> workflow.WorkflowCancelCommand.Payload
	7,  // 18: workflow.WorkflowTriggerCommand.Payload.context:type_name -> workflow.WorkflowTriggerCommand.Payload.Context
	23, // 19: workflow.WorkflowTriggerCommand.Payload.Context.trigger_input:type_name -> google.protobuf.Struct
	8,  // 20: workflow.WorkflowTriggerCommand.Payload.Context.env:type_name -> workflow.WorkflowTriggerCommand.Payload.Context.EnvEntry
	10, // 21: workflow.WorkflowTriggerAsyncCommand.Payload.context:type_name -> workflow.WorkflowTriggerAsyncCommand.Payload.Context
	23, // 22: workflow.WorkflowTriggerAsyncCommand.Payload.Context.trigger_input:type_name -> google.protobuf.Struct
	11, // 23: workflow.WorkflowTriggerAsyncCommand.Payload.Context.env:type_name -> workflow.WorkflowTriggerAsyncCommand.Payload.Context.EnvEntry
	13, // 24: workflow.WorkflowExecuteCommand.Payload.context:type_name -> workflow.WorkflowExecuteCommand.Payload.Context
	23, // 25: workflow.WorkflowExecuteCommand.Payload.Context.initial_input:type_name -> google.protobuf.Struct
	14, // 26: workflow.WorkflowExecuteCommand.Payload.Context.resolved_env:type_name -> workflow.WorkflowExecuteCommand.Payload.Context.ResolvedEnvEntry
	16, // 27: workflow.WorkflowPauseCommand.Payload.context:type_name -> workflow.WorkflowPauseCommand.Payload.Context
	23, // 28: workflow.WorkflowResumeCommand.Payload.resume_data:type_name -> google.protobuf.Struct
	18, // 29: workflow.WorkflowResumeCommand.Payload.context:type_name -> workflow.WorkflowResumeCommand.Payload.Context
	20, // 30: workflow.WorkflowCancelCommand.Payload.context:type_name -> workflow.WorkflowCancelCommand.Payload.Context
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_workflow_cmds_proto_init() }
func file_workflow_cmds_proto_init() {
	if File_workflow_cmds_proto != nil {
		return
	}
	file_workflow_cmds_proto_msgTypes[13].OneofWrappers = []any{}
	file_workflow_cmds_proto_msgTypes[16].OneofWrappers = []any{}
	file_workflow_cmds_proto_msgTypes[17].OneofWrappers = []any{}
	file_workflow_cmds_proto_msgTypes[18].OneofWrappers = []any{}
	file_workflow_cmds_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_cmds_proto_rawDesc), len(file_workflow_cmds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_cmds_proto_goTypes,
		DependencyIndexes: file_workflow_cmds_proto_depIdxs,
		MessageInfos:      file_workflow_cmds_proto_msgTypes,
	}.Build()
	File_workflow_cmds_proto = out.File
	file_workflow_cmds_proto_goTypes = nil
	file_workflow_cmds_proto_depIdxs = nil
}
