// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: workflow/events.proto

package workflow

import (
	common "github.com/compozy/compozy/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED WorkflowStatus = 0
	WorkflowStatus_WORKFLOW_STATUS_PENDING     WorkflowStatus = 1
	WorkflowStatus_WORKFLOW_STATUS_RUNNING     WorkflowStatus = 2
	WorkflowStatus_WORKFLOW_STATUS_WAITING     WorkflowStatus = 3
	WorkflowStatus_WORKFLOW_STATUS_SUCCESS     WorkflowStatus = 4
	WorkflowStatus_WORKFLOW_STATUS_FAILED      WorkflowStatus = 5
	WorkflowStatus_WORKFLOW_STATUS_TIMED_OUT   WorkflowStatus = 6
	WorkflowStatus_WORKFLOW_STATUS_CANCELLED   WorkflowStatus = 7
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_PENDING",
		2: "WORKFLOW_STATUS_RUNNING",
		3: "WORKFLOW_STATUS_WAITING",
		4: "WORKFLOW_STATUS_SUCCESS",
		5: "WORKFLOW_STATUS_FAILED",
		6: "WORKFLOW_STATUS_TIMED_OUT",
		7: "WORKFLOW_STATUS_CANCELLED",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED": 0,
		"WORKFLOW_STATUS_PENDING":     1,
		"WORKFLOW_STATUS_RUNNING":     2,
		"WORKFLOW_STATUS_WAITING":     3,
		"WORKFLOW_STATUS_SUCCESS":     4,
		"WORKFLOW_STATUS_FAILED":      5,
		"WORKFLOW_STATUS_TIMED_OUT":   6,
		"WORKFLOW_STATUS_CANCELLED":   7,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_events_proto_enumTypes[0].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_workflow_events_proto_enumTypes[0]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{0}
}

type WorkflowExecutionStartedEvent struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Metadata      *common.Metadata                       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo                   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowExecutionStartedEvent_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionStartedEvent) Reset() {
	*x = WorkflowExecutionStartedEvent{}
	mi := &file_workflow_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionStartedEvent) ProtoMessage() {}

func (x *WorkflowExecutionStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionStartedEvent.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionStartedEvent) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowExecutionStartedEvent) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowExecutionStartedEvent) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowExecutionStartedEvent) GetPayload() *WorkflowExecutionStartedEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowExecutionPausedEvent struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Metadata      *common.Metadata                      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo                  `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowExecutionPausedEvent_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionPausedEvent) Reset() {
	*x = WorkflowExecutionPausedEvent{}
	mi := &file_workflow_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionPausedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionPausedEvent) ProtoMessage() {}

func (x *WorkflowExecutionPausedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionPausedEvent.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionPausedEvent) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowExecutionPausedEvent) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowExecutionPausedEvent) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowExecutionPausedEvent) GetPayload() *WorkflowExecutionPausedEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowExecutionResumedEvent struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Metadata      *common.Metadata                       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo                   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowExecutionResumedEvent_Payload `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionResumedEvent) Reset() {
	*x = WorkflowExecutionResumedEvent{}
	mi := &file_workflow_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionResumedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionResumedEvent) ProtoMessage() {}

func (x *WorkflowExecutionResumedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionResumedEvent.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionResumedEvent) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowExecutionResumedEvent) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowExecutionResumedEvent) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowExecutionResumedEvent) GetPayload() *WorkflowExecutionResumedEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowExecutionSuccessEvent struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Metadata      *common.Metadata                       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo                   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowExecutionSuccessEvent_Payload `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionSuccessEvent) Reset() {
	*x = WorkflowExecutionSuccessEvent{}
	mi := &file_workflow_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionSuccessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionSuccessEvent) ProtoMessage() {}

func (x *WorkflowExecutionSuccessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionSuccessEvent.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionSuccessEvent) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowExecutionSuccessEvent) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowExecutionSuccessEvent) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowExecutionSuccessEvent) GetPayload() *WorkflowExecutionSuccessEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowExecutionFailedEvent struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Metadata      *common.Metadata                      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo                  `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowExecutionFailedEvent_Payload `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionFailedEvent) Reset() {
	*x = WorkflowExecutionFailedEvent{}
	mi := &file_workflow_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionFailedEvent) ProtoMessage() {}

func (x *WorkflowExecutionFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionFailedEvent.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionFailedEvent) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowExecutionFailedEvent) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowExecutionFailedEvent) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowExecutionFailedEvent) GetPayload() *WorkflowExecutionFailedEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowExecutionCancelledEvent struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Metadata      *common.Metadata                         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo                     `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowExecutionCancelledEvent_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionCancelledEvent) Reset() {
	*x = WorkflowExecutionCancelledEvent{}
	mi := &file_workflow_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionCancelledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionCancelledEvent) ProtoMessage() {}

func (x *WorkflowExecutionCancelledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionCancelledEvent.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionCancelledEvent) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowExecutionCancelledEvent) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowExecutionCancelledEvent) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowExecutionCancelledEvent) GetPayload() *WorkflowExecutionCancelledEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowExecutionTimedOutEvent struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Metadata      *common.Metadata                        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Workflow      *common.WorkflowInfo                    `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload       *WorkflowExecutionTimedOutEvent_Payload `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionTimedOutEvent) Reset() {
	*x = WorkflowExecutionTimedOutEvent{}
	mi := &file_workflow_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionTimedOutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionTimedOutEvent) ProtoMessage() {}

func (x *WorkflowExecutionTimedOutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionTimedOutEvent.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionTimedOutEvent) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowExecutionTimedOutEvent) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowExecutionTimedOutEvent) GetWorkflow() *common.WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowExecutionTimedOutEvent) GetPayload() *WorkflowExecutionTimedOutEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkflowExecutionStartedEvent_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflow.WorkflowStatus" json:"status,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionStartedEvent_Payload) Reset() {
	*x = WorkflowExecutionStartedEvent_Payload{}
	mi := &file_workflow_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionStartedEvent_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionStartedEvent_Payload) ProtoMessage() {}

func (x *WorkflowExecutionStartedEvent_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionStartedEvent_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionStartedEvent_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WorkflowExecutionStartedEvent_Payload) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowExecutionStartedEvent_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowExecutionPausedEvent_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflow.WorkflowStatus" json:"status,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionPausedEvent_Payload) Reset() {
	*x = WorkflowExecutionPausedEvent_Payload{}
	mi := &file_workflow_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionPausedEvent_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionPausedEvent_Payload) ProtoMessage() {}

func (x *WorkflowExecutionPausedEvent_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionPausedEvent_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionPausedEvent_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{1, 0}
}

func (x *WorkflowExecutionPausedEvent_Payload) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowExecutionPausedEvent_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type WorkflowExecutionResumedEvent_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflow.WorkflowStatus" json:"status,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionResumedEvent_Payload) Reset() {
	*x = WorkflowExecutionResumedEvent_Payload{}
	mi := &file_workflow_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionResumedEvent_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionResumedEvent_Payload) ProtoMessage() {}

func (x *WorkflowExecutionResumedEvent_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionResumedEvent_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionResumedEvent_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{2, 0}
}

func (x *WorkflowExecutionResumedEvent_Payload) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowExecutionResumedEvent_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WorkflowExecutionResumedEvent_Payload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type WorkflowExecutionSuccessEvent_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflow.WorkflowStatus" json:"status,omitempty"`
	Result        *common.Result         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionSuccessEvent_Payload) Reset() {
	*x = WorkflowExecutionSuccessEvent_Payload{}
	mi := &file_workflow_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionSuccessEvent_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionSuccessEvent_Payload) ProtoMessage() {}

func (x *WorkflowExecutionSuccessEvent_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionSuccessEvent_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionSuccessEvent_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{3, 0}
}

func (x *WorkflowExecutionSuccessEvent_Payload) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowExecutionSuccessEvent_Payload) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WorkflowExecutionSuccessEvent_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WorkflowExecutionSuccessEvent_Payload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type WorkflowExecutionFailedEvent_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflow.WorkflowStatus" json:"status,omitempty"`
	Result        *common.Result         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionFailedEvent_Payload) Reset() {
	*x = WorkflowExecutionFailedEvent_Payload{}
	mi := &file_workflow_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionFailedEvent_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionFailedEvent_Payload) ProtoMessage() {}

func (x *WorkflowExecutionFailedEvent_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionFailedEvent_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionFailedEvent_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{4, 0}
}

func (x *WorkflowExecutionFailedEvent_Payload) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowExecutionFailedEvent_Payload) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WorkflowExecutionFailedEvent_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WorkflowExecutionFailedEvent_Payload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type WorkflowExecutionCancelledEvent_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflow.WorkflowStatus" json:"status,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionCancelledEvent_Payload) Reset() {
	*x = WorkflowExecutionCancelledEvent_Payload{}
	mi := &file_workflow_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionCancelledEvent_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionCancelledEvent_Payload) ProtoMessage() {}

func (x *WorkflowExecutionCancelledEvent_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionCancelledEvent_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionCancelledEvent_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{5, 0}
}

func (x *WorkflowExecutionCancelledEvent_Payload) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowExecutionCancelledEvent_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WorkflowExecutionCancelledEvent_Payload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type WorkflowExecutionTimedOutEvent_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflow.WorkflowStatus" json:"status,omitempty"`
	Result        *common.Result         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionTimedOutEvent_Payload) Reset() {
	*x = WorkflowExecutionTimedOutEvent_Payload{}
	mi := &file_workflow_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionTimedOutEvent_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionTimedOutEvent_Payload) ProtoMessage() {}

func (x *WorkflowExecutionTimedOutEvent_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionTimedOutEvent_Payload.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionTimedOutEvent_Payload) Descriptor() ([]byte, []int) {
	return file_workflow_events_proto_rawDescGZIP(), []int{6, 0}
}

func (x *WorkflowExecutionTimedOutEvent_Payload) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowExecutionTimedOutEvent_Payload) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WorkflowExecutionTimedOutEvent_Payload) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WorkflowExecutionTimedOutEvent_Payload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_workflow_events_proto protoreflect.FileDescriptor

const file_workflow_events_proto_rawDesc = "" +
	"\n" +
	"\x15workflow/events.proto\x12\bworkflow\x1a\x15common/metadata.proto\x1a\x15common/entities.proto\x1a\x14common/payload.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xba\x02\n" +
	"\x1dWorkflowExecutionStartedEvent\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12I\n" +
	"\apayload\x18\x03 \x01(\v2/.workflow.WorkflowExecutionStartedEvent.PayloadR\apayload\x1an\n" +
	"\aPayload\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.workflow.WorkflowStatusR\x06status\x121\n" +
	"\acontext\x18\x02 \x01(\v2\x17.google.protobuf.StructR\acontext\"\xb8\x02\n" +
	"\x1cWorkflowExecutionPausedEvent\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12H\n" +
	"\apayload\x18\x03 \x01(\v2..workflow.WorkflowExecutionPausedEvent.PayloadR\apayload\x1an\n" +
	"\aPayload\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.workflow.WorkflowStatusR\x06status\x121\n" +
	"\acontext\x18\x02 \x01(\v2\x17.google.protobuf.StructR\acontext\"\xdc\x02\n" +
	"\x1dWorkflowExecutionResumedEvent\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12I\n" +
	"\apayload\x18\x04 \x01(\v2/.workflow.WorkflowExecutionResumedEvent.PayloadR\apayload\x1a\x8f\x01\n" +
	"\aPayload\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.workflow.WorkflowStatusR\x06status\x121\n" +
	"\acontext\x18\x02 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"\x84\x03\n" +
	"\x1dWorkflowExecutionSuccessEvent\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12I\n" +
	"\apayload\x18\x04 \x01(\v2/.workflow.WorkflowExecutionSuccessEvent.PayloadR\apayload\x1a\xb7\x01\n" +
	"\aPayload\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.workflow.WorkflowStatusR\x06status\x12&\n" +
	"\x06result\x18\x02 \x01(\v2\x0e.common.ResultR\x06result\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\x82\x03\n" +
	"\x1cWorkflowExecutionFailedEvent\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12H\n" +
	"\apayload\x18\x04 \x01(\v2..workflow.WorkflowExecutionFailedEvent.PayloadR\apayload\x1a\xb7\x01\n" +
	"\aPayload\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.workflow.WorkflowStatusR\x06status\x12&\n" +
	"\x06result\x18\x02 \x01(\v2\x0e.common.ResultR\x06result\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\xe0\x02\n" +
	"\x1fWorkflowExecutionCancelledEvent\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12K\n" +
	"\apayload\x18\x03 \x01(\v21.workflow.WorkflowExecutionCancelledEvent.PayloadR\apayload\x1a\x8f\x01\n" +
	"\aPayload\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.workflow.WorkflowStatusR\x06status\x121\n" +
	"\acontext\x18\x02 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"\x86\x03\n" +
	"\x1eWorkflowExecutionTimedOutEvent\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x120\n" +
	"\bworkflow\x18\x02 \x01(\v2\x14.common.WorkflowInfoR\bworkflow\x12J\n" +
	"\apayload\x18\x05 \x01(\v20.workflow.WorkflowExecutionTimedOutEvent.PayloadR\apayload\x1a\xb7\x01\n" +
	"\aPayload\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.workflow.WorkflowStatusR\x06status\x12&\n" +
	"\x06result\x18\x02 \x01(\v2\x0e.common.ResultR\x06result\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs*\xff\x01\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x02\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_WAITING\x10\x03\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_SUCCESS\x10\x04\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x05\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_TIMED_OUT\x10\x06\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_CANCELLED\x10\aB,Z*github.com/compozy/compozy/pkg/pb/workflowb\x06proto3"

var (
	file_workflow_events_proto_rawDescOnce sync.Once
	file_workflow_events_proto_rawDescData []byte
)

func file_workflow_events_proto_rawDescGZIP() []byte {
	file_workflow_events_proto_rawDescOnce.Do(func() {
		file_workflow_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_events_proto_rawDesc), len(file_workflow_events_proto_rawDesc)))
	})
	return file_workflow_events_proto_rawDescData
}

var file_workflow_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workflow_events_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_workflow_events_proto_goTypes = []any{
	(WorkflowStatus)(0),                             // 0: workflow.WorkflowStatus
	(*WorkflowExecutionStartedEvent)(nil),           // 1: workflow.WorkflowExecutionStartedEvent
	(*WorkflowExecutionPausedEvent)(nil),            // 2: workflow.WorkflowExecutionPausedEvent
	(*WorkflowExecutionResumedEvent)(nil),           // 3: workflow.WorkflowExecutionResumedEvent
	(*WorkflowExecutionSuccessEvent)(nil),           // 4: workflow.WorkflowExecutionSuccessEvent
	(*WorkflowExecutionFailedEvent)(nil),            // 5: workflow.WorkflowExecutionFailedEvent
	(*WorkflowExecutionCancelledEvent)(nil),         // 6: workflow.WorkflowExecutionCancelledEvent
	(*WorkflowExecutionTimedOutEvent)(nil),          // 7: workflow.WorkflowExecutionTimedOutEvent
	(*WorkflowExecutionStartedEvent_Payload)(nil),   // 8: workflow.WorkflowExecutionStartedEvent.Payload
	(*WorkflowExecutionPausedEvent_Payload)(nil),    // 9: workflow.WorkflowExecutionPausedEvent.Payload
	(*WorkflowExecutionResumedEvent_Payload)(nil),   // 10: workflow.WorkflowExecutionResumedEvent.Payload
	(*WorkflowExecutionSuccessEvent_Payload)(nil),   // 11: workflow.WorkflowExecutionSuccessEvent.Payload
	(*WorkflowExecutionFailedEvent_Payload)(nil),    // 12: workflow.WorkflowExecutionFailedEvent.Payload
	(*WorkflowExecutionCancelledEvent_Payload)(nil), // 13: workflow.WorkflowExecutionCancelledEvent.Payload
	(*WorkflowExecutionTimedOutEvent_Payload)(nil),  // 14: workflow.WorkflowExecutionTimedOutEvent.Payload
	(*common.Metadata)(nil),                         // 15: common.Metadata
	(*common.WorkflowInfo)(nil),                     // 16: common.WorkflowInfo
	(*structpb.Struct)(nil),                         // 17: google.protobuf.Struct
	(*common.Result)(nil),                           // 18: common.Result
}
var file_workflow_events_proto_depIdxs = []int32{
	15, // 0: workflow.WorkflowExecutionStartedEvent.metadata:type_name -> common.Metadata
	16, // 1: workflow.WorkflowExecutionStartedEvent.workflow:type_name -> common.WorkflowInfo
	8,  // 2: workflow.WorkflowExecutionStartedEvent.payload:type_name -> workflow.WorkflowExecutionStartedEvent.Payload
	15, // 3: workflow.WorkflowExecutionPausedEvent.metadata:type_name -> common.Metadata
	16, // 4: workflow.WorkflowExecutionPausedEvent.workflow:type_name -> common.WorkflowInfo
	9,  // 5: workflow.WorkflowExecutionPausedEvent.payload:type_name -> workflow.WorkflowExecutionPausedEvent.Payload
	15, // 6: workflow.WorkflowExecutionResumedEvent.metadata:type_name -> common.Metadata
	16, // 7: workflow.WorkflowExecutionResumedEvent.workflow:type_name -> common.WorkflowInfo
	10, // 8: workflow.WorkflowExecutionResumedEvent.payload:type_name -> workflow.WorkflowExecutionResumedEvent.Payload
	15, // 9: workflow.WorkflowExecutionSuccessEvent.metadata:type_name -> common.Metadata
	16, // 10: workflow.WorkflowExecutionSuccessEvent.workflow:type_name -> common.WorkflowInfo
	11, // 11: workflow.WorkflowExecutionSuccessEvent.payload:type_name -> workflow.WorkflowExecutionSuccessEvent.Payload
	15, // 12: workflow.WorkflowExecutionFailedEvent.metadata:type_name -> common.Metadata
	16, // 13: workflow.WorkflowExecutionFailedEvent.workflow:type_name -> common.WorkflowInfo
	12, // 14: workflow.WorkflowExecutionFailedEvent.payload:type_name -> workflow.WorkflowExecutionFailedEvent.Payload
	15, // 15: workflow.WorkflowExecutionCancelledEvent.metadata:type_name -> common.Metadata
	16, // 16: workflow.WorkflowExecutionCancelledEvent.workflow:type_name -> common.WorkflowInfo
	13, // 17: workflow.WorkflowExecutionCancelledEvent.payload:type_name -> workflow.WorkflowExecutionCancelledEvent.Payload
	15, // 18: workflow.WorkflowExecutionTimedOutEvent.metadata:type_name -> common.Metadata
	16, // 19: workflow.WorkflowExecutionTimedOutEvent.workflow:type_name -> common.WorkflowInfo
	14, // 20: workflow.WorkflowExecutionTimedOutEvent.payload:type_name -> workflow.WorkflowExecutionTimedOutEvent.Payload
	0,  // 21: workflow.WorkflowExecutionStartedEvent.Payload.status:type_name -> workflow.WorkflowStatus
	17, // 22: workflow.WorkflowExecutionStartedEvent.Payload.context:type_name -> google.protobuf.Struct
	0,  // 23: workflow.WorkflowExecutionPausedEvent.Payload.status:type_name -> workflow.WorkflowStatus
	17, // 24: workflow.WorkflowExecutionPausedEvent.Payload.context:type_name -> google.protobuf.Struct
	0,  // 25: workflow.WorkflowExecutionResumedEvent.Payload.status:type_name -> workflow.WorkflowStatus
	17, // 26: workflow.WorkflowExecutionResumedEvent.Payload.context:type_name -> google.protobuf.Struct
	0,  // 27: workflow.WorkflowExecutionSuccessEvent.Payload.status:type_name -> workflow.WorkflowStatus
	18, // 28: workflow.WorkflowExecutionSuccessEvent.Payload.result:type_name -> common.Result
	17, // 29: workflow.WorkflowExecutionSuccessEvent.Payload.context:type_name -> google.protobuf.Struct
	0,  // 30: workflow.WorkflowExecutionFailedEvent.Payload.status:type_name -> workflow.WorkflowStatus
	18, // 31: workflow.WorkflowExecutionFailedEvent.Payload.result:type_name -> common.Result
	17, // 32: workflow.WorkflowExecutionFailedEvent.Payload.context:type_name -> google.protobuf.Struct
	0,  // 33: workflow.WorkflowExecutionCancelledEvent.Payload.status:type_name -> workflow.WorkflowStatus
	17, // 34: workflow.WorkflowExecutionCancelledEvent.Payload.context:type_name -> google.protobuf.Struct
	0,  // 35: workflow.WorkflowExecutionTimedOutEvent.Payload.status:type_name -> workflow.WorkflowStatus
	18, // 36: workflow.WorkflowExecutionTimedOutEvent.Payload.result:type_name -> common.Result
	17, // 37: workflow.WorkflowExecutionTimedOutEvent.Payload.context:type_name -> google.protobuf.Struct
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_workflow_events_proto_init() }
func file_workflow_events_proto_init() {
	if File_workflow_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_events_proto_rawDesc), len(file_workflow_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_events_proto_goTypes,
		DependencyIndexes: file_workflow_events_proto_depIdxs,
		EnumInfos:         file_workflow_events_proto_enumTypes,
		MessageInfos:      file_workflow_events_proto_msgTypes,
	}.Build()
	File_workflow_events_proto = out.File
	file_workflow_events_proto_goTypes = nil
	file_workflow_events_proto_depIdxs = nil
}
