version: "3.9"

services:
  temporal:
    image: temporalio/auto-setup:1.26.0
    environment:
      - DB=sqlite
      - DB_PORT=7233
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development_sqlite.yaml
    ports:
      - "7233:7233"
    healthcheck:
      test:
        - "CMD"
        - "temporal"
        - "operator"
        - "cluster"
        - "describe"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  temporal-ui:
    image: temporalio/ui:2.26.2
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "8088:8080"
    depends_on:
      temporal:
        condition: service_healthy
