global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Compozy application metrics
  - job_name: "compozy"
    static_configs:
      - targets: ["host.docker.internal:5001"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: "http"

  # Temporal service metrics
  - job_name: "temporal"
    static_configs:
      - targets: ["temporal:8000"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: "http"

  # Grafana metrics (optional)
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s
