package docpost

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestFilenameToCommand(t *testing.T) {
	t.Parallel()

	tests := []struct {
		filename string
		want     string
	}{
		{"compozy.md", "compozy"},
		{"compozy_session.md", "compozy session"},
		{"compozy_session_list.md", "compozy session list"},
		{"compozy_daemon_start.md", "compozy daemon start"},
	}

	for _, tt := range tests {
		t.Run(tt.filename, func(t *testing.T) {
			t.Parallel()
			got := filenameToCommand(tt.filename)
			if got != tt.want {
				t.Errorf("filenameToCommand(%q) = %q, want %q", tt.filename, got, tt.want)
			}
		})
	}
}

func TestExtractDescription(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		raw  string
		want string
	}{
		{
			name: "standard cobra output",
			raw:  "## compozy session list\n\nList all active sessions\n\n### Synopsis\n",
			want: "List all active sessions",
		},
		{
			name: "no description",
			raw:  "## compozy\n\n### Synopsis\n",
			want: "",
		},
		{
			name: "multiline before synopsis",
			raw:  "## compozy session\n\nManage agent sessions\n\nMore details here\n\n### Synopsis\n",
			want: "Manage agent sessions",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := extractDescription(tt.raw)
			if got != tt.want {
				t.Errorf("extractDescription() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestStripBoilerplate(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		raw  string
		want string
	}{
		{
			name: "removes auto generated footer",
			raw:  "content here\n\n###### Auto generated by spf13/cobra on 1-Jan-2024\n",
			want: "content here\n\n",
		},
		{
			name: "removes SEE ALSO section",
			raw: "content here\n\n### SEE ALSO\n\n" +
				"* [compozy](compozy.md) - parent\n" +
				"* [compozy session list](compozy_session_list.md) - child\n",
			want: "content here\n\n",
		},
		{
			name: "removes both",
			raw:  "content here\n\n### SEE ALSO\n\n* [compozy](compozy.md)\n\n###### Auto generated by spf13/cobra\n",
			want: "content here\n\n",
		},
		{
			name: "no boilerplate",
			raw:  "clean content\n",
			want: "clean content\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := stripBoilerplate(tt.raw)
			if got != tt.want {
				t.Errorf("stripBoilerplate() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestRewriteLinks(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		raw  string
		want string
	}{
		{
			name: "rewrites md link",
			raw:  "* [compozy session](compozy_session.md) - manage sessions",
			want: "* [compozy session](compozy_session) - manage sessions",
		},
		{
			name: "rewrites multiple links",
			raw:  "[compozy](compozy.md) and [compozy session](compozy_session.md)",
			want: "[compozy](compozy) and [compozy session](compozy_session)",
		},
		{
			name: "no links",
			raw:  "plain text here",
			want: "plain text here",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := rewriteLinks(tt.raw)
			if got != tt.want {
				t.Errorf("rewriteLinks() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestTransformMarkdown(t *testing.T) {
	t.Parallel()

	raw := `## compozy session list

List all active sessions

### Synopsis

List all sessions currently tracked by the Compozy daemon.

` + "```" + `
compozy session list [flags]
` + "```" + `

### Options

` + "```" + `
  -h, --help   help for session list
` + "```" + `

### SEE ALSO

* [compozy session](compozy_session.md) - Manage sessions

###### Auto generated by spf13/cobra on 15-Apr-2026
`

	result := TransformMarkdown(raw, "compozy session list")

	// Verify frontmatter is present.
	if !strings.HasPrefix(result, "---\n") {
		t.Error("result should start with YAML frontmatter delimiter")
	}
	if !strings.Contains(result, `title: "compozy session list"`) {
		t.Error("frontmatter should contain title")
	}
	if !strings.Contains(result, `description: "List all active sessions"`) {
		t.Error("frontmatter should contain description")
	}

	// Verify boilerplate is stripped.
	if strings.Contains(result, "Auto generated") {
		t.Error("auto-generated footer should be stripped")
	}
	if strings.Contains(result, "### SEE ALSO") {
		t.Error("SEE ALSO section should be stripped")
	}

	// Verify .md links are rewritten.
	if strings.Contains(result, ".md)") {
		t.Error("should not contain .md links")
	}

	// Verify content is preserved.
	if !strings.Contains(result, "### Synopsis") {
		t.Error("synopsis section should be preserved")
	}
	if !strings.Contains(result, "### Options") {
		t.Error("options section should be preserved")
	}
}

func TestRenderOutputFormatsSection(t *testing.T) {
	t.Parallel()

	body := `---
	title: "compozy status"
	description: "Show runtime status"
---

## compozy status

Show runtime status

` + "```" + `
compozy status [flags]
` + "```" + `

### Options inherited from parent commands

` + "```" + `
  -o, --output string   Output format: human, json, or toon (default "human")
` + "```" + `
`

	result := renderOutputFormatsSection(body)

	if !strings.Contains(result, "## Output Formats") {
		t.Fatal("expected output formats section heading")
	}
	if !strings.Contains(result, "compozy status -o json") {
		t.Fatal("expected JSON usage example")
	}
}

func TestRenderSubcommandsSection(t *testing.T) {
	t.Parallel()

	t.Run("Should render a canonical subcommand table", func(t *testing.T) {
		t.Parallel()

		inputs := []input{
			{
				fileName: "compozy_task.md",
				baseName: "compozy_task",
				segments: []string{"task"},
				raw:      "## compozy task\n\nManage tasks and task runs\n\n",
			},
			{
				fileName: "compozy_task_create.md",
				baseName: "compozy_task_create",
				segments: []string{"task", "create"},
				raw:      "## compozy task create\n\nCreate a task\n\n",
			},
			{
				fileName: "compozy_task_list.md",
				baseName: "compozy_task_list",
				segments: []string{"task", "list"},
				raw:      "## compozy task list\n\nList tasks\n\n",
			},
		}

		targets := map[string]string{
			"compozy_task":        "/docs/cli/task",
			"compozy_task_create": "/docs/cli/task/create",
			"compozy_task_list":   "/docs/cli/task/list",
		}

		result := renderSubcommandsSection(inputs[0], inputs, targets)
		want := `## Subcommands

| Command                                      | Description   |
| -------------------------------------------- | ------------- |
| [compozy task create](/docs/cli/task/create) | Create a task |
| [compozy task list](/docs/cli/task/list)     | List tasks    |`
		if result != want {
			t.Fatalf("renderSubcommandsSection() = %q, want %q", result, want)
		}
	})
}

func TestEscapeJSX(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		raw  string
		want string
	}{
		{
			name: "escapes angle brackets in text",
			raw:  "Use backoff:<max_retries>:<base_delay> format",
			want: `Use backoff:\<max_retries>:\<base_delay> format`,
		},
		{
			name: "preserves angle brackets in fenced code",
			raw:  "text\n```\nsource <(cmd)\n```\nmore",
			want: "text\n```\nsource <(cmd)\n```\nmore",
		},
		{
			name: "preserves angle brackets in inline code",
			raw:  "Use `<flag>` in your command",
			want: "Use `<flag>` in your command",
		},
		{
			name: "no angle brackets",
			raw:  "plain text",
			want: "plain text",
		},
		{
			name: "process substitution outside fence",
			raw:  "source <(compozy completion bash)",
			want: `source \<(compozy completion bash)`,
		},
		{
			name: "escapes curly braces in text",
			raw:  `use "${fpath[1]}/_compozy" format`,
			want: `use "$\{fpath[1]}/_compozy" format`,
		},
		{
			name: "preserves curly braces in inline code",
			raw:  "Use `${fpath[1]}` in your shell",
			want: "Use `${fpath[1]}` in your shell",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := escapeJSX(tt.raw)
			if got != tt.want {
				t.Errorf("escapeJSX() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestTransformMarkdown_NoAbsolutePaths(t *testing.T) {
	t.Parallel()

	raw := `## compozy version

Print the Compozy version

### Synopsis

Print version info.
`

	result := TransformMarkdown(raw, "compozy version")
	if strings.Contains(result, "/Users/") || strings.Contains(result, "/home/") || strings.Contains(result, "/tmp/") {
		t.Error("output should not contain absolute file paths")
	}
}

func TestFenceIndentedBlocks_PreservesBlankLinesInsideBlock(t *testing.T) {
	t.Parallel()

	raw := "Before\n\n    compozy daemon start\n\n    compozy session new\nAfter"
	want := "Before\n\n```\ncompozy daemon start\n\ncompozy session new\n```\nAfter"

	got := fenceIndentedBlocks(raw)
	if got != want {
		t.Fatalf("fenceIndentedBlocks() = %q, want %q", got, want)
	}
}

func TestComputeHasChildren(t *testing.T) {
	t.Parallel()

	inputs := []input{
		{baseName: "compozy"},
		{baseName: "compozy_agent"},
		{baseName: "compozy_agent_list"},
		{baseName: "compozy_agent_info"},
		{baseName: "compozy_version"},
		{baseName: "compozy_automation"},
		{baseName: "compozy_automation_jobs"},
		{baseName: "compozy_automation_jobs_create"},
	}

	got := computeHasChildren(inputs)

	want := map[string]bool{
		"compozy":                 true,
		"compozy_agent":           true,
		"compozy_automation":      true,
		"compozy_automation_jobs": true,
	}

	for k, v := range want {
		if got[k] != v {
			t.Errorf("hasChildren[%q] = %v, want %v", k, got[k], v)
		}
	}

	shouldNotHaveChildren := []string{
		"compozy_agent_list",
		"compozy_agent_info",
		"compozy_version",
		"compozy_automation_jobs_create",
	}
	for _, k := range shouldNotHaveChildren {
		if got[k] {
			t.Errorf("hasChildren[%q] = true, want false", k)
		}
	}
}

func TestOutPath(t *testing.T) {
	t.Parallel()

	hasChildren := map[string]bool{
		"compozy":                 true,
		"compozy_agent":           true,
		"compozy_automation":      true,
		"compozy_automation_jobs": true,
		"compozy_task":            true,
		"compozy_task_run":        true,
	}

	tests := []struct {
		in   input
		want string
	}{
		{input{baseName: "compozy", segments: nil}, "compozy.mdx"},
		{input{baseName: "compozy_version", segments: []string{"version"}}, "version.mdx"},
		{input{baseName: "compozy_agent", segments: []string{"agent"}}, "agent/index.mdx"},
		{input{baseName: "compozy_agent_list", segments: []string{"agent", "list"}}, "agent/list.mdx"},
		{input{baseName: "compozy_automation", segments: []string{"automation"}}, "automation/index.mdx"},
		{
			input{baseName: "compozy_automation_jobs", segments: []string{"automation", "jobs"}},
			"automation/jobs/index.mdx",
		},
		{
			input{baseName: "compozy_automation_jobs_create", segments: []string{"automation", "jobs", "create"}},
			"automation/jobs/create.mdx",
		},
		{input{baseName: "compozy_task_run_start", segments: []string{"task", "run", "start"}}, "task/run/start.mdx"},
	}

	for _, tt := range tests {
		t.Run(tt.in.baseName, func(t *testing.T) {
			t.Parallel()
			got := outPath(tt.in, hasChildren)
			if got != tt.want {
				t.Errorf("outPath(%q) = %q, want %q", tt.in.baseName, got, tt.want)
			}
		})
	}
}

func TestBuildTargetMap(t *testing.T) {
	t.Parallel()

	inputs := []input{
		{baseName: "compozy"},
		{baseName: "compozy_agent", segments: []string{"agent"}},
		{baseName: "compozy_agent_list", segments: []string{"agent", "list"}},
		{baseName: "compozy_automation_jobs_create", segments: []string{"automation", "jobs", "create"}},
	}

	targets := buildTargetMap(inputs)

	want := map[string]string{
		"compozy":                        "/docs/cli/compozy",
		"compozy_agent":                  "/docs/cli/agent",
		"compozy_agent_list":             "/docs/cli/agent/list",
		"compozy_automation_jobs_create": "/docs/cli/automation/jobs/create",
	}

	for k, v := range want {
		if targets[k] != v {
			t.Errorf("targets[%q] = %q, want %q", k, targets[k], v)
		}
	}
}

func TestRemapLinks(t *testing.T) {
	t.Parallel()

	targets := map[string]string{
		"compozy":            "/docs/cli/compozy",
		"compozy_agent":      "/docs/cli/agent",
		"compozy_agent_list": "/docs/cli/agent/list",
	}

	tests := []struct {
		name string
		raw  string
		want string
	}{
		{
			name: "remaps stripped cross link",
			raw:  "* [compozy agent list](compozy_agent_list) - list agents",
			want: "* [compozy agent list](/docs/cli/agent/list) - list agents",
		},
		{
			name: "remaps root",
			raw:  "See [compozy](compozy) for the root command.",
			want: "See [compozy](/docs/cli/compozy) for the root command.",
		},
		{
			name: "leaves unknown targets alone",
			raw:  "See [external](compozy_not_a_command) here",
			want: "See [external](compozy_not_a_command) here",
		},
		{
			name: "leaves non-compozy links untouched",
			raw:  "See [docs](/docs/intro) here",
			want: "See [docs](/docs/intro) here",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := remapLinks(tt.raw, targets)
			if got != tt.want {
				t.Errorf("remapLinks() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestTitleCase(t *testing.T) {
	t.Parallel()

	tests := []struct {
		in, want string
	}{
		{"agent", "Agent"},
		{"automation", "Automation"},
		{"test-delivery", "Test Delivery"},
		{"jobs", "Jobs"},
		{"", ""},
	}

	for _, tt := range tests {
		t.Run(tt.in, func(t *testing.T) {
			t.Parallel()
			got := titleCase(tt.in)
			if got != tt.want {
				t.Errorf("titleCase(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestCleanOutput_PreservesRootEditorialFiles(t *testing.T) {
	t.Parallel()

	dstDir := t.TempDir()

	// Seed with hand-maintained root files and some stale generated files/dirs.
	rootMeta := []byte(`{"title":"CLI Reference","pages":["index","agent"]}`)
	if err := os.WriteFile(filepath.Join(dstDir, "meta.json"), rootMeta, 0o600); err != nil {
		t.Fatal(err)
	}
	rootIndex := []byte("---\ntitle: CLI Reference\n---\n\n# CLI Reference\n")
	if err := os.WriteFile(filepath.Join(dstDir, "index.mdx"), rootIndex, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dstDir, "stale.mdx"), []byte("stale"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(dstDir, "agent"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dstDir, "agent", "list.mdx"), []byte("stale"), 0o600); err != nil {
		t.Fatal(err)
	}

	if err := cleanOutput(context.Background(), dstDir); err != nil {
		t.Fatalf("cleanOutput() error: %v", err)
	}

	// Root editorial files must survive.
	got, err := os.ReadFile(filepath.Join(dstDir, "meta.json"))
	if err != nil {
		t.Fatalf("root meta.json should still exist: %v", err)
	}
	if !bytes.Equal(got, rootMeta) {
		t.Errorf("root meta.json content changed, want %q, got %q", rootMeta, got)
	}
	got, err = os.ReadFile(filepath.Join(dstDir, "index.mdx"))
	if err != nil {
		t.Fatalf("root index.mdx should still exist: %v", err)
	}
	if !bytes.Equal(got, rootIndex) {
		t.Errorf("root index.mdx content changed, want %q, got %q", rootIndex, got)
	}

	// Stale files must be gone.
	if _, err := os.Stat(filepath.Join(dstDir, "stale.mdx")); !os.IsNotExist(err) {
		t.Error("stale.mdx should have been removed")
	}
	if _, err := os.Stat(filepath.Join(dstDir, "agent")); !os.IsNotExist(err) {
		t.Error("agent/ subdir should have been removed")
	}
}

func TestWriteDirMeta_ErrorIncludesTargetPath(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	if err := os.Mkdir(filepath.Join(dir, "meta.json"), 0o755); err != nil {
		t.Fatalf("mkdir meta.json dir: %v", err)
	}

	err := writeDirMeta(context.Background(), dir)
	if err == nil {
		t.Fatal("writeDirMeta() should fail when meta.json is a directory")
	}
	if !strings.Contains(err.Error(), filepath.Join(dir, "meta.json")) {
		t.Fatalf("writeDirMeta() error should include target path, got: %v", err)
	}
}

func TestProcess_NestedLayout(t *testing.T) {
	t.Parallel()

	srcDir := t.TempDir()
	dstDir := t.TempDir()

	// Seed hand-maintained root files — Process must preserve them.
	rootMeta := `{"title":"CLI Reference","root":true,"pages":["index","agent","automation","version"]}`
	if err := os.WriteFile(filepath.Join(dstDir, "meta.json"), []byte(rootMeta), 0o600); err != nil {
		t.Fatal(err)
	}
	rootIndex := "---\ntitle: CLI Reference\n---\n\n# Editorial overview\n"
	if err := os.WriteFile(filepath.Join(dstDir, "index.mdx"), []byte(rootIndex), 0o600); err != nil {
		t.Fatal(err)
	}

	files := map[string]string{
		"compozy.md": `## compozy

Compozy — agent operating system

### Synopsis

Compozy is an agent operating system.

###### Auto generated by spf13/cobra
`,
		"compozy_agent.md": `## compozy agent

Manage agents

### Synopsis

Manage agents in Compozy.

### SEE ALSO

* [compozy](compozy.md) - parent
* [compozy agent list](compozy_agent_list.md) - list agents

###### Auto generated by spf13/cobra
`,
		"compozy_agent_list.md": `## compozy agent list

List registered agents

### Synopsis

List all registered agent definitions.

### SEE ALSO

* [compozy agent](compozy_agent.md) - parent

###### Auto generated by spf13/cobra
`,
		"compozy_agent_info.md": `## compozy agent info

Show agent info

### Synopsis

Show agent info.
`,
		"compozy_automation.md": `## compozy automation

Automation commands

### Synopsis

Manage automation.
`,
		"compozy_automation_jobs.md": `## compozy automation jobs

Manage jobs

### Synopsis

Manage automation jobs.
`,
		"compozy_automation_jobs_create.md": `## compozy automation jobs create

Create a job

### Synopsis

Create a new automation job.

See [compozy automation jobs](compozy_automation_jobs.md) for the parent command.
`,
		"compozy_version.md": `## compozy version

Print the Compozy version

### Synopsis

Print the version.
`,
	}

	for name, content := range files {
		if err := os.WriteFile(filepath.Join(srcDir, name), []byte(content), 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}

	if err := Process(context.Background(), srcDir, dstDir); err != nil {
		t.Fatalf("Process() error: %v", err)
	}

	// Expected layout.
	want := []string{
		"compozy.mdx",                // generated root command page
		"index.mdx",                  // hand-authored overview
		"version.mdx",                // leaf, no children
		"agent/index.mdx",            // parent (compozy_agent has children)
		"agent/info.mdx",             // leaf
		"agent/list.mdx",             // leaf
		"agent/meta.json",            // auto-generated
		"automation/index.mdx",       // parent
		"automation/jobs/index.mdx",  // parent
		"automation/jobs/create.mdx", // leaf
		"automation/meta.json",       // auto-generated
		"automation/jobs/meta.json",  // auto-generated
	}
	for _, rel := range want {
		if _, err := os.Stat(filepath.Join(dstDir, rel)); err != nil {
			t.Errorf("expected output %s to exist: %v", rel, err)
		}
	}

	// Root meta.json must be untouched.
	got, err := os.ReadFile(filepath.Join(dstDir, "meta.json"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != rootMeta {
		t.Errorf("root meta.json was modified. got=%q want=%q", got, rootMeta)
	}
	got, err = os.ReadFile(filepath.Join(dstDir, "index.mdx"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != rootIndex {
		t.Errorf("root index.mdx was modified. got=%q want=%q", got, rootIndex)
	}

	// Cross-links in agent/index.mdx must point to absolute URLs.
	agentIdx, err := os.ReadFile(filepath.Join(dstDir, "agent", "index.mdx"))
	if err != nil {
		t.Fatal(err)
	}
	// The SEE ALSO section is stripped by stripBoilerplate, so the
	// remapped link only appears if the cross-link survives outside that
	// section. For this test we verify that the link is NOT left in raw
	// `compozy_agent_list` form if it leaked through anywhere.
	if strings.Contains(string(agentIdx), "](compozy_agent_list)") {
		t.Error("agent/index.mdx should not contain unresolved stripped cross-links")
	}

	// automation/jobs/create.mdx has an inline reference to the parent
	// that lives OUTSIDE the SEE ALSO section — verify remapping worked.
	createMDX, err := os.ReadFile(filepath.Join(dstDir, "automation", "jobs", "create.mdx"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(createMDX), "(/docs/cli/automation/jobs)") {
		t.Errorf("automation/jobs/create.mdx should contain absolute cross-link, got:\n%s", createMDX)
	}
	if strings.Contains(string(createMDX), "(compozy_automation_jobs)") {
		t.Error("automation/jobs/create.mdx should not contain raw base-name cross-links")
	}

	// Per-directory meta.json must list direct children with index first.
	var agentMeta struct {
		Title string   `json:"title"`
		Pages []string `json:"pages"`
	}
	data, err := os.ReadFile(filepath.Join(dstDir, "agent", "meta.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(data, &agentMeta); err != nil {
		t.Fatal(err)
	}
	if agentMeta.Title != "Agent" {
		t.Errorf("agent meta title = %q, want %q", agentMeta.Title, "Agent")
	}
	wantPages := []string{"index", "info", "list"}
	if len(agentMeta.Pages) != len(wantPages) {
		t.Errorf("agent meta pages = %v, want %v", agentMeta.Pages, wantPages)
	} else {
		for i, p := range wantPages {
			if agentMeta.Pages[i] != p {
				t.Errorf("agent meta pages[%d] = %q, want %q", i, agentMeta.Pages[i], p)
			}
		}
	}

	// automation/meta.json should list the jobs subdirectory.
	data, err = os.ReadFile(filepath.Join(dstDir, "automation", "meta.json"))
	if err != nil {
		t.Fatal(err)
	}
	var autoMeta struct {
		Title string   `json:"title"`
		Pages []string `json:"pages"`
	}
	if err := json.Unmarshal(data, &autoMeta); err != nil {
		t.Fatal(err)
	}
	wantAutoPages := []string{"index", "jobs"}
	if len(autoMeta.Pages) != len(wantAutoPages) {
		t.Errorf("automation meta pages = %v, want %v", autoMeta.Pages, wantAutoPages)
	} else {
		for i, p := range wantAutoPages {
			if autoMeta.Pages[i] != p {
				t.Errorf("automation meta pages[%d] = %q, want %q", i, autoMeta.Pages[i], p)
			}
		}
	}
}

func TestProcess_CreatesOutputDir(t *testing.T) {
	t.Parallel()

	srcDir := t.TempDir()
	dstDir := filepath.Join(t.TempDir(), "nested", "deep", "output")

	// Write a minimal .md file so Process has something to work on.
	content := "## compozy\n\nCompozy agent OS\n"
	if err := os.WriteFile(filepath.Join(srcDir, "compozy.md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := Process(context.Background(), srcDir, dstDir); err != nil {
		t.Fatalf("Process() should create output dir: %v", err)
	}

	if _, err := os.Stat(dstDir); os.IsNotExist(err) {
		t.Error("output directory should have been created")
	}
	if _, err := os.Stat(filepath.Join(dstDir, "compozy.mdx")); os.IsNotExist(err) {
		t.Error("compozy.mdx should have been written (from compozy.md)")
	} else if err != nil {
		t.Fatalf("stat compozy.mdx: %v", err)
	}
}

func TestProcessRejectsNonManagedOutputDir(t *testing.T) {
	t.Parallel()

	srcDir := t.TempDir()
	dstDir := t.TempDir()

	if err := os.WriteFile(
		filepath.Join(srcDir, "compozy.md"),
		[]byte("## compozy\n\nCompozy agent OS\n"),
		0o644,
	); err != nil {
		t.Fatalf("write source file: %v", err)
	}

	sentinelPath := filepath.Join(dstDir, "notes.txt")
	const sentinelBody = "do not delete"
	if err := os.WriteFile(sentinelPath, []byte(sentinelBody), 0o600); err != nil {
		t.Fatalf("write sentinel: %v", err)
	}

	err := Process(context.Background(), srcDir, dstDir)
	if err == nil || !strings.Contains(err.Error(), "refusing to clean non-empty unmanaged output dir") {
		t.Fatalf("Process() error = %v, want unmanaged output-dir refusal", err)
	}

	got, readErr := os.ReadFile(sentinelPath)
	if readErr != nil {
		t.Fatalf("sentinel should remain after refusal: %v", readErr)
	}
	if string(got) != sentinelBody {
		t.Fatalf("sentinel content changed = %q, want %q", got, sentinelBody)
	}
}

func TestProcessAllowsRerunIntoGeneratedOutputDir(t *testing.T) {
	t.Parallel()

	srcDir := t.TempDir()
	dstDir := filepath.Join(t.TempDir(), "output")
	content := "## compozy\n\nCompozy agent OS\n"
	if err := os.WriteFile(filepath.Join(srcDir, "compozy.md"), []byte(content), 0o644); err != nil {
		t.Fatalf("write source file: %v", err)
	}

	if err := Process(context.Background(), srcDir, dstDir); err != nil {
		t.Fatalf("initial Process() error = %v", err)
	}
	if err := Process(context.Background(), srcDir, dstDir); err != nil {
		t.Fatalf("rerun Process() error = %v", err)
	}
}

func TestProcessAllowsManagedRootFilesAndDirs(t *testing.T) {
	t.Parallel()

	srcDir := t.TempDir()
	dstDir := t.TempDir()

	if err := os.WriteFile(
		filepath.Join(srcDir, "compozy.md"),
		[]byte("## compozy\n\nCompozy agent OS\n"),
		0o644,
	); err != nil {
		t.Fatalf("write source file: %v", err)
	}
	if err := os.WriteFile(
		filepath.Join(dstDir, "index.mdx"),
		[]byte("---\ntitle: CLI Reference\n---\n"),
		0o600,
	); err != nil {
		t.Fatalf("write editorial index: %v", err)
	}
	if err := os.WriteFile(
		filepath.Join(dstDir, "meta.json"),
		[]byte(`{"title":"CLI Reference","pages":["index"]}`),
		0o600,
	); err != nil {
		t.Fatalf("write editorial meta: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dstDir, "compozy.mdx"), []byte("old root"), 0o600); err != nil {
		t.Fatalf("write generated root: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dstDir, "install.mdx"), []byte("old leaf"), 0o600); err != nil {
		t.Fatalf("write generated leaf: %v", err)
	}
	if err := os.Mkdir(filepath.Join(dstDir, "session"), 0o755); err != nil {
		t.Fatalf("mkdir generated subdir: %v", err)
	}

	if err := Process(context.Background(), srcDir, dstDir); err != nil {
		t.Fatalf("Process() should allow managed root files and dirs: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dstDir, "index.mdx")); err != nil {
		t.Fatalf("editorial index should be preserved: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dstDir, "meta.json")); err != nil {
		t.Fatalf("editorial meta should be preserved: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dstDir, "compozy.mdx")); err != nil {
		t.Fatalf("generated root should be rewritten: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dstDir, "install.mdx")); !os.IsNotExist(err) {
		t.Fatalf("stale generated root leaf should be removed, stat err = %v", err)
	}
	if _, err := os.Stat(filepath.Join(dstDir, "session")); !os.IsNotExist(err) {
		t.Fatalf("stale generated subdir should be removed, stat err = %v", err)
	}
}

func TestProcess_StopsWhenContextCanceled(t *testing.T) {
	t.Parallel()

	srcDir := t.TempDir()
	dstDir := filepath.Join(t.TempDir(), "output")
	if err := os.WriteFile(
		filepath.Join(srcDir, "compozy.md"),
		[]byte("## compozy\n\nCompozy agent OS\n"),
		0o644,
	); err != nil {
		t.Fatalf("write source file: %v", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	err := Process(ctx, srcDir, dstDir)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("Process() error = %v, want context.Canceled", err)
	}
	if _, statErr := os.Stat(filepath.Join(dstDir, "compozy.mdx")); !os.IsNotExist(statErr) {
		t.Fatalf("Process() should not write output after cancellation, stat err = %v", statErr)
	}
}
