services:
  temporal:
    image: temporalio/auto-setup:1.26
    environment:
      - DB=sqlite
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    ports:
      - "7233:7233"
    healthcheck:
      test: ["CMD-SHELL", "tctl --address 127.0.0.1:7233 namespace list >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: compozy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

