// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common/metadata.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represent the string version of State.ID (<component>:<corr_id>:<exec_id>)
	Id            string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      *string `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_common_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_common_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_common_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *State) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

type Metadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId   string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SourceComponent string                 `protobuf:"bytes,2,opt,name=source_component,json=sourceComponent,proto3" json:"source_component,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EndedAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3,oneof" json:"ended_at,omitempty"`
	State           *State                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_common_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_common_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Metadata) GetSourceComponent() string {
	if x != nil {
		return x.SourceComponent
	}
	return ""
}

func (x *Metadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Metadata) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Metadata) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

var File_common_metadata_proto protoreflect.FileDescriptor

const file_common_metadata_proto_rawDesc = "" +
	"\n" +
	"\x15common/metadata.proto\x12\x06common\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n" +
	"\x05State\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_id\"\x85\x02\n" +
	"\bMetadata\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12)\n" +
	"\x10source_component\x18\x02 \x01(\tR\x0fsourceComponent\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12:\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendedAt\x88\x01\x01\x12#\n" +
	"\x05state\x18\x05 \x01(\v2\r.common.StateR\x05stateB\v\n" +
	"\t_ended_atB*Z(github.com/compozy/compozy/pkg/pb/commonb\x06proto3"

var (
	file_common_metadata_proto_rawDescOnce sync.Once
	file_common_metadata_proto_rawDescData []byte
)

func file_common_metadata_proto_rawDescGZIP() []byte {
	file_common_metadata_proto_rawDescOnce.Do(func() {
		file_common_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_metadata_proto_rawDesc), len(file_common_metadata_proto_rawDesc)))
	})
	return file_common_metadata_proto_rawDescData
}

var file_common_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_metadata_proto_goTypes = []any{
	(*State)(nil),                 // 0: common.State
	(*Metadata)(nil),              // 1: common.Metadata
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_common_metadata_proto_depIdxs = []int32{
	2, // 0: common.Metadata.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: common.Metadata.ended_at:type_name -> google.protobuf.Timestamp
	0, // 2: common.Metadata.state:type_name -> common.State
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_metadata_proto_init() }
func file_common_metadata_proto_init() {
	if File_common_metadata_proto != nil {
		return
	}
	file_common_metadata_proto_msgTypes[0].OneofWrappers = []any{}
	file_common_metadata_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_metadata_proto_rawDesc), len(file_common_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_metadata_proto_goTypes,
		DependencyIndexes: file_common_metadata_proto_depIdxs,
		MessageInfos:      file_common_metadata_proto_msgTypes,
	}.Build()
	File_common_metadata_proto = out.File
	file_common_metadata_proto_goTypes = nil
	file_common_metadata_proto_depIdxs = nil
}
