id: receiver

triggers:
  - type: signal
    name: workflow-ready

tools:
  - id: log_tool
    description: Log a message

tasks:
  - id: process-signal
    type: basic
    $use: tool(local::tools.#(id="log_tool"))
    with:
      message: 'Received: {{ .workflow.input.message | default "manually started" }}'
