id: pokemon-img
version: 0.1.0
description: Identify which Pokémon appears in an input image

schemas:
  - id: image_input
    type: object
    properties:
      image_url:
        type: string
        description: Publicly accessible image URL of the Pokémon
    required:
      - image_url

config:
  input:
    $ref: local::schemas.#(id=="image_input")

agents:
  - id: pokedex
    instructions: |
      You are a Pokédex assistant. Given the name of a Pokémon, provide concise, factual basics.
      Prefer canonical game data; if uncertain, state so. Always return valid JSON when requested.
    actions:
      - id: pokemon_info
        json_mode: true
        prompt: |
          Provide basic information about the Pokémon "{{ .input.pokemon }}".
          Keep answers accurate and concise. If multiple forms exist, describe the most common.
          Return a JSON object with the fields below.
        output:
          type: object
          properties:
            name:
              type: string
            pokedex_number:
              type: number
            types:
              type: array
              items:
                type: string
            abilities:
              type: array
              items:
                type: string
            generation:
              type: string
            summary:
              type: string
          required:
            - name
            - types
            - summary

  - id: vision
    instructions: |
      You are a precise Pokémon recognition assistant. Analyze images and
      identify the most likely Pokémon. When uncertain, choose the best guess
      and lower confidence accordingly.
    actions:
      - id: recognize_from_image
        json_mode: true
        prompt: |
          Identify the Pokémon in the provided image and return JSON only with:
          - pokemon (string)
          - confidence (0-1)
          - reasoning (short string)
        output:
          type: object
          properties:
            pokemon:
              type: string
            confidence:
              type: number
            reasoning:
              type: string
          required:
            - pokemon

tasks:
  - id: recognize
    type: basic
    $use: agent(local::agents.#(id=="vision"))
    action: recognize_from_image
    with:
      image_url: "{{ .workflow.input.image_url }}"
    on_success:
      next: info

  - id: info
    type: basic
    $use: agent(local::agents.#(id=="pokedex"))
    action: pokemon_info
    with:
      pokemon: "{{ .tasks.recognize.output.pokemon }}"
    final: true

outputs:
  pokemon: "{{ .tasks.recognize.output.pokemon }}"
  confidence: "{{ .tasks.recognize.output.confidence }}"
  reasoning: "{{ .tasks.recognize.output.reasoning }}"
  pokedex:
    name: "{{ .tasks.info.output.name | default .tasks.recognize.output.pokemon }}"
    pokedex_number: "{{ .tasks.info.output.pokedex_number }}"
    types: "{{ .tasks.info.output.types }}"
    abilities: "{{ .tasks.info.output.abilities }}"
    generation: "{{ .tasks.info.output.generation }}"
    summary: "{{ .tasks.info.output.summary }}"
