id: debugging
version: 0.1.0
description: Runs a validation tool that intentionally fails for negative inputs to demonstrate debugging
  workflows.

schemas:
  - id: debug_input
    type: object
    properties:
      value:
        type: integer
        description: Numeric value that must be positive for the workflow to succeed
    required:
      - value

config:
  input: debug_input

tools:
  - id: validate_input
    description: Validates that the provided number is positive.
    input:
      type: object
      properties:
        value:
          type: integer
      required:
        - value
    output:
      type: object
      properties:
        value:
          type: integer

tasks:
  - id: validate
    type: basic
    tool: validate_input
    with:
      value: "{{ .workflow.input.value }}"

  - id: summarize
    type: basic
    prompt: |-
      Confirm that the validation succeeded for the value {{ .tasks.validate.output.value }}.
      Mention the workflow run ID {{ .workflow.metadata.run_id }} and note that debug logging is enabled.
    final: true
