-- +goose Up
-- create "model_catalog_options" table
CREATE TABLE `model_catalog_options` (`source_id` text NOT NULL, `provider_id` text NOT NULL, `model_id` text NOT NULL, `option_id` text NOT NULL, `label` text NOT NULL DEFAULT '', `description` text NOT NULL DEFAULT '', `category` text NOT NULL DEFAULT '', `kind` text NOT NULL, `current_value_id` text NULL, `current_bool` integer NULL, PRIMARY KEY (`source_id`, `provider_id`, `model_id`, `option_id`), CONSTRAINT `0` FOREIGN KEY (`source_id`, `provider_id`, `model_id`) REFERENCES `model_catalog_rows` (`source_id`, `provider_id`, `model_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (trim(source_id) <> ''), CHECK (trim(provider_id) <> ''), CHECK (trim(model_id) <> ''), CHECK (trim(option_id) <> ''), CHECK (trim(kind) <> ''), CHECK (current_bool IN (0, 1) OR current_bool IS NULL), CHECK (current_value_id IS NULL OR trim(current_value_id) <> ''), CHECK (NOT (current_value_id IS NOT NULL AND current_bool IS NOT NULL)));
-- create "model_catalog_option_values" table
CREATE TABLE `model_catalog_option_values` (`source_id` text NOT NULL, `provider_id` text NOT NULL, `model_id` text NOT NULL, `option_id` text NOT NULL, `value_id` text NOT NULL, `label` text NOT NULL DEFAULT '', `description` text NOT NULL DEFAULT '', `group_id` text NOT NULL DEFAULT '', `group_label` text NOT NULL DEFAULT '', `rank` integer NOT NULL, PRIMARY KEY (`source_id`, `provider_id`, `model_id`, `option_id`, `value_id`), CONSTRAINT `0` FOREIGN KEY (`source_id`, `provider_id`, `model_id`, `option_id`) REFERENCES `model_catalog_options` (`source_id`, `provider_id`, `model_id`, `option_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (trim(source_id) <> ''), CHECK (trim(provider_id) <> ''), CHECK (trim(model_id) <> ''), CHECK (trim(option_id) <> ''), CHECK (trim(value_id) <> ''), CHECK (rank >= 0));
-- create index "idx_model_catalog_option_values_option" to table: "model_catalog_option_values"
CREATE INDEX `idx_model_catalog_option_values_option` ON `model_catalog_option_values` (`source_id`, `provider_id`, `model_id`, `option_id`, `rank`, `value_id`);
-- create "model_catalog_transport_binding_selections" table
CREATE TABLE `model_catalog_transport_binding_selections` (`source_id` text NOT NULL, `provider_id` text NOT NULL, `model_id` text NOT NULL, `transport_model_id` text NOT NULL, `option_id` text NOT NULL, `value_id` text NULL, `bool_value` integer NULL, PRIMARY KEY (`source_id`, `provider_id`, `model_id`, `transport_model_id`, `option_id`), CONSTRAINT `0` FOREIGN KEY (`source_id`, `provider_id`, `model_id`, `option_id`, `value_id`) REFERENCES `model_catalog_option_values` (`source_id`, `provider_id`, `model_id`, `option_id`, `value_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `1` FOREIGN KEY (`source_id`, `provider_id`, `model_id`, `option_id`) REFERENCES `model_catalog_options` (`source_id`, `provider_id`, `model_id`, `option_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `2` FOREIGN KEY (`source_id`, `provider_id`, `model_id`, `transport_model_id`) REFERENCES `model_catalog_transport_bindings` (`source_id`, `provider_id`, `model_id`, `transport_model_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (trim(source_id) <> ''), CHECK (trim(provider_id) <> ''), CHECK (trim(model_id) <> ''), CHECK (trim(transport_model_id) <> ''), CHECK (trim(option_id) <> ''), CHECK (bool_value IN (0, 1) OR bool_value IS NULL), CHECK (value_id IS NULL OR trim(value_id) <> ''), CHECK ((value_id IS NOT NULL AND bool_value IS NULL) OR (value_id IS NULL AND bool_value IS NOT NULL)));
-- create index "idx_model_catalog_binding_selections_binding" to table: "model_catalog_transport_binding_selections"
CREATE INDEX `idx_model_catalog_binding_selections_binding` ON `model_catalog_transport_binding_selections` (`source_id`, `provider_id`, `model_id`, `transport_model_id`, `option_id`);
