-- +goose Up
-- disable the enforcement of foreign-keys constraints
PRAGMA foreign_keys = off;
-- create the execution-context owner before rebuilding catalog tables
CREATE TABLE `model_catalog_execution_contexts` (`context_id` text NOT NULL, `scope` text NOT NULL, `profile_id` text NOT NULL DEFAULT '', `workspace_id` text NOT NULL DEFAULT '', `command_fingerprint` text NOT NULL DEFAULT '', PRIMARY KEY (`context_id`), CHECK (trim(context_id) <> ''), CHECK (scope IN ('global', 'profile', 'workspace')), CHECK (
				(scope = 'global' AND profile_id = '' AND workspace_id = '' AND command_fingerprint = '') OR
				(scope = 'profile' AND trim(profile_id) <> '' AND workspace_id = '' AND trim(command_fingerprint) <> '') OR
				(scope = 'workspace' AND trim(profile_id) <> '' AND trim(workspace_id) <> '' AND trim(command_fingerprint) <> '')
			));
-- preserve provider-independent cache rows in the canonical global context; scoped observations are rediscovered
INSERT INTO `model_catalog_execution_contexts` (`context_id`, `scope`, `profile_id`, `workspace_id`, `command_fingerprint`) VALUES ('f4e0af598701912cd0516d11908757cf6c4f7a694c3113922f1f77d0fbd8c80e', 'global', '', '', '');
-- create "new_model_catalog_reasoning_efforts" table
CREATE TABLE `new_model_catalog_reasoning_efforts` (`context_id` text NOT NULL, `source_id` text NOT NULL, `provider_id` text NOT NULL, `model_id` text NOT NULL, `effort` text NOT NULL, `rank` integer NOT NULL, PRIMARY KEY (`context_id`, `source_id`, `provider_id`, `model_id`, `effort`), CONSTRAINT `0` FOREIGN KEY (`context_id`, `source_id`, `provider_id`, `model_id`) REFERENCES `model_catalog_rows` (`context_id`, `source_id`, `provider_id`, `model_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (trim(context_id) <> ''), CHECK (trim(effort) <> ''), CHECK (rank >= 0));
-- copy rows from old table "model_catalog_reasoning_efforts" to new temporary table "new_model_catalog_reasoning_efforts"
INSERT INTO `new_model_catalog_reasoning_efforts` (`context_id`, `source_id`, `provider_id`, `model_id`, `effort`, `rank`) SELECT 'f4e0af598701912cd0516d11908757cf6c4f7a694c3113922f1f77d0fbd8c80e', `source_id`, `provider_id`, `model_id`, `effort`, `rank` FROM `model_catalog_reasoning_efforts` WHERE `source_id` IN ('builtin', 'config', 'models_dev');
-- drop "model_catalog_reasoning_efforts" table after copying rows
DROP TABLE `model_catalog_reasoning_efforts`;
-- rename temporary table "new_model_catalog_reasoning_efforts" to "model_catalog_reasoning_efforts"
ALTER TABLE `new_model_catalog_reasoning_efforts` RENAME TO `model_catalog_reasoning_efforts`;
-- create "new_model_catalog_rows" table
CREATE TABLE `new_model_catalog_rows` (`context_id` text NOT NULL, `source_id` text NOT NULL, `provider_id` text NOT NULL, `model_id` text NOT NULL, `source_kind` text NOT NULL, `priority` integer NOT NULL, `available` integer NULL, `stale` integer NOT NULL DEFAULT 0, `refreshed_at` text NOT NULL DEFAULT '', `expires_at` text NOT NULL DEFAULT '', `display_name` text NOT NULL DEFAULT '', `context_window` integer NULL, `max_input_tokens` integer NULL, `max_output_tokens` integer NULL, `supports_tools` integer NULL, `supports_reasoning` integer NULL, `default_reasoning_effort` text NULL, `cost_input_per_million` real NULL, `cost_output_per_million` real NULL, `cost_cache_read_per_million` real NULL, `cost_cache_write_per_million` real NULL, `cost_reasoning_per_million` real NULL, `last_error` text NOT NULL DEFAULT '', `deprecated` integer NOT NULL DEFAULT 0, `hidden` integer NOT NULL DEFAULT 0, `featured` integer NOT NULL DEFAULT 0, `release_date` text NULL, `explicitly_curated` integer NOT NULL DEFAULT 0, `deprecated_set` integer NOT NULL DEFAULT 0, `hidden_set` integer NOT NULL DEFAULT 0, `featured_set` integer NOT NULL DEFAULT 0, PRIMARY KEY (`context_id`, `source_id`, `provider_id`, `model_id`), CONSTRAINT `0` FOREIGN KEY (`context_id`, `source_id`, `provider_id`) REFERENCES `model_catalog_sources` (`context_id`, `source_id`, `provider_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (trim(context_id) <> ''), CHECK (trim(source_id) <> ''), CHECK (trim(provider_id) <> ''), CHECK (trim(model_id) <> ''), CHECK (trim(source_kind) <> ''), CHECK (available IN (0, 1) OR available IS NULL), CHECK (stale IN (0, 1)), CHECK (supports_tools IN (0, 1) OR supports_tools IS NULL), CHECK (supports_reasoning IN (0, 1) OR supports_reasoning IS NULL), CHECK (deprecated IN (0, 1)), CHECK (hidden IN (0, 1)), CHECK (featured IN (0, 1)), CHECK (explicitly_curated IN (0, 1)), CHECK (deprecated_set IN (0, 1)), CHECK (hidden_set IN (0, 1)), CHECK (featured_set IN (0, 1)));
-- copy rows from old table "model_catalog_rows" to new temporary table "new_model_catalog_rows"
INSERT INTO `new_model_catalog_rows` (`context_id`, `source_id`, `provider_id`, `model_id`, `source_kind`, `priority`, `available`, `stale`, `refreshed_at`, `expires_at`, `display_name`, `context_window`, `max_input_tokens`, `max_output_tokens`, `supports_tools`, `supports_reasoning`, `default_reasoning_effort`, `cost_input_per_million`, `cost_output_per_million`, `cost_cache_read_per_million`, `cost_cache_write_per_million`, `cost_reasoning_per_million`, `last_error`, `deprecated`, `hidden`, `featured`, `release_date`, `explicitly_curated`, `deprecated_set`, `hidden_set`, `featured_set`) SELECT 'f4e0af598701912cd0516d11908757cf6c4f7a694c3113922f1f77d0fbd8c80e', `source_id`, `provider_id`, `model_id`, `source_kind`, `priority`, `available`, `stale`, `refreshed_at`, `expires_at`, `display_name`, `context_window`, `max_input_tokens`, `max_output_tokens`, `supports_tools`, `supports_reasoning`, `default_reasoning_effort`, `cost_input_per_million`, `cost_output_per_million`, `cost_cache_read_per_million`, `cost_cache_write_per_million`, `cost_reasoning_per_million`, `last_error`, `deprecated`, `hidden`, `featured`, `release_date`, `explicitly_curated`, `deprecated_set`, `hidden_set`, `featured_set` FROM `model_catalog_rows` WHERE `source_id` IN ('builtin', 'config', 'models_dev');
-- drop "model_catalog_rows" table after copying rows
DROP TABLE `model_catalog_rows`;
-- rename temporary table "new_model_catalog_rows" to "model_catalog_rows"
ALTER TABLE `new_model_catalog_rows` RENAME TO `model_catalog_rows`;
-- create index "idx_model_catalog_rows_provider_model" to table: "model_catalog_rows"
CREATE INDEX `idx_model_catalog_rows_provider_model` ON `model_catalog_rows` (`context_id`, `provider_id`, `model_id`, `priority` DESC, `refreshed_at` DESC, `source_id`);
-- create index "idx_model_catalog_rows_source_provider" to table: "model_catalog_rows"
CREATE INDEX `idx_model_catalog_rows_source_provider` ON `model_catalog_rows` (`context_id`, `source_id`, `provider_id`);
-- create "new_model_catalog_sources" table
CREATE TABLE `new_model_catalog_sources` (`context_id` text NOT NULL, `source_id` text NOT NULL, `provider_id` text NOT NULL, `source_kind` text NOT NULL, `priority` integer NOT NULL, `refresh_state` text NOT NULL, `last_refresh_at` text NOT NULL DEFAULT '', `next_refresh_at` text NOT NULL DEFAULT '', `last_success_at` text NOT NULL DEFAULT '', `last_error` text NOT NULL DEFAULT '', `row_count` integer NOT NULL DEFAULT 0, `stale` integer NOT NULL DEFAULT 0, PRIMARY KEY (`context_id`, `source_id`, `provider_id`), CONSTRAINT `0` FOREIGN KEY (`context_id`) REFERENCES `model_catalog_execution_contexts` (`context_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (trim(context_id) <> ''), CHECK (trim(source_id) <> ''), CHECK (trim(provider_id) <> ''), CHECK (trim(source_kind) <> ''), CHECK (trim(refresh_state) <> ''), CHECK (row_count >= 0), CHECK (stale IN (0, 1)));
-- copy rows from old table "model_catalog_sources" to new temporary table "new_model_catalog_sources"
INSERT INTO `new_model_catalog_sources` (`context_id`, `source_id`, `provider_id`, `source_kind`, `priority`, `refresh_state`, `last_refresh_at`, `next_refresh_at`, `last_success_at`, `last_error`, `row_count`, `stale`) SELECT 'f4e0af598701912cd0516d11908757cf6c4f7a694c3113922f1f77d0fbd8c80e', `source_id`, `provider_id`, `source_kind`, `priority`, `refresh_state`, `last_refresh_at`, `next_refresh_at`, `last_success_at`, `last_error`, `row_count`, `stale` FROM `model_catalog_sources` WHERE `source_id` IN ('builtin', 'config', 'models_dev');
-- drop "model_catalog_sources" table after copying rows
DROP TABLE `model_catalog_sources`;
-- rename temporary table "new_model_catalog_sources" to "model_catalog_sources"
ALTER TABLE `new_model_catalog_sources` RENAME TO `model_catalog_sources`;
-- create index "idx_model_catalog_sources_provider" to table: "model_catalog_sources"
CREATE INDEX `idx_model_catalog_sources_provider` ON `model_catalog_sources` (`context_id`, `provider_id`, `refresh_state`, `stale`);
-- create "new_model_catalog_transport_bindings" table
CREATE TABLE `new_model_catalog_transport_bindings` (`context_id` text NOT NULL, `source_id` text NOT NULL, `provider_id` text NOT NULL, `model_id` text NOT NULL, `transport_model_id` text NOT NULL, `label` text NOT NULL DEFAULT '', `reasoning_effort` text NULL, `fast` integer NULL, `thinking` integer NULL, `rank` integer NOT NULL, PRIMARY KEY (`context_id`, `source_id`, `provider_id`, `model_id`, `transport_model_id`), CONSTRAINT `0` FOREIGN KEY (`context_id`, `source_id`, `provider_id`, `model_id`) REFERENCES `model_catalog_rows` (`context_id`, `source_id`, `provider_id`, `model_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (trim(context_id) <> ''), CHECK (trim(source_id) <> ''), CHECK (trim(provider_id) <> ''), CHECK (trim(model_id) <> ''), CHECK (trim(transport_model_id) <> ''), CHECK (fast IN (0, 1) OR fast IS NULL), CHECK (thinking IN (0, 1) OR thinking IS NULL), CHECK (rank >= 0));
-- copy rows from old table "model_catalog_transport_bindings" to new temporary table "new_model_catalog_transport_bindings"
INSERT INTO `new_model_catalog_transport_bindings` (`context_id`, `source_id`, `provider_id`, `model_id`, `transport_model_id`, `label`, `reasoning_effort`, `fast`, `thinking`, `rank`) SELECT 'f4e0af598701912cd0516d11908757cf6c4f7a694c3113922f1f77d0fbd8c80e', `source_id`, `provider_id`, `model_id`, `transport_model_id`, `label`, `reasoning_effort`, `fast`, `thinking`, `rank` FROM `model_catalog_transport_bindings` WHERE `source_id` IN ('builtin', 'config', 'models_dev');
-- drop "model_catalog_transport_bindings" table after copying rows
DROP TABLE `model_catalog_transport_bindings`;
-- rename temporary table "new_model_catalog_transport_bindings" to "model_catalog_transport_bindings"
ALTER TABLE `new_model_catalog_transport_bindings` RENAME TO `model_catalog_transport_bindings`;
-- create index "idx_model_catalog_transport_bindings_row" to table: "model_catalog_transport_bindings"
CREATE INDEX `idx_model_catalog_transport_bindings_row` ON `model_catalog_transport_bindings` (`context_id`, `source_id`, `provider_id`, `model_id`, `rank`, `transport_model_id`);
-- create "new_model_catalog_options" table
CREATE TABLE `new_model_catalog_options` (`context_id` text NOT NULL, `source_id` text NOT NULL, `provider_id` text NOT NULL, `model_id` text NOT NULL, `option_id` text NOT NULL, `label` text NOT NULL DEFAULT '', `description` text NOT NULL DEFAULT '', `category` text NOT NULL DEFAULT '', `kind` text NOT NULL, `current_value_id` text NULL, `current_bool` integer NULL, PRIMARY KEY (`context_id`, `source_id`, `provider_id`, `model_id`, `option_id`), CONSTRAINT `0` FOREIGN KEY (`context_id`, `source_id`, `provider_id`, `model_id`) REFERENCES `model_catalog_rows` (`context_id`, `source_id`, `provider_id`, `model_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (trim(context_id) <> ''), CHECK (trim(source_id) <> ''), CHECK (trim(provider_id) <> ''), CHECK (trim(model_id) <> ''), CHECK (trim(option_id) <> ''), CHECK (trim(kind) <> ''), CHECK (current_bool IN (0, 1) OR current_bool IS NULL), CHECK (current_value_id IS NULL OR trim(current_value_id) <> ''), CHECK (NOT (current_value_id IS NOT NULL AND current_bool IS NOT NULL)));
-- copy rows from old table "model_catalog_options" to new temporary table "new_model_catalog_options"
INSERT INTO `new_model_catalog_options` (`context_id`, `source_id`, `provider_id`, `model_id`, `option_id`, `label`, `description`, `category`, `kind`, `current_value_id`, `current_bool`) SELECT 'f4e0af598701912cd0516d11908757cf6c4f7a694c3113922f1f77d0fbd8c80e', `source_id`, `provider_id`, `model_id`, `option_id`, `label`, `description`, `category`, `kind`, `current_value_id`, `current_bool` FROM `model_catalog_options` WHERE `source_id` IN ('builtin', 'config', 'models_dev');
-- drop "model_catalog_options" table after copying rows
DROP TABLE `model_catalog_options`;
-- rename temporary table "new_model_catalog_options" to "model_catalog_options"
ALTER TABLE `new_model_catalog_options` RENAME TO `model_catalog_options`;
-- create "new_model_catalog_option_values" table
CREATE TABLE `new_model_catalog_option_values` (`context_id` text NOT NULL, `source_id` text NOT NULL, `provider_id` text NOT NULL, `model_id` text NOT NULL, `option_id` text NOT NULL, `value_id` text NOT NULL, `label` text NOT NULL DEFAULT '', `description` text NOT NULL DEFAULT '', `group_id` text NOT NULL DEFAULT '', `group_label` text NOT NULL DEFAULT '', `rank` integer NOT NULL, PRIMARY KEY (`context_id`, `source_id`, `provider_id`, `model_id`, `option_id`, `value_id`), CONSTRAINT `0` FOREIGN KEY (`context_id`, `source_id`, `provider_id`, `model_id`, `option_id`) REFERENCES `model_catalog_options` (`context_id`, `source_id`, `provider_id`, `model_id`, `option_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (trim(context_id) <> ''), CHECK (trim(source_id) <> ''), CHECK (trim(provider_id) <> ''), CHECK (trim(model_id) <> ''), CHECK (trim(option_id) <> ''), CHECK (trim(value_id) <> ''), CHECK (rank >= 0));
-- copy rows from old table "model_catalog_option_values" to new temporary table "new_model_catalog_option_values"
INSERT INTO `new_model_catalog_option_values` (`context_id`, `source_id`, `provider_id`, `model_id`, `option_id`, `value_id`, `label`, `description`, `group_id`, `group_label`, `rank`) SELECT 'f4e0af598701912cd0516d11908757cf6c4f7a694c3113922f1f77d0fbd8c80e', `source_id`, `provider_id`, `model_id`, `option_id`, `value_id`, `label`, `description`, `group_id`, `group_label`, `rank` FROM `model_catalog_option_values` WHERE `source_id` IN ('builtin', 'config', 'models_dev');
-- drop "model_catalog_option_values" table after copying rows
DROP TABLE `model_catalog_option_values`;
-- rename temporary table "new_model_catalog_option_values" to "model_catalog_option_values"
ALTER TABLE `new_model_catalog_option_values` RENAME TO `model_catalog_option_values`;
-- create index "idx_model_catalog_option_values_option" to table: "model_catalog_option_values"
CREATE INDEX `idx_model_catalog_option_values_option` ON `model_catalog_option_values` (`context_id`, `source_id`, `provider_id`, `model_id`, `option_id`, `rank`, `value_id`);
-- create "new_model_catalog_transport_binding_selections" table
CREATE TABLE `new_model_catalog_transport_binding_selections` (`context_id` text NOT NULL, `source_id` text NOT NULL, `provider_id` text NOT NULL, `model_id` text NOT NULL, `transport_model_id` text NOT NULL, `option_id` text NOT NULL, `value_id` text NULL, `bool_value` integer NULL, PRIMARY KEY (`context_id`, `source_id`, `provider_id`, `model_id`, `transport_model_id`, `option_id`), CONSTRAINT `0` FOREIGN KEY (`context_id`, `source_id`, `provider_id`, `model_id`, `option_id`, `value_id`) REFERENCES `model_catalog_option_values` (`context_id`, `source_id`, `provider_id`, `model_id`, `option_id`, `value_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `1` FOREIGN KEY (`context_id`, `source_id`, `provider_id`, `model_id`, `option_id`) REFERENCES `model_catalog_options` (`context_id`, `source_id`, `provider_id`, `model_id`, `option_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `2` FOREIGN KEY (`context_id`, `source_id`, `provider_id`, `model_id`, `transport_model_id`) REFERENCES `model_catalog_transport_bindings` (`context_id`, `source_id`, `provider_id`, `model_id`, `transport_model_id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (trim(context_id) <> ''), CHECK (trim(source_id) <> ''), CHECK (trim(provider_id) <> ''), CHECK (trim(model_id) <> ''), CHECK (trim(transport_model_id) <> ''), CHECK (trim(option_id) <> ''), CHECK (bool_value IN (0, 1) OR bool_value IS NULL), CHECK (value_id IS NULL OR trim(value_id) <> ''), CHECK ((value_id IS NOT NULL AND bool_value IS NULL) OR (value_id IS NULL AND bool_value IS NOT NULL)));
-- copy rows from old table "model_catalog_transport_binding_selections" to new temporary table "new_model_catalog_transport_binding_selections"
INSERT INTO `new_model_catalog_transport_binding_selections` (`context_id`, `source_id`, `provider_id`, `model_id`, `transport_model_id`, `option_id`, `value_id`, `bool_value`) SELECT 'f4e0af598701912cd0516d11908757cf6c4f7a694c3113922f1f77d0fbd8c80e', `source_id`, `provider_id`, `model_id`, `transport_model_id`, `option_id`, `value_id`, `bool_value` FROM `model_catalog_transport_binding_selections` WHERE `source_id` IN ('builtin', 'config', 'models_dev');
-- drop "model_catalog_transport_binding_selections" table after copying rows
DROP TABLE `model_catalog_transport_binding_selections`;
-- rename temporary table "new_model_catalog_transport_binding_selections" to "model_catalog_transport_binding_selections"
ALTER TABLE `new_model_catalog_transport_binding_selections` RENAME TO `model_catalog_transport_binding_selections`;
-- create index "idx_model_catalog_binding_selections_binding" to table: "model_catalog_transport_binding_selections"
CREATE INDEX `idx_model_catalog_binding_selections_binding` ON `model_catalog_transport_binding_selections` (`context_id`, `source_id`, `provider_id`, `model_id`, `transport_model_id`, `option_id`);
-- create index "model_catalog_execution_contexts_scope_profile_id_workspace_id_command_fingerprint" to table: "model_catalog_execution_contexts"
CREATE UNIQUE INDEX `model_catalog_execution_contexts_scope_profile_id_workspace_id_command_fingerprint` ON `model_catalog_execution_contexts` (`scope`, `profile_id`, `workspace_id`, `command_fingerprint`);
-- enable back the enforcement of foreign-keys constraints
PRAGMA foreign_keys = on;
