-- +goose Up
-- disable the enforcement of foreign-keys constraints
PRAGMA foreign_keys = off;
-- create "new_session_input_queue" table
CREATE TABLE `new_session_input_queue` (`id` text NULL, `session_id` text NOT NULL, `prompt_admission_id` text NULL, `message_id` text NOT NULL DEFAULT '', `idempotency_key` text NOT NULL DEFAULT '', `turn_id` text NOT NULL DEFAULT '', `target_turn_id` text NOT NULL DEFAULT '', `event_id` text NOT NULL DEFAULT '', `status` text NOT NULL, `mode` text NOT NULL, `delivery` text NOT NULL DEFAULT 'after_turn', `steer_delivery` text NULL, `text` text NOT NULL, `synthetic_prompt_json` text NULL, `skill_invocations_json` text NOT NULL DEFAULT '[]', `attachments_json` text NOT NULL DEFAULT '[]', `runtime_provider` text NOT NULL DEFAULT '', `runtime_model` text NOT NULL DEFAULT '', `runtime_reasoning_effort` text NOT NULL DEFAULT '', `runtime_speed` text NOT NULL DEFAULT '', `runtime_acp_options_json` text NOT NULL DEFAULT '[]', `session_generation` integer NOT NULL DEFAULT 0, `task_run_id` text NOT NULL DEFAULT '', `run_generation` integer NULL, `attempt_count` integer NOT NULL DEFAULT 0, `enqueued_at` text NOT NULL, `dispatch_started_at` text NULL, `sent_at` text NULL, `failed_at` text NULL, `failure_summary` text NOT NULL DEFAULT '', `canceled_at` text NULL, `updated_at` text NOT NULL, `loop_run_id` text NULL, `owner_kind` text NULL, `owner_epoch` integer NULL, `binding_epoch` integer NULL, `prompt_id` text NULL, `prompt_kind` text NULL, `operation_usage_base_tokens` integer NULL, `prompt_attempt` integer NOT NULL DEFAULT 0, `dispatchable` integer NOT NULL DEFAULT 1, `activated_at` timestamp NULL, `dispatch_token_hash` text NULL, `fence_kind` text NULL, `fence_disposition` text NULL, `fence_reason_code` text NULL, `fenced_at` timestamp NULL, `terminal_event_start_seq` integer NULL, `terminal_event_end_seq` integer NULL, `terminal_kind` text NULL, `terminal_stop_reason` text NULL, `terminal_disposition` text NULL, `terminal_reason_code` text NULL, `terminal_tokens_reported` integer NOT NULL DEFAULT 0, `terminal_tokens_used` integer NULL, `terminal_at` timestamp NULL, `priority` integer NOT NULL DEFAULT 0, PRIMARY KEY (`id`), CONSTRAINT `0` FOREIGN KEY (`prompt_admission_id`) REFERENCES `session_prompt_admissions` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT `1` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (status IN ('queued', 'dispatching', 'sent', 'failed', 'canceled')), CHECK (mode IN ('queue', 'steer', 'interrupt')), CHECK (delivery IN ('after_turn', 'interrupt_then_prompt')), CHECK (steer_delivery IN ('injected', 'pending_injection', 'interrupt_fallback')), CHECK (synthetic_prompt_json IS NULL OR json_valid(synthetic_prompt_json)), CHECK (json_valid(skill_invocations_json)), CHECK (json_valid(attachments_json)), CHECK (json_valid(runtime_acp_options_json)), CHECK (attempt_count >= 0), CHECK (prompt_attempt >= 0), CHECK (dispatchable IN (0,1)), CHECK (terminal_tokens_reported IN (0,1)), CHECK (terminal_tokens_used IS NULL OR terminal_tokens_used >= 0));
-- copy rows from old table "session_input_queue" to new temporary table "new_session_input_queue"
INSERT INTO `new_session_input_queue` (`id`, `session_id`, `prompt_admission_id`, `message_id`, `idempotency_key`, `turn_id`, `target_turn_id`, `event_id`, `status`, `mode`, `delivery`, `steer_delivery`, `text`, `synthetic_prompt_json`, `skill_invocations_json`, `attachments_json`, `runtime_provider`, `runtime_model`, `runtime_reasoning_effort`, `runtime_speed`, `runtime_acp_options_json`, `session_generation`, `task_run_id`, `run_generation`, `attempt_count`, `enqueued_at`, `dispatch_started_at`, `sent_at`, `failed_at`, `failure_summary`, `canceled_at`, `updated_at`, `loop_run_id`, `owner_kind`, `owner_epoch`, `binding_epoch`, `prompt_id`, `prompt_kind`, `operation_usage_base_tokens`, `prompt_attempt`, `dispatchable`, `activated_at`, `dispatch_token_hash`, `fence_kind`, `fence_disposition`, `fence_reason_code`, `fenced_at`, `terminal_event_start_seq`, `terminal_event_end_seq`, `terminal_kind`, `terminal_stop_reason`, `terminal_disposition`, `terminal_reason_code`, `terminal_tokens_reported`, `terminal_tokens_used`, `terminal_at`) SELECT `id`, `session_id`, `prompt_admission_id`, `message_id`, `idempotency_key`, `turn_id`, `target_turn_id`, `event_id`, `status`, `mode`, `delivery`, `steer_delivery`, `text`, `synthetic_prompt_json`, `skill_invocations_json`, `attachments_json`, `runtime_provider`, `runtime_model`, `runtime_reasoning_effort`, `runtime_speed`, `runtime_acp_options_json`, `session_generation`, `task_run_id`, `run_generation`, `attempt_count`, `enqueued_at`, `dispatch_started_at`, `sent_at`, `failed_at`, `failure_summary`, `canceled_at`, `updated_at`, `loop_run_id`, `owner_kind`, `owner_epoch`, `binding_epoch`, `prompt_id`, `prompt_kind`, `operation_usage_base_tokens`, `prompt_attempt`, `dispatchable`, `activated_at`, `dispatch_token_hash`, `fence_kind`, `fence_disposition`, `fence_reason_code`, `fenced_at`, `terminal_event_start_seq`, `terminal_event_end_seq`, `terminal_kind`, `terminal_stop_reason`, `terminal_disposition`, `terminal_reason_code`, `terminal_tokens_reported`, `terminal_tokens_used`, `terminal_at` FROM `session_input_queue`;
-- drop "session_input_queue" table after copying rows
DROP TABLE `session_input_queue`;
-- rename temporary table "new_session_input_queue" to "session_input_queue"
ALTER TABLE `new_session_input_queue` RENAME TO `session_input_queue`;
-- create index "idx_session_input_queue_generation" to table: "session_input_queue"
CREATE INDEX `idx_session_input_queue_generation` ON `session_input_queue` (`session_id`, `session_generation`, `status`);
-- create index "idx_session_input_queue_goal_owner" to table: "session_input_queue"
CREATE INDEX `idx_session_input_queue_goal_owner` ON `session_input_queue` (`loop_run_id`, `task_run_id`, `owner_epoch`, `status`, `dispatchable`, `fence_kind`);
-- create index "idx_session_input_queue_pending" to table: "session_input_queue"
CREATE INDEX `idx_session_input_queue_pending` ON `session_input_queue` (`session_id`, `status`, `delivery` DESC, `priority` DESC, `enqueued_at`, `id`);
-- create index "uq_session_input_queue_prompt_admission" to table: "session_input_queue"
CREATE UNIQUE INDEX `uq_session_input_queue_prompt_admission` ON `session_input_queue` (`prompt_admission_id`) WHERE prompt_admission_id IS NOT NULL;
-- create index "uq_session_input_queue_active_steer" to table: "session_input_queue"
CREATE UNIQUE INDEX `uq_session_input_queue_active_steer` ON `session_input_queue` (`session_id`) WHERE mode = 'steer' AND status = 'queued';
-- create index "uq_session_input_queue_goal_prompt" to table: "session_input_queue"
CREATE UNIQUE INDEX `uq_session_input_queue_goal_prompt` ON `session_input_queue` (`loop_run_id`, `prompt_id`) WHERE prompt_id IS NOT NULL;
-- create index "uq_session_input_queue_synthetic_message" to table: "session_input_queue"
CREATE UNIQUE INDEX `uq_session_input_queue_synthetic_message` ON `session_input_queue` (`session_id`, `message_id`) WHERE owner_kind = 'synthetic' AND message_id <> '' AND status IN ('queued','dispatching');
-- create "session_subagent_wakes" table
CREATE TABLE `session_subagent_wakes` (`wake_message_id` text NULL, `workspace_id` text NOT NULL, `parent_session_id` text NOT NULL, `state` text NOT NULL, `route` text NOT NULL, `input_entry_id` text NOT NULL DEFAULT '', `steer_requeued` integer NOT NULL DEFAULT 0, `attempts` integer NOT NULL DEFAULT 0 CHECK (attempts >= 0), `created_at` text NOT NULL, `updated_at` text NOT NULL, PRIMARY KEY (`wake_message_id`), CONSTRAINT `0` FOREIGN KEY (`workspace_id`, `parent_session_id`) REFERENCES `sessions` (`workspace_id`, `id`) ON UPDATE NO ACTION ON DELETE CASCADE, CHECK (state IN ('open','dispatched','settled','canceled')), CHECK (route IN ('queue','steer')));
CREATE INDEX `idx_session_subagent_wakes_parent_state` ON `session_subagent_wakes` (`parent_session_id`, `state`);
-- create index "uq_session_subagent_wakes_open" to table: "session_subagent_wakes"
CREATE UNIQUE INDEX `uq_session_subagent_wakes_open` ON `session_subagent_wakes` (`parent_session_id`) WHERE state = 'open';
-- create "session_subagents" table
CREATE TABLE `session_subagents` (`id` text NULL, `workspace_id` text NOT NULL, `parent_session_id` text NOT NULL, `parent_turn_id` text NOT NULL, `parent_tool_call_id` text NOT NULL DEFAULT '', `child_session_id` text NULL, `origin` text NOT NULL, `provider_tool_call_id` text NOT NULL DEFAULT '', `idempotency_key` text NOT NULL, `request_fingerprint` text NOT NULL, `title` text NOT NULL, `role` text NOT NULL DEFAULT 'general', `task_chars` integer NOT NULL, `pending_task` text NULL, `runtime_agent` text NOT NULL DEFAULT '', `runtime_provider` text NOT NULL DEFAULT '', `runtime_model` text NOT NULL DEFAULT '', `runtime_reasoning_effort` text NOT NULL DEFAULT '', `runtime_speed` text NOT NULL DEFAULT '', `depth` integer NOT NULL, `status` text NOT NULL, `work_state` text NOT NULL, `progress` text NOT NULL DEFAULT '', `result` text NULL, `result_truncated` integer NOT NULL DEFAULT 0, `error` text NULL, `wake_policy` text NOT NULL, `delivery` text NOT NULL DEFAULT 'none', `wake_message_id` text NULL, `acknowledged_turn_id` text NOT NULL DEFAULT '', `started_at` text NULL, `settled_at` text NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `0` FOREIGN KEY (`workspace_id`, `parent_session_id`) REFERENCES `sessions` (`workspace_id`, `id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `1` FOREIGN KEY (`wake_message_id`) REFERENCES `session_subagent_wakes` (`wake_message_id`) ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT `2` FOREIGN KEY (`child_session_id`) REFERENCES `sessions` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, CHECK (origin IN ('delegated','provider_native')), CHECK (length(title) <= 512), CHECK (depth >= 1), CHECK (status IN ('queued','running','waiting','completed','failed','canceled','interrupted')), CHECK (work_state IN ('working','waiting_for_children','result_available')), CHECK (length(progress) <= 280), CHECK (wake_policy IN ('always','settled_only')), CHECK (delivery IN ('none','pending','claimed','delivered','acknowledged','disposed')));
-- create index "session_subagents_child_session_id" to table: "session_subagents"
CREATE UNIQUE INDEX `session_subagents_child_session_id` ON `session_subagents` (`child_session_id`);
-- create index "session_subagents_parent_session_id_idempotency_key" to table: "session_subagents"
CREATE UNIQUE INDEX `session_subagents_parent_session_id_idempotency_key` ON `session_subagents` (`parent_session_id`, `idempotency_key`);
-- create index "idx_session_subagents_parent_created" to table: "session_subagents"
CREATE INDEX `idx_session_subagents_parent_created` ON `session_subagents` (`parent_session_id`, `created_at`);
-- create index "idx_session_subagents_workspace_status" to table: "session_subagents"
CREATE INDEX `idx_session_subagents_workspace_status` ON `session_subagents` (`workspace_id`, `status`);
-- create index "idx_session_subagents_parent_delivery" to table: "session_subagents"
CREATE INDEX `idx_session_subagents_parent_delivery` ON `session_subagents` (`parent_session_id`, `delivery`) WHERE delivery IN ('pending','claimed');
-- create index "idx_session_subagents_provider_tool" to table: "session_subagents"
CREATE INDEX `idx_session_subagents_provider_tool` ON `session_subagents` (`parent_session_id`, `provider_tool_call_id`) WHERE origin = 'provider_native';
-- enable back the enforcement of foreign-keys constraints
PRAGMA foreign_keys = on;
