-- +goose Up
-- disable the enforcement of foreign-keys constraints
PRAGMA foreign_keys = off;
-- create "new_session_subagents" table
CREATE TABLE `new_session_subagents` (`id` text NULL, `workspace_id` text NOT NULL, `parent_session_id` text NOT NULL, `parent_turn_id` text NOT NULL, `parent_tool_call_id` text NOT NULL DEFAULT '', `child_session_id` text NULL, `origin` text NOT NULL, `provider_tool_call_id` text NOT NULL DEFAULT '', `idempotency_key` text NOT NULL, `request_fingerprint` text NOT NULL, `title` text NOT NULL, `role` text NOT NULL DEFAULT 'general', `task_chars` integer NOT NULL, `pending_task` text NULL, `runtime_agent` text NOT NULL DEFAULT '', `runtime_provider` text NOT NULL DEFAULT '', `runtime_model` text NOT NULL DEFAULT '', `runtime_reasoning_effort` text NOT NULL DEFAULT '', `runtime_speed` text NOT NULL DEFAULT '', `depth` integer NOT NULL, `status` text NOT NULL, `work_state` text NOT NULL, `progress` text NOT NULL DEFAULT '', `result` text NULL, `result_truncated` integer NOT NULL DEFAULT 0, `error` text NULL, `wake_policy` text NOT NULL, `delivery` text NOT NULL DEFAULT 'none', `wake_message_id` text NULL, `acknowledged_turn_id` text NOT NULL DEFAULT '', `started_at` text NULL, `settled_at` text NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL, `isolation` text NOT NULL DEFAULT 'shared', `worktree_id` text NULL, `worktree_name` text NULL, `worktree_branch` text NULL, `worktree_base_ref` text NULL, `worktree_path` text NULL, `worktree_base_sha` text NULL, `worktree_cleanup` text NULL, `git_head_sha` text NULL, `git_commits_ahead` integer NULL, `git_dirty_files` integer NULL, `git_observed_at` text NULL, `pr_status` text NULL, `pr_url` text NULL, `pr_number` integer NULL, PRIMARY KEY (`id`), CONSTRAINT `0` FOREIGN KEY (`workspace_id`, `parent_session_id`) REFERENCES `sessions` (`workspace_id`, `id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `1` FOREIGN KEY (`wake_message_id`) REFERENCES `session_subagent_wakes` (`wake_message_id`) ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT `2` FOREIGN KEY (`child_session_id`) REFERENCES `sessions` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, CHECK (origin IN ('delegated','provider_native')), CHECK (length(title) <= 512), CHECK (depth >= 1), CHECK (status IN ('queued','running','waiting','completed','failed','canceled','interrupted')), CHECK (work_state IN ('working','waiting_for_children','result_available')), CHECK (length(progress) <= 280), CHECK (wake_policy IN ('always','settled_only')), CHECK (delivery IN ('none','pending','claimed','delivered','acknowledged','disposed')), CHECK (isolation IN ('shared','worktree')), CHECK (worktree_cleanup IN ('pending','done')), CHECK (pr_status IN ('unknown','none','open','draft','merged','closed')));
-- copy rows from old table "session_subagents" to new temporary table "new_session_subagents"
INSERT INTO `new_session_subagents` (`id`, `workspace_id`, `parent_session_id`, `parent_turn_id`, `parent_tool_call_id`, `child_session_id`, `origin`, `provider_tool_call_id`, `idempotency_key`, `request_fingerprint`, `title`, `role`, `task_chars`, `pending_task`, `runtime_agent`, `runtime_provider`, `runtime_model`, `runtime_reasoning_effort`, `runtime_speed`, `depth`, `status`, `work_state`, `progress`, `result`, `result_truncated`, `error`, `wake_policy`, `delivery`, `wake_message_id`, `acknowledged_turn_id`, `started_at`, `settled_at`, `created_at`, `updated_at`) SELECT `id`, `workspace_id`, `parent_session_id`, `parent_turn_id`, `parent_tool_call_id`, `child_session_id`, `origin`, `provider_tool_call_id`, `idempotency_key`, `request_fingerprint`, `title`, `role`, `task_chars`, `pending_task`, `runtime_agent`, `runtime_provider`, `runtime_model`, `runtime_reasoning_effort`, `runtime_speed`, `depth`, `status`, `work_state`, `progress`, `result`, `result_truncated`, `error`, `wake_policy`, `delivery`, `wake_message_id`, `acknowledged_turn_id`, `started_at`, `settled_at`, `created_at`, `updated_at` FROM `session_subagents`;
-- drop "session_subagents" table after copying rows
DROP TABLE `session_subagents`;
-- rename temporary table "new_session_subagents" to "session_subagents"
ALTER TABLE `new_session_subagents` RENAME TO `session_subagents`;
-- create index "session_subagents_child_session_id" to table: "session_subagents"
CREATE UNIQUE INDEX `session_subagents_child_session_id` ON `session_subagents` (`child_session_id`);
-- create index "session_subagents_parent_session_id_idempotency_key" to table: "session_subagents"
CREATE UNIQUE INDEX `session_subagents_parent_session_id_idempotency_key` ON `session_subagents` (`parent_session_id`, `idempotency_key`);
-- create index "idx_session_subagents_parent_created" to table: "session_subagents"
CREATE INDEX `idx_session_subagents_parent_created` ON `session_subagents` (`parent_session_id`, `created_at`);
-- create index "idx_session_subagents_workspace_status" to table: "session_subagents"
CREATE INDEX `idx_session_subagents_workspace_status` ON `session_subagents` (`workspace_id`, `status`);
-- create index "idx_session_subagents_parent_delivery" to table: "session_subagents"
CREATE INDEX `idx_session_subagents_parent_delivery` ON `session_subagents` (`parent_session_id`, `delivery`) WHERE delivery IN ('pending','claimed');
-- create index "idx_session_subagents_provider_tool" to table: "session_subagents"
CREATE INDEX `idx_session_subagents_provider_tool` ON `session_subagents` (`parent_session_id`, `provider_tool_call_id`) WHERE origin = 'provider_native';
-- create index "idx_session_subagents_worktree_cleanup" to table: "session_subagents"
CREATE INDEX `idx_session_subagents_worktree_cleanup` ON `session_subagents` (`worktree_cleanup`) WHERE worktree_cleanup = 'pending';
-- enable back the enforcement of foreign-keys constraints
PRAGMA foreign_keys = on;
