id: hello
version: 0.1.0
description: Greets the provided name to verify Temporal standalone mode is running.

schemas:
  - id: hello_input
    type: object
    properties:
      name:
        type: string
        description: Name to mention in the greeting
    required:
      - name

config:
  input: hello_input

tasks:
  - id: compose_greeting
    type: basic
    prompt: |-
      You are a friendly assistant verifying that Temporal standalone mode works.
      Respond with a short greeting that mentions {{ .workflow.input.name }} and
      confirms the workflow executed in standalone mode.
    final: true
