package builtin

const loopStatusOutputSchema = `{
	"type":"object",
	"required":["run"],
	"properties":{
		"run":{
			"type":"object",
			"properties":{
				"best_generation":{"type":"integer","minimum":1},
				"best_score":{"type":"number"}
			},
			"additionalProperties":true
		},
		"executed_definition":{"type":"object"},
		"generations":{
			"type":"array",
			"items":{
				"type":"object",
				"required":["generation","parent_generation","origin","verdicts","outputs"],
				"properties":{
					"generation":{"type":"integer","minimum":1},
					"parent_generation":{"type":"integer","minimum":0},
					"origin":{
						"type":"string",
						"enum":[
							"initial","stop_when","reattempt","gate_revise",
							"gate_next_generation","dod_retry","ratchet_restore"
						]
					},
					"verdicts":{
						"type":"array",
						"items":{
							"type":"object",
							"required":["gate_id","outcome"],
							"properties":{
								"gate_id":{"type":"string","minLength":1},
								"outcome":{
									"type":"string",
									"enum":[
										"approved","rejected","awaiting_approval","blocked",
										"error","timeout","invalid_output"
									]
								},
								"score":{"type":"number"},
								"route_cause_rank":{"type":"integer","minimum":0}
							},
							"additionalProperties":false
						}
					},
					"outputs":{"type":"array","items":{"type":"object"}}
				},
				"additionalProperties":false
			}
		},
		"watch_events":{"type":"object"}
	},
	"additionalProperties":false
}`

const loopRunsOutputSchema = `{
	"type":"object",
	"required":["runs","aggregates"],
	"properties":{
		"runs":{
			"type":"array",
			"items":{
				"type":"object",
				"not":{"required":["generations"]},
				"properties":{
					"best_generation":{"type":"integer","minimum":1},
					"best_score":{"type":"number"}
				},
				"additionalProperties":true
			}
		},
		"aggregates":{
			"type":"object",
			"required":["total","live","terminal","succeeded","failed"],
			"properties":{
				"total":{"type":"integer","minimum":0},
				"live":{"type":"integer","minimum":0},
				"terminal":{"type":"integer","minimum":0},
				"succeeded":{"type":"integer","minimum":0},
				"failed":{"type":"integer","minimum":0}
			},
			"additionalProperties":false
		}
	},
	"additionalProperties":false
}`
