package builtin

import toolspkg "github.com/compozy/agh/internal/tools"

const (
	tasksNotificationsKey = "notifications"
)

const (
	tasksBridgesKey                = "bridges"
	tasksExecutionProfileKey       = "execution_profile"
	tasksReviewsKey                = "reviews"
	tasksRunsKey                   = "runs"
	tasksTaskExecutionProfileValue = "task execution profile"
	tasksTasksKey                  = "tasks"
)

var taskTools = []toolspkg.Descriptor{
	nativeDescriptor(
		toolspkg.ToolIDTaskList,
		"task_list",
		"Task List",
		"List task summaries through the existing task service.",
		taskListInputSchema,
		toolspkg.RiskRead,
		true,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, "coordination"},
		[]string{"task summaries", "task inbox"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskRead,
		"task_read",
		"Task Read",
		"Read one task view through the existing task service.",
		taskReadInputSchema,
		toolspkg.RiskRead,
		true,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, "coordination"},
		[]string{"task details", "task view"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskCreate,
		"task_create",
		"Task Create",
		"Create one root task through the existing task service.",
		taskCreateInputSchema,
		toolspkg.RiskMutating,
		false,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, "create"},
		[]string{"create task", "new task"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskChildCreate,
		"task_child_create",
		"Task Child Create",
		"Create one child task through the task service.",
		taskChildCreateInputSchema,
		toolspkg.RiskMutating,
		false,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, "create", "children"},
		[]string{"create child task", "task lineage"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskUpdate,
		"task_update",
		"Task Update",
		"Update one task through the task service.",
		taskUpdateInputSchema,
		toolspkg.RiskMutating,
		false,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, descriptorKeywordUpdate},
		[]string{"edit task", "patch task"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskCancel,
		"task_cancel",
		"Task Cancel",
		"Cancel one task through the task service.",
		taskCancelInputSchema,
		toolspkg.RiskDestructive,
		false,
		true,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, "cancel"},
		[]string{"cancel task", "stop task tree"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskBlock,
		"task_block",
		"Task Block",
		"Create a typed task block through the task service.",
		taskBlockInputSchema,
		toolspkg.RiskMutating,
		false,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, "block"},
		[]string{"block task", "task blocked reason"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskUnblock,
		"task_unblock",
		"Task Unblock",
		"Clear one task block through the task service.",
		taskUnblockInputSchema,
		toolspkg.RiskMutating,
		false,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, "unblock"},
		[]string{"unblock task", "clear task block"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskBlocks,
		"task_blocks",
		"Task Blocks",
		"List task blocks through the task service.",
		taskBlocksInputSchema,
		toolspkg.RiskRead,
		true,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, "blocks"},
		[]string{"task blocks", "blocked reasons"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskRecover,
		"task_recover",
		"Task Recover",
		"Recover one task from needs_attention through the task service.",
		taskRecoverInputSchema,
		toolspkg.RiskMutating,
		false,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, "recover"},
		[]string{"recover task", "needs_attention"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskRunList,
		"task_run_list",
		"Task Run List",
		"List task runs through the task service.",
		taskRunListInputSchema,
		toolspkg.RiskRead,
		true,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksRunsKey},
		[]string{"task runs", "run history"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskRunReviewRequest,
		"task_run_review_request",
		"Task Run Review Request",
		"Request a persisted review for one terminal task run through the task service.",
		taskRunReviewRequestInputSchema,
		toolspkg.RiskMutating,
		false,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksReviewsKey},
		[]string{"request task review", "run review"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskRunReviewList,
		"task_run_review_list",
		"Task Run Review List",
		"List persisted task-run reviews through the task service.",
		taskRunReviewListInputSchema,
		toolspkg.RiskRead,
		true,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksReviewsKey},
		[]string{"review history", "task reviews"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskRunReviewShow,
		"task_run_review_show",
		"Task Run Review Show",
		"Read one persisted task-run review through the task service.",
		taskRunReviewShowInputSchema,
		toolspkg.RiskRead,
		true,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksReviewsKey},
		[]string{"review detail", "show task review"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskExecutionProfileGet,
		"task_execution_profile_get",
		"Task Execution Profile Get",
		"Read one task execution profile through the task service.",
		taskExecutionProfileGetInputSchema,
		toolspkg.RiskRead,
		true,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksExecutionProfileKey},
		[]string{tasksTaskExecutionProfileValue, "profile get"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskExecutionProfileSet,
		"task_execution_profile_set",
		"Task Execution Profile Set",
		"Update one task execution profile through the task service.",
		taskExecutionProfileSetInputSchema,
		toolspkg.RiskMutating,
		false,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksExecutionProfileKey},
		[]string{tasksTaskExecutionProfileValue, "profile set"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskExecutionProfileDelete,
		"task_execution_profile_delete",
		"Task Execution Profile Delete",
		"Delete one task execution profile through the task service.",
		taskExecutionProfileDeleteInputSchema,
		toolspkg.RiskDestructive,
		false,
		true,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksExecutionProfileKey},
		[]string{tasksTaskExecutionProfileValue, "profile delete"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskNotificationSubscribe,
		"task_notification_subscribe",
		"Task Notification Subscribe",
		"Create one bridge notification subscription for terminal task events.",
		taskNotificationSubscribeInputSchema,
		toolspkg.RiskMutating,
		false,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksNotificationsKey, tasksBridgesKey},
		[]string{"task notification subscribe", "bridge task subscription"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskNotificationList,
		"task_notification_list",
		"Task Notification List",
		"List bridge notification subscriptions for one task.",
		taskNotificationListInputSchema,
		toolspkg.RiskRead,
		true,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksNotificationsKey, tasksBridgesKey},
		[]string{"task notification list", "bridge task subscriptions"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskNotificationShow,
		"task_notification_show",
		"Task Notification Show",
		"Read one bridge notification subscription for one task.",
		taskNotificationShowInputSchema,
		toolspkg.RiskRead,
		true,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksNotificationsKey, tasksBridgesKey},
		[]string{"task notification show", "bridge task subscription detail"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskNotificationDelete,
		"task_notification_delete",
		"Task Notification Delete",
		"Delete one bridge notification subscription for one task.",
		taskNotificationDeleteInputSchema,
		toolspkg.RiskDestructive,
		false,
		true,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksNotificationsKey, tasksBridgesKey},
		[]string{"task notification delete", "unsubscribe bridge task notification"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskPromoteFromThread,
		"task_promote_from_thread",
		"Task Promote From Thread",
		"Promote one AGH network thread message into a durable workspace task.",
		taskPromoteFromThreadInputSchema,
		toolspkg.RiskMutating,
		false,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks, toolspkg.ToolsetIDCoordination},
		[]string{tasksTasksKey, "network", "promote"},
		[]string{"promote network thread", "thread to task"},
	),
	nativeDescriptor(
		toolspkg.ToolIDTaskFanOutRuns,
		"task_fanout_runs",
		"Task Fan-Out Runs",
		"Create designated sibling runs for one task.",
		taskFanOutRunsInputSchema,
		toolspkg.RiskMutating,
		false,
		false,
		false,
		[]toolspkg.ToolsetID{toolspkg.ToolsetIDTasks},
		[]string{tasksTasksKey, tasksRunsKey, "fanout"},
		[]string{"task fan-out", "designated task runs"},
	),
}

func taskDescriptors() []toolspkg.Descriptor {
	return taskTools
}
