services:
  postgres:
    image: postgres:16-alpine
    container_name: compozy-distributed-postgres
    environment:
      POSTGRES_DB: compozy
      POSTGRES_USER: compozy
      POSTGRES_PASSWORD: compozy
    ports:
      - "55432:5432"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U compozy"
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: compozy-distributed-redis
    command:
      - "redis-server"
      - "--save"
      - "60"
      - "1"
      - "--loglevel"
      - "warning"
    ports:
      - "56379:6379"
    healthcheck:
      test:
        - "CMD"
        - "redis-cli"
        - "ping"
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - redis-data:/data

  temporal:
    image: temporalio/auto-setup:1.23.0
    container_name: compozy-distributed-temporal
    environment:
      - DB=sqlite
      - SQLITE_PATH=/var/lib/temporal/temporal.db
      - SQLITE_PRAGMA_JOURNAL_MODE=wal
      - TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE:-compozy-distributed}
    ports:
      - "7233:7233"
    healthcheck:
      test:
        - "CMD"
        - "temporal"
        - "workflow"
        - "list"
        - "--address"
        - "temporal:7233"
        - "--namespace"
        - "${TEMPORAL_NAMESPACE:-compozy-distributed}"
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - temporal-data:/var/lib/temporal

  temporal-ui:
    image: temporalio/ui:2.24.0
    container_name: compozy-distributed-temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE:-compozy-distributed}
    ports:
      - "8233:8080"
    depends_on:
      - temporal

volumes:
  postgres-data:
  redis-data:
  temporal-data:
