package bridges

import (
	"errors"
	"fmt"
	"slices"
	"strings"

	bridgecontract "github.com/compozy/agh/internal/bridges/contract"
)

const (
	slackPlatform                     = "slack"
	slackManifestNameMaxLength        = 35
	slackManifestDescriptionMaxLength = 140
	slackBotDisplayNameMaxLength      = 80
	slackManifestBackgroundColor      = "#E8572A"
)

type slackBotEvent string

const (
	slackEventAppMention      slackBotEvent = "app_mention"
	slackEventMessageChannels slackBotEvent = "message.channels"
	slackEventMessageGroups   slackBotEvent = "message.groups"
	slackEventMessageIM       slackBotEvent = "message.im"
	slackEventMessageMPIM     slackBotEvent = "message.mpim"
	slackEventReactionAdded   slackBotEvent = "reaction_added"
	slackEventReactionRemoved slackBotEvent = "reaction_removed"
)

type slackBotScope string

const (
	slackScopeAppMentionsRead slackBotScope = "app_mentions:read"
	slackScopeChannelsHistory slackBotScope = "channels:history"
	slackScopeGroupsHistory   slackBotScope = "groups:history"
	slackScopeIMHistory       slackBotScope = "im:history"
	slackScopeMPIMHistory     slackBotScope = "mpim:history"
	slackScopeReactionsRead   slackBotScope = "reactions:read"
)

var slackRequiredScopesByEvent = map[slackBotEvent][]slackBotScope{
	slackEventAppMention:      {slackScopeAppMentionsRead},
	slackEventMessageChannels: {slackScopeChannelsHistory},
	slackEventMessageGroups:   {slackScopeGroupsHistory},
	slackEventMessageIM:       {slackScopeIMHistory},
	slackEventMessageMPIM:     {slackScopeMPIMHistory},
	slackEventReactionAdded:   {slackScopeReactionsRead},
	slackEventReactionRemoved: {slackScopeReactionsRead},
}

// SlackAppManifest is the webhook-based Slack application artifact generated by AGH.
type SlackAppManifest struct {
	Metadata           SlackManifestMetadata           `json:"_metadata"`
	DisplayInformation SlackManifestDisplayInformation `json:"display_information"`
	Features           SlackManifestFeatures           `json:"features"`
	OAuthConfig        SlackManifestOAuthConfig        `json:"oauth_config"`
	Settings           SlackManifestSettings           `json:"settings"`
}

// SlackManifestMetadata selects Slack app manifest v1.
type SlackManifestMetadata struct {
	MajorVersion int `json:"major_version"`
	MinorVersion int `json:"minor_version"`
}

// SlackManifestDisplayInformation identifies the app in Slack's catalog and installer.
type SlackManifestDisplayInformation struct {
	Name            string `json:"name"`
	Description     string `json:"description"`
	BackgroundColor string `json:"background_color"`
}

// SlackManifestFeatures declares the bot user and catch-all slash command.
type SlackManifestFeatures struct {
	BotUser       SlackManifestBotUser        `json:"bot_user"`
	SlashCommands []SlackManifestSlashCommand `json:"slash_commands"`
}

// SlackManifestBotUser configures the installed Slack bot identity.
type SlackManifestBotUser struct {
	DisplayName  string `json:"display_name"`
	AlwaysOnline bool   `json:"always_online"`
}

// SlackManifestSlashCommand maps a Slack command to the bridge webhook.
type SlackManifestSlashCommand struct {
	Command      string `json:"command"`
	URL          string `json:"url"`
	Description  string `json:"description"`
	UsageHint    string `json:"usage_hint"`
	ShouldEscape bool   `json:"should_escape"`
}

// SlackManifestOAuthConfig declares the bot scopes installed with the app.
type SlackManifestOAuthConfig struct {
	Scopes SlackManifestOAuthScopes `json:"scopes"`
}

// SlackManifestOAuthScopes contains the required Slack bot token scopes.
type SlackManifestOAuthScopes struct {
	Bot []string `json:"bot"`
}

// SlackManifestSettings configures webhook delivery and disables Socket Mode.
type SlackManifestSettings struct {
	EventSubscriptions   SlackManifestEventSubscriptions `json:"event_subscriptions"`
	Interactivity        SlackManifestInteractivity      `json:"interactivity"`
	OrgDeployEnabled     bool                            `json:"org_deploy_enabled"`
	SocketModeEnabled    bool                            `json:"socket_mode_enabled"`
	TokenRotationEnabled bool                            `json:"token_rotation_enabled"`
}

// SlackManifestEventSubscriptions routes subscribed Slack events to AGH.
type SlackManifestEventSubscriptions struct {
	RequestURL string   `json:"request_url"`
	BotEvents  []string `json:"bot_events"`
}

// SlackManifestInteractivity routes Slack actions to AGH.
type SlackManifestInteractivity struct {
	IsEnabled  bool   `json:"is_enabled"`
	RequestURL string `json:"request_url"`
}

// SlackBotScopes returns a defensive copy of the canonical required bot scopes.
func SlackBotScopes() []string {
	return bridgecontract.SlackBotScopes()
}

// SlackBotEvents returns a defensive copy of the canonical subscribed bot events.
func SlackBotEvents() []string {
	result := make([]string, 0, len(slackRequiredScopesByEvent))
	for event := range slackRequiredScopesByEvent {
		result = append(result, string(event))
	}
	slices.Sort(result)
	return result
}

// SlackRequiredScopesForEvent returns the read scopes required by one subscribed event.
func SlackRequiredScopesForEvent(event string) []string {
	scopes := slackRequiredScopesByEvent[slackBotEvent(strings.TrimSpace(event))]
	if scopes == nil {
		return nil
	}
	result := make([]string, len(scopes))
	for index, scope := range scopes {
		result[index] = string(scope)
	}
	return result
}

// BuildSlackAppManifest composes one Slack artifact from installed provider and instance metadata.
func BuildSlackAppManifest(instance BridgeInstance, provider BridgeProvider) (SlackAppManifest, error) {
	normalized := instance.Normalized()
	if normalized.Platform != slackPlatform {
		return SlackAppManifest{}, fmt.Errorf(
			"bridges: Slack manifest requires a Slack instance, got %q",
			normalized.Platform,
		)
	}
	if strings.TrimSpace(provider.Platform) != slackPlatform ||
		strings.TrimSpace(provider.ExtensionName) != normalized.ExtensionName {
		return SlackAppManifest{}, errors.New("bridges: Slack manifest provider does not own the bridge instance")
	}
	publicURL, err := WebhookPublicURL(normalized)
	if err != nil {
		return SlackAppManifest{}, fmt.Errorf("bridges: build Slack manifest: %w", err)
	}

	name := truncateSlackManifestText(normalized.DisplayName, slackManifestNameMaxLength)
	botName := truncateSlackManifestText(normalized.DisplayName, slackBotDisplayNameMaxLength)
	description := strings.TrimSpace(provider.Description)
	if description == "" {
		description = "Connect Slack messages to AGH."
	}
	description = truncateSlackManifestText(description, slackManifestDescriptionMaxLength)

	return SlackAppManifest{
		Metadata: SlackManifestMetadata{MajorVersion: 1, MinorVersion: 1},
		DisplayInformation: SlackManifestDisplayInformation{
			Name:            name,
			Description:     description,
			BackgroundColor: slackManifestBackgroundColor,
		},
		Features: SlackManifestFeatures{
			BotUser: SlackManifestBotUser{DisplayName: botName},
			SlashCommands: []SlackManifestSlashCommand{{
				Command:      "/agh",
				URL:          publicURL,
				Description:  "Send a command to AGH",
				UsageHint:    "<command>",
				ShouldEscape: false,
			}},
		},
		OAuthConfig: SlackManifestOAuthConfig{
			Scopes: SlackManifestOAuthScopes{Bot: SlackBotScopes()},
		},
		Settings: SlackManifestSettings{
			EventSubscriptions: SlackManifestEventSubscriptions{
				RequestURL: publicURL,
				BotEvents:  SlackBotEvents(),
			},
			Interactivity: SlackManifestInteractivity{
				IsEnabled:  true,
				RequestURL: publicURL,
			},
			SocketModeEnabled: false,
		},
	}, nil
}

func truncateSlackManifestText(value string, maxRunes int) string {
	trimmed := strings.TrimSpace(value)
	runes := []rune(trimmed)
	if len(runes) <= maxRunes {
		return trimmed
	}
	return string(runes[:maxRunes])
}
