// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extension_mcp_overrides.sql

package sqlcgen

import (
	"context"
)

const deleteExtensionMCPAllocation = `-- name: DeleteExtensionMCPAllocation :exec
DELETE FROM extension_mcp_overrides
WHERE extension = ?1 AND profile = ?2
 AND workspace_id = ?3 AND server = ?4
`

type DeleteExtensionMCPAllocationParams struct {
	Extension   string `json:"extension"`
	Profile     string `json:"profile"`
	WorkspaceID string `json:"workspace_id"`
	Server      string `json:"server"`
}

func (q *Queries) DeleteExtensionMCPAllocation(ctx context.Context, arg DeleteExtensionMCPAllocationParams) error {
	_, err := q.db.ExecContext(ctx, deleteExtensionMCPAllocation,
		arg.Extension,
		arg.Profile,
		arg.WorkspaceID,
		arg.Server,
	)
	return err
}

const deleteExtensionMCPOverrides = `-- name: DeleteExtensionMCPOverrides :exec
DELETE FROM extension_mcp_overrides
WHERE extension = ?1 AND profile = ?2
 AND workspace_id = ?3
`

type DeleteExtensionMCPOverridesParams struct {
	Extension   string `json:"extension"`
	Profile     string `json:"profile"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteExtensionMCPOverrides(ctx context.Context, arg DeleteExtensionMCPOverridesParams) error {
	_, err := q.db.ExecContext(ctx, deleteExtensionMCPOverrides, arg.Extension, arg.Profile, arg.WorkspaceID)
	return err
}

const deleteExtensionMCPWorkspace = `-- name: DeleteExtensionMCPWorkspace :exec
DELETE FROM extension_mcp_overrides
WHERE extension = ?1 AND workspace_id = ?2
`

type DeleteExtensionMCPWorkspaceParams struct {
	Extension   string `json:"extension"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteExtensionMCPWorkspace(ctx context.Context, arg DeleteExtensionMCPWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, deleteExtensionMCPWorkspace, arg.Extension, arg.WorkspaceID)
	return err
}

const insertExtensionMCPAllocation = `-- name: InsertExtensionMCPAllocation :exec
INSERT INTO extension_mcp_overrides (
 extension, profile, workspace_id, server, runtime_name, updated_at
) VALUES (
 ?1, ?2, ?3, ?4,
 ?5, ?6
)
`

type InsertExtensionMCPAllocationParams struct {
	Extension   string `json:"extension"`
	Profile     string `json:"profile"`
	WorkspaceID string `json:"workspace_id"`
	Server      string `json:"server"`
	RuntimeName string `json:"runtime_name"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) InsertExtensionMCPAllocation(ctx context.Context, arg InsertExtensionMCPAllocationParams) error {
	_, err := q.db.ExecContext(ctx, insertExtensionMCPAllocation,
		arg.Extension,
		arg.Profile,
		arg.WorkspaceID,
		arg.Server,
		arg.RuntimeName,
		arg.UpdatedAt,
	)
	return err
}

const listAllExtensionMCPOverrides = `-- name: ListAllExtensionMCPOverrides :many
SELECT extension, profile, workspace_id, server, runtime_name, env_json, headers_json, url, updated_at FROM extension_mcp_overrides ORDER BY profile, workspace_id, extension, server
`

func (q *Queries) ListAllExtensionMCPOverrides(ctx context.Context) ([]ExtensionMcpOverride, error) {
	rows, err := q.db.QueryContext(ctx, listAllExtensionMCPOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtensionMcpOverride{}
	for rows.Next() {
		var i ExtensionMcpOverride
		if err := rows.Scan(
			&i.Extension,
			&i.Profile,
			&i.WorkspaceID,
			&i.Server,
			&i.RuntimeName,
			&i.EnvJson,
			&i.HeadersJson,
			&i.Url,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensionMCPOverrides = `-- name: ListExtensionMCPOverrides :many
SELECT extension, profile, workspace_id, server, runtime_name, env_json, headers_json, url, updated_at FROM extension_mcp_overrides
WHERE profile = ?1 AND workspace_id = ?2
ORDER BY extension, server
`

type ListExtensionMCPOverridesParams struct {
	Profile     string `json:"profile"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListExtensionMCPOverrides(ctx context.Context, arg ListExtensionMCPOverridesParams) ([]ExtensionMcpOverride, error) {
	rows, err := q.db.QueryContext(ctx, listExtensionMCPOverrides, arg.Profile, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtensionMcpOverride{}
	for rows.Next() {
		var i ExtensionMcpOverride
		if err := rows.Scan(
			&i.Extension,
			&i.Profile,
			&i.WorkspaceID,
			&i.Server,
			&i.RuntimeName,
			&i.EnvJson,
			&i.HeadersJson,
			&i.Url,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExtensionMCPOverride = `-- name: UpdateExtensionMCPOverride :execrows
UPDATE extension_mcp_overrides
SET env_json = ?1, headers_json = ?2,
 url = ?3, updated_at = ?4
WHERE extension = ?5 AND profile = ?6
 AND workspace_id = ?7 AND server = ?8
`

type UpdateExtensionMCPOverrideParams struct {
	EnvJson     string `json:"env_json"`
	HeadersJson string `json:"headers_json"`
	Url         string `json:"url"`
	UpdatedAt   string `json:"updated_at"`
	Extension   string `json:"extension"`
	Profile     string `json:"profile"`
	WorkspaceID string `json:"workspace_id"`
	Server      string `json:"server"`
}

func (q *Queries) UpdateExtensionMCPOverride(ctx context.Context, arg UpdateExtensionMCPOverrideParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateExtensionMCPOverride,
		arg.EnvJson,
		arg.HeadersJson,
		arg.Url,
		arg.UpdatedAt,
		arg.Extension,
		arg.Profile,
		arg.WorkspaceID,
		arg.Server,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
