// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extension_env_bindings.sql

package sqlcgen

import (
	"context"
)

const countExtensionEnvBindingsBySecretRef = `-- name: CountExtensionEnvBindingsBySecretRef :one
SELECT COUNT(*)
FROM extension_env_bindings
WHERE secret_ref = ?1
`

func (q *Queries) CountExtensionEnvBindingsBySecretRef(ctx context.Context, secretRef string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExtensionEnvBindingsBySecretRef, secretRef)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExtensionEnvBinding = `-- name: DeleteExtensionEnvBinding :execrows
DELETE FROM extension_env_bindings
WHERE extension_name = ?1
  AND workspace_id = ?2
  AND env_name = ?3
`

type DeleteExtensionEnvBindingParams struct {
	ExtensionName string `json:"extension_name"`
	WorkspaceID   string `json:"workspace_id"`
	EnvName       string `json:"env_name"`
}

func (q *Queries) DeleteExtensionEnvBinding(ctx context.Context, arg DeleteExtensionEnvBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExtensionEnvBinding, arg.ExtensionName, arg.WorkspaceID, arg.EnvName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExtensionEnvBindings = `-- name: DeleteExtensionEnvBindings :execrows
DELETE FROM extension_env_bindings
WHERE extension_name = ?1
  AND workspace_id = ?2
`

type DeleteExtensionEnvBindingsParams struct {
	ExtensionName string `json:"extension_name"`
	WorkspaceID   string `json:"workspace_id"`
}

func (q *Queries) DeleteExtensionEnvBindings(ctx context.Context, arg DeleteExtensionEnvBindingsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExtensionEnvBindings, arg.ExtensionName, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExtensionEnvBindingsByWorkspace = `-- name: DeleteExtensionEnvBindingsByWorkspace :execrows
DELETE FROM extension_env_bindings
WHERE workspace_id = ?1
`

func (q *Queries) DeleteExtensionEnvBindingsByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExtensionEnvBindingsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listExtensionEnvBindings = `-- name: ListExtensionEnvBindings :many
SELECT extension_name, workspace_id, env_name, secret_ref, mcp_server, header_name, kind, created_at, updated_at
FROM extension_env_bindings
WHERE extension_name = ?1
  AND workspace_id = ?2
ORDER BY env_name ASC
`

type ListExtensionEnvBindingsParams struct {
	ExtensionName string `json:"extension_name"`
	WorkspaceID   string `json:"workspace_id"`
}

func (q *Queries) ListExtensionEnvBindings(ctx context.Context, arg ListExtensionEnvBindingsParams) ([]ExtensionEnvBinding, error) {
	rows, err := q.db.QueryContext(ctx, listExtensionEnvBindings, arg.ExtensionName, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtensionEnvBinding{}
	for rows.Next() {
		var i ExtensionEnvBinding
		if err := rows.Scan(
			&i.ExtensionName,
			&i.WorkspaceID,
			&i.EnvName,
			&i.SecretRef,
			&i.McpServer,
			&i.HeaderName,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensionEnvSecretRefsByWorkspace = `-- name: ListExtensionEnvSecretRefsByWorkspace :many
SELECT DISTINCT secret_ref
FROM extension_env_bindings
WHERE workspace_id = ?1
ORDER BY secret_ref ASC
`

func (q *Queries) ListExtensionEnvSecretRefsByWorkspace(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExtensionEnvSecretRefsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var secret_ref string
		if err := rows.Scan(&secret_ref); err != nil {
			return nil, err
		}
		items = append(items, secret_ref)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExtensionEnvBinding = `-- name: UpsertExtensionEnvBinding :exec
INSERT INTO extension_env_bindings (
  extension_name, workspace_id, env_name, secret_ref, kind, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7
)
ON CONFLICT(extension_name, workspace_id, env_name) DO UPDATE SET
  secret_ref = excluded.secret_ref,
  kind = excluded.kind,
  updated_at = excluded.updated_at
`

type UpsertExtensionEnvBindingParams struct {
	ExtensionName string `json:"extension_name"`
	WorkspaceID   string `json:"workspace_id"`
	EnvName       string `json:"env_name"`
	SecretRef     string `json:"secret_ref"`
	Kind          string `json:"kind"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) UpsertExtensionEnvBinding(ctx context.Context, arg UpsertExtensionEnvBindingParams) error {
	_, err := q.db.ExecContext(ctx, upsertExtensionEnvBinding,
		arg.ExtensionName,
		arg.WorkspaceID,
		arg.EnvName,
		arg.SecretRef,
		arg.Kind,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
