// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goal_core.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const activeGoalPromptBindingExists = `-- name: ActiveGoalPromptBindingExists :one
SELECT 1 FROM loop_session_bindings
WHERE loop_run_id = ?1 AND workspace_id = ?2
  AND handle = ?3 AND binding_epoch = ?4
  AND session_id = ?5 AND state = 'active'
`

type ActiveGoalPromptBindingExistsParams struct {
	LoopRunID    string `json:"loop_run_id"`
	WorkspaceID  string `json:"workspace_id"`
	Handle       string `json:"handle"`
	BindingEpoch int64  `json:"binding_epoch"`
	SessionID    string `json:"session_id"`
}

func (q *Queries) ActiveGoalPromptBindingExists(ctx context.Context, arg ActiveGoalPromptBindingExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeGoalPromptBindingExists,
		arg.LoopRunID,
		arg.WorkspaceID,
		arg.Handle,
		arg.BindingEpoch,
		arg.SessionID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getGoalPromptRow = `-- name: GetGoalPromptRow :one
SELECT id, session_id, status, text, task_run_id, run_generation,
       loop_run_id, owner_kind, owner_epoch, binding_epoch, prompt_id, prompt_kind,
       prompt_attempt, dispatchable, operation_usage_base_tokens, dispatch_token_hash,
       fence_kind, fence_disposition, fence_reason_code,
       terminal_event_start_seq, terminal_event_end_seq, terminal_kind,
       terminal_stop_reason, terminal_disposition, terminal_reason_code,
       terminal_tokens_reported, terminal_tokens_used, terminal_at
FROM session_input_queue
WHERE loop_run_id = ?1 AND prompt_id = ?2
`

type GetGoalPromptRowParams struct {
	LoopRunID sql.NullString `json:"loop_run_id"`
	PromptID  sql.NullString `json:"prompt_id"`
}

type GetGoalPromptRowRow struct {
	ID                       string         `json:"id"`
	SessionID                string         `json:"session_id"`
	Status                   string         `json:"status"`
	Text                     string         `json:"text"`
	TaskRunID                string         `json:"task_run_id"`
	RunGeneration            sql.NullInt64  `json:"run_generation"`
	LoopRunID                sql.NullString `json:"loop_run_id"`
	OwnerKind                sql.NullString `json:"owner_kind"`
	OwnerEpoch               sql.NullInt64  `json:"owner_epoch"`
	BindingEpoch             sql.NullInt64  `json:"binding_epoch"`
	PromptID                 sql.NullString `json:"prompt_id"`
	PromptKind               sql.NullString `json:"prompt_kind"`
	PromptAttempt            int64          `json:"prompt_attempt"`
	Dispatchable             int64          `json:"dispatchable"`
	OperationUsageBaseTokens sql.NullInt64  `json:"operation_usage_base_tokens"`
	DispatchTokenHash        sql.NullString `json:"dispatch_token_hash"`
	FenceKind                sql.NullString `json:"fence_kind"`
	FenceDisposition         sql.NullString `json:"fence_disposition"`
	FenceReasonCode          sql.NullString `json:"fence_reason_code"`
	TerminalEventStartSeq    sql.NullInt64  `json:"terminal_event_start_seq"`
	TerminalEventEndSeq      sql.NullInt64  `json:"terminal_event_end_seq"`
	TerminalKind             sql.NullString `json:"terminal_kind"`
	TerminalStopReason       sql.NullString `json:"terminal_stop_reason"`
	TerminalDisposition      sql.NullString `json:"terminal_disposition"`
	TerminalReasonCode       sql.NullString `json:"terminal_reason_code"`
	TerminalTokensReported   int64          `json:"terminal_tokens_reported"`
	TerminalTokensUsed       sql.NullInt64  `json:"terminal_tokens_used"`
	TerminalAt               sql.NullTime   `json:"terminal_at"`
}

func (q *Queries) GetGoalPromptRow(ctx context.Context, arg GetGoalPromptRowParams) (GetGoalPromptRowRow, error) {
	row := q.db.QueryRowContext(ctx, getGoalPromptRow, arg.LoopRunID, arg.PromptID)
	var i GetGoalPromptRowRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.Text,
		&i.TaskRunID,
		&i.RunGeneration,
		&i.LoopRunID,
		&i.OwnerKind,
		&i.OwnerEpoch,
		&i.BindingEpoch,
		&i.PromptID,
		&i.PromptKind,
		&i.PromptAttempt,
		&i.Dispatchable,
		&i.OperationUsageBaseTokens,
		&i.DispatchTokenHash,
		&i.FenceKind,
		&i.FenceDisposition,
		&i.FenceReasonCode,
		&i.TerminalEventStartSeq,
		&i.TerminalEventEndSeq,
		&i.TerminalKind,
		&i.TerminalStopReason,
		&i.TerminalDisposition,
		&i.TerminalReasonCode,
		&i.TerminalTokensReported,
		&i.TerminalTokensUsed,
		&i.TerminalAt,
	)
	return i, err
}

const goalRunWorkspaceExists = `-- name: GoalRunWorkspaceExists :one
SELECT 1 FROM loop_runs WHERE id = ?1 AND workspace_id = ?2
`

type GoalRunWorkspaceExistsParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GoalRunWorkspaceExists(ctx context.Context, arg GoalRunWorkspaceExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, goalRunWorkspaceExists, arg.ID, arg.WorkspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const projectGoalCheckpointCounts = `-- name: ProjectGoalCheckpointCounts :exec
UPDATE loop_generation_outputs
SET goal_status = ?1, goal_turns_used = ?2,
    goal_turn_limit = ?3
WHERE loop_run_id = ?4 AND generation = ?5
  AND node_id = ?6 AND item_index = ?7
`

type ProjectGoalCheckpointCountsParams struct {
	GoalStatus    sql.NullString `json:"goal_status"`
	GoalTurnsUsed sql.NullInt64  `json:"goal_turns_used"`
	GoalTurnLimit sql.NullInt64  `json:"goal_turn_limit"`
	LoopRunID     string         `json:"loop_run_id"`
	Generation    int64          `json:"generation"`
	NodeID        string         `json:"node_id"`
	ItemIndex     int64          `json:"item_index"`
}

func (q *Queries) ProjectGoalCheckpointCounts(ctx context.Context, arg ProjectGoalCheckpointCountsParams) error {
	_, err := q.db.ExecContext(ctx, projectGoalCheckpointCounts,
		arg.GoalStatus,
		arg.GoalTurnsUsed,
		arg.GoalTurnLimit,
		arg.LoopRunID,
		arg.Generation,
		arg.NodeID,
		arg.ItemIndex,
	)
	return err
}

const recoverGoalQueueTerminal = `-- name: RecoverGoalQueueTerminal :execrows
UPDATE session_input_queue
SET status = ?1, terminal_event_start_seq = ?2,
    terminal_event_end_seq = ?3, terminal_kind = ?4,
    terminal_stop_reason = ?5, terminal_disposition = ?6,
    terminal_reason_code = ?7, terminal_tokens_reported = ?8,
    terminal_tokens_used = ?9, terminal_at = CAST(?10 AS TEXT),
    failed_at = CASE WHEN ?1 = 'failed' THEN CAST(?10 AS TEXT) ELSE failed_at END,
    updated_at = CAST(?10 AS TEXT)
WHERE id = ?11 AND loop_run_id = ?12
  AND task_run_id = ?13 AND prompt_id = ?14
  AND owner_kind = ?15 AND owner_epoch = ?16
  AND binding_epoch = ?17 AND session_id = ?18
  AND status IN ('dispatching', 'sent') AND terminal_at IS NULL
  AND dispatch_token_hash = ?19
`

type RecoverGoalQueueTerminalParams struct {
	Status                 string         `json:"status"`
	TerminalEventStartSeq  sql.NullInt64  `json:"terminal_event_start_seq"`
	TerminalEventEndSeq    sql.NullInt64  `json:"terminal_event_end_seq"`
	TerminalKind           sql.NullString `json:"terminal_kind"`
	TerminalStopReason     sql.NullString `json:"terminal_stop_reason"`
	TerminalDisposition    sql.NullString `json:"terminal_disposition"`
	TerminalReasonCode     sql.NullString `json:"terminal_reason_code"`
	TerminalTokensReported int64          `json:"terminal_tokens_reported"`
	TerminalTokensUsed     sql.NullInt64  `json:"terminal_tokens_used"`
	TerminalAt             string         `json:"terminal_at"`
	ID                     string         `json:"id"`
	LoopRunID              sql.NullString `json:"loop_run_id"`
	TaskRunID              string         `json:"task_run_id"`
	PromptID               sql.NullString `json:"prompt_id"`
	OwnerKind              sql.NullString `json:"owner_kind"`
	OwnerEpoch             sql.NullInt64  `json:"owner_epoch"`
	BindingEpoch           sql.NullInt64  `json:"binding_epoch"`
	SessionID              string         `json:"session_id"`
	DispatchTokenHash      sql.NullString `json:"dispatch_token_hash"`
}

func (q *Queries) RecoverGoalQueueTerminal(ctx context.Context, arg RecoverGoalQueueTerminalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recoverGoalQueueTerminal,
		arg.Status,
		arg.TerminalEventStartSeq,
		arg.TerminalEventEndSeq,
		arg.TerminalKind,
		arg.TerminalStopReason,
		arg.TerminalDisposition,
		arg.TerminalReasonCode,
		arg.TerminalTokensReported,
		arg.TerminalTokensUsed,
		arg.TerminalAt,
		arg.ID,
		arg.LoopRunID,
		arg.TaskRunID,
		arg.PromptID,
		arg.OwnerKind,
		arg.OwnerEpoch,
		arg.BindingEpoch,
		arg.SessionID,
		arg.DispatchTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const settleGoalCompactionCheckpoint = `-- name: SettleGoalCompactionCheckpoint :execrows
UPDATE loop_goal_checkpoints
SET phase = 'idle', goal_status = 'active', control_cause = NULL,
    queue_entry_id = NULL, prompt_id = NULL, prompt_kind = NULL, prompt_attempt = 0,
    context_state = ?1, usage_sequence = ?2,
    usage_pending_after_sequence = ?3,
    compaction_baseline_used = ?4,
    compaction_recovery_required = ?5,
    recovery_streak = ?6,
    compaction_cancel_prompt_id = NULL, compaction_cancel_cause = NULL,
    compaction_cancel_requested_at = NULL,
    control_grant_consumed = CASE WHEN ?7 = 1 THEN 1 ELSE control_grant_consumed END,
    updated_at = CAST(?8 AS TEXT)
WHERE loop_run_id = ?9 AND generation = ?10
  AND node_id = ?11 AND item_index = ?12
  AND control_epoch = ?13 AND binding_epoch = ?14
  AND phase = 'compacting' AND task_run_id = ?15
  AND queue_entry_id = ?16 AND prompt_id = ?17
`

type SettleGoalCompactionCheckpointParams struct {
	ContextState               string         `json:"context_state"`
	UsageSequence              sql.NullInt64  `json:"usage_sequence"`
	UsagePendingAfterSequence  sql.NullInt64  `json:"usage_pending_after_sequence"`
	CompactionBaselineUsed     sql.NullInt64  `json:"compaction_baseline_used"`
	CompactionRecoveryRequired int64          `json:"compaction_recovery_required"`
	RecoveryStreak             int64          `json:"recovery_streak"`
	ConsumeGrant               any            `json:"consume_grant"`
	UpdatedAt                  string         `json:"updated_at"`
	LoopRunID                  string         `json:"loop_run_id"`
	Generation                 int64          `json:"generation"`
	NodeID                     string         `json:"node_id"`
	ItemIndex                  int64          `json:"item_index"`
	ControlEpoch               int64          `json:"control_epoch"`
	BindingEpoch               sql.NullInt64  `json:"binding_epoch"`
	TaskRunID                  sql.NullString `json:"task_run_id"`
	QueueEntryID               sql.NullString `json:"queue_entry_id"`
	PromptID                   sql.NullString `json:"prompt_id"`
}

func (q *Queries) SettleGoalCompactionCheckpoint(ctx context.Context, arg SettleGoalCompactionCheckpointParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, settleGoalCompactionCheckpoint,
		arg.ContextState,
		arg.UsageSequence,
		arg.UsagePendingAfterSequence,
		arg.CompactionBaselineUsed,
		arg.CompactionRecoveryRequired,
		arg.RecoveryStreak,
		arg.ConsumeGrant,
		arg.UpdatedAt,
		arg.LoopRunID,
		arg.Generation,
		arg.NodeID,
		arg.ItemIndex,
		arg.ControlEpoch,
		arg.BindingEpoch,
		arg.TaskRunID,
		arg.QueueEntryID,
		arg.PromptID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateGoalContextUsage = `-- name: UpdateGoalContextUsage :execrows
UPDATE loop_goal_checkpoints
SET context_state = ?1, usage_sequence = ?2,
    usage_pending_after_sequence = ?3,
    compaction_baseline_used = ?4,
    compaction_recovery_required = ?5,
    recovery_streak = ?6, updated_at = CAST(?7 AS TEXT)
WHERE loop_run_id = ?8 AND generation = ?9
  AND node_id = ?10 AND item_index = ?11
  AND control_epoch = ?12 AND binding_epoch = ?13
  AND phase = ?14 AND goal_status = 'active'
  AND session_id = ?15 AND binding_handle = ?16
`

type UpdateGoalContextUsageParams struct {
	ContextState               string         `json:"context_state"`
	UsageSequence              sql.NullInt64  `json:"usage_sequence"`
	UsagePendingAfterSequence  sql.NullInt64  `json:"usage_pending_after_sequence"`
	CompactionBaselineUsed     sql.NullInt64  `json:"compaction_baseline_used"`
	CompactionRecoveryRequired int64          `json:"compaction_recovery_required"`
	RecoveryStreak             int64          `json:"recovery_streak"`
	UpdatedAt                  string         `json:"updated_at"`
	LoopRunID                  string         `json:"loop_run_id"`
	Generation                 int64          `json:"generation"`
	NodeID                     string         `json:"node_id"`
	ItemIndex                  int64          `json:"item_index"`
	ControlEpoch               int64          `json:"control_epoch"`
	BindingEpoch               sql.NullInt64  `json:"binding_epoch"`
	Phase                      string         `json:"phase"`
	SessionID                  sql.NullString `json:"session_id"`
	BindingHandle              sql.NullString `json:"binding_handle"`
}

func (q *Queries) UpdateGoalContextUsage(ctx context.Context, arg UpdateGoalContextUsageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGoalContextUsage,
		arg.ContextState,
		arg.UsageSequence,
		arg.UsagePendingAfterSequence,
		arg.CompactionBaselineUsed,
		arg.CompactionRecoveryRequired,
		arg.RecoveryStreak,
		arg.UpdatedAt,
		arg.LoopRunID,
		arg.Generation,
		arg.NodeID,
		arg.ItemIndex,
		arg.ControlEpoch,
		arg.BindingEpoch,
		arg.Phase,
		arg.SessionID,
		arg.BindingHandle,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
