// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goal_runtime.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const acknowledgeGoalSessionCleanup = `-- name: AcknowledgeGoalSessionCleanup :execrows
UPDATE loop_goal_session_cleanup
SET completed_at = CAST(?1 AS TEXT)
WHERE cleanup_id = ?2 AND completed_at IS NULL
`

type AcknowledgeGoalSessionCleanupParams struct {
	CompletedAt string `json:"completed_at"`
	CleanupID   string `json:"cleanup_id"`
}

func (q *Queries) AcknowledgeGoalSessionCleanup(ctx context.Context, arg AcknowledgeGoalSessionCleanupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acknowledgeGoalSessionCleanup, arg.CompletedAt, arg.CleanupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const acknowledgeGoalSessionOutbox = `-- name: AcknowledgeGoalSessionOutbox :exec
UPDATE loop_goal_session_outbox
SET delivered_at = CAST(?1 AS TEXT)
WHERE event_id = ?2 AND delivered_at IS NULL
`

type AcknowledgeGoalSessionOutboxParams struct {
	DeliveredAt string `json:"delivered_at"`
	EventID     string `json:"event_id"`
}

func (q *Queries) AcknowledgeGoalSessionOutbox(ctx context.Context, arg AcknowledgeGoalSessionOutboxParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeGoalSessionOutbox, arg.DeliveredAt, arg.EventID)
	return err
}

const claimGoalSessionCleanup = `-- name: ClaimGoalSessionCleanup :many
SELECT cleanup.id, cleanup.cleanup_id, cleanup.workspace_id, cleanup.loop_run_id,
       cleanup.handle, cleanup.binding_epoch, cleanup.session_id, cleanup.cause,
       cleanup.created_at, cleanup.completed_at
FROM loop_goal_session_cleanup AS cleanup
JOIN loop_session_bindings AS binding
  ON binding.loop_run_id = cleanup.loop_run_id
 AND binding.handle = cleanup.handle
 AND binding.binding_epoch = cleanup.binding_epoch
WHERE cleanup.completed_at IS NULL
  AND NOT (binding.state = 'failed' AND binding.failure_code = ?1)
ORDER BY cleanup.id ASC
LIMIT ?2
`

type ClaimGoalSessionCleanupParams struct {
	UnsettledFailureCode sql.NullString `json:"unsettled_failure_code"`
	ClaimLimit           int64          `json:"claim_limit"`
}

func (q *Queries) ClaimGoalSessionCleanup(ctx context.Context, arg ClaimGoalSessionCleanupParams) ([]LoopGoalSessionCleanup, error) {
	rows, err := q.db.QueryContext(ctx, claimGoalSessionCleanup, arg.UnsettledFailureCode, arg.ClaimLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoopGoalSessionCleanup{}
	for rows.Next() {
		var i LoopGoalSessionCleanup
		if err := rows.Scan(
			&i.ID,
			&i.CleanupID,
			&i.WorkspaceID,
			&i.LoopRunID,
			&i.Handle,
			&i.BindingEpoch,
			&i.SessionID,
			&i.Cause,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimGoalSessionOutbox = `-- name: ClaimGoalSessionOutbox :many
SELECT id, event_id, workspace_id, origin_session_id, loop_run_id, bound_session_id,
       cause, created_at, delivered_at
FROM loop_goal_session_outbox
WHERE delivered_at IS NULL
ORDER BY id ASC
LIMIT ?1
`

func (q *Queries) ClaimGoalSessionOutbox(ctx context.Context, claimLimit int64) ([]LoopGoalSessionOutbox, error) {
	rows, err := q.db.QueryContext(ctx, claimGoalSessionOutbox, claimLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoopGoalSessionOutbox{}
	for rows.Next() {
		var i LoopGoalSessionOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.WorkspaceID,
			&i.OriginSessionID,
			&i.LoopRunID,
			&i.BoundSessionID,
			&i.Cause,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueGoalSessionCleanup = `-- name: EnqueueGoalSessionCleanup :exec
INSERT INTO loop_goal_session_cleanup (
    cleanup_id, workspace_id, loop_run_id, handle, binding_epoch, session_id, cause, created_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, CAST(?8 AS TEXT)
)
ON CONFLICT(cleanup_id) DO NOTHING
`

type EnqueueGoalSessionCleanupParams struct {
	CleanupID    string `json:"cleanup_id"`
	WorkspaceID  string `json:"workspace_id"`
	LoopRunID    string `json:"loop_run_id"`
	Handle       string `json:"handle"`
	BindingEpoch int64  `json:"binding_epoch"`
	SessionID    string `json:"session_id"`
	Cause        string `json:"cause"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) EnqueueGoalSessionCleanup(ctx context.Context, arg EnqueueGoalSessionCleanupParams) error {
	_, err := q.db.ExecContext(ctx, enqueueGoalSessionCleanup,
		arg.CleanupID,
		arg.WorkspaceID,
		arg.LoopRunID,
		arg.Handle,
		arg.BindingEpoch,
		arg.SessionID,
		arg.Cause,
		arg.CreatedAt,
	)
	return err
}

const enqueueGoalSessionOutbox = `-- name: EnqueueGoalSessionOutbox :exec
INSERT INTO loop_goal_session_outbox (
    event_id, workspace_id, origin_session_id, loop_run_id,
    bound_session_id, cause, created_at
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6, CAST(?7 AS TEXT)
)
ON CONFLICT(event_id) DO NOTHING
`

type EnqueueGoalSessionOutboxParams struct {
	EventID         string         `json:"event_id"`
	WorkspaceID     string         `json:"workspace_id"`
	OriginSessionID string         `json:"origin_session_id"`
	LoopRunID       string         `json:"loop_run_id"`
	BoundSessionID  sql.NullString `json:"bound_session_id"`
	Cause           string         `json:"cause"`
	CreatedAt       string         `json:"created_at"`
}

func (q *Queries) EnqueueGoalSessionOutbox(ctx context.Context, arg EnqueueGoalSessionOutboxParams) error {
	_, err := q.db.ExecContext(ctx, enqueueGoalSessionOutbox,
		arg.EventID,
		arg.WorkspaceID,
		arg.OriginSessionID,
		arg.LoopRunID,
		arg.BoundSessionID,
		arg.Cause,
		arg.CreatedAt,
	)
	return err
}

const getGoalRunOrigin = `-- name: GetGoalRunOrigin :one
SELECT origin_kind, origin_session_id
FROM loop_runs
WHERE id = ?1 AND workspace_id = ?2
`

type GetGoalRunOriginParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

type GetGoalRunOriginRow struct {
	OriginKind      string         `json:"origin_kind"`
	OriginSessionID sql.NullString `json:"origin_session_id"`
}

func (q *Queries) GetGoalRunOrigin(ctx context.Context, arg GetGoalRunOriginParams) (GetGoalRunOriginRow, error) {
	row := q.db.QueryRowContext(ctx, getGoalRunOrigin, arg.ID, arg.WorkspaceID)
	var i GetGoalRunOriginRow
	err := row.Scan(&i.OriginKind, &i.OriginSessionID)
	return i, err
}

const getGoalSessionCleanup = `-- name: GetGoalSessionCleanup :one
SELECT id, cleanup_id, workspace_id, loop_run_id, handle, binding_epoch,
       session_id, cause, created_at, completed_at
FROM loop_goal_session_cleanup
WHERE cleanup_id = ?1
`

func (q *Queries) GetGoalSessionCleanup(ctx context.Context, cleanupID string) (LoopGoalSessionCleanup, error) {
	row := q.db.QueryRowContext(ctx, getGoalSessionCleanup, cleanupID)
	var i LoopGoalSessionCleanup
	err := row.Scan(
		&i.ID,
		&i.CleanupID,
		&i.WorkspaceID,
		&i.LoopRunID,
		&i.Handle,
		&i.BindingEpoch,
		&i.SessionID,
		&i.Cause,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getGoalSessionOutboxByEventID = `-- name: GetGoalSessionOutboxByEventID :one
SELECT id, event_id, workspace_id, origin_session_id, loop_run_id, bound_session_id,
       cause, created_at, delivered_at
FROM loop_goal_session_outbox
WHERE event_id = ?1
`

func (q *Queries) GetGoalSessionOutboxByEventID(ctx context.Context, eventID string) (LoopGoalSessionOutbox, error) {
	row := q.db.QueryRowContext(ctx, getGoalSessionOutboxByEventID, eventID)
	var i LoopGoalSessionOutbox
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.WorkspaceID,
		&i.OriginSessionID,
		&i.LoopRunID,
		&i.BoundSessionID,
		&i.Cause,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const readGoalSessionProjection = `-- name: ReadGoalSessionProjection :one
SELECT id, status, definition_digest, origin_session_id, goal_context_nudge_ratio, goal_cleared_at
FROM loop_runs
WHERE workspace_id = ?1
  AND origin_kind = 'session'
  AND origin_session_id = ?2
ORDER BY created_at DESC, rowid DESC
LIMIT 1
`

type ReadGoalSessionProjectionParams struct {
	WorkspaceID     string         `json:"workspace_id"`
	OriginSessionID sql.NullString `json:"origin_session_id"`
}

type ReadGoalSessionProjectionRow struct {
	ID                    string         `json:"id"`
	Status                string         `json:"status"`
	DefinitionDigest      string         `json:"definition_digest"`
	OriginSessionID       sql.NullString `json:"origin_session_id"`
	GoalContextNudgeRatio float64        `json:"goal_context_nudge_ratio"`
	GoalClearedAt         sql.NullTime   `json:"goal_cleared_at"`
}

func (q *Queries) ReadGoalSessionProjection(ctx context.Context, arg ReadGoalSessionProjectionParams) (ReadGoalSessionProjectionRow, error) {
	row := q.db.QueryRowContext(ctx, readGoalSessionProjection, arg.WorkspaceID, arg.OriginSessionID)
	var i ReadGoalSessionProjectionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.DefinitionDigest,
		&i.OriginSessionID,
		&i.GoalContextNudgeRatio,
		&i.GoalClearedAt,
	)
	return i, err
}

const readLatestGoalSessionCheckpoint = `-- name: ReadLatestGoalSessionCheckpoint :one
SELECT loop_run_id, generation, node_id, item_index, control_epoch, control_actor_kind, control_actor_id, control_requested_at, phase, goal_status, turns_used, turn_limit, broken_streak, recovery_streak, task_run_id, queue_entry_id, prompt_id, prompt_kind, prompt_attempt, context_state, usage_sequence, usage_pending_after_sequence, session_id, binding_handle, binding_epoch, context_nudge_ratio, control_grant_id, control_grant_kind, control_grant_cause, control_grant_turn, control_grant_scope, control_grant_consumed, judge_attempt_id, compaction_cancel_prompt_id, compaction_cancel_cause, compaction_cancel_requested_at, report_prompt_id, report_status, report_evidence_ref, report_binding_epoch, report_actor_kind, report_actor_id, report_recorded_at, updated_at, control_cause, compaction_baseline_used, compaction_recovery_required
FROM loop_goal_checkpoints
WHERE loop_run_id = ?1
ORDER BY generation DESC, updated_at DESC, node_id ASC, item_index ASC
LIMIT 1
`

func (q *Queries) ReadLatestGoalSessionCheckpoint(ctx context.Context, loopRunID string) (LoopGoalCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, readLatestGoalSessionCheckpoint, loopRunID)
	var i LoopGoalCheckpoint
	err := row.Scan(
		&i.LoopRunID,
		&i.Generation,
		&i.NodeID,
		&i.ItemIndex,
		&i.ControlEpoch,
		&i.ControlActorKind,
		&i.ControlActorID,
		&i.ControlRequestedAt,
		&i.Phase,
		&i.GoalStatus,
		&i.TurnsUsed,
		&i.TurnLimit,
		&i.BrokenStreak,
		&i.RecoveryStreak,
		&i.TaskRunID,
		&i.QueueEntryID,
		&i.PromptID,
		&i.PromptKind,
		&i.PromptAttempt,
		&i.ContextState,
		&i.UsageSequence,
		&i.UsagePendingAfterSequence,
		&i.SessionID,
		&i.BindingHandle,
		&i.BindingEpoch,
		&i.ContextNudgeRatio,
		&i.ControlGrantID,
		&i.ControlGrantKind,
		&i.ControlGrantCause,
		&i.ControlGrantTurn,
		&i.ControlGrantScope,
		&i.ControlGrantConsumed,
		&i.JudgeAttemptID,
		&i.CompactionCancelPromptID,
		&i.CompactionCancelCause,
		&i.CompactionCancelRequestedAt,
		&i.ReportPromptID,
		&i.ReportStatus,
		&i.ReportEvidenceRef,
		&i.ReportBindingEpoch,
		&i.ReportActorKind,
		&i.ReportActorID,
		&i.ReportRecordedAt,
		&i.UpdatedAt,
		&i.ControlCause,
		&i.CompactionBaselineUsed,
		&i.CompactionRecoveryRequired,
	)
	return i, err
}

const readLatestGoalSessionVerdict = `-- name: ReadLatestGoalSessionVerdict :one
SELECT loop_run_id, seq, generation, node_id, item_index, turn, session_id, binding_handle, binding_epoch, prompt_id, prompt_attempt, usage_base_tokens, result_status, stop_reason, reason_code, verdict_outcome, blocking_json, evidence_ref, prompt_ref, tokens_used, actor_kind, actor_id, started_at, ended_at
FROM loop_goal_turns
WHERE loop_run_id = ?1 AND verdict_outcome IS NOT NULL
ORDER BY seq DESC
LIMIT 1
`

func (q *Queries) ReadLatestGoalSessionVerdict(ctx context.Context, loopRunID string) (LoopGoalTurn, error) {
	row := q.db.QueryRowContext(ctx, readLatestGoalSessionVerdict, loopRunID)
	var i LoopGoalTurn
	err := row.Scan(
		&i.LoopRunID,
		&i.Seq,
		&i.Generation,
		&i.NodeID,
		&i.ItemIndex,
		&i.Turn,
		&i.SessionID,
		&i.BindingHandle,
		&i.BindingEpoch,
		&i.PromptID,
		&i.PromptAttempt,
		&i.UsageBaseTokens,
		&i.ResultStatus,
		&i.StopReason,
		&i.ReasonCode,
		&i.VerdictOutcome,
		&i.BlockingJson,
		&i.EvidenceRef,
		&i.PromptRef,
		&i.TokensUsed,
		&i.ActorKind,
		&i.ActorID,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const reconcileGoalSessionCleanup = `-- name: ReconcileGoalSessionCleanup :exec
UPDATE loop_session_bindings
SET failure_code = ?1
WHERE state = 'failed' AND failure_code = ?2
  AND EXISTS (
      SELECT 1 FROM loop_goal_session_cleanup AS cleanup
      WHERE cleanup.loop_run_id = loop_session_bindings.loop_run_id
        AND cleanup.handle = loop_session_bindings.handle
        AND cleanup.binding_epoch = loop_session_bindings.binding_epoch
        AND cleanup.completed_at IS NULL
  )
`

type ReconcileGoalSessionCleanupParams struct {
	SettledFailureCode   sql.NullString `json:"settled_failure_code"`
	UnsettledFailureCode sql.NullString `json:"unsettled_failure_code"`
}

func (q *Queries) ReconcileGoalSessionCleanup(ctx context.Context, arg ReconcileGoalSessionCleanupParams) error {
	_, err := q.db.ExecContext(ctx, reconcileGoalSessionCleanup, arg.SettledFailureCode, arg.UnsettledFailureCode)
	return err
}

const validateGoalSessionWorkspace = `-- name: ValidateGoalSessionWorkspace :one
SELECT 1
FROM sessions
WHERE id = ?1 AND workspace_id = ?2
`

type ValidateGoalSessionWorkspaceParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ValidateGoalSessionWorkspace(ctx context.Context, arg ValidateGoalSessionWorkspaceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, validateGoalSessionWorkspace, arg.ID, arg.WorkspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
