// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loop_runtime.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const activateLoopApproval = `-- name: ActivateLoopApproval :execrows
UPDATE loop_runs
SET active_gate_id = ?1,
    active_human_criteria_json = ?2,
    budget_approval_seq = budget_approval_seq + ?3
WHERE id = ?4
`

type ActivateLoopApprovalParams struct {
	ActiveGateID            string `json:"active_gate_id"`
	ActiveHumanCriteriaJson string `json:"active_human_criteria_json"`
	BudgetDelta             int64  `json:"budget_delta"`
	ID                      string `json:"id"`
}

func (q *Queries) ActivateLoopApproval(ctx context.Context, arg ActivateLoopApprovalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateLoopApproval,
		arg.ActiveGateID,
		arg.ActiveHumanCriteriaJson,
		arg.BudgetDelta,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceLoopRunProgress = `-- name: AdvanceLoopRunProgress :exec
UPDATE loop_runs
SET last_progress_at = CASE
  WHEN last_progress_at IS NULL OR last_progress_at < ?1 THEN ?1
  ELSE last_progress_at
END
WHERE id = ?2
`

type AdvanceLoopRunProgressParams struct {
	ProgressAt time.Time `json:"progress_at"`
	ID         string    `json:"id"`
}

func (q *Queries) AdvanceLoopRunProgress(ctx context.Context, arg AdvanceLoopRunProgressParams) error {
	_, err := q.db.ExecContext(ctx, advanceLoopRunProgress, arg.ProgressAt, arg.ID)
	return err
}

const compareAndSwapLoopRunStatus = `-- name: CompareAndSwapLoopRunStatus :execrows
UPDATE loop_runs
SET status = ?1,
    pause_requested = CASE WHEN ?2 THEN 0 ELSE pause_requested END,
    control_actor_kind = CASE WHEN ?2 THEN NULL ELSE control_actor_kind END,
    control_actor_id = CASE WHEN ?2 THEN NULL ELSE control_actor_id END,
    control_requested_at = CASE WHEN ?2 THEN NULL ELSE control_requested_at END,
    active_gate_id = CASE WHEN ?1 != 'needs-approval' THEN '' ELSE active_gate_id END,
    active_human_criteria_json = CASE WHEN ?1 != 'needs-approval' THEN '[]' ELSE active_human_criteria_json END
WHERE id = ?3 AND status = ?4
`

type CompareAndSwapLoopRunStatusParams struct {
	Status            string `json:"status"`
	ClearControlState int64  `json:"clear_control_state"`
	ID                string `json:"id"`
	ExpectedStatus    string `json:"expected_status"`
}

func (q *Queries) CompareAndSwapLoopRunStatus(ctx context.Context, arg CompareAndSwapLoopRunStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, compareAndSwapLoopRunStatus,
		arg.Status,
		arg.ClearControlState,
		arg.ID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLastCoordinatorTaskIDForLoopRun = `-- name: GetLastCoordinatorTaskIDForLoopRun :one
SELECT task_id FROM task_runs
WHERE loop_run_id = ?1 AND run_kind = 'coordinator'
ORDER BY queued_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetLastCoordinatorTaskIDForLoopRun(ctx context.Context, loopRunID sql.NullString) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getLastCoordinatorTaskIDForLoopRun, loopRunID)
	var task_id sql.NullString
	err := row.Scan(&task_id)
	return task_id, err
}

const getLastLoopTokenTick = `-- name: GetLastLoopTokenTick :one
SELECT payload_json, at FROM loop_run_events
WHERE loop_run_id = ?1 AND kind = ?2
ORDER BY seq DESC LIMIT 1
`

type GetLastLoopTokenTickParams struct {
	LoopRunID string `json:"loop_run_id"`
	Kind      string `json:"kind"`
}

type GetLastLoopTokenTickRow struct {
	PayloadJson string    `json:"payload_json"`
	At          time.Time `json:"at"`
}

func (q *Queries) GetLastLoopTokenTick(ctx context.Context, arg GetLastLoopTokenTickParams) (GetLastLoopTokenTickRow, error) {
	row := q.db.QueryRowContext(ctx, getLastLoopTokenTick, arg.LoopRunID, arg.Kind)
	var i GetLastLoopTokenTickRow
	err := row.Scan(&i.PayloadJson, &i.At)
	return i, err
}

const getLoopDefinitionSnapshot = `-- name: GetLoopDefinitionSnapshot :one
SELECT workspace_id, definition_digest, definition_version, definition_json, byte_size,
       created_at, last_used_at
FROM loop_definition_snapshots
WHERE workspace_id = ?1 AND definition_digest = ?2
`

type GetLoopDefinitionSnapshotParams struct {
	WorkspaceID      string `json:"workspace_id"`
	DefinitionDigest string `json:"definition_digest"`
}

func (q *Queries) GetLoopDefinitionSnapshot(ctx context.Context, arg GetLoopDefinitionSnapshotParams) (LoopDefinitionSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getLoopDefinitionSnapshot, arg.WorkspaceID, arg.DefinitionDigest)
	var i LoopDefinitionSnapshot
	err := row.Scan(
		&i.WorkspaceID,
		&i.DefinitionDigest,
		&i.DefinitionVersion,
		&i.DefinitionJson,
		&i.ByteSize,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getLoopGenerationOutputStatus = `-- name: GetLoopGenerationOutputStatus :one
SELECT status FROM loop_generation_outputs
WHERE loop_run_id = ?1 AND task_run_id = ?2
ORDER BY generation DESC LIMIT 1
`

type GetLoopGenerationOutputStatusParams struct {
	LoopRunID string         `json:"loop_run_id"`
	TaskRunID sql.NullString `json:"task_run_id"`
}

func (q *Queries) GetLoopGenerationOutputStatus(ctx context.Context, arg GetLoopGenerationOutputStatusParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getLoopGenerationOutputStatus, arg.LoopRunID, arg.TaskRunID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getLoopOutputBlob = `-- name: GetLoopOutputBlob :one
SELECT payload_json FROM loop_output_blobs WHERE output_ref = ?1
`

func (q *Queries) GetLoopOutputBlob(ctx context.Context, outputRef string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLoopOutputBlob, outputRef)
	var payload_json string
	err := row.Scan(&payload_json)
	return payload_json, err
}

const getLoopRunPauseState = `-- name: GetLoopRunPauseState :one
SELECT status, pause_requested, control_actor_kind, control_actor_id
FROM loop_runs WHERE workspace_id = ?1 AND id = ?2
`

type GetLoopRunPauseStateParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

type GetLoopRunPauseStateRow struct {
	Status           string         `json:"status"`
	PauseRequested   int64          `json:"pause_requested"`
	ControlActorKind sql.NullString `json:"control_actor_kind"`
	ControlActorID   sql.NullString `json:"control_actor_id"`
}

func (q *Queries) GetLoopRunPauseState(ctx context.Context, arg GetLoopRunPauseStateParams) (GetLoopRunPauseStateRow, error) {
	row := q.db.QueryRowContext(ctx, getLoopRunPauseState, arg.WorkspaceID, arg.ID)
	var i GetLoopRunPauseStateRow
	err := row.Scan(
		&i.Status,
		&i.PauseRequested,
		&i.ControlActorKind,
		&i.ControlActorID,
	)
	return i, err
}

const listLoopCatalogAggregates = `-- name: ListLoopCatalogAggregates :many
WITH requested_names(loop_name) AS (
  SELECT DISTINCT CAST(value AS TEXT) FROM json_each(?3)
)
SELECT lr.loop_name, COUNT(*) AS runs,
       SUM(CASE WHEN lr.status = 'done' THEN 1 ELSE 0 END) AS succeeded,
       SUM(CASE WHEN lr.status IN ('failed', 'blocked', 'exhausted', 'stalled') THEN 1 ELSE 0 END) AS failed
FROM requested_names AS requested
JOIN loop_runs AS lr INDEXED BY idx_loop_runs_catalog
  ON lr.workspace_id = ?1 AND lr.loop_name = requested.loop_name
WHERE lr.created_at >= ?2
GROUP BY lr.loop_name
`

type ListLoopCatalogAggregatesParams struct {
	WorkspaceID    string `json:"workspace_id"`
	AggregateAfter string `json:"aggregate_after"`
	NamesJson      any    `json:"names_json"`
}

type ListLoopCatalogAggregatesRow struct {
	LoopName  string          `json:"loop_name"`
	Runs      int64           `json:"runs"`
	Succeeded sql.NullFloat64 `json:"succeeded"`
	Failed    sql.NullFloat64 `json:"failed"`
}

func (q *Queries) ListLoopCatalogAggregates(ctx context.Context, arg ListLoopCatalogAggregatesParams) ([]ListLoopCatalogAggregatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoopCatalogAggregates, arg.WorkspaceID, arg.AggregateAfter, arg.NamesJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoopCatalogAggregatesRow{}
	for rows.Next() {
		var i ListLoopCatalogAggregatesRow
		if err := rows.Scan(
			&i.LoopName,
			&i.Runs,
			&i.Succeeded,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoopCatalogLatestRuns = `-- name: ListLoopCatalogLatestRuns :many
WITH requested_names(loop_name) AS (
  SELECT DISTINCT CAST(value AS TEXT) FROM json_each(?1)
), latest_ids(id) AS (
  SELECT (
    SELECT candidate.id FROM loop_runs AS candidate INDEXED BY idx_loop_runs_catalog
    WHERE candidate.workspace_id = ?2
      AND candidate.loop_name = requested.loop_name
    ORDER BY candidate.created_at DESC, candidate.id DESC LIMIT 1
  )
  FROM requested_names AS requested
)
SELECT lr.id, lr.loop_name, lr.status, lr.created_at
FROM loop_runs AS lr JOIN latest_ids ON latest_ids.id = lr.id
`

type ListLoopCatalogLatestRunsParams struct {
	NamesJson   any    `json:"names_json"`
	WorkspaceID string `json:"workspace_id"`
}

type ListLoopCatalogLatestRunsRow struct {
	ID        string `json:"id"`
	LoopName  string `json:"loop_name"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) ListLoopCatalogLatestRuns(ctx context.Context, arg ListLoopCatalogLatestRunsParams) ([]ListLoopCatalogLatestRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoopCatalogLatestRuns, arg.NamesJson, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoopCatalogLatestRunsRow{}
	for rows.Next() {
		var i ListLoopCatalogLatestRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.LoopName,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoopGateDecisions = `-- name: ListLoopGateDecisions :many
SELECT criterion_id, decision, actor_kind, actor_ref, origin_kind, origin_ref, note
FROM loop_gate_decisions
WHERE workspace_id = ?1 AND loop_run_id = ?2
  AND generation = ?3 AND gate_id = ?4
ORDER BY criterion_id ASC
`

type ListLoopGateDecisionsParams struct {
	WorkspaceID string `json:"workspace_id"`
	LoopRunID   string `json:"loop_run_id"`
	Generation  int64  `json:"generation"`
	GateID      string `json:"gate_id"`
}

type ListLoopGateDecisionsRow struct {
	CriterionID string `json:"criterion_id"`
	Decision    string `json:"decision"`
	ActorKind   string `json:"actor_kind"`
	ActorRef    string `json:"actor_ref"`
	OriginKind  string `json:"origin_kind"`
	OriginRef   string `json:"origin_ref"`
	Note        string `json:"note"`
}

func (q *Queries) ListLoopGateDecisions(ctx context.Context, arg ListLoopGateDecisionsParams) ([]ListLoopGateDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoopGateDecisions,
		arg.WorkspaceID,
		arg.LoopRunID,
		arg.Generation,
		arg.GateID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoopGateDecisionsRow{}
	for rows.Next() {
		var i ListLoopGateDecisionsRow
		if err := rows.Scan(
			&i.CriterionID,
			&i.Decision,
			&i.ActorKind,
			&i.ActorRef,
			&i.OriginKind,
			&i.OriginRef,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoopGenerationOutputs = `-- name: ListLoopGenerationOutputs :many
SELECT generation, node_id, item_index, status, output_ref, task_run_id, child_loop_run_id
FROM loop_generation_outputs
WHERE loop_run_id = ?1 AND generation = ?2
ORDER BY node_id ASC, item_index ASC
`

type ListLoopGenerationOutputsParams struct {
	LoopRunID  string `json:"loop_run_id"`
	Generation int64  `json:"generation"`
}

type ListLoopGenerationOutputsRow struct {
	Generation     int64          `json:"generation"`
	NodeID         string         `json:"node_id"`
	ItemIndex      int64          `json:"item_index"`
	Status         string         `json:"status"`
	OutputRef      sql.NullString `json:"output_ref"`
	TaskRunID      sql.NullString `json:"task_run_id"`
	ChildLoopRunID sql.NullString `json:"child_loop_run_id"`
}

func (q *Queries) ListLoopGenerationOutputs(ctx context.Context, arg ListLoopGenerationOutputsParams) ([]ListLoopGenerationOutputsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoopGenerationOutputs, arg.LoopRunID, arg.Generation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoopGenerationOutputsRow{}
	for rows.Next() {
		var i ListLoopGenerationOutputsRow
		if err := rows.Scan(
			&i.Generation,
			&i.NodeID,
			&i.ItemIndex,
			&i.Status,
			&i.OutputRef,
			&i.TaskRunID,
			&i.ChildLoopRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoopRunsMissingActiveCoordinator = `-- name: ListLoopRunsMissingActiveCoordinator :many
SELECT lr.id, lr.generation
FROM loop_runs lr
WHERE lr.status = 'running'
  AND NOT EXISTS (
    SELECT 1 FROM task_runs tr
    WHERE tr.loop_run_id = lr.id AND tr.run_kind = 'coordinator'
      AND tr.status IN ('queued', 'claimed', 'starting', 'running')
  )
ORDER BY lr.created_at ASC, lr.id ASC
`

type ListLoopRunsMissingActiveCoordinatorRow struct {
	ID         string `json:"id"`
	Generation int64  `json:"generation"`
}

func (q *Queries) ListLoopRunsMissingActiveCoordinator(ctx context.Context) ([]ListLoopRunsMissingActiveCoordinatorRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoopRunsMissingActiveCoordinator)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoopRunsMissingActiveCoordinatorRow{}
	for rows.Next() {
		var i ListLoopRunsMissingActiveCoordinatorRow
		if err := rows.Scan(&i.ID, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedLoopRunsReadyForPromotion = `-- name: ListQueuedLoopRunsReadyForPromotion :many
SELECT q.id, q.workspace_id, q.loop_name, q.generation
FROM loop_runs q
WHERE q.status = 'queued'
  AND NOT EXISTS (
    SELECT 1 FROM loop_runs active
    WHERE active.workspace_id = q.workspace_id AND active.loop_name = q.loop_name
      AND active.status IN ('running', 'watching', 'needs-approval', 'paused')
  )
  AND NOT EXISTS (
    SELECT 1 FROM loop_runs older
    WHERE older.workspace_id = q.workspace_id AND older.loop_name = q.loop_name
      AND older.status = 'queued'
      AND (older.created_at < q.created_at OR (older.created_at = q.created_at AND older.id < q.id))
  )
ORDER BY q.created_at ASC, q.id ASC
`

type ListQueuedLoopRunsReadyForPromotionRow struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	LoopName    string `json:"loop_name"`
	Generation  int64  `json:"generation"`
}

func (q *Queries) ListQueuedLoopRunsReadyForPromotion(ctx context.Context) ([]ListQueuedLoopRunsReadyForPromotionRow, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedLoopRunsReadyForPromotion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueuedLoopRunsReadyForPromotionRow{}
	for rows.Next() {
		var i ListQueuedLoopRunsReadyForPromotionRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.LoopName,
			&i.Generation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestQueuedLoopRunReadyForPromotion = `-- name: OldestQueuedLoopRunReadyForPromotion :one
SELECT q.id, q.workspace_id, q.loop_name, q.generation
FROM loop_runs q
WHERE q.workspace_id = ?1
  AND q.loop_name = ?2
  AND q.status = 'queued'
  AND NOT EXISTS (
    SELECT 1 FROM loop_runs active
    WHERE active.workspace_id = q.workspace_id AND active.loop_name = q.loop_name
      AND active.status IN ('running', 'watching', 'needs-approval', 'paused')
  )
  AND NOT EXISTS (
    SELECT 1 FROM loop_runs older
    WHERE older.workspace_id = q.workspace_id AND older.loop_name = q.loop_name
      AND older.status = 'queued'
      AND (older.created_at < q.created_at OR (older.created_at = q.created_at AND older.id < q.id))
  )
ORDER BY q.created_at ASC, q.id ASC LIMIT 1
`

type OldestQueuedLoopRunReadyForPromotionParams struct {
	WorkspaceID string `json:"workspace_id"`
	LoopName    string `json:"loop_name"`
}

type OldestQueuedLoopRunReadyForPromotionRow struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	LoopName    string `json:"loop_name"`
	Generation  int64  `json:"generation"`
}

func (q *Queries) OldestQueuedLoopRunReadyForPromotion(ctx context.Context, arg OldestQueuedLoopRunReadyForPromotionParams) (OldestQueuedLoopRunReadyForPromotionRow, error) {
	row := q.db.QueryRowContext(ctx, oldestQueuedLoopRunReadyForPromotion, arg.WorkspaceID, arg.LoopName)
	var i OldestQueuedLoopRunReadyForPromotionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LoopName,
		&i.Generation,
	)
	return i, err
}

const projectLoopPauseToGoalCheckpoints = `-- name: ProjectLoopPauseToGoalCheckpoints :exec
UPDATE loop_goal_checkpoints
SET control_actor_kind = CASE WHEN ?1 = 1 THEN ?2 ELSE NULL END,
    control_actor_id = CASE WHEN ?1 = 1 THEN ?3 ELSE NULL END,
    control_requested_at = CASE WHEN ?1 = 1 THEN ?4 ELSE NULL END,
    updated_at = ?5
WHERE loop_run_id = ?6 AND phase NOT IN ('awaiting_control', 'terminal')
`

type ProjectLoopPauseToGoalCheckpointsParams struct {
	Requested   any            `json:"requested"`
	ActorKind   sql.NullString `json:"actor_kind"`
	ActorID     sql.NullString `json:"actor_id"`
	RequestedAt sql.NullTime   `json:"requested_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	LoopRunID   string         `json:"loop_run_id"`
}

func (q *Queries) ProjectLoopPauseToGoalCheckpoints(ctx context.Context, arg ProjectLoopPauseToGoalCheckpointsParams) error {
	_, err := q.db.ExecContext(ctx, projectLoopPauseToGoalCheckpoints,
		arg.Requested,
		arg.ActorKind,
		arg.ActorID,
		arg.RequestedAt,
		arg.UpdatedAt,
		arg.LoopRunID,
	)
	return err
}

const setLoopRunPauseState = `-- name: SetLoopRunPauseState :execrows
UPDATE loop_runs
SET pause_requested = ?1,
    control_actor_kind = CASE WHEN ?1 = 1 THEN ?2 ELSE NULL END,
    control_actor_id = CASE WHEN ?1 = 1 THEN ?3 ELSE NULL END,
    control_requested_at = CASE WHEN ?1 = 1 THEN ?4 ELSE NULL END
WHERE workspace_id = ?5 AND id = ?6
  AND status = 'running' AND pause_requested = ?7
`

type SetLoopRunPauseStateParams struct {
	Requested     int64          `json:"requested"`
	ActorKind     sql.NullString `json:"actor_kind"`
	ActorID       sql.NullString `json:"actor_id"`
	RequestedAt   sql.NullTime   `json:"requested_at"`
	WorkspaceID   string         `json:"workspace_id"`
	ID            string         `json:"id"`
	ExpectedPause int64          `json:"expected_pause"`
}

func (q *Queries) SetLoopRunPauseState(ctx context.Context, arg SetLoopRunPauseStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setLoopRunPauseState,
		arg.Requested,
		arg.ActorKind,
		arg.ActorID,
		arg.RequestedAt,
		arg.WorkspaceID,
		arg.ID,
		arg.ExpectedPause,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sweepOrphanedLoopOutputBlobs = `-- name: SweepOrphanedLoopOutputBlobs :exec
DELETE FROM loop_output_blobs
WHERE NOT EXISTS (
  SELECT 1 FROM loop_generation_outputs
  WHERE loop_generation_outputs.output_ref = loop_output_blobs.output_ref
)
AND NOT EXISTS (
  SELECT 1 FROM loop_goal_turns
  WHERE loop_goal_turns.evidence_ref = loop_output_blobs.output_ref
     OR loop_goal_turns.prompt_ref = loop_output_blobs.output_ref
)
AND NOT EXISTS (
  SELECT 1 FROM loop_goal_judge_attempts
  WHERE loop_goal_judge_attempts.evidence_ref = loop_output_blobs.output_ref
)
AND NOT EXISTS (
  SELECT 1 FROM loop_goal_checkpoints
  WHERE loop_goal_checkpoints.report_evidence_ref = loop_output_blobs.output_ref
)
`

func (q *Queries) SweepOrphanedLoopOutputBlobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, sweepOrphanedLoopOutputBlobs)
	return err
}

const upsertLoopDefinitionSnapshot = `-- name: UpsertLoopDefinitionSnapshot :execrows
INSERT INTO loop_definition_snapshots (
  workspace_id, definition_digest, definition_version, definition_json, byte_size,
  created_at, last_used_at
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6, ?7
)
ON CONFLICT(workspace_id, definition_digest) DO UPDATE SET
  last_used_at = excluded.last_used_at
WHERE loop_definition_snapshots.definition_version = excluded.definition_version
  AND loop_definition_snapshots.definition_json = excluded.definition_json
  AND loop_definition_snapshots.byte_size = excluded.byte_size
`

type UpsertLoopDefinitionSnapshotParams struct {
	WorkspaceID       string `json:"workspace_id"`
	DefinitionDigest  string `json:"definition_digest"`
	DefinitionVersion int64  `json:"definition_version"`
	DefinitionJson    string `json:"definition_json"`
	ByteSize          int64  `json:"byte_size"`
	CreatedAt         string `json:"created_at"`
	LastUsedAt        string `json:"last_used_at"`
}

func (q *Queries) UpsertLoopDefinitionSnapshot(ctx context.Context, arg UpsertLoopDefinitionSnapshotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertLoopDefinitionSnapshot,
		arg.WorkspaceID,
		arg.DefinitionDigest,
		arg.DefinitionVersion,
		arg.DefinitionJson,
		arg.ByteSize,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertLoopGateDecision = `-- name: UpsertLoopGateDecision :exec
INSERT INTO loop_gate_decisions (
  workspace_id, loop_run_id, generation, gate_id, criterion_id, decision,
  actor_kind, actor_ref, origin_kind, origin_ref, note, decided_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9, ?10, ?11, ?12
)
ON CONFLICT(loop_run_id, generation, gate_id, criterion_id) DO UPDATE SET
  decision = excluded.decision, actor_kind = excluded.actor_kind, actor_ref = excluded.actor_ref,
  origin_kind = excluded.origin_kind, origin_ref = excluded.origin_ref,
  note = excluded.note, decided_at = excluded.decided_at
`

type UpsertLoopGateDecisionParams struct {
	WorkspaceID string `json:"workspace_id"`
	LoopRunID   string `json:"loop_run_id"`
	Generation  int64  `json:"generation"`
	GateID      string `json:"gate_id"`
	CriterionID string `json:"criterion_id"`
	Decision    string `json:"decision"`
	ActorKind   string `json:"actor_kind"`
	ActorRef    string `json:"actor_ref"`
	OriginKind  string `json:"origin_kind"`
	OriginRef   string `json:"origin_ref"`
	Note        string `json:"note"`
	DecidedAt   string `json:"decided_at"`
}

func (q *Queries) UpsertLoopGateDecision(ctx context.Context, arg UpsertLoopGateDecisionParams) error {
	_, err := q.db.ExecContext(ctx, upsertLoopGateDecision,
		arg.WorkspaceID,
		arg.LoopRunID,
		arg.Generation,
		arg.GateID,
		arg.CriterionID,
		arg.Decision,
		arg.ActorKind,
		arg.ActorRef,
		arg.OriginKind,
		arg.OriginRef,
		arg.Note,
		arg.DecidedAt,
	)
	return err
}
