// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loop_reconciliation.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getLoopReconciliationStatus = `-- name: GetLoopReconciliationStatus :one
SELECT status FROM loop_runs WHERE id = ?
`

func (q *Queries) GetLoopReconciliationStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLoopReconciliationStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listLoopProvenance = `-- name: ListLoopProvenance :many
WITH coordinators AS (
    SELECT task_id, workspace_id, loop_run_id,
        ROW_NUMBER() OVER (PARTITION BY task_id, workspace_id ORDER BY queued_at DESC, id DESC) AS precedence
    FROM task_runs
    WHERE run_kind = 'coordinator' AND loop_run_id IS NOT NULL AND trim(loop_run_id) <> ''
)
SELECT t.id, t.workspace_id, t.metadata_json, tr.loop_run_id, lr.loop_name
FROM tasks t
JOIN coordinators tr ON tr.task_id = t.id AND tr.workspace_id = t.workspace_id AND tr.precedence = 1
LEFT JOIN loop_runs lr ON lr.id = tr.loop_run_id AND lr.workspace_id = t.workspace_id
`

type ListLoopProvenanceRow struct {
	ID           string         `json:"id"`
	WorkspaceID  sql.NullString `json:"workspace_id"`
	MetadataJson sql.NullString `json:"metadata_json"`
	LoopRunID    sql.NullString `json:"loop_run_id"`
	LoopName     sql.NullString `json:"loop_name"`
}

func (q *Queries) ListLoopProvenance(ctx context.Context) ([]ListLoopProvenanceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoopProvenance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoopProvenanceRow{}
	for rows.Next() {
		var i ListLoopProvenanceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.MetadataJson,
			&i.LoopRunID,
			&i.LoopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoopReconciliationCandidates = `-- name: ListLoopReconciliationCandidates :many
SELECT candidate.loop_run_id FROM (
    SELECT loop_run_id FROM task_runs
    WHERE status IN ('queued','claimed','starting','running','needs_attention')
      AND loop_run_id IS NOT NULL AND trim(loop_run_id) <> ''
    UNION
    SELECT tr.loop_run_id FROM tasks t INDEXED BY idx_tasks_unsettled CROSS JOIN task_runs tr ON tr.task_id = t.id
    WHERE t.status NOT IN ('completed','failed','canceled')
      AND tr.loop_run_id IS NOT NULL AND trim(tr.loop_run_id) <> ''
) candidate LEFT JOIN loop_runs lr ON lr.id = candidate.loop_run_id
WHERE lr.id IS NULL OR lr.status IN ('done','no-op','blocked','failed','exhausted','stalled','canceled')
ORDER BY candidate.loop_run_id
`

func (q *Queries) ListLoopReconciliationCandidates(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listLoopReconciliationCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var loop_run_id sql.NullString
		if err := rows.Scan(&loop_run_id); err != nil {
			return nil, err
		}
		items = append(items, loop_run_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoopProvenance = `-- name: UpdateLoopProvenance :execrows
;

UPDATE tasks SET metadata_json = ?1
WHERE id = ?2 AND metadata_json IS ?3
`

type UpdateLoopProvenanceParams struct {
	Metadata         sql.NullString `json:"metadata"`
	ID               string         `json:"id"`
	PreviousMetadata sql.NullString `json:"previous_metadata"`
}

func (q *Queries) UpdateLoopProvenance(ctx context.Context, arg UpdateLoopProvenanceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLoopProvenance, arg.Metadata, arg.ID, arg.PreviousMetadata)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
