// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: network_conversation_write.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countNetworkDirectMessages = `-- name: CountNetworkDirectMessages :one
SELECT COUNT(*) FROM network_timeline_log
WHERE workspace_id = ?1 AND channel = ?2
  AND surface = 'direct' AND direct_id = ?3
`

type CountNetworkDirectMessagesParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Channel     string         `json:"channel"`
	DirectID    sql.NullString `json:"direct_id"`
}

func (q *Queries) CountNetworkDirectMessages(ctx context.Context, arg CountNetworkDirectMessagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNetworkDirectMessages, arg.WorkspaceID, arg.Channel, arg.DirectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNetworkThreadMessages = `-- name: CountNetworkThreadMessages :one
SELECT COUNT(*) FROM network_timeline_log
WHERE workspace_id = ?1 AND channel = ?2
  AND surface = 'thread' AND thread_id = ?3
`

type CountNetworkThreadMessagesParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Channel     string         `json:"channel"`
	ThreadID    sql.NullString `json:"thread_id"`
}

func (q *Queries) CountNetworkThreadMessages(ctx context.Context, arg CountNetworkThreadMessagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNetworkThreadMessages, arg.WorkspaceID, arg.Channel, arg.ThreadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNetworkThreadParticipants = `-- name: CountNetworkThreadParticipants :one
SELECT COUNT(*) FROM network_thread_participants
WHERE workspace_id = ?1 AND channel = ?2
  AND thread_id = ?3
`

type CountNetworkThreadParticipantsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Channel     string `json:"channel"`
	ThreadID    string `json:"thread_id"`
}

func (q *Queries) CountNetworkThreadParticipants(ctx context.Context, arg CountNetworkThreadParticipantsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNetworkThreadParticipants, arg.WorkspaceID, arg.Channel, arg.ThreadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenNetworkDirectWork = `-- name: CountOpenNetworkDirectWork :one
SELECT COUNT(*) FROM network_work
WHERE workspace_id = ?1 AND channel = ?2
  AND surface = 'direct' AND direct_id = ?3
  AND state NOT IN (?4, ?5, ?6)
`

type CountOpenNetworkDirectWorkParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Channel     string         `json:"channel"`
	DirectID    sql.NullString `json:"direct_id"`
	Completed   string         `json:"completed"`
	Failed      string         `json:"failed"`
	Canceled    string         `json:"canceled"`
}

func (q *Queries) CountOpenNetworkDirectWork(ctx context.Context, arg CountOpenNetworkDirectWorkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenNetworkDirectWork,
		arg.WorkspaceID,
		arg.Channel,
		arg.DirectID,
		arg.Completed,
		arg.Failed,
		arg.Canceled,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenNetworkThreadWork = `-- name: CountOpenNetworkThreadWork :one
SELECT COUNT(*) FROM network_work
WHERE workspace_id = ?1 AND channel = ?2
  AND surface = 'thread' AND thread_id = ?3
  AND state NOT IN (?4, ?5, ?6)
`

type CountOpenNetworkThreadWorkParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Channel     string         `json:"channel"`
	ThreadID    sql.NullString `json:"thread_id"`
	Completed   string         `json:"completed"`
	Failed      string         `json:"failed"`
	Canceled    string         `json:"canceled"`
}

func (q *Queries) CountOpenNetworkThreadWork(ctx context.Context, arg CountOpenNetworkThreadWorkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenNetworkThreadWork,
		arg.WorkspaceID,
		arg.Channel,
		arg.ThreadID,
		arg.Completed,
		arg.Failed,
		arg.Canceled,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLatestNetworkDirectMessage = `-- name: GetLatestNetworkDirectMessage :one
SELECT sequence, timestamp, preview_text
FROM network_timeline_log
WHERE workspace_id = ?1 AND channel = ?2
  AND surface = 'direct' AND direct_id = ?3
ORDER BY sequence DESC LIMIT 1
`

type GetLatestNetworkDirectMessageParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Channel     string         `json:"channel"`
	DirectID    sql.NullString `json:"direct_id"`
}

type GetLatestNetworkDirectMessageRow struct {
	Sequence    int64  `json:"sequence"`
	Timestamp   string `json:"timestamp"`
	PreviewText string `json:"preview_text"`
}

func (q *Queries) GetLatestNetworkDirectMessage(ctx context.Context, arg GetLatestNetworkDirectMessageParams) (GetLatestNetworkDirectMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestNetworkDirectMessage, arg.WorkspaceID, arg.Channel, arg.DirectID)
	var i GetLatestNetworkDirectMessageRow
	err := row.Scan(&i.Sequence, &i.Timestamp, &i.PreviewText)
	return i, err
}

const getLatestNetworkThreadMessage = `-- name: GetLatestNetworkThreadMessage :one
SELECT sequence, timestamp, preview_text
FROM network_timeline_log
WHERE workspace_id = ?1 AND channel = ?2
  AND surface = 'thread' AND thread_id = ?3
ORDER BY sequence DESC LIMIT 1
`

type GetLatestNetworkThreadMessageParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Channel     string         `json:"channel"`
	ThreadID    sql.NullString `json:"thread_id"`
}

type GetLatestNetworkThreadMessageRow struct {
	Sequence    int64  `json:"sequence"`
	Timestamp   string `json:"timestamp"`
	PreviewText string `json:"preview_text"`
}

func (q *Queries) GetLatestNetworkThreadMessage(ctx context.Context, arg GetLatestNetworkThreadMessageParams) (GetLatestNetworkThreadMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestNetworkThreadMessage, arg.WorkspaceID, arg.Channel, arg.ThreadID)
	var i GetLatestNetworkThreadMessageRow
	err := row.Scan(&i.Sequence, &i.Timestamp, &i.PreviewText)
	return i, err
}

const getNetworkCursorMessageID = `-- name: GetNetworkCursorMessageID :one
SELECT message_id FROM network_timeline_log
WHERE workspace_id = ?1 AND channel = ?2
  AND surface = ?3 AND sequence = ?4
  AND ((?3 = 'thread' AND thread_id = ?5)
    OR (?3 = 'direct' AND direct_id = ?5))
`

type GetNetworkCursorMessageIDParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Channel     string         `json:"channel"`
	Surface     sql.NullString `json:"surface"`
	Sequence    int64          `json:"sequence"`
	ContainerID sql.NullString `json:"container_id"`
}

func (q *Queries) GetNetworkCursorMessageID(ctx context.Context, arg GetNetworkCursorMessageIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNetworkCursorMessageID,
		arg.WorkspaceID,
		arg.Channel,
		arg.Surface,
		arg.Sequence,
		arg.ContainerID,
	)
	var message_id string
	err := row.Scan(&message_id)
	return message_id, err
}

const getNetworkCursorSequence = `-- name: GetNetworkCursorSequence :one
SELECT sequence FROM network_timeline_log
WHERE workspace_id = ?1 AND channel = ?2
  AND surface = ?3 AND message_id = ?4
  AND ((?3 = 'thread' AND thread_id = ?5)
    OR (?3 = 'direct' AND direct_id = ?5))
`

type GetNetworkCursorSequenceParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Channel     string         `json:"channel"`
	Surface     sql.NullString `json:"surface"`
	MessageID   string         `json:"message_id"`
	ContainerID sql.NullString `json:"container_id"`
}

func (q *Queries) GetNetworkCursorSequence(ctx context.Context, arg GetNetworkCursorSequenceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNetworkCursorSequence,
		arg.WorkspaceID,
		arg.Channel,
		arg.Surface,
		arg.MessageID,
		arg.ContainerID,
	)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const getNetworkDirectRoomBySessionPair = `-- name: GetNetworkDirectRoomBySessionPair :one
SELECT workspace_id, channel, direct_id, session_a, session_b,
       opened_at, opened_sequence, last_activity_at, last_activity_sequence,
       message_count, open_work_count, last_message_preview
FROM network_direct_rooms
WHERE workspace_id = ?1 AND channel = ?2
  AND session_a = ?3 AND session_b = ?4
`

type GetNetworkDirectRoomBySessionPairParams struct {
	WorkspaceID string `json:"workspace_id"`
	Channel     string `json:"channel"`
	SessionA    string `json:"session_a"`
	SessionB    string `json:"session_b"`
}

type GetNetworkDirectRoomBySessionPairRow struct {
	WorkspaceID          string `json:"workspace_id"`
	Channel              string `json:"channel"`
	DirectID             string `json:"direct_id"`
	SessionA             string `json:"session_a"`
	SessionB             string `json:"session_b"`
	OpenedAt             string `json:"opened_at"`
	OpenedSequence       int64  `json:"opened_sequence"`
	LastActivityAt       string `json:"last_activity_at"`
	LastActivitySequence int64  `json:"last_activity_sequence"`
	MessageCount         int64  `json:"message_count"`
	OpenWorkCount        int64  `json:"open_work_count"`
	LastMessagePreview   string `json:"last_message_preview"`
}

func (q *Queries) GetNetworkDirectRoomBySessionPair(ctx context.Context, arg GetNetworkDirectRoomBySessionPairParams) (GetNetworkDirectRoomBySessionPairRow, error) {
	row := q.db.QueryRowContext(ctx, getNetworkDirectRoomBySessionPair,
		arg.WorkspaceID,
		arg.Channel,
		arg.SessionA,
		arg.SessionB,
	)
	var i GetNetworkDirectRoomBySessionPairRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.Channel,
		&i.DirectID,
		&i.SessionA,
		&i.SessionB,
		&i.OpenedAt,
		&i.OpenedSequence,
		&i.LastActivityAt,
		&i.LastActivitySequence,
		&i.MessageCount,
		&i.OpenWorkCount,
		&i.LastMessagePreview,
	)
	return i, err
}

const getNetworkMessageTimestamp = `-- name: GetNetworkMessageTimestamp :one
SELECT timestamp FROM network_timeline_log
WHERE workspace_id = ?1 AND message_id = ?2
`

type GetNetworkMessageTimestampParams struct {
	WorkspaceID string `json:"workspace_id"`
	MessageID   string `json:"message_id"`
}

func (q *Queries) GetNetworkMessageTimestamp(ctx context.Context, arg GetNetworkMessageTimestampParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNetworkMessageTimestamp, arg.WorkspaceID, arg.MessageID)
	var timestamp string
	err := row.Scan(&timestamp)
	return timestamp, err
}

const getNetworkWork = `-- name: GetNetworkWork :one
SELECT work_id, workspace_id, channel, surface, thread_id, direct_id, opened_by_session_id,
       target_session_id, state, opened_at, last_activity_at, terminal_at
FROM network_work
WHERE workspace_id = ?1 AND work_id = ?2
`

type GetNetworkWorkParams struct {
	WorkspaceID string `json:"workspace_id"`
	WorkID      string `json:"work_id"`
}

func (q *Queries) GetNetworkWork(ctx context.Context, arg GetNetworkWorkParams) (NetworkWork, error) {
	row := q.db.QueryRowContext(ctx, getNetworkWork, arg.WorkspaceID, arg.WorkID)
	var i NetworkWork
	err := row.Scan(
		&i.WorkID,
		&i.WorkspaceID,
		&i.Channel,
		&i.Surface,
		&i.ThreadID,
		&i.DirectID,
		&i.OpenedBySessionID,
		&i.TargetSessionID,
		&i.State,
		&i.OpenedAt,
		&i.LastActivityAt,
		&i.TerminalAt,
	)
	return i, err
}

const getPriorNetworkTimelineWorkState = `-- name: GetPriorNetworkTimelineWorkState :one
SELECT COALESCE((
  SELECT prior.work_state
  FROM network_timeline_log prior
  WHERE prior.workspace_id = current.workspace_id
    AND prior.work_id = current.work_id
    AND prior.sequence < current.sequence
    AND prior.work_state <> ''
  ORDER BY prior.sequence DESC LIMIT 1
), '')
FROM network_timeline_log current
WHERE current.workspace_id = ?1 AND current.message_id = ?2
`

type GetPriorNetworkTimelineWorkStateParams struct {
	WorkspaceID string `json:"workspace_id"`
	MessageID   string `json:"message_id"`
}

func (q *Queries) GetPriorNetworkTimelineWorkState(ctx context.Context, arg GetPriorNetworkTimelineWorkStateParams) (any, error) {
	row := q.db.QueryRowContext(ctx, getPriorNetworkTimelineWorkState, arg.WorkspaceID, arg.MessageID)
	var coalesce any
	err := row.Scan(&coalesce)
	return coalesce, err
}

const initializeNetworkDirectRoomSequence = `-- name: InitializeNetworkDirectRoomSequence :execrows
UPDATE network_direct_rooms
SET opened_sequence = ?1, last_activity_sequence = ?2
WHERE workspace_id = ?3 AND channel = ?4
  AND direct_id = ?5 AND opened_sequence = 0
`

type InitializeNetworkDirectRoomSequenceParams struct {
	OpenedSequence       int64  `json:"opened_sequence"`
	LastActivitySequence int64  `json:"last_activity_sequence"`
	WorkspaceID          string `json:"workspace_id"`
	Channel              string `json:"channel"`
	DirectID             string `json:"direct_id"`
}

func (q *Queries) InitializeNetworkDirectRoomSequence(ctx context.Context, arg InitializeNetworkDirectRoomSequenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, initializeNetworkDirectRoomSequence,
		arg.OpenedSequence,
		arg.LastActivitySequence,
		arg.WorkspaceID,
		arg.Channel,
		arg.DirectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertNetworkDirectRoom = `-- name: InsertNetworkDirectRoom :execrows
INSERT OR IGNORE INTO network_direct_rooms (
  workspace_id, channel, direct_id, session_a, session_b, opened_at, last_activity_at,
  message_count, open_work_count, last_message_preview
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, 0, 0, ''
)
`

type InsertNetworkDirectRoomParams struct {
	WorkspaceID    string `json:"workspace_id"`
	Channel        string `json:"channel"`
	DirectID       string `json:"direct_id"`
	SessionA       string `json:"session_a"`
	SessionB       string `json:"session_b"`
	OpenedAt       string `json:"opened_at"`
	LastActivityAt string `json:"last_activity_at"`
}

func (q *Queries) InsertNetworkDirectRoom(ctx context.Context, arg InsertNetworkDirectRoomParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertNetworkDirectRoom,
		arg.WorkspaceID,
		arg.Channel,
		arg.DirectID,
		arg.SessionA,
		arg.SessionB,
		arg.OpenedAt,
		arg.LastActivityAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertNetworkThread = `-- name: InsertNetworkThread :execrows
INSERT OR IGNORE INTO network_threads (
  workspace_id, channel, thread_id, root_message_id, title, opened_by_peer_id, opened_session_id,
  opened_at, opened_sequence, last_activity_at, last_activity_sequence,
  message_count, participant_count, open_work_count, last_message_preview
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9, ?10, ?11, 0, 0, 0, ''
)
`

type InsertNetworkThreadParams struct {
	WorkspaceID          string `json:"workspace_id"`
	Channel              string `json:"channel"`
	ThreadID             string `json:"thread_id"`
	RootMessageID        string `json:"root_message_id"`
	Title                string `json:"title"`
	OpenedByPeerID       string `json:"opened_by_peer_id"`
	OpenedSessionID      string `json:"opened_session_id"`
	OpenedAt             string `json:"opened_at"`
	OpenedSequence       int64  `json:"opened_sequence"`
	LastActivityAt       string `json:"last_activity_at"`
	LastActivitySequence int64  `json:"last_activity_sequence"`
}

func (q *Queries) InsertNetworkThread(ctx context.Context, arg InsertNetworkThreadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertNetworkThread,
		arg.WorkspaceID,
		arg.Channel,
		arg.ThreadID,
		arg.RootMessageID,
		arg.Title,
		arg.OpenedByPeerID,
		arg.OpenedSessionID,
		arg.OpenedAt,
		arg.OpenedSequence,
		arg.LastActivityAt,
		arg.LastActivitySequence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertNetworkTimelineMessage = `-- name: InsertNetworkTimelineMessage :execresult
INSERT INTO network_timeline_log (
  message_id, session_id, workspace_id, channel, surface, thread_id, direct_id, direction,
  peer_from, peer_to, kind, work_id, reply_to, trace_id, causation_id, intent, text, preview_text,
  mentions_json, ext_json, body_json, timestamp
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9, ?10, ?11, ?12, ?13,
  ?14, ?15, ?16, ?17,
  ?18, ?19, ?20, ?21,
  ?22
)
ON CONFLICT(workspace_id, message_id) DO NOTHING
`

type InsertNetworkTimelineMessageParams struct {
	MessageID    string         `json:"message_id"`
	SessionID    sql.NullString `json:"session_id"`
	WorkspaceID  string         `json:"workspace_id"`
	Channel      string         `json:"channel"`
	Surface      sql.NullString `json:"surface"`
	ThreadID     sql.NullString `json:"thread_id"`
	DirectID     sql.NullString `json:"direct_id"`
	Direction    string         `json:"direction"`
	PeerFrom     string         `json:"peer_from"`
	PeerTo       sql.NullString `json:"peer_to"`
	Kind         string         `json:"kind"`
	WorkID       sql.NullString `json:"work_id"`
	ReplyTo      sql.NullString `json:"reply_to"`
	TraceID      sql.NullString `json:"trace_id"`
	CausationID  sql.NullString `json:"causation_id"`
	Intent       sql.NullString `json:"intent"`
	Text         sql.NullString `json:"text"`
	PreviewText  string         `json:"preview_text"`
	MentionsJson string         `json:"mentions_json"`
	ExtJson      string         `json:"ext_json"`
	BodyJson     string         `json:"body_json"`
	Timestamp    string         `json:"timestamp"`
}

func (q *Queries) InsertNetworkTimelineMessage(ctx context.Context, arg InsertNetworkTimelineMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertNetworkTimelineMessage,
		arg.MessageID,
		arg.SessionID,
		arg.WorkspaceID,
		arg.Channel,
		arg.Surface,
		arg.ThreadID,
		arg.DirectID,
		arg.Direction,
		arg.PeerFrom,
		arg.PeerTo,
		arg.Kind,
		arg.WorkID,
		arg.ReplyTo,
		arg.TraceID,
		arg.CausationID,
		arg.Intent,
		arg.Text,
		arg.PreviewText,
		arg.MentionsJson,
		arg.ExtJson,
		arg.BodyJson,
		arg.Timestamp,
	)
}

const insertNetworkWork = `-- name: InsertNetworkWork :exec
INSERT INTO network_work (
  work_id, workspace_id, channel, surface, thread_id, direct_id, opened_by_session_id,
  target_session_id, state, opened_at, last_activity_at, terminal_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9,
  ?10, ?11, NULL
)
`

type InsertNetworkWorkParams struct {
	WorkID            string         `json:"work_id"`
	WorkspaceID       string         `json:"workspace_id"`
	Channel           string         `json:"channel"`
	Surface           string         `json:"surface"`
	ThreadID          sql.NullString `json:"thread_id"`
	DirectID          sql.NullString `json:"direct_id"`
	OpenedBySessionID string         `json:"opened_by_session_id"`
	TargetSessionID   sql.NullString `json:"target_session_id"`
	State             string         `json:"state"`
	OpenedAt          string         `json:"opened_at"`
	LastActivityAt    string         `json:"last_activity_at"`
}

func (q *Queries) InsertNetworkWork(ctx context.Context, arg InsertNetworkWorkParams) error {
	_, err := q.db.ExecContext(ctx, insertNetworkWork,
		arg.WorkID,
		arg.WorkspaceID,
		arg.Channel,
		arg.Surface,
		arg.ThreadID,
		arg.DirectID,
		arg.OpenedBySessionID,
		arg.TargetSessionID,
		arg.State,
		arg.OpenedAt,
		arg.LastActivityAt,
	)
	return err
}

const updateNetworkDirectRoomSummary = `-- name: UpdateNetworkDirectRoomSummary :exec
UPDATE network_direct_rooms
SET last_activity_at = ?1,
    last_activity_sequence = ?2,
    message_count = ?3,
    open_work_count = ?4,
    last_message_preview = ?5
WHERE workspace_id = ?6 AND channel = ?7
  AND direct_id = ?8
`

type UpdateNetworkDirectRoomSummaryParams struct {
	LastActivityAt       string `json:"last_activity_at"`
	LastActivitySequence int64  `json:"last_activity_sequence"`
	MessageCount         int64  `json:"message_count"`
	OpenWorkCount        int64  `json:"open_work_count"`
	LastMessagePreview   string `json:"last_message_preview"`
	WorkspaceID          string `json:"workspace_id"`
	Channel              string `json:"channel"`
	DirectID             string `json:"direct_id"`
}

func (q *Queries) UpdateNetworkDirectRoomSummary(ctx context.Context, arg UpdateNetworkDirectRoomSummaryParams) error {
	_, err := q.db.ExecContext(ctx, updateNetworkDirectRoomSummary,
		arg.LastActivityAt,
		arg.LastActivitySequence,
		arg.MessageCount,
		arg.OpenWorkCount,
		arg.LastMessagePreview,
		arg.WorkspaceID,
		arg.Channel,
		arg.DirectID,
	)
	return err
}

const updateNetworkThreadSummary = `-- name: UpdateNetworkThreadSummary :exec
UPDATE network_threads
SET last_activity_at = ?1,
    last_activity_sequence = ?2,
    message_count = ?3,
    participant_count = ?4,
    open_work_count = ?5,
    last_message_preview = ?6
WHERE workspace_id = ?7 AND channel = ?8
  AND thread_id = ?9
`

type UpdateNetworkThreadSummaryParams struct {
	LastActivityAt       string `json:"last_activity_at"`
	LastActivitySequence int64  `json:"last_activity_sequence"`
	MessageCount         int64  `json:"message_count"`
	ParticipantCount     int64  `json:"participant_count"`
	OpenWorkCount        int64  `json:"open_work_count"`
	LastMessagePreview   string `json:"last_message_preview"`
	WorkspaceID          string `json:"workspace_id"`
	Channel              string `json:"channel"`
	ThreadID             string `json:"thread_id"`
}

func (q *Queries) UpdateNetworkThreadSummary(ctx context.Context, arg UpdateNetworkThreadSummaryParams) error {
	_, err := q.db.ExecContext(ctx, updateNetworkThreadSummary,
		arg.LastActivityAt,
		arg.LastActivitySequence,
		arg.MessageCount,
		arg.ParticipantCount,
		arg.OpenWorkCount,
		arg.LastMessagePreview,
		arg.WorkspaceID,
		arg.Channel,
		arg.ThreadID,
	)
	return err
}

const updateNetworkTimelineWorkProjection = `-- name: UpdateNetworkTimelineWorkProjection :exec
UPDATE network_timeline_log
SET work_opened = ?1, work_transitioned = ?2,
    work_state = ?3
WHERE workspace_id = ?4 AND message_id = ?5
`

type UpdateNetworkTimelineWorkProjectionParams struct {
	WorkOpened       int64  `json:"work_opened"`
	WorkTransitioned int64  `json:"work_transitioned"`
	WorkState        string `json:"work_state"`
	WorkspaceID      string `json:"workspace_id"`
	MessageID        string `json:"message_id"`
}

func (q *Queries) UpdateNetworkTimelineWorkProjection(ctx context.Context, arg UpdateNetworkTimelineWorkProjectionParams) error {
	_, err := q.db.ExecContext(ctx, updateNetworkTimelineWorkProjection,
		arg.WorkOpened,
		arg.WorkTransitioned,
		arg.WorkState,
		arg.WorkspaceID,
		arg.MessageID,
	)
	return err
}

const updateNetworkWork = `-- name: UpdateNetworkWork :exec
UPDATE network_work
SET state = ?1, last_activity_at = ?2, terminal_at = ?3
WHERE workspace_id = ?4 AND work_id = ?5
`

type UpdateNetworkWorkParams struct {
	State          string         `json:"state"`
	LastActivityAt string         `json:"last_activity_at"`
	TerminalAt     sql.NullString `json:"terminal_at"`
	WorkspaceID    string         `json:"workspace_id"`
	WorkID         string         `json:"work_id"`
}

func (q *Queries) UpdateNetworkWork(ctx context.Context, arg UpdateNetworkWorkParams) error {
	_, err := q.db.ExecContext(ctx, updateNetworkWork,
		arg.State,
		arg.LastActivityAt,
		arg.TerminalAt,
		arg.WorkspaceID,
		arg.WorkID,
	)
	return err
}

const upsertNetworkThreadParticipant = `-- name: UpsertNetworkThreadParticipant :exec
INSERT INTO network_thread_participants (
  workspace_id, channel, thread_id, session_id, first_message_id, first_seen_at, last_seen_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7
)
ON CONFLICT(workspace_id, channel, thread_id, session_id) DO UPDATE SET
  last_seen_at = excluded.last_seen_at
`

type UpsertNetworkThreadParticipantParams struct {
	WorkspaceID    string `json:"workspace_id"`
	Channel        string `json:"channel"`
	ThreadID       string `json:"thread_id"`
	SessionID      string `json:"session_id"`
	FirstMessageID string `json:"first_message_id"`
	FirstSeenAt    string `json:"first_seen_at"`
	LastSeenAt     string `json:"last_seen_at"`
}

func (q *Queries) UpsertNetworkThreadParticipant(ctx context.Context, arg UpsertNetworkThreadParticipantParams) error {
	_, err := q.db.ExecContext(ctx, upsertNetworkThreadParticipant,
		arg.WorkspaceID,
		arg.Channel,
		arg.ThreadID,
		arg.SessionID,
		arg.FirstMessageID,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	return err
}
