// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_input_clear.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const clearQueuedSessionInput = `-- name: ClearQueuedSessionInput :execrows
UPDATE session_input_queue
SET status = 'canceled', dispatchable = 0, canceled_at = ?1, updated_at = ?1,
    terminal_at = CASE WHEN owner_kind = 'goal' THEN ?1 ELSE terminal_at END,
    terminal_kind = CASE WHEN owner_kind = 'goal' THEN 'control-fenced' ELSE terminal_kind END,
    terminal_disposition = CASE WHEN owner_kind = 'goal' THEN 'paused' ELSE terminal_disposition END,
    terminal_reason_code = CASE WHEN owner_kind = 'goal' THEN 'goal_control_revoked_in_flight' ELSE terminal_reason_code END
WHERE session_id = ?2 AND id = ?3 AND status = 'queued'
`

type ClearQueuedSessionInputParams struct {
	Now       sql.NullString `json:"now"`
	SessionID string         `json:"session_id"`
	EntryID   string         `json:"entry_id"`
}

func (q *Queries) ClearQueuedSessionInput(ctx context.Context, arg ClearQueuedSessionInputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearQueuedSessionInput, arg.Now, arg.SessionID, arg.EntryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertSessionInputClearTrace = `-- name: InsertSessionInputClearTrace :exec
INSERT INTO session_input_clear_traces
    (entry_id, session_id, turn_id, actor_kind, actor_id, queue_generation, created_at)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7)
`

type InsertSessionInputClearTraceParams struct {
	EntryID         string `json:"entry_id"`
	SessionID       string `json:"session_id"`
	TurnID          string `json:"turn_id"`
	ActorKind       string `json:"actor_kind"`
	ActorID         string `json:"actor_id"`
	QueueGeneration int64  `json:"queue_generation"`
	CreatedAt       string `json:"created_at"`
}

func (q *Queries) InsertSessionInputClearTrace(ctx context.Context, arg InsertSessionInputClearTraceParams) error {
	_, err := q.db.ExecContext(ctx, insertSessionInputClearTrace,
		arg.EntryID,
		arg.SessionID,
		arg.TurnID,
		arg.ActorKind,
		arg.ActorID,
		arg.QueueGeneration,
		arg.CreatedAt,
	)
	return err
}

const listPendingSessionInputClearTraces = `-- name: ListPendingSessionInputClearTraces :many
SELECT entry_id, session_id, turn_id, actor_kind, actor_id, queue_generation, created_at, projected_at FROM session_input_clear_traces
WHERE session_id = ?1 AND projected_at IS NULL
ORDER BY created_at, entry_id
`

func (q *Queries) ListPendingSessionInputClearTraces(ctx context.Context, sessionID string) ([]SessionInputClearTrace, error) {
	rows, err := q.db.QueryContext(ctx, listPendingSessionInputClearTraces, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionInputClearTrace{}
	for rows.Next() {
		var i SessionInputClearTrace
		if err := rows.Scan(
			&i.EntryID,
			&i.SessionID,
			&i.TurnID,
			&i.ActorKind,
			&i.ActorID,
			&i.QueueGeneration,
			&i.CreatedAt,
			&i.ProjectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionInputClearTraceProjected = `-- name: MarkSessionInputClearTraceProjected :exec
UPDATE session_input_clear_traces SET projected_at = ?1
WHERE session_id = ?2 AND entry_id = ?3 AND projected_at IS NULL
`

type MarkSessionInputClearTraceProjectedParams struct {
	Now       sql.NullString `json:"now"`
	SessionID string         `json:"session_id"`
	EntryID   string         `json:"entry_id"`
}

func (q *Queries) MarkSessionInputClearTraceProjected(ctx context.Context, arg MarkSessionInputClearTraceProjectedParams) error {
	_, err := q.db.ExecContext(ctx, markSessionInputClearTraceProjected, arg.Now, arg.SessionID, arg.EntryID)
	return err
}

const rebaseDispatchingSessionInputs = `-- name: RebaseDispatchingSessionInputs :exec
UPDATE session_input_queue SET session_generation = ?1
WHERE session_id = ?2 AND status = 'dispatching'
`

type RebaseDispatchingSessionInputsParams struct {
	Generation int64  `json:"generation"`
	SessionID  string `json:"session_id"`
}

func (q *Queries) RebaseDispatchingSessionInputs(ctx context.Context, arg RebaseDispatchingSessionInputsParams) error {
	_, err := q.db.ExecContext(ctx, rebaseDispatchingSessionInputs, arg.Generation, arg.SessionID)
	return err
}
