// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_core.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const countActiveTaskRunSessionBindings = `-- name: CountActiveTaskRunSessionBindings :one
SELECT COUNT(1)
FROM task_runs
WHERE session_id = ?1
  AND status IN (?2, ?3, ?4)
`

type CountActiveTaskRunSessionBindingsParams struct {
	SessionID      sql.NullString `json:"session_id"`
	ClaimedStatus  string         `json:"claimed_status"`
	StartingStatus string         `json:"starting_status"`
	RunningStatus  string         `json:"running_status"`
}

func (q *Queries) CountActiveTaskRunSessionBindings(ctx context.Context, arg CountActiveTaskRunSessionBindingsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTaskRunSessionBindings,
		arg.SessionID,
		arg.ClaimedStatus,
		arg.StartingStatus,
		arg.RunningStatus,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDirectTaskChildren = `-- name: CountDirectTaskChildren :one
SELECT COUNT(1) FROM tasks WHERE parent_task_id = ?1
`

func (q *Queries) CountDirectTaskChildren(ctx context.Context, parentTaskID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDirectTaskChildren, parentTaskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePreferredTaskRunCapabilities = `-- name: DeletePreferredTaskRunCapabilities :exec
DELETE FROM task_run_preferred_capabilities WHERE run_id = ?1
`

func (q *Queries) DeletePreferredTaskRunCapabilities(ctx context.Context, runID string) error {
	_, err := q.db.ExecContext(ctx, deletePreferredTaskRunCapabilities, runID)
	return err
}

const deleteRequiredTaskRunCapabilities = `-- name: DeleteRequiredTaskRunCapabilities :exec
DELETE FROM task_run_required_capabilities WHERE run_id = ?1
`

func (q *Queries) DeleteRequiredTaskRunCapabilities(ctx context.Context, runID string) error {
	_, err := q.db.ExecContext(ctx, deleteRequiredTaskRunCapabilities, runID)
	return err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks WHERE id = ?1
`

func (q *Queries) DeleteTask(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTask = `-- name: GetTask :one
SELECT
  id, identifier, scope, workspace_id, parent_task_id, title, description,
  priority, max_attempts, auto_enqueue_on_ready, status, approval_policy, approval_state,
  owner_kind, owner_ref, created_by_kind, created_by_ref, origin_kind, origin_ref,
  created_at, updated_at, closed_at, current_run_id,
  CAST(COALESCE((SELECT MAX(te.event_seq) FROM task_events te WHERE te.task_id = tasks.id), 0) AS INTEGER) AS latest_event_seq,
  paused, paused_by, paused_at, paused_reason, needs_attention_reason, needs_attention_at,
  needs_attention_by_kind, needs_attention_by_ref, wake_creator, metadata_json
FROM tasks
WHERE tasks.id = ?1
`

type GetTaskRow struct {
	ID                   string         `json:"id"`
	Identifier           sql.NullString `json:"identifier"`
	Scope                string         `json:"scope"`
	WorkspaceID          sql.NullString `json:"workspace_id"`
	ParentTaskID         sql.NullString `json:"parent_task_id"`
	Title                string         `json:"title"`
	Description          sql.NullString `json:"description"`
	Priority             string         `json:"priority"`
	MaxAttempts          int64          `json:"max_attempts"`
	AutoEnqueueOnReady   int64          `json:"auto_enqueue_on_ready"`
	Status               string         `json:"status"`
	ApprovalPolicy       string         `json:"approval_policy"`
	ApprovalState        string         `json:"approval_state"`
	OwnerKind            sql.NullString `json:"owner_kind"`
	OwnerRef             sql.NullString `json:"owner_ref"`
	CreatedByKind        string         `json:"created_by_kind"`
	CreatedByRef         string         `json:"created_by_ref"`
	OriginKind           string         `json:"origin_kind"`
	OriginRef            string         `json:"origin_ref"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	ClosedAt             sql.NullString `json:"closed_at"`
	CurrentRunID         sql.NullString `json:"current_run_id"`
	LatestEventSeq       int64          `json:"latest_event_seq"`
	Paused               int64          `json:"paused"`
	PausedBy             string         `json:"paused_by"`
	PausedAt             sql.NullString `json:"paused_at"`
	PausedReason         string         `json:"paused_reason"`
	NeedsAttentionReason sql.NullString `json:"needs_attention_reason"`
	NeedsAttentionAt     sql.NullString `json:"needs_attention_at"`
	NeedsAttentionByKind sql.NullString `json:"needs_attention_by_kind"`
	NeedsAttentionByRef  sql.NullString `json:"needs_attention_by_ref"`
	WakeCreator          int64          `json:"wake_creator"`
	MetadataJson         sql.NullString `json:"metadata_json"`
}

func (q *Queries) GetTask(ctx context.Context, taskID string) (GetTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getTask, taskID)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Scope,
		&i.WorkspaceID,
		&i.ParentTaskID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.MaxAttempts,
		&i.AutoEnqueueOnReady,
		&i.Status,
		&i.ApprovalPolicy,
		&i.ApprovalState,
		&i.OwnerKind,
		&i.OwnerRef,
		&i.CreatedByKind,
		&i.CreatedByRef,
		&i.OriginKind,
		&i.OriginRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.CurrentRunID,
		&i.LatestEventSeq,
		&i.Paused,
		&i.PausedBy,
		&i.PausedAt,
		&i.PausedReason,
		&i.NeedsAttentionReason,
		&i.NeedsAttentionAt,
		&i.NeedsAttentionByKind,
		&i.NeedsAttentionByRef,
		&i.WakeCreator,
		&i.MetadataJson,
	)
	return i, err
}

const getTaskID = `-- name: GetTaskID :one
SELECT id FROM tasks WHERE tasks.id = ?1
`

func (q *Queries) GetTaskID(ctx context.Context, taskID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskID, taskID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getTaskRun = `-- name: GetTaskRun :one
SELECT
  id, task_id, workspace_id, run_kind, loop_run_id, status, attempt, recovery_count, previous_run_id, failure_kind,
  claimed_by_kind, claimed_by_ref, session_id, origin_kind, origin_ref, idempotency_key,
  network_spec_json, network_mode, network_channel, network_source, designation_group_id,
  '' AS claim_token, claim_token_hash, lease_until, heartbeat_at, queued_at, claimed_at, started_at, ended_at,
  tokens_used, error, metadata_json, result_json, review_required, review_request_round,
  review_policy_snapshot, review_request_id, parent_run_id, review_id, review_round,
  continuation_reason, missing_work_json, next_round_guidance,
  network_wake_id, network_target_session_id, network_owner_key
FROM task_runs
WHERE id = ?1
`

type GetTaskRunRow struct {
	ID                     string         `json:"id"`
	TaskID                 sql.NullString `json:"task_id"`
	WorkspaceID            sql.NullString `json:"workspace_id"`
	RunKind                string         `json:"run_kind"`
	LoopRunID              sql.NullString `json:"loop_run_id"`
	Status                 string         `json:"status"`
	Attempt                int64          `json:"attempt"`
	RecoveryCount          int64          `json:"recovery_count"`
	PreviousRunID          sql.NullString `json:"previous_run_id"`
	FailureKind            string         `json:"failure_kind"`
	ClaimedByKind          sql.NullString `json:"claimed_by_kind"`
	ClaimedByRef           sql.NullString `json:"claimed_by_ref"`
	SessionID              sql.NullString `json:"session_id"`
	OriginKind             string         `json:"origin_kind"`
	OriginRef              string         `json:"origin_ref"`
	IdempotencyKey         sql.NullString `json:"idempotency_key"`
	NetworkSpecJson        string         `json:"network_spec_json"`
	NetworkMode            string         `json:"network_mode"`
	NetworkChannel         sql.NullString `json:"network_channel"`
	NetworkSource          string         `json:"network_source"`
	DesignationGroupID     string         `json:"designation_group_id"`
	ClaimToken             string         `json:"claim_token"`
	ClaimTokenHash         sql.NullString `json:"claim_token_hash"`
	LeaseUntil             sql.NullString `json:"lease_until"`
	HeartbeatAt            sql.NullString `json:"heartbeat_at"`
	QueuedAt               string         `json:"queued_at"`
	ClaimedAt              sql.NullString `json:"claimed_at"`
	StartedAt              sql.NullString `json:"started_at"`
	EndedAt                sql.NullString `json:"ended_at"`
	TokensUsed             int64          `json:"tokens_used"`
	Error                  sql.NullString `json:"error"`
	MetadataJson           sql.NullString `json:"metadata_json"`
	ResultJson             sql.NullString `json:"result_json"`
	ReviewRequired         bool           `json:"review_required"`
	ReviewRequestRound     int64          `json:"review_request_round"`
	ReviewPolicySnapshot   string         `json:"review_policy_snapshot"`
	ReviewRequestID        sql.NullString `json:"review_request_id"`
	ParentRunID            sql.NullString `json:"parent_run_id"`
	ReviewID               sql.NullString `json:"review_id"`
	ReviewRound            int64          `json:"review_round"`
	ContinuationReason     string         `json:"continuation_reason"`
	MissingWorkJson        string         `json:"missing_work_json"`
	NextRoundGuidance      string         `json:"next_round_guidance"`
	NetworkWakeID          sql.NullString `json:"network_wake_id"`
	NetworkTargetSessionID sql.NullString `json:"network_target_session_id"`
	NetworkOwnerKey        sql.NullString `json:"network_owner_key"`
}

func (q *Queries) GetTaskRun(ctx context.Context, id string) (GetTaskRunRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskRun, id)
	var i GetTaskRunRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.WorkspaceID,
		&i.RunKind,
		&i.LoopRunID,
		&i.Status,
		&i.Attempt,
		&i.RecoveryCount,
		&i.PreviousRunID,
		&i.FailureKind,
		&i.ClaimedByKind,
		&i.ClaimedByRef,
		&i.SessionID,
		&i.OriginKind,
		&i.OriginRef,
		&i.IdempotencyKey,
		&i.NetworkSpecJson,
		&i.NetworkMode,
		&i.NetworkChannel,
		&i.NetworkSource,
		&i.DesignationGroupID,
		&i.ClaimToken,
		&i.ClaimTokenHash,
		&i.LeaseUntil,
		&i.HeartbeatAt,
		&i.QueuedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.TokensUsed,
		&i.Error,
		&i.MetadataJson,
		&i.ResultJson,
		&i.ReviewRequired,
		&i.ReviewRequestRound,
		&i.ReviewPolicySnapshot,
		&i.ReviewRequestID,
		&i.ParentRunID,
		&i.ReviewID,
		&i.ReviewRound,
		&i.ContinuationReason,
		&i.MissingWorkJson,
		&i.NextRoundGuidance,
		&i.NetworkWakeID,
		&i.NetworkTargetSessionID,
		&i.NetworkOwnerKey,
	)
	return i, err
}

const getWorkspaceID = `-- name: GetWorkspaceID :one
SELECT id FROM workspaces WHERE workspaces.id = ?1
`

func (q *Queries) GetWorkspaceID(ctx context.Context, workspaceID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceID, workspaceID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertPreferredTaskRunCapability = `-- name: InsertPreferredTaskRunCapability :exec
INSERT INTO task_run_preferred_capabilities (run_id, capability_id)
VALUES (?1, ?2)
`

type InsertPreferredTaskRunCapabilityParams struct {
	RunID        string `json:"run_id"`
	CapabilityID string `json:"capability_id"`
}

func (q *Queries) InsertPreferredTaskRunCapability(ctx context.Context, arg InsertPreferredTaskRunCapabilityParams) error {
	_, err := q.db.ExecContext(ctx, insertPreferredTaskRunCapability, arg.RunID, arg.CapabilityID)
	return err
}

const insertRequiredTaskRunCapability = `-- name: InsertRequiredTaskRunCapability :exec
INSERT INTO task_run_required_capabilities (run_id, capability_id)
VALUES (?1, ?2)
`

type InsertRequiredTaskRunCapabilityParams struct {
	RunID        string `json:"run_id"`
	CapabilityID string `json:"capability_id"`
}

func (q *Queries) InsertRequiredTaskRunCapability(ctx context.Context, arg InsertRequiredTaskRunCapabilityParams) error {
	_, err := q.db.ExecContext(ctx, insertRequiredTaskRunCapability, arg.RunID, arg.CapabilityID)
	return err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks (
  id, identifier, scope, workspace_id, parent_task_id, title, description,
  priority, max_attempts, auto_enqueue_on_ready, status, approval_policy, approval_state,
  owner_kind, owner_ref, created_by_kind, created_by_ref, origin_kind, origin_ref,
  created_at, updated_at, closed_at, paused, paused_by, paused_at, paused_reason, wake_creator,
  metadata_json
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10, ?11,
  ?12, ?13, ?14, ?15,
  ?16, ?17, ?18, ?19,
  ?20, ?21, ?22, ?23,
  ?24, ?25, ?26, ?27,
  ?28
)
`

type InsertTaskParams struct {
	ID                 string         `json:"id"`
	Identifier         sql.NullString `json:"identifier"`
	Scope              string         `json:"scope"`
	WorkspaceID        sql.NullString `json:"workspace_id"`
	ParentTaskID       sql.NullString `json:"parent_task_id"`
	Title              string         `json:"title"`
	Description        sql.NullString `json:"description"`
	Priority           string         `json:"priority"`
	MaxAttempts        int64          `json:"max_attempts"`
	AutoEnqueueOnReady int64          `json:"auto_enqueue_on_ready"`
	Status             string         `json:"status"`
	ApprovalPolicy     string         `json:"approval_policy"`
	ApprovalState      string         `json:"approval_state"`
	OwnerKind          sql.NullString `json:"owner_kind"`
	OwnerRef           sql.NullString `json:"owner_ref"`
	CreatedByKind      string         `json:"created_by_kind"`
	CreatedByRef       string         `json:"created_by_ref"`
	OriginKind         string         `json:"origin_kind"`
	OriginRef          string         `json:"origin_ref"`
	CreatedAt          string         `json:"created_at"`
	UpdatedAt          string         `json:"updated_at"`
	ClosedAt           sql.NullString `json:"closed_at"`
	Paused             int64          `json:"paused"`
	PausedBy           string         `json:"paused_by"`
	PausedAt           sql.NullString `json:"paused_at"`
	PausedReason       string         `json:"paused_reason"`
	WakeCreator        int64          `json:"wake_creator"`
	MetadataJson       sql.NullString `json:"metadata_json"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTask,
		arg.ID,
		arg.Identifier,
		arg.Scope,
		arg.WorkspaceID,
		arg.ParentTaskID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.MaxAttempts,
		arg.AutoEnqueueOnReady,
		arg.Status,
		arg.ApprovalPolicy,
		arg.ApprovalState,
		arg.OwnerKind,
		arg.OwnerRef,
		arg.CreatedByKind,
		arg.CreatedByRef,
		arg.OriginKind,
		arg.OriginRef,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClosedAt,
		arg.Paused,
		arg.PausedBy,
		arg.PausedAt,
		arg.PausedReason,
		arg.WakeCreator,
		arg.MetadataJson,
	)
	return err
}

const insertTaskRun = `-- name: InsertTaskRun :exec
INSERT INTO task_runs (
  id, task_id, workspace_id, run_kind, loop_run_id, status, attempt, recovery_count, previous_run_id, failure_kind,
  claimed_by_kind, claimed_by_ref, session_id, origin_kind, origin_ref, idempotency_key,
  network_spec_json, network_mode, network_channel, network_source, designation_group_id,
  claim_token, claim_token_hash, lease_until, heartbeat_at, queued_at, claimed_at, started_at, ended_at,
  tokens_used, error, metadata_json, result_json, review_required, review_request_round,
  review_policy_snapshot, review_request_id, parent_run_id, review_id, review_round,
  continuation_reason, missing_work_json, next_round_guidance,
  network_wake_id, network_target_session_id, network_owner_key
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6,
  ?7, ?8, ?9, ?10, ?11,
  ?12, ?13, ?14, ?15,
  ?16, ?17, ?18,
  ?19, ?20, ?21,
  NULL, ?22, ?23, ?24,
  ?25, ?26, ?27, ?28,
  ?29, ?30,
  ?31, ?32, ?33,
  ?34, ?35, ?36,
  ?37, ?38, ?39,
  ?40, ?41, ?42,
  ?43, ?44, ?45
)
`

type InsertTaskRunParams struct {
	ID                     string         `json:"id"`
	TaskID                 sql.NullString `json:"task_id"`
	WorkspaceID            sql.NullString `json:"workspace_id"`
	RunKind                string         `json:"run_kind"`
	LoopRunID              sql.NullString `json:"loop_run_id"`
	Status                 string         `json:"status"`
	Attempt                int64          `json:"attempt"`
	RecoveryCount          int64          `json:"recovery_count"`
	PreviousRunID          sql.NullString `json:"previous_run_id"`
	FailureKind            string         `json:"failure_kind"`
	ClaimedByKind          sql.NullString `json:"claimed_by_kind"`
	ClaimedByRef           sql.NullString `json:"claimed_by_ref"`
	SessionID              sql.NullString `json:"session_id"`
	OriginKind             string         `json:"origin_kind"`
	OriginRef              string         `json:"origin_ref"`
	IdempotencyKey         sql.NullString `json:"idempotency_key"`
	NetworkSpecJson        string         `json:"network_spec_json"`
	NetworkMode            string         `json:"network_mode"`
	NetworkChannel         sql.NullString `json:"network_channel"`
	NetworkSource          string         `json:"network_source"`
	DesignationGroupID     string         `json:"designation_group_id"`
	ClaimTokenHash         sql.NullString `json:"claim_token_hash"`
	LeaseUntil             sql.NullString `json:"lease_until"`
	HeartbeatAt            sql.NullString `json:"heartbeat_at"`
	QueuedAt               string         `json:"queued_at"`
	ClaimedAt              sql.NullString `json:"claimed_at"`
	StartedAt              sql.NullString `json:"started_at"`
	EndedAt                sql.NullString `json:"ended_at"`
	TokensUsed             int64          `json:"tokens_used"`
	Error                  sql.NullString `json:"error"`
	MetadataJson           sql.NullString `json:"metadata_json"`
	ResultJson             sql.NullString `json:"result_json"`
	ReviewRequired         bool           `json:"review_required"`
	ReviewRequestRound     int64          `json:"review_request_round"`
	ReviewPolicySnapshot   string         `json:"review_policy_snapshot"`
	ReviewRequestID        sql.NullString `json:"review_request_id"`
	ParentRunID            sql.NullString `json:"parent_run_id"`
	ReviewID               sql.NullString `json:"review_id"`
	ReviewRound            int64          `json:"review_round"`
	ContinuationReason     string         `json:"continuation_reason"`
	MissingWorkJson        string         `json:"missing_work_json"`
	NextRoundGuidance      string         `json:"next_round_guidance"`
	NetworkWakeID          sql.NullString `json:"network_wake_id"`
	NetworkTargetSessionID sql.NullString `json:"network_target_session_id"`
	NetworkOwnerKey        sql.NullString `json:"network_owner_key"`
}

func (q *Queries) InsertTaskRun(ctx context.Context, arg InsertTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskRun,
		arg.ID,
		arg.TaskID,
		arg.WorkspaceID,
		arg.RunKind,
		arg.LoopRunID,
		arg.Status,
		arg.Attempt,
		arg.RecoveryCount,
		arg.PreviousRunID,
		arg.FailureKind,
		arg.ClaimedByKind,
		arg.ClaimedByRef,
		arg.SessionID,
		arg.OriginKind,
		arg.OriginRef,
		arg.IdempotencyKey,
		arg.NetworkSpecJson,
		arg.NetworkMode,
		arg.NetworkChannel,
		arg.NetworkSource,
		arg.DesignationGroupID,
		arg.ClaimTokenHash,
		arg.LeaseUntil,
		arg.HeartbeatAt,
		arg.QueuedAt,
		arg.ClaimedAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.TokensUsed,
		arg.Error,
		arg.MetadataJson,
		arg.ResultJson,
		arg.ReviewRequired,
		arg.ReviewRequestRound,
		arg.ReviewPolicySnapshot,
		arg.ReviewRequestID,
		arg.ParentRunID,
		arg.ReviewID,
		arg.ReviewRound,
		arg.ContinuationReason,
		arg.MissingWorkJson,
		arg.NextRoundGuidance,
		arg.NetworkWakeID,
		arg.NetworkTargetSessionID,
		arg.NetworkOwnerKey,
	)
	return err
}

const listPreferredTaskRunCapabilities = `-- name: ListPreferredTaskRunCapabilities :many
SELECT run_id, capability_id
FROM task_run_preferred_capabilities
WHERE run_id IN (/*SLICE:run_ids*/?)
ORDER BY run_id ASC, capability_id ASC
`

func (q *Queries) ListPreferredTaskRunCapabilities(ctx context.Context, runIds []string) ([]TaskRunPreferredCapability, error) {
	query := listPreferredTaskRunCapabilities
	var queryParams []any
	if len(runIds) > 0 {
		for _, v := range runIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:run_ids*/?", strings.Repeat(",?", len(runIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:run_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskRunPreferredCapability{}
	for rows.Next() {
		var i TaskRunPreferredCapability
		if err := rows.Scan(&i.RunID, &i.CapabilityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequiredTaskRunCapabilities = `-- name: ListRequiredTaskRunCapabilities :many
SELECT run_id, capability_id
FROM task_run_required_capabilities
WHERE run_id IN (/*SLICE:run_ids*/?)
ORDER BY run_id ASC, capability_id ASC
`

func (q *Queries) ListRequiredTaskRunCapabilities(ctx context.Context, runIds []string) ([]TaskRunRequiredCapability, error) {
	query := listRequiredTaskRunCapabilities
	var queryParams []any
	if len(runIds) > 0 {
		for _, v := range runIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:run_ids*/?", strings.Repeat(",?", len(runIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:run_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskRunRequiredCapability{}
	for rows.Next() {
		var i TaskRunRequiredCapability
		if err := rows.Scan(&i.RunID, &i.CapabilityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskRunsByStatus = `-- name: ListTaskRunsByStatus :many
SELECT
  id, task_id, workspace_id, run_kind, loop_run_id, status, attempt, recovery_count, previous_run_id, failure_kind,
  claimed_by_kind, claimed_by_ref, session_id, origin_kind, origin_ref, idempotency_key,
  network_spec_json, network_mode, network_channel, network_source, designation_group_id,
  '' AS claim_token, claim_token_hash, lease_until, heartbeat_at, queued_at, claimed_at, started_at, ended_at,
  tokens_used, error, metadata_json, result_json, review_required, review_request_round,
  review_policy_snapshot, review_request_id, parent_run_id, review_id, review_round,
  continuation_reason, missing_work_json, next_round_guidance,
  network_wake_id, network_target_session_id, network_owner_key
FROM task_runs
WHERE status IN (/*SLICE:statuses*/?)
ORDER BY queued_at ASC, id ASC
`

type ListTaskRunsByStatusRow struct {
	ID                     string         `json:"id"`
	TaskID                 sql.NullString `json:"task_id"`
	WorkspaceID            sql.NullString `json:"workspace_id"`
	RunKind                string         `json:"run_kind"`
	LoopRunID              sql.NullString `json:"loop_run_id"`
	Status                 string         `json:"status"`
	Attempt                int64          `json:"attempt"`
	RecoveryCount          int64          `json:"recovery_count"`
	PreviousRunID          sql.NullString `json:"previous_run_id"`
	FailureKind            string         `json:"failure_kind"`
	ClaimedByKind          sql.NullString `json:"claimed_by_kind"`
	ClaimedByRef           sql.NullString `json:"claimed_by_ref"`
	SessionID              sql.NullString `json:"session_id"`
	OriginKind             string         `json:"origin_kind"`
	OriginRef              string         `json:"origin_ref"`
	IdempotencyKey         sql.NullString `json:"idempotency_key"`
	NetworkSpecJson        string         `json:"network_spec_json"`
	NetworkMode            string         `json:"network_mode"`
	NetworkChannel         sql.NullString `json:"network_channel"`
	NetworkSource          string         `json:"network_source"`
	DesignationGroupID     string         `json:"designation_group_id"`
	ClaimToken             string         `json:"claim_token"`
	ClaimTokenHash         sql.NullString `json:"claim_token_hash"`
	LeaseUntil             sql.NullString `json:"lease_until"`
	HeartbeatAt            sql.NullString `json:"heartbeat_at"`
	QueuedAt               string         `json:"queued_at"`
	ClaimedAt              sql.NullString `json:"claimed_at"`
	StartedAt              sql.NullString `json:"started_at"`
	EndedAt                sql.NullString `json:"ended_at"`
	TokensUsed             int64          `json:"tokens_used"`
	Error                  sql.NullString `json:"error"`
	MetadataJson           sql.NullString `json:"metadata_json"`
	ResultJson             sql.NullString `json:"result_json"`
	ReviewRequired         bool           `json:"review_required"`
	ReviewRequestRound     int64          `json:"review_request_round"`
	ReviewPolicySnapshot   string         `json:"review_policy_snapshot"`
	ReviewRequestID        sql.NullString `json:"review_request_id"`
	ParentRunID            sql.NullString `json:"parent_run_id"`
	ReviewID               sql.NullString `json:"review_id"`
	ReviewRound            int64          `json:"review_round"`
	ContinuationReason     string         `json:"continuation_reason"`
	MissingWorkJson        string         `json:"missing_work_json"`
	NextRoundGuidance      string         `json:"next_round_guidance"`
	NetworkWakeID          sql.NullString `json:"network_wake_id"`
	NetworkTargetSessionID sql.NullString `json:"network_target_session_id"`
	NetworkOwnerKey        sql.NullString `json:"network_owner_key"`
}

func (q *Queries) ListTaskRunsByStatus(ctx context.Context, statuses []string) ([]ListTaskRunsByStatusRow, error) {
	query := listTaskRunsByStatus
	var queryParams []any
	if len(statuses) > 0 {
		for _, v := range statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskRunsByStatusRow{}
	for rows.Next() {
		var i ListTaskRunsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.WorkspaceID,
			&i.RunKind,
			&i.LoopRunID,
			&i.Status,
			&i.Attempt,
			&i.RecoveryCount,
			&i.PreviousRunID,
			&i.FailureKind,
			&i.ClaimedByKind,
			&i.ClaimedByRef,
			&i.SessionID,
			&i.OriginKind,
			&i.OriginRef,
			&i.IdempotencyKey,
			&i.NetworkSpecJson,
			&i.NetworkMode,
			&i.NetworkChannel,
			&i.NetworkSource,
			&i.DesignationGroupID,
			&i.ClaimToken,
			&i.ClaimTokenHash,
			&i.LeaseUntil,
			&i.HeartbeatAt,
			&i.QueuedAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.TokensUsed,
			&i.Error,
			&i.MetadataJson,
			&i.ResultJson,
			&i.ReviewRequired,
			&i.ReviewRequestRound,
			&i.ReviewPolicySnapshot,
			&i.ReviewRequestID,
			&i.ParentRunID,
			&i.ReviewID,
			&i.ReviewRound,
			&i.ContinuationReason,
			&i.MissingWorkJson,
			&i.NextRoundGuidance,
			&i.NetworkWakeID,
			&i.NetworkTargetSessionID,
			&i.NetworkOwnerKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :execrows
UPDATE tasks
SET identifier = ?1,
    scope = ?2,
    workspace_id = ?3,
    parent_task_id = ?4,
    title = ?5,
    description = ?6,
    priority = ?7,
    max_attempts = ?8,
    auto_enqueue_on_ready = ?9,
    approval_policy = ?10,
    approval_state = ?11,
    owner_kind = ?12,
    owner_ref = ?13,
    created_by_kind = ?14,
    created_by_ref = ?15,
    origin_kind = ?16,
    origin_ref = ?17,
    created_at = ?18,
    updated_at = ?19,
    closed_at = ?20,
    paused = ?21,
    paused_by = ?22,
    paused_at = ?23,
    paused_reason = ?24,
    needs_attention_reason = ?25,
    needs_attention_at = ?26,
    needs_attention_by_kind = ?27,
    needs_attention_by_ref = ?28,
    wake_creator = ?29,
    metadata_json = ?30
WHERE id = ?31
`

type UpdateTaskParams struct {
	Identifier           sql.NullString `json:"identifier"`
	Scope                string         `json:"scope"`
	WorkspaceID          sql.NullString `json:"workspace_id"`
	ParentTaskID         sql.NullString `json:"parent_task_id"`
	Title                string         `json:"title"`
	Description          sql.NullString `json:"description"`
	Priority             string         `json:"priority"`
	MaxAttempts          int64          `json:"max_attempts"`
	AutoEnqueueOnReady   int64          `json:"auto_enqueue_on_ready"`
	ApprovalPolicy       string         `json:"approval_policy"`
	ApprovalState        string         `json:"approval_state"`
	OwnerKind            sql.NullString `json:"owner_kind"`
	OwnerRef             sql.NullString `json:"owner_ref"`
	CreatedByKind        string         `json:"created_by_kind"`
	CreatedByRef         string         `json:"created_by_ref"`
	OriginKind           string         `json:"origin_kind"`
	OriginRef            string         `json:"origin_ref"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	ClosedAt             sql.NullString `json:"closed_at"`
	Paused               int64          `json:"paused"`
	PausedBy             string         `json:"paused_by"`
	PausedAt             sql.NullString `json:"paused_at"`
	PausedReason         string         `json:"paused_reason"`
	NeedsAttentionReason sql.NullString `json:"needs_attention_reason"`
	NeedsAttentionAt     sql.NullString `json:"needs_attention_at"`
	NeedsAttentionByKind sql.NullString `json:"needs_attention_by_kind"`
	NeedsAttentionByRef  sql.NullString `json:"needs_attention_by_ref"`
	WakeCreator          int64          `json:"wake_creator"`
	MetadataJson         sql.NullString `json:"metadata_json"`
	ID                   string         `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTask,
		arg.Identifier,
		arg.Scope,
		arg.WorkspaceID,
		arg.ParentTaskID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.MaxAttempts,
		arg.AutoEnqueueOnReady,
		arg.ApprovalPolicy,
		arg.ApprovalState,
		arg.OwnerKind,
		arg.OwnerRef,
		arg.CreatedByKind,
		arg.CreatedByRef,
		arg.OriginKind,
		arg.OriginRef,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClosedAt,
		arg.Paused,
		arg.PausedBy,
		arg.PausedAt,
		arg.PausedReason,
		arg.NeedsAttentionReason,
		arg.NeedsAttentionAt,
		arg.NeedsAttentionByKind,
		arg.NeedsAttentionByRef,
		arg.WakeCreator,
		arg.MetadataJson,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskRun = `-- name: UpdateTaskRun :execrows
UPDATE task_runs
SET task_id = ?1,
    workspace_id = ?2,
    run_kind = ?3,
    loop_run_id = ?4,
    status = ?5,
    attempt = ?6,
    recovery_count = ?7,
    previous_run_id = ?8,
    failure_kind = ?9,
    claimed_by_kind = ?10,
    claimed_by_ref = ?11,
    session_id = ?12,
    origin_kind = ?13,
    origin_ref = ?14,
    idempotency_key = ?15,
    network_spec_json = ?16,
    network_mode = ?17,
    network_channel = ?18,
    network_source = ?19,
    designation_group_id = ?20,
    claim_token = CASE WHEN ?21 IS NOT NULL AND claim_token_hash = ?21 THEN claim_token ELSE NULL END,
    claim_token_hash = ?21,
    lease_until = ?22,
    heartbeat_at = ?23,
    queued_at = ?24,
    claimed_at = ?25,
    started_at = ?26,
    ended_at = ?27,
    tokens_used = ?28,
    error = ?29,
    metadata_json = ?30,
    result_json = ?31,
    review_required = ?32,
    review_request_round = ?33,
    review_policy_snapshot = ?34,
    review_request_id = ?35,
    parent_run_id = ?36,
    review_id = ?37,
    review_round = ?38,
    continuation_reason = ?39,
    missing_work_json = ?40,
    next_round_guidance = ?41,
    network_wake_id = ?42,
    network_target_session_id = ?43,
    network_owner_key = ?44
WHERE id = ?45
`

type UpdateTaskRunParams struct {
	TaskID                 sql.NullString `json:"task_id"`
	WorkspaceID            sql.NullString `json:"workspace_id"`
	RunKind                string         `json:"run_kind"`
	LoopRunID              sql.NullString `json:"loop_run_id"`
	Status                 string         `json:"status"`
	Attempt                int64          `json:"attempt"`
	RecoveryCount          int64          `json:"recovery_count"`
	PreviousRunID          sql.NullString `json:"previous_run_id"`
	FailureKind            string         `json:"failure_kind"`
	ClaimedByKind          sql.NullString `json:"claimed_by_kind"`
	ClaimedByRef           sql.NullString `json:"claimed_by_ref"`
	SessionID              sql.NullString `json:"session_id"`
	OriginKind             string         `json:"origin_kind"`
	OriginRef              string         `json:"origin_ref"`
	IdempotencyKey         sql.NullString `json:"idempotency_key"`
	NetworkSpecJson        string         `json:"network_spec_json"`
	NetworkMode            string         `json:"network_mode"`
	NetworkChannel         sql.NullString `json:"network_channel"`
	NetworkSource          string         `json:"network_source"`
	DesignationGroupID     string         `json:"designation_group_id"`
	ClaimTokenHash         sql.NullString `json:"claim_token_hash"`
	LeaseUntil             sql.NullString `json:"lease_until"`
	HeartbeatAt            sql.NullString `json:"heartbeat_at"`
	QueuedAt               string         `json:"queued_at"`
	ClaimedAt              sql.NullString `json:"claimed_at"`
	StartedAt              sql.NullString `json:"started_at"`
	EndedAt                sql.NullString `json:"ended_at"`
	TokensUsed             int64          `json:"tokens_used"`
	Error                  sql.NullString `json:"error"`
	MetadataJson           sql.NullString `json:"metadata_json"`
	ResultJson             sql.NullString `json:"result_json"`
	ReviewRequired         bool           `json:"review_required"`
	ReviewRequestRound     int64          `json:"review_request_round"`
	ReviewPolicySnapshot   string         `json:"review_policy_snapshot"`
	ReviewRequestID        sql.NullString `json:"review_request_id"`
	ParentRunID            sql.NullString `json:"parent_run_id"`
	ReviewID               sql.NullString `json:"review_id"`
	ReviewRound            int64          `json:"review_round"`
	ContinuationReason     string         `json:"continuation_reason"`
	MissingWorkJson        string         `json:"missing_work_json"`
	NextRoundGuidance      string         `json:"next_round_guidance"`
	NetworkWakeID          sql.NullString `json:"network_wake_id"`
	NetworkTargetSessionID sql.NullString `json:"network_target_session_id"`
	NetworkOwnerKey        sql.NullString `json:"network_owner_key"`
	ID                     string         `json:"id"`
}

func (q *Queries) UpdateTaskRun(ctx context.Context, arg UpdateTaskRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskRun,
		arg.TaskID,
		arg.WorkspaceID,
		arg.RunKind,
		arg.LoopRunID,
		arg.Status,
		arg.Attempt,
		arg.RecoveryCount,
		arg.PreviousRunID,
		arg.FailureKind,
		arg.ClaimedByKind,
		arg.ClaimedByRef,
		arg.SessionID,
		arg.OriginKind,
		arg.OriginRef,
		arg.IdempotencyKey,
		arg.NetworkSpecJson,
		arg.NetworkMode,
		arg.NetworkChannel,
		arg.NetworkSource,
		arg.DesignationGroupID,
		arg.ClaimTokenHash,
		arg.LeaseUntil,
		arg.HeartbeatAt,
		arg.QueuedAt,
		arg.ClaimedAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.TokensUsed,
		arg.Error,
		arg.MetadataJson,
		arg.ResultJson,
		arg.ReviewRequired,
		arg.ReviewRequestRound,
		arg.ReviewPolicySnapshot,
		arg.ReviewRequestID,
		arg.ParentRunID,
		arg.ReviewID,
		arg.ReviewRound,
		arg.ContinuationReason,
		arg.MissingWorkJson,
		arg.NextRoundGuidance,
		arg.NetworkWakeID,
		arg.NetworkTargetSessionID,
		arg.NetworkOwnerKey,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
