// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_state.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const clearTaskCurrentRunProjection = `-- name: ClearTaskCurrentRunProjection :execrows
UPDATE tasks
SET current_run_id = NULL
WHERE id = ?1 AND current_run_id = ?2
`

type ClearTaskCurrentRunProjectionParams struct {
	TaskID string         `json:"task_id"`
	RunID  sql.NullString `json:"run_id"`
}

func (q *Queries) ClearTaskCurrentRunProjection(ctx context.Context, arg ClearTaskCurrentRunProjectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearTaskCurrentRunProjection, arg.TaskID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearTaskNeedsAttention = `-- name: ClearTaskNeedsAttention :execrows
UPDATE tasks
SET needs_attention_reason = NULL,
    needs_attention_at = NULL,
    needs_attention_by_kind = NULL,
    needs_attention_by_ref = NULL,
    updated_at = ?1
WHERE id = ?2 AND needs_attention_at IS NOT NULL
`

type ClearTaskNeedsAttentionParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ClearTaskNeedsAttention(ctx context.Context, arg ClearTaskNeedsAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearTaskNeedsAttention, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countActiveTaskRunClaims = `-- name: CountActiveTaskRunClaims :one
SELECT COUNT(1)
FROM task_runs
WHERE status IN (?1, ?2, ?3)
`

type CountActiveTaskRunClaimsParams struct {
	ClaimedStatus  string `json:"claimed_status"`
	StartingStatus string `json:"starting_status"`
	RunningStatus  string `json:"running_status"`
}

func (q *Queries) CountActiveTaskRunClaims(ctx context.Context, arg CountActiveTaskRunClaimsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTaskRunClaims, arg.ClaimedStatus, arg.StartingStatus, arg.RunningStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllQueuedTaskRuns = `-- name: CountAllQueuedTaskRuns :one
SELECT COUNT(1)
FROM task_runs
WHERE status = ?1
`

func (q *Queries) CountAllQueuedTaskRuns(ctx context.Context, queuedStatus string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllQueuedTaskRuns, queuedStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNeedsAttentionTaskRuns = `-- name: CountNeedsAttentionTaskRuns :one
SELECT COUNT(1)
FROM task_runs
WHERE status = ?1
`

func (q *Queries) CountNeedsAttentionTaskRuns(ctx context.Context, needsAttentionStatus string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNeedsAttentionTaskRuns, needsAttentionStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPausedTasks = `-- name: CountPausedTasks :one
SELECT COUNT(1) FROM tasks WHERE paused = 1
`

func (q *Queries) CountPausedTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPausedTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSchedulerPause = `-- name: GetSchedulerPause :one
SELECT paused, paused_by, paused_at, reason, updated_at
FROM scheduler_pause
WHERE id = 1
`

type GetSchedulerPauseRow struct {
	Paused    int64          `json:"paused"`
	PausedBy  string         `json:"paused_by"`
	PausedAt  sql.NullString `json:"paused_at"`
	Reason    string         `json:"reason"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) GetSchedulerPause(ctx context.Context) (GetSchedulerPauseRow, error) {
	row := q.db.QueryRowContext(ctx, getSchedulerPause)
	var i GetSchedulerPauseRow
	err := row.Scan(
		&i.Paused,
		&i.PausedBy,
		&i.PausedAt,
		&i.Reason,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskCurrentRunProjection = `-- name: GetTaskCurrentRunProjection :one
SELECT current_run_id FROM tasks WHERE id = ?1
`

func (q *Queries) GetTaskCurrentRunProjection(ctx context.Context, id string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTaskCurrentRunProjection, id)
	var current_run_id sql.NullString
	err := row.Scan(&current_run_id)
	return current_run_id, err
}

const getTaskStatus = `-- name: GetTaskStatus :one
SELECT status FROM tasks WHERE id = ?1
`

func (q *Queries) GetTaskStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const pauseTask = `-- name: PauseTask :execrows
UPDATE tasks
SET paused = 1,
    paused_by = ?1,
    paused_at = ?2,
    paused_reason = ?3,
    updated_at = ?4
WHERE id = ?5
`

type PauseTaskParams struct {
	PausedBy     string         `json:"paused_by"`
	PausedAt     sql.NullString `json:"paused_at"`
	PausedReason string         `json:"paused_reason"`
	UpdatedAt    string         `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) PauseTask(ctx context.Context, arg PauseTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pauseTask,
		arg.PausedBy,
		arg.PausedAt,
		arg.PausedReason,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resumeTask = `-- name: ResumeTask :execrows
UPDATE tasks
SET paused = 0,
    paused_by = '',
    paused_at = NULL,
    paused_reason = '',
    updated_at = ?1
WHERE id = ?2
`

type ResumeTaskParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ResumeTask(ctx context.Context, arg ResumeTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resumeTask, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSchedulerPaused = `-- name: SetSchedulerPaused :exec
INSERT INTO scheduler_pause (id, paused, paused_by, paused_at, reason, updated_at)
VALUES (
    1, 1, ?1, ?2,
    ?3, ?4
)
ON CONFLICT(id) DO UPDATE SET
    paused = 1,
    paused_by = excluded.paused_by,
    paused_at = excluded.paused_at,
    reason = excluded.reason,
    updated_at = excluded.updated_at
`

type SetSchedulerPausedParams struct {
	PausedBy  string         `json:"paused_by"`
	PausedAt  sql.NullString `json:"paused_at"`
	Reason    string         `json:"reason"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) SetSchedulerPaused(ctx context.Context, arg SetSchedulerPausedParams) error {
	_, err := q.db.ExecContext(ctx, setSchedulerPaused,
		arg.PausedBy,
		arg.PausedAt,
		arg.Reason,
		arg.UpdatedAt,
	)
	return err
}

const setSchedulerResumed = `-- name: SetSchedulerResumed :exec
INSERT INTO scheduler_pause (id, paused, paused_by, paused_at, reason, updated_at)
VALUES (1, 0, '', NULL, '', ?1)
ON CONFLICT(id) DO UPDATE SET
    paused = 0,
    paused_by = '',
    paused_at = NULL,
    reason = '',
    updated_at = excluded.updated_at
`

func (q *Queries) SetSchedulerResumed(ctx context.Context, updatedAt string) error {
	_, err := q.db.ExecContext(ctx, setSchedulerResumed, updatedAt)
	return err
}

const setTaskCurrentRunProjection = `-- name: SetTaskCurrentRunProjection :execrows
UPDATE tasks
SET current_run_id = ?1
WHERE id = ?2
  AND (current_run_id IS NULL OR current_run_id = '' OR current_run_id = ?1)
`

type SetTaskCurrentRunProjectionParams struct {
	RunID  sql.NullString `json:"run_id"`
	TaskID string         `json:"task_id"`
}

func (q *Queries) SetTaskCurrentRunProjection(ctx context.Context, arg SetTaskCurrentRunProjectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskCurrentRunProjection, arg.RunID, arg.TaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskStatusChokepoint = `-- name: UpdateTaskStatusChokepoint :execrows
UPDATE tasks
SET status = ?1
WHERE id = ?2 AND status = ?3
`

type UpdateTaskStatusChokepointParams struct {
	ToStatus   string `json:"to_status"`
	ID         string `json:"id"`
	FromStatus string `json:"from_status"`
}

func (q *Queries) UpdateTaskStatusChokepoint(ctx context.Context, arg UpdateTaskStatusChokepointParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskStatusChokepoint, arg.ToStatus, arg.ID, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
