// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_deletions.sql

package sqlcgen

import (
	"context"
)

const deleteWorkspaceDeletionIntent = `-- name: DeleteWorkspaceDeletionIntent :execrows
DELETE FROM workspace_deletion_intents
WHERE workspace_id = ?1
`

func (q *Queries) DeleteWorkspaceDeletionIntent(ctx context.Context, workspaceID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkspaceDeletionIntent, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWorkspaceDeletionIntent = `-- name: GetWorkspaceDeletionIntent :one
SELECT
  workspace_id, root_dir, add_dirs, name, default_agent, sandbox_ref,
  created_at, updated_at, requested_at
FROM workspace_deletion_intents
WHERE workspace_id = ?1
`

func (q *Queries) GetWorkspaceDeletionIntent(ctx context.Context, workspaceID string) (WorkspaceDeletionIntent, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceDeletionIntent, workspaceID)
	var i WorkspaceDeletionIntent
	err := row.Scan(
		&i.WorkspaceID,
		&i.RootDir,
		&i.AddDirs,
		&i.Name,
		&i.DefaultAgent,
		&i.SandboxRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestedAt,
	)
	return i, err
}

const insertWorkspaceDeletionIntent = `-- name: InsertWorkspaceDeletionIntent :execrows
INSERT INTO workspace_deletion_intents (
  workspace_id, root_dir, add_dirs, name, default_agent, sandbox_ref,
  created_at, updated_at, requested_at
)
SELECT
  id, root_dir, add_dirs, name, default_agent, sandbox_ref,
  created_at, updated_at, ?1
FROM workspaces
WHERE id = ?2
`

type InsertWorkspaceDeletionIntentParams struct {
	RequestedAt string `json:"requested_at"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) InsertWorkspaceDeletionIntent(ctx context.Context, arg InsertWorkspaceDeletionIntentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertWorkspaceDeletionIntent, arg.RequestedAt, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listWorkspaceDeletionIntents = `-- name: ListWorkspaceDeletionIntents :many
SELECT
  workspace_id, root_dir, add_dirs, name, default_agent, sandbox_ref,
  created_at, updated_at, requested_at
FROM workspace_deletion_intents
ORDER BY requested_at, workspace_id
`

func (q *Queries) ListWorkspaceDeletionIntents(ctx context.Context) ([]WorkspaceDeletionIntent, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceDeletionIntents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceDeletionIntent{}
	for rows.Next() {
		var i WorkspaceDeletionIntent
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.RootDir,
			&i.AddDirs,
			&i.Name,
			&i.DefaultAgent,
			&i.SandboxRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
