// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
)

type MessageEndPatch struct {
	Deny       bool    `json:"deny,omitempty"`
	DenyReason string  `json:"deny_reason,omitempty"`
	Role       *string `json:"role,omitempty"`
	DeltaType  *string `json:"delta_type,omitempty"`
	Text       *string `json:"text,omitempty"`
}

type MessageEndPayload struct {
	Event          HookEvent       `json:"event"`
	Timestamp      time.Time       `json:"timestamp"`
	SessionID      string          `json:"session_id,omitempty"`
	SessionName    string          `json:"session_name,omitempty"`
	SessionType    string          `json:"session_type,omitempty"`
	AgentName      string          `json:"agent_name,omitempty"`
	WorkspaceID    string          `json:"workspace_id,omitempty"`
	Workspace      string          `json:"workspace,omitempty"`
	WorktreeID     string          `json:"worktree_id,omitempty"`
	ACPSessionID   string          `json:"acp_session_id,omitempty"`
	State          string          `json:"state,omitempty"`
	SoulSnapshotID string          `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string          `json:"soul_digest,omitempty"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	TurnID         string          `json:"turn_id,omitempty"`
	MessageID      string          `json:"message_id,omitempty"`
	Role           string          `json:"role,omitempty"`
	DeltaType      string          `json:"delta_type,omitempty"`
	Text           string          `json:"text,omitempty"`
	Raw            json.RawMessage `json:"raw,omitempty"`
}

type MessagePatch struct {
	Deny       bool    `json:"deny,omitempty"`
	DenyReason string  `json:"deny_reason,omitempty"`
	Role       *string `json:"role,omitempty"`
	DeltaType  *string `json:"delta_type,omitempty"`
	Text       *string `json:"text,omitempty"`
}

type MessagePayload struct {
	Event          HookEvent       `json:"event"`
	Timestamp      time.Time       `json:"timestamp"`
	SessionID      string          `json:"session_id,omitempty"`
	SessionName    string          `json:"session_name,omitempty"`
	SessionType    string          `json:"session_type,omitempty"`
	AgentName      string          `json:"agent_name,omitempty"`
	WorkspaceID    string          `json:"workspace_id,omitempty"`
	Workspace      string          `json:"workspace,omitempty"`
	WorktreeID     string          `json:"worktree_id,omitempty"`
	ACPSessionID   string          `json:"acp_session_id,omitempty"`
	State          string          `json:"state,omitempty"`
	SoulSnapshotID string          `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string          `json:"soul_digest,omitempty"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	TurnID         string          `json:"turn_id,omitempty"`
	MessageID      string          `json:"message_id,omitempty"`
	Role           string          `json:"role,omitempty"`
	DeltaType      string          `json:"delta_type,omitempty"`
	Text           string          `json:"text,omitempty"`
	Raw            json.RawMessage `json:"raw,omitempty"`
}

type MessageSender struct {
	ID          string `json:"id,omitempty"`
	Username    string `json:"username,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
}

type MessageStartPatch struct {
	Deny       bool    `json:"deny,omitempty"`
	DenyReason string  `json:"deny_reason,omitempty"`
	Role       *string `json:"role,omitempty"`
	DeltaType  *string `json:"delta_type,omitempty"`
	Text       *string `json:"text,omitempty"`
}

type MessageStartPayload struct {
	Event          HookEvent       `json:"event"`
	Timestamp      time.Time       `json:"timestamp"`
	SessionID      string          `json:"session_id,omitempty"`
	SessionName    string          `json:"session_name,omitempty"`
	SessionType    string          `json:"session_type,omitempty"`
	AgentName      string          `json:"agent_name,omitempty"`
	WorkspaceID    string          `json:"workspace_id,omitempty"`
	Workspace      string          `json:"workspace,omitempty"`
	WorktreeID     string          `json:"worktree_id,omitempty"`
	ACPSessionID   string          `json:"acp_session_id,omitempty"`
	State          string          `json:"state,omitempty"`
	SoulSnapshotID string          `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string          `json:"soul_digest,omitempty"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	TurnID         string          `json:"turn_id,omitempty"`
	MessageID      string          `json:"message_id,omitempty"`
	Role           string          `json:"role,omitempty"`
	DeltaType      string          `json:"delta_type,omitempty"`
	Text           string          `json:"text,omitempty"`
	Raw            json.RawMessage `json:"raw,omitempty"`
}

type MetaField struct {
	Label    string            `json:"label"`
	Value    string            `json:"value"`
	Requires map[string]string `json:"requires,omitempty"`
	Fallback string            `json:"fallback,omitempty"`
}

type Mode string

type ModelCatalogCostPayload struct {
	InputPerMillion      *float64 `json:"input_per_million,omitempty"`
	OutputPerMillion     *float64 `json:"output_per_million,omitempty"`
	CacheReadPerMillion  *float64 `json:"cache_read_per_million,omitempty"`
	CacheWritePerMillion *float64 `json:"cache_write_per_million,omitempty"`
	ReasoningPerMillion  *float64 `json:"reasoning_per_million,omitempty"`
}

type ModelCatalogSourceRefPayload struct {
	SourceID    string `json:"source_id"`
	SourceKind  string `json:"source_kind"`
	Priority    int    `json:"priority"`
	RefreshedAt string `json:"refreshed_at,omitempty"`
	Stale       bool   `json:"stale"`
	LastError   string `json:"last_error,omitempty"`
}

type ModelCatalogSourceStatusPayload struct {
	SourceID     string `json:"source_id"`
	SourceKind   string `json:"source_kind"`
	ProviderID   string `json:"provider_id"`
	Priority     int    `json:"priority"`
	LastRefresh  string `json:"last_refresh,omitempty"`
	NextRefresh  string `json:"next_refresh,omitempty"`
	LastSuccess  string `json:"last_success,omitempty"`
	LastError    string `json:"last_error,omitempty"`
	RefreshState string `json:"refresh_state"`
	RowCount     int    `json:"row_count"`
	Stale        bool   `json:"stale"`
}

type ModelSourceListParams struct {
	ProviderID   string `json:"provider_id,omitempty"`
	Refresh      bool   `json:"refresh,omitempty"`
	IncludeStale bool   `json:"include_stale,omitempty"`
}

type ModelSourceListResponse struct {
	Rows []ModelSourceRow `json:"rows"`
}

type ModelSourceRow struct {
	SourceID               string                   `json:"source_id"`
	ProviderID             string                   `json:"provider_id"`
	ModelID                string                   `json:"model_id"`
	DisplayName            string                   `json:"display_name,omitempty"`
	Priority               int                      `json:"priority,omitempty"`
	Available              *bool                    `json:"available,omitempty"`
	Stale                  bool                     `json:"stale,omitempty"`
	RefreshedAt            time.Time                `json:"refreshed_at"`
	ExpiresAt              time.Time                `json:"expires_at"`
	ContextWindow          *int64                   `json:"context_window,omitempty"`
	MaxInputTokens         *int64                   `json:"max_input_tokens,omitempty"`
	MaxOutputTokens        *int64                   `json:"max_output_tokens,omitempty"`
	SupportsTools          *bool                    `json:"supports_tools,omitempty"`
	SupportsReasoning      *bool                    `json:"supports_reasoning,omitempty"`
	ReasoningEfforts       []Effort                 `json:"reasoning_efforts,omitempty"`
	DefaultReasoningEffort *Effort                  `json:"default_reasoning_effort,omitempty"`
	Cost                   *ModelCatalogCostPayload `json:"cost,omitempty"`
	Deprecated             *bool                    `json:"deprecated,omitempty"`
	Hidden                 *bool                    `json:"hidden,omitempty"`
	Featured               *bool                    `json:"featured,omitempty"`
	ReleaseDate            *string                  `json:"release_date,omitempty"`
	LastError              string                   `json:"last_error,omitempty"`
}

type ModelsListParams struct {
	ProviderID   string `json:"provider_id,omitempty"`
	SourceID     string `json:"source_id,omitempty"`
	Refresh      bool   `json:"refresh,omitempty"`
	IncludeStale bool   `json:"include_stale,omitempty"`
}

type ModelsRefreshParams struct {
	ProviderID string `json:"provider_id,omitempty"`
	SourceID   string `json:"source_id,omitempty"`
	Force      bool   `json:"force,omitempty"`
	RequestID  string `json:"request_id,omitempty"`
}

type ModelsStatusParams struct {
	ProviderID string `json:"provider_id,omitempty"`
}

type NetworkBudgetUsagePayload struct {
	ParticipationStatus ParticipationStatus `json:"participation_status"`
	WakesUsed           int                 `json:"wakes_used"`
	WallTimeUsed        string              `json:"wall_time_used"`
	InputTokensUsed     int64               `json:"input_tokens_used"`
	OutputTokensUsed    int64               `json:"output_tokens_used"`
	ExhaustedReason     string              `json:"exhausted_reason,omitempty"`
	UpdatedAt           time.Time           `json:"updated_at"`
}

type NetworkCapabilityBriefPayload struct {
	ID      string `json:"id"`
	Summary string `json:"summary"`
}

type NetworkChannelPayload struct {
	Channel                    string     `json:"channel"`
	WorkspaceID                string     `json:"workspace_id,omitempty"`
	Purpose                    string     `json:"purpose,omitempty"`
	FanoutPolicy               string     `json:"fanout_policy,omitempty"`
	CoordinatorPeerID          string     `json:"coordinator_peer_id,omitempty"`
	CreatedBy                  string     `json:"created_by,omitempty"`
	CreatedAt                  *time.Time `json:"created_at,omitempty"`
	PeerCount                  int        `json:"peer_count"`
	LocalPeerCount             int        `json:"local_peer_count,omitempty"`
	SessionCount               int        `json:"session_count,omitempty"`
	MessageCount               int        `json:"message_count,omitempty"`
	PresenceCount              int        `json:"presence_count,omitempty"`
	HistoricalParticipantCount int        `json:"historical_participant_count,omitempty"`
	LastActivityAt             *time.Time `json:"last_activity_at,omitempty"`
	LastPresenceAt             *time.Time `json:"last_presence_at,omitempty"`
	LastMessagePreview         string     `json:"last_message_preview,omitempty"`
}

type NetworkChannelsParams struct {
	WorkspaceID string `json:"workspace_id"`
}

type NetworkConversationMessagePayload struct {
	MessageID   string          `json:"message_id"`
	WorkspaceID string          `json:"workspace_id,omitempty"`
	Channel     string          `json:"channel"`
	Surface     string          `json:"surface,omitempty"`
	ThreadID    string          `json:"thread_id,omitempty"`
	DirectID    string          `json:"direct_id,omitempty"`
	Kind        string          `json:"kind"`
	Direction   string          `json:"direction"`
	PeerFrom    string          `json:"peer_from"`
	PeerTo      string          `json:"peer_to,omitempty"`
	Mentions    []string        `json:"mentions,omitempty"`
	DisplayName string          `json:"display_name,omitempty"`
	SessionID   string          `json:"session_id,omitempty"`
	Local       bool            `json:"local,omitempty"`
	WorkID      string          `json:"work_id,omitempty"`
	ReplyTo     string          `json:"reply_to,omitempty"`
	TraceID     string          `json:"trace_id,omitempty"`
	CausationID string          `json:"causation_id,omitempty"`
	Intent      string          `json:"intent,omitempty"`
	Text        string          `json:"text,omitempty"`
	PreviewText string          `json:"preview_text,omitempty"`
	SizeBytes   int64           `json:"size_bytes,omitempty"`
	Body        json.RawMessage `json:"body"`
	Timestamp   time.Time       `json:"timestamp"`
}

type NetworkConversationRef struct {
	Channel     string                     `json:"channel"`
	Surface     NetworkConversationSurface `json:"surface"`
	ThreadID    string                     `json:"thread_id,omitempty"`
	DirectID    string                     `json:"direct_id,omitempty"`
	WorkID      string                     `json:"work_id,omitempty"`
	ReplyTo     string                     `json:"reply_to,omitempty"`
	TraceID     string                     `json:"trace_id,omitempty"`
	CausationID string                     `json:"causation_id,omitempty"`
}
