// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

type AutomationRunFailedPayload struct {
	ProfileID   string `json:"profile_id,omitempty"`
	RunID       string `json:"run_id"`
	JobID       string `json:"job_id,omitempty"`
	TriggerID   string `json:"trigger_id,omitempty"`
	AgentName   string `json:"agent_name,omitempty"`
	WorkspaceID string `json:"workspace_id,omitempty"`
	SessionID   string `json:"session_id,omitempty"`
	Error       string `json:"error,omitempty"`
	Attempt     int    `json:"attempt,omitempty"`
	WillRetry   bool   `json:"will_retry,omitempty"`
}

type AutomationRunsParams struct {
	JobID     string    `json:"job_id,omitempty"`
	TriggerID string    `json:"trigger_id,omitempty"`
	Status    RunStatus `json:"status,omitempty"`
	Limit     int       `json:"limit,omitempty"`
}

type AutomationSchedulePayload struct {
	Mode     string `json:"mode,omitempty"`
	Expr     string `json:"expr,omitempty"`
	Interval string `json:"interval,omitempty"`
	Time     string `json:"time,omitempty"`
}

type AutomationTargetParams struct {
	ID string `json:"id"`
}

type AutomationTriggerCreateParams struct {
	Scope              Scope             `json:"scope"`
	Name               string            `json:"name"`
	TargetKind         TargetKind        `json:"target_kind,omitempty"`
	AgentName          string            `json:"agent_name"`
	WorkspaceID        string            `json:"workspace_id,omitempty"`
	Prompt             string            `json:"prompt"`
	Event              string            `json:"event"`
	Filter             map[string]string `json:"filter,omitempty"`
	LoopTarget         *LoopTarget       `json:"loop_target,omitempty"`
	Enabled            *bool             `json:"enabled,omitempty"`
	Retry              *RetryConfig      `json:"retry,omitempty"`
	FireLimit          *FireLimitConfig  `json:"fire_limit,omitempty"`
	WebhookID          string            `json:"webhook_id,omitempty"`
	EndpointSlug       string            `json:"endpoint_slug,omitempty"`
	WebhookSecretValue string            `json:"webhook_secret_value,omitempty"`
}

type AutomationTriggerFireParams struct {
	Event       string         `json:"event"`
	Scope       Scope          `json:"scope"`
	WorkspaceID string         `json:"workspace_id,omitempty"`
	Payload     map[string]any `json:"payload,omitempty"`
}

type AutomationTriggerPostFirePayload struct {
	ProfileID   string `json:"profile_id,omitempty"`
	TriggerID   string `json:"trigger_id"`
	TriggerName string `json:"trigger_name,omitempty"`
	Event       string `json:"event,omitempty"`
	AgentName   string `json:"agent_name,omitempty"`
	WorkspaceID string `json:"workspace_id,omitempty"`
	RunID       string `json:"run_id,omitempty"`
	SessionID   string `json:"session_id,omitempty"`
}

type AutomationTriggerPreFirePayload struct {
	ProfileID   string         `json:"profile_id,omitempty"`
	TriggerID   string         `json:"trigger_id"`
	TriggerName string         `json:"trigger_name,omitempty"`
	Event       string         `json:"event,omitempty"`
	AgentName   string         `json:"agent_name,omitempty"`
	WorkspaceID string         `json:"workspace_id,omitempty"`
	Prompt      string         `json:"prompt,omitempty"`
	Payload     map[string]any `json:"payload,omitempty"`
	Attempt     int            `json:"attempt,omitempty"`
}

type AutomationTriggerRunsParams struct {
	ID     string    `json:"id"`
	Status RunStatus `json:"status,omitempty"`
	Limit  int       `json:"limit,omitempty"`
}

type AutomationTriggerUpdateParams struct {
	ID                 string            `json:"id"`
	Name               *string           `json:"name,omitempty"`
	Prompt             *string           `json:"prompt,omitempty"`
	Event              *string           `json:"event,omitempty"`
	Filter             map[string]string `json:"filter,omitempty"`
	LoopTarget         *LoopTarget       `json:"loop_target,omitempty"`
	Enabled            *bool             `json:"enabled,omitempty"`
	Retry              *RetryConfig      `json:"retry,omitempty"`
	FireLimit          *FireLimitConfig  `json:"fire_limit,omitempty"`
	WebhookID          *string           `json:"webhook_id,omitempty"`
	EndpointSlug       *string           `json:"endpoint_slug,omitempty"`
	WebhookSecretValue *string           `json:"webhook_secret_value,omitempty"`
}

type AutomationTriggersParams struct {
	Scope       Scope  `json:"scope,omitempty"`
	WorkspaceID string `json:"workspace_id,omitempty"`
	Event       string `json:"event,omitempty"`
	Enabled     *bool  `json:"enabled,omitempty"`
	Query       string `json:"q,omitempty"`
	Cursor      string `json:"cursor,omitempty"`
	Limit       int    `json:"limit,omitempty"`
}

type AutomationTriggersResult struct {
	Triggers []Trigger                `json:"triggers"`
	Page     CountedCursorPagePayload `json:"page"`
}

type AutonomyMatcher struct {
	TaskID               string `json:"task_id,omitempty"`
	RunID                string `json:"run_id,omitempty"`
	LoopRunID            string `json:"loop_run_id,omitempty"`
	LoopName             string `json:"loop_name,omitempty"`
	NodeID               string `json:"node_id,omitempty"`
	WorkflowID           string `json:"workflow_id,omitempty"`
	CoordinatorSessionID string `json:"coordinator_session_id,omitempty"`
	ParentSessionID      string `json:"parent_session_id,omitempty"`
	RootSessionID        string `json:"root_session_id,omitempty"`
	ChildSessionID       string `json:"child_session_id,omitempty"`
	SpawnRole            string `json:"spawn_role,omitempty"`
	ReleaseReason        string `json:"release_reason,omitempty"`
}

type AutonomyObservationPatch struct {
	Labels map[string]string `json:"labels,omitempty"`
}

type BackendKind string

type BackendRef struct {
	Kind                 BackendKind `json:"kind"`
	ExtensionID          string      `json:"extension_id,omitempty"`
	Handler              string      `json:"handler,omitempty"`
	MCPServer            string      `json:"mcp_server,omitempty"`
	MCPTool              string      `json:"mcp_tool,omitempty"`
	NativeName           string      `json:"native_name,omitempty"`
	RequiresCapabilities []string    `json:"requires_capabilities,omitempty"`
}

type Badge string

type BlockKind string

type BlockedReason struct {
	Source           BlockedSource `json:"source"`
	Kind             BlockKind     `json:"kind,omitempty"`
	Reason           string        `json:"reason,omitempty"`
	BlockID          string        `json:"block_id,omitempty"`
	DependsOnTaskIDs []string      `json:"depends_on_task_ids,omitempty"`
}

type BlockedSource string

type CatalogScope string

type CatalogSort string

type Chip struct {
	ID       string            `json:"id"`
	Label    string            `json:"label"`
	Count    *int              `json:"count,omitempty"`
	Requires map[string]string `json:"requires,omitempty"`
	Fallback string            `json:"fallback,omitempty"`
}

type ClarifyAnswer struct {
	Choice   *int   `json:"choice"`
	Text     string `json:"text"`
	Fallback bool   `json:"fallback"`
}
