// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
)

type BridgeInstance struct {
	ID                   string               `json:"id"`
	Scope                BridgeScope          `json:"scope"`
	WorkspaceID          string               `json:"workspace_id,omitempty"`
	Platform             string               `json:"platform"`
	ExtensionName        string               `json:"extension_name"`
	DisplayName          string               `json:"display_name"`
	Source               BridgeInstanceSource `json:"source,omitempty"`
	Enabled              bool                 `json:"enabled"`
	Status               BridgeStatus         `json:"status"`
	DMPolicy             BridgeDMPolicy       `json:"dm_policy,omitempty"`
	RoutingPolicy        RoutingPolicy        `json:"routing_policy"`
	ProviderConfig       json.RawMessage      `json:"provider_config,omitempty"`
	DeliveryDefaults     json.RawMessage      `json:"delivery_defaults,omitempty"`
	NotificationSuppress bool                 `json:"notification_suppress"`
	Degradation          *BridgeDegradation   `json:"degradation,omitempty"`
	CreatedAt            time.Time            `json:"created_at"`
	UpdatedAt            time.Time            `json:"updated_at"`
}

type BridgeInstanceSource string

type BridgeInstanceTargetParams struct {
	BridgeInstanceID string `json:"bridge_instance_id"`
}

type BridgeRuntimePurpose string

type BridgeScope string

type BridgeStatus string

type BridgeStatusCounts struct {
	Disabled     int `json:"disabled"`
	Starting     int `json:"starting"`
	Ready        int `json:"ready"`
	Degraded     int `json:"degraded"`
	AuthRequired int `json:"auth_required"`
	Error        int `json:"error"`
}

type BridgeTargetSnapshot struct {
	CanonicalRoute string           `json:"canonical_route"`
	DisplayName    string           `json:"display_name"`
	TargetType     BridgeTargetType `json:"target_type"`
	Qualifier      string           `json:"qualifier,omitempty"`
	Capabilities   []string         `json:"capabilities,omitempty"`
	LastSeenAt     time.Time        `json:"last_seen_at,omitzero"`
}

type BridgeTargetSnapshotRequest struct {
	BridgeInstanceID string `json:"bridge_instance_id"`
}

type BridgeTargetSnapshotResponse struct {
	Targets []BridgeTargetSnapshot `json:"targets"`
}

type BridgeTargetType string

type BridgeWebhookRegistrationRequest struct {
	BridgeInstanceID string `json:"bridge_instance_id"`
}

type BridgeWebhookRegistrationResponse struct {
	Status      BridgeCheckStatus `json:"status"`
	Remediation string            `json:"remediation"`
}

type BridgesInstancesReportStateParams struct {
	BridgeInstanceID string             `json:"bridge_instance_id"`
	Status           BridgeStatus       `json:"status"`
	Degradation      *BridgeDegradation `json:"degradation,omitempty"`
	ClearDegradation bool               `json:"clear_degradation,omitempty"`
}

type BridgesMessagesIngestResult struct {
	SessionID    string     `json:"session_id"`
	RouteCreated bool       `json:"route_created"`
	RoutingKey   RoutingKey `json:"routing_key"`
}

type CatalogScope string

type CatalogSort string

type ChannelStrategy string

type ClarifyAnswer struct {
	Choice   *int   `json:"choice"`
	Text     string `json:"text"`
	Fallback bool   `json:"fallback"`
}

type ClarifyAskParams struct {
	InvocationID string   `json:"invocation_id"`
	Question     string   `json:"question"`
	Choices      []string `json:"choices,omitempty"`
}

type CompactionMatcher struct {
	Reason   string `json:"compaction_reason,omitempty"`
	Strategy string `json:"compaction_strategy,omitempty"`
}

type ContextBlock struct {
	Kind     string            `json:"kind,omitempty"`
	Text     string            `json:"text,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

type ContextCompactPayload struct {
	Event          HookEvent      `json:"event"`
	Timestamp      time.Time      `json:"timestamp"`
	SessionID      string         `json:"session_id,omitempty"`
	SessionName    string         `json:"session_name,omitempty"`
	SessionType    string         `json:"session_type,omitempty"`
	AgentName      string         `json:"agent_name,omitempty"`
	WorkspaceID    string         `json:"workspace_id,omitempty"`
	Workspace      string         `json:"workspace,omitempty"`
	ACPSessionID   string         `json:"acp_session_id,omitempty"`
	State          string         `json:"state,omitempty"`
	SoulSnapshotID string         `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string         `json:"soul_digest,omitempty"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	TurnID         string         `json:"turn_id,omitempty"`
	Reason         string         `json:"reason,omitempty"`
	Strategy       string         `json:"strategy,omitempty"`
	Summary        string         `json:"summary,omitempty"`
	ContextBlocks  []ContextBlock `json:"context_blocks,omitempty"`
}

type ContextCompactionPatch struct {
	Deny          bool           `json:"deny,omitempty"`
	DenyReason    string         `json:"deny_reason,omitempty"`
	Reason        *string        `json:"reason,omitempty"`
	Strategy      *string        `json:"strategy,omitempty"`
	ContextBlocks []ContextBlock `json:"context_blocks,omitempty"`
}
