// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
)

type NetworkDirectRoomPayload struct {
	WorkspaceID        string     `json:"workspace_id,omitempty"`
	Channel            string     `json:"channel"`
	DirectID           string     `json:"direct_id"`
	SessionA           string     `json:"session_a"`
	SessionB           string     `json:"session_b"`
	OpenedAt           *time.Time `json:"opened_at,omitempty"`
	LastActivityAt     *time.Time `json:"last_activity_at,omitempty"`
	MessageCount       int        `json:"message_count"`
	OpenWorkCount      int        `json:"open_work_count"`
	LastMessagePreview string     `json:"last_message_preview,omitempty"`
}

type NetworkDirectRoomsResponse struct {
	Directs []NetworkDirectRoomPayload `json:"directs"`
	Page    CountedCursorPagePayload   `json:"page"`
}

type NetworkDirectsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Channel     string `json:"channel"`
	Query       string `json:"query,omitempty"`
	PeerID      string `json:"peer_id,omitempty"`
	Sort        string `json:"sort,omitempty"`
	HasWork     *bool  `json:"has_work,omitempty"`
	Limit       int    `json:"limit,omitempty"`
	After       string `json:"after,omitempty"`
}

type NetworkKindMetricPayload struct {
	Kind      string `json:"kind"`
	Sent      int64  `json:"sent"`
	Received  int64  `json:"received"`
	Rejected  int64  `json:"rejected"`
	Delivered int64  `json:"delivered"`
}

type NetworkMatcher struct {
	Channel             string `json:"channel,omitempty"`
	Surface             string `json:"surface,omitempty"`
	Kind                string `json:"kind,omitempty"`
	Direction           string `json:"direction,omitempty"`
	WorkState           string `json:"work_state,omitempty"`
	ParticipationMode   string `json:"participation_mode,omitempty"`
	ParticipationSource string `json:"participation_source,omitempty"`
}

type NetworkMessagePersistedPayload struct {
	Event       HookEvent  `json:"event"`
	Timestamp   time.Time  `json:"timestamp"`
	WorkspaceID string     `json:"workspace_id,omitempty"`
	SessionID   string     `json:"session_id,omitempty"`
	Channel     string     `json:"channel,omitempty"`
	Surface     string     `json:"surface,omitempty"`
	ThreadID    string     `json:"thread_id,omitempty"`
	DirectID    string     `json:"direct_id,omitempty"`
	MessageID   string     `json:"message_id,omitempty"`
	Kind        string     `json:"kind,omitempty"`
	Direction   string     `json:"direction,omitempty"`
	WorkID      string     `json:"work_id,omitempty"`
	WorkState   string     `json:"work_state,omitempty"`
	PeerID      string     `json:"peer_id,omitempty"`
	PeerFrom    string     `json:"peer_from,omitempty"`
	PeerTo      string     `json:"peer_to,omitempty"`
	LastSeenAt  *time.Time `json:"last_seen_at,omitempty"`
	TraceID     string     `json:"trace_id,omitempty"`
	CausationID string     `json:"causation_id,omitempty"`
}

type NetworkObservationPatch struct {
	Labels map[string]string `json:"labels,omitempty"`
}

type NetworkParticipationPreResolvePatch struct {
	Deny       bool     `json:"deny,omitempty"`
	DenyReason string   `json:"deny_reason,omitempty"`
	Request    *Request `json:"request,omitempty"`
}

type NetworkParticipationPreResolvePayload struct {
	WorkspaceID string   `json:"workspace_id"`
	Owner       OwnerRef `json:"owner"`
	Request     *Request `json:"request,omitempty"`
	Source      Source   `json:"source,omitempty"`
	OwnerKey    string   `json:"owner_key,omitempty"`
}

type NetworkParticipationResolvedPatch struct{}

type NetworkParticipationResolvedPayload struct {
	WorkspaceID string   `json:"workspace_id"`
	Owner       OwnerRef `json:"owner"`
	OwnerKey    string   `json:"owner_key,omitempty"`
	Spec        Spec     `json:"resolved_network_participation"`
}

type NetworkPayload struct {
	Event       HookEvent  `json:"event"`
	Timestamp   time.Time  `json:"timestamp"`
	WorkspaceID string     `json:"workspace_id,omitempty"`
	SessionID   string     `json:"session_id,omitempty"`
	Channel     string     `json:"channel,omitempty"`
	Surface     string     `json:"surface,omitempty"`
	ThreadID    string     `json:"thread_id,omitempty"`
	DirectID    string     `json:"direct_id,omitempty"`
	MessageID   string     `json:"message_id,omitempty"`
	Kind        string     `json:"kind,omitempty"`
	Direction   string     `json:"direction,omitempty"`
	WorkID      string     `json:"work_id,omitempty"`
	WorkState   string     `json:"work_state,omitempty"`
	PeerID      string     `json:"peer_id,omitempty"`
	PeerFrom    string     `json:"peer_from,omitempty"`
	PeerTo      string     `json:"peer_to,omitempty"`
	LastSeenAt  *time.Time `json:"last_seen_at,omitempty"`
	TraceID     string     `json:"trace_id,omitempty"`
	CausationID string     `json:"causation_id,omitempty"`
}

type NetworkPeerCardPayload struct {
	PeerID              string                          `json:"peer_id"`
	DisplayName         *string                         `json:"display_name,omitempty"`
	ProfilesSupported   []string                        `json:"profiles_supported"`
	Capabilities        []NetworkCapabilityBriefPayload `json:"capabilities"`
	ArtifactsSupported  []string                        `json:"artifacts_supported"`
	TrustModesSupported []string                        `json:"trust_modes_supported"`
	Ext                 map[string]json.RawMessage      `json:"ext,omitempty"`
}

type NetworkPeerJoinedPayload struct {
	Event       HookEvent  `json:"event"`
	Timestamp   time.Time  `json:"timestamp"`
	WorkspaceID string     `json:"workspace_id,omitempty"`
	SessionID   string     `json:"session_id,omitempty"`
	Channel     string     `json:"channel,omitempty"`
	Surface     string     `json:"surface,omitempty"`
	ThreadID    string     `json:"thread_id,omitempty"`
	DirectID    string     `json:"direct_id,omitempty"`
	MessageID   string     `json:"message_id,omitempty"`
	Kind        string     `json:"kind,omitempty"`
	Direction   string     `json:"direction,omitempty"`
	WorkID      string     `json:"work_id,omitempty"`
	WorkState   string     `json:"work_state,omitempty"`
	PeerID      string     `json:"peer_id,omitempty"`
	PeerFrom    string     `json:"peer_from,omitempty"`
	PeerTo      string     `json:"peer_to,omitempty"`
	LastSeenAt  *time.Time `json:"last_seen_at,omitempty"`
	TraceID     string     `json:"trace_id,omitempty"`
	CausationID string     `json:"causation_id,omitempty"`
}

type NetworkPeerLeftPayload struct {
	Event       HookEvent  `json:"event"`
	Timestamp   time.Time  `json:"timestamp"`
	WorkspaceID string     `json:"workspace_id,omitempty"`
	SessionID   string     `json:"session_id,omitempty"`
	Channel     string     `json:"channel,omitempty"`
	Surface     string     `json:"surface,omitempty"`
	ThreadID    string     `json:"thread_id,omitempty"`
	DirectID    string     `json:"direct_id,omitempty"`
	MessageID   string     `json:"message_id,omitempty"`
	Kind        string     `json:"kind,omitempty"`
	Direction   string     `json:"direction,omitempty"`
	WorkID      string     `json:"work_id,omitempty"`
	WorkState   string     `json:"work_state,omitempty"`
	PeerID      string     `json:"peer_id,omitempty"`
	PeerFrom    string     `json:"peer_from,omitempty"`
	PeerTo      string     `json:"peer_to,omitempty"`
	LastSeenAt  *time.Time `json:"last_seen_at,omitempty"`
	TraceID     string     `json:"trace_id,omitempty"`
	CausationID string     `json:"causation_id,omitempty"`
}

type NetworkPeerPayload struct {
	WorkspaceID   string                 `json:"workspace_id,omitempty"`
	SessionID     *string                `json:"session_id,omitempty"`
	PeerID        string                 `json:"peer_id"`
	DisplayName   string                 `json:"display_name,omitempty"`
	Channel       string                 `json:"channel"`
	Local         bool                   `json:"local"`
	PeerCard      NetworkPeerCardPayload `json:"peer_card"`
	JoinedAt      *time.Time             `json:"joined_at,omitempty"`
	PresenceState string                 `json:"presence_state"`
}

type NetworkPeersParams struct {
	WorkspaceID string `json:"workspace_id"`
	Channel     string `json:"channel,omitempty"`
}

type NetworkSendParams struct {
	WorkspaceID string                     `json:"workspace_id,omitempty"`
	SessionID   string                     `json:"session_id"`
	Channel     string                     `json:"channel"`
	Surface     string                     `json:"surface,omitempty"`
	ThreadID    string                     `json:"thread_id,omitempty"`
	DirectID    string                     `json:"direct_id,omitempty"`
	Kind        string                     `json:"kind"`
	To          string                     `json:"to,omitempty"`
	Mentions    []string                   `json:"mentions,omitempty"`
	Body        json.RawMessage            `json:"body"`
	WorkID      string                     `json:"work_id,omitempty"`
	ReplyTo     string                     `json:"reply_to,omitempty"`
	TraceID     string                     `json:"trace_id,omitempty"`
	CausationID string                     `json:"causation_id,omitempty"`
	ExpiresAt   *int64                     `json:"expires_at,omitempty"`
	ID          string                     `json:"id,omitempty"`
	Ext         map[string]json.RawMessage `json:"ext,omitempty"`
}

type NetworkSendPayload struct {
	ID          string                     `json:"id"`
	WorkspaceID string                     `json:"workspace_id,omitempty"`
	SessionID   string                     `json:"session_id"`
	Channel     string                     `json:"channel"`
	Surface     string                     `json:"surface,omitempty"`
	ThreadID    string                     `json:"thread_id,omitempty"`
	DirectID    string                     `json:"direct_id,omitempty"`
	Kind        string                     `json:"kind"`
	To          string                     `json:"to,omitempty"`
	Mentions    []string                   `json:"mentions,omitempty"`
	WorkID      string                     `json:"work_id,omitempty"`
	ReplyTo     string                     `json:"reply_to,omitempty"`
	TraceID     string                     `json:"trace_id,omitempty"`
	CausationID string                     `json:"causation_id,omitempty"`
	ExpiresAt   *int64                     `json:"expires_at,omitempty"`
	Ext         map[string]json.RawMessage `json:"ext,omitempty"`
}

type NetworkStatusPayload struct {
	Enabled              bool                       `json:"enabled"`
	Status               string                     `json:"status"`
	LocalPeers           int                        `json:"local_peers"`
	Channels             int                        `json:"channels"`
	MessagesSent         int64                      `json:"messages_sent"`
	MessagesReceived     int64                      `json:"messages_received"`
	MessagesRejected     int64                      `json:"messages_rejected"`
	MessagesDelivered    int64                      `json:"messages_delivered"`
	WorkflowTaggedEvents int64                      `json:"workflow_tagged_events"`
	HandoffTaggedEvents  int64                      `json:"handoff_tagged_events"`
	OpenThreads          int64                      `json:"open_threads"`
	OpenDirectRooms      int64                      `json:"open_direct_rooms"`
	OpenWorkItems        int64                      `json:"open_work_items"`
	ConversationMessages int64                      `json:"conversation_messages"`
	WorkTransitions      int64                      `json:"work_transitions"`
	DirectResolves       int64                      `json:"direct_resolves"`
	KindMetrics          []NetworkKindMetricPayload `json:"kind_metrics"`
}

type NetworkThreadMessagesParams struct {
	WorkspaceID string `json:"workspace_id"`
	Channel     string `json:"channel"`
	ThreadID    string `json:"thread_id"`
	Before      string `json:"before,omitempty"`
	After       string `json:"after,omitempty"`
	Kind        string `json:"kind,omitempty"`
	WorkID      string `json:"work_id,omitempty"`
	Limit       int    `json:"limit,omitempty"`
}

type NetworkThreadMessagesResponse struct {
	Messages []NetworkConversationMessagePayload `json:"messages"`
	Page     CursorPagePayload                   `json:"page"`
}

type NetworkThreadOpenedPayload struct {
	Event       HookEvent  `json:"event"`
	Timestamp   time.Time  `json:"timestamp"`
	WorkspaceID string     `json:"workspace_id,omitempty"`
	SessionID   string     `json:"session_id,omitempty"`
	Channel     string     `json:"channel,omitempty"`
	Surface     string     `json:"surface,omitempty"`
	ThreadID    string     `json:"thread_id,omitempty"`
	DirectID    string     `json:"direct_id,omitempty"`
	MessageID   string     `json:"message_id,omitempty"`
	Kind        string     `json:"kind,omitempty"`
	Direction   string     `json:"direction,omitempty"`
	WorkID      string     `json:"work_id,omitempty"`
	WorkState   string     `json:"work_state,omitempty"`
	PeerID      string     `json:"peer_id,omitempty"`
	PeerFrom    string     `json:"peer_from,omitempty"`
	PeerTo      string     `json:"peer_to,omitempty"`
	LastSeenAt  *time.Time `json:"last_seen_at,omitempty"`
	TraceID     string     `json:"trace_id,omitempty"`
	CausationID string     `json:"causation_id,omitempty"`
}

type NetworkThreadSummaryPayload struct {
	WorkspaceID        string                          `json:"workspace_id,omitempty"`
	Channel            string                          `json:"channel"`
	ThreadID           string                          `json:"thread_id"`
	RootMessageID      string                          `json:"root_message_id"`
	Title              string                          `json:"title,omitempty"`
	OpenedByPeerID     string                          `json:"opened_by_peer_id,omitempty"`
	OpenedSessionID    string                          `json:"opened_session_id,omitempty"`
	OpenedAt           *time.Time                      `json:"opened_at,omitempty"`
	LastActivityAt     *time.Time                      `json:"last_activity_at,omitempty"`
	MessageCount       int                             `json:"message_count"`
	ParticipantCount   int                             `json:"participant_count"`
	OpenWorkCount      int                             `json:"open_work_count"`
	CoordinationCost   *NetworkCoordinationCostPayload `json:"coordination_cost,omitempty"`
	LastMessagePreview string                          `json:"last_message_preview,omitempty"`
}
