// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
)

type HookRunOutcome string

type HookSkillSource string

type HookSource uint8

type InboundAction struct {
	ActionID  string `json:"action_id"`
	MessageID string `json:"message_id,omitempty"`
	Value     string `json:"value,omitempty"`
	TriggerID string `json:"trigger_id,omitempty"`
}

type InboundCommand struct {
	Command   string `json:"command"`
	Text      string `json:"text,omitempty"`
	TriggerID string `json:"trigger_id,omitempty"`
}

type InboundEdit struct {
	MessageID         string               `json:"message_id"`
	NewText           string               `json:"new_text"`
	OriginalTimestamp time.Time            `json:"original_timestamp"`
	Operation         InboundEditOperation `json:"operation"`
}

type InboundEditOperation string

type InboundEventFamily string

type InboundMessageEnvelope struct {
	BridgeInstanceID  string                  `json:"bridge_instance_id"`
	Scope             BridgeScope             `json:"scope"`
	WorkspaceID       string                  `json:"workspace_id,omitempty"`
	PeerID            string                  `json:"peer_id,omitempty"`
	ThreadID          string                  `json:"thread_id,omitempty"`
	GroupID           string                  `json:"group_id,omitempty"`
	PlatformMessageID string                  `json:"platform_message_id,omitempty"`
	ReceivedAt        time.Time               `json:"received_at"`
	Sender            MessageSender           `json:"sender"`
	Content           MessageContent          `json:"content,omitzero"`
	Attachments       []MessageAttachment     `json:"attachments,omitempty"`
	EventFamily       InboundEventFamily      `json:"event_family"`
	Command           *InboundCommand         `json:"command,omitempty"`
	Action            *InboundAction          `json:"action,omitempty"`
	Reaction          *InboundReaction        `json:"reaction,omitempty"`
	Edit              *InboundEdit            `json:"edit,omitempty"`
	ReplyToText       string                  `json:"reply_to_text,omitempty"`
	ReplyToAuthorID   string                  `json:"reply_to_author_id,omitempty"`
	ReplyToAuthorName string                  `json:"reply_to_author_name,omitempty"`
	Conversation      *NetworkConversationRef `json:"conversation,omitempty"`
	ProviderMetadata  json.RawMessage         `json:"provider_metadata,omitempty"`
	IdempotencyKey    string                  `json:"idempotency_key"`
}

type InboundReaction struct {
	MessageID string `json:"message_id"`
	Emoji     string `json:"emoji"`
	RawEmoji  string `json:"raw_emoji,omitempty"`
	Added     bool   `json:"added"`
}

type InitializeBridgeBoundSecret struct {
	BindingName string `json:"binding_name"`
	Kind        string `json:"kind"`
	Value       string `json:"value"`
}

type InitializeBridgeManagedInstance struct {
	Instance     BridgeInstance                `json:"instance"`
	BoundSecrets []InitializeBridgeBoundSecret `json:"bound_secrets,omitempty"`
}

type InitializeBridgeRuntime struct {
	RuntimeVersion   string                            `json:"runtime_version"`
	Purpose          BridgeRuntimePurpose              `json:"purpose"`
	Provider         string                            `json:"provider"`
	Platform         string                            `json:"platform"`
	AllowedMethods   []string                          `json:"allowed_methods,omitempty"`
	ManagedInstances []InitializeBridgeManagedInstance `json:"managed_instances,omitempty"`
}

type InitializeCapabilities struct {
	Provides              []string        `json:"provides"`
	GrantedPermissions    []HostAPIMethod `json:"granted_permissions"`
	GrantedResourceKinds  []string        `json:"granted_resource_kinds"`
	GrantedResourceScopes []string        `json:"granted_resource_scopes"`
}

type InitializeExtension struct {
	Name       string `json:"name"`
	Version    string `json:"version"`
	SourceTier string `json:"source_tier"`
}

type InitializeExtensionInfo struct {
	Name       string `json:"name"`
	Version    string `json:"version"`
	SDKName    string `json:"sdk_name,omitempty"`
	SDKVersion string `json:"sdk_version,omitempty"`
}

type InitializeMethods struct {
	DaemonRequests    []string `json:"daemon_requests"`
	ExtensionServices []string `json:"extension_services"`
}

type InitializeRequest struct {
	ProtocolVersion          string                 `json:"protocol_version"`
	SupportedProtocolVersion []string               `json:"supported_protocol_versions"`
	CompozyVersion           string                 `json:"compozy_version"`
	SessionNonce             string                 `json:"session_nonce"`
	Extension                InitializeExtension    `json:"extension"`
	Capabilities             InitializeCapabilities `json:"capabilities"`
	Methods                  InitializeMethods      `json:"methods"`
	Runtime                  InitializeRuntime      `json:"runtime"`
}

type InitializeResponse struct {
	ProtocolVersion      string                  `json:"protocol_version"`
	ExtensionInfo        InitializeExtensionInfo `json:"extension_info"`
	AcceptedCapabilities AcceptedCapabilities    `json:"accepted_capabilities"`
	ImplementedMethods   []string                `json:"implemented_methods"`
	SupportedHookEvents  []string                `json:"supported_hook_events"`
	WatchSourceKinds     []string                `json:"watch_source_kinds,omitempty"`
	Supports             InitializeSupports      `json:"supports"`
}

type InitializeRuntime struct {
	HealthCheckIntervalMS int64                    `json:"health_check_interval_ms"`
	HealthCheckTimeoutMS  int64                    `json:"health_check_timeout_ms"`
	ShutdownTimeoutMS     int64                    `json:"shutdown_timeout_ms"`
	DefaultHookTimeoutMS  int64                    `json:"default_hook_timeout_ms"`
	Bridge                *InitializeBridgeRuntime `json:"bridge,omitempty"`
}

type InitializeSupports struct {
	HealthCheck bool `json:"health_check"`
}

type InputPreSubmitPatch struct {
	Deny          bool           `json:"deny,omitempty"`
	DenyReason    string         `json:"deny_reason,omitempty"`
	Message       *string        `json:"message,omitempty"`
	ContextBlocks []ContextBlock `json:"context_blocks,omitempty"`
}

type InputPreSubmitPayload struct {
	Event          HookEvent      `json:"event"`
	Timestamp      time.Time      `json:"timestamp"`
	SessionID      string         `json:"session_id,omitempty"`
	SessionName    string         `json:"session_name,omitempty"`
	SessionType    string         `json:"session_type,omitempty"`
	AgentName      string         `json:"agent_name,omitempty"`
	WorkspaceID    string         `json:"workspace_id,omitempty"`
	Workspace      string         `json:"workspace,omitempty"`
	ACPSessionID   string         `json:"acp_session_id,omitempty"`
	State          string         `json:"state,omitempty"`
	SoulSnapshotID string         `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string         `json:"soul_digest,omitempty"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	TurnID         string         `json:"turn_id,omitempty"`
	InputClass     string         `json:"input_class,omitempty"`
	Message        string         `json:"message,omitempty"`
	ContextBlocks  []ContextBlock `json:"context_blocks,omitempty"`
}

type IssueSeverity string

const (
	IssueSeverityError   IssueSeverity = "error"
	IssueSeverityWarning IssueSeverity = "warning"
)
