// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
)

type MemoryScope string

type MemoryStoreParams struct {
	Key       string      `json:"key"`
	Content   string      `json:"content"`
	Scope     MemoryScope `json:"scope,omitempty"`
	Workspace string      `json:"workspace,omitempty"`
	Tags      []string    `json:"tags,omitempty"`
}

type MessageAttachment struct {
	ID       string `json:"id,omitempty"`
	Name     string `json:"name,omitempty"`
	MIMEType string `json:"mime_type,omitempty"`
	URL      string `json:"url,omitempty"`
}

type MessageContent struct {
	Text string `json:"text,omitempty"`
}

type MessageDeltaPatch struct {
	Deny       bool    `json:"deny,omitempty"`
	DenyReason string  `json:"deny_reason,omitempty"`
	Role       *string `json:"role,omitempty"`
	DeltaType  *string `json:"delta_type,omitempty"`
	Text       *string `json:"text,omitempty"`
}

type MessageDeltaPayload struct {
	Event          HookEvent       `json:"event"`
	Timestamp      time.Time       `json:"timestamp"`
	ProfileID      string          `json:"profile_id,omitempty"`
	SessionID      string          `json:"session_id,omitempty"`
	SessionName    string          `json:"session_name,omitempty"`
	SessionType    string          `json:"session_type,omitempty"`
	AgentName      string          `json:"agent_name,omitempty"`
	WorkspaceID    string          `json:"workspace_id,omitempty"`
	Workspace      string          `json:"workspace,omitempty"`
	WorktreeID     string          `json:"worktree_id,omitempty"`
	ACPSessionID   string          `json:"acp_session_id,omitempty"`
	State          string          `json:"state,omitempty"`
	SoulSnapshotID string          `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string          `json:"soul_digest,omitempty"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	TurnID         string          `json:"turn_id,omitempty"`
	MessageID      string          `json:"message_id,omitempty"`
	Role           string          `json:"role,omitempty"`
	DeltaType      string          `json:"delta_type,omitempty"`
	Text           string          `json:"text,omitempty"`
	Raw            json.RawMessage `json:"raw,omitempty"`
}

type MessageEndPatch struct {
	Deny       bool    `json:"deny,omitempty"`
	DenyReason string  `json:"deny_reason,omitempty"`
	Role       *string `json:"role,omitempty"`
	DeltaType  *string `json:"delta_type,omitempty"`
	Text       *string `json:"text,omitempty"`
}

type MessageEndPayload struct {
	Event          HookEvent       `json:"event"`
	Timestamp      time.Time       `json:"timestamp"`
	ProfileID      string          `json:"profile_id,omitempty"`
	SessionID      string          `json:"session_id,omitempty"`
	SessionName    string          `json:"session_name,omitempty"`
	SessionType    string          `json:"session_type,omitempty"`
	AgentName      string          `json:"agent_name,omitempty"`
	WorkspaceID    string          `json:"workspace_id,omitempty"`
	Workspace      string          `json:"workspace,omitempty"`
	WorktreeID     string          `json:"worktree_id,omitempty"`
	ACPSessionID   string          `json:"acp_session_id,omitempty"`
	State          string          `json:"state,omitempty"`
	SoulSnapshotID string          `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string          `json:"soul_digest,omitempty"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	TurnID         string          `json:"turn_id,omitempty"`
	MessageID      string          `json:"message_id,omitempty"`
	Role           string          `json:"role,omitempty"`
	DeltaType      string          `json:"delta_type,omitempty"`
	Text           string          `json:"text,omitempty"`
	Raw            json.RawMessage `json:"raw,omitempty"`
}

type MessagePatch struct {
	Deny       bool    `json:"deny,omitempty"`
	DenyReason string  `json:"deny_reason,omitempty"`
	Role       *string `json:"role,omitempty"`
	DeltaType  *string `json:"delta_type,omitempty"`
	Text       *string `json:"text,omitempty"`
}

type MessagePayload struct {
	Event          HookEvent       `json:"event"`
	Timestamp      time.Time       `json:"timestamp"`
	ProfileID      string          `json:"profile_id,omitempty"`
	SessionID      string          `json:"session_id,omitempty"`
	SessionName    string          `json:"session_name,omitempty"`
	SessionType    string          `json:"session_type,omitempty"`
	AgentName      string          `json:"agent_name,omitempty"`
	WorkspaceID    string          `json:"workspace_id,omitempty"`
	Workspace      string          `json:"workspace,omitempty"`
	WorktreeID     string          `json:"worktree_id,omitempty"`
	ACPSessionID   string          `json:"acp_session_id,omitempty"`
	State          string          `json:"state,omitempty"`
	SoulSnapshotID string          `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string          `json:"soul_digest,omitempty"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	TurnID         string          `json:"turn_id,omitempty"`
	MessageID      string          `json:"message_id,omitempty"`
	Role           string          `json:"role,omitempty"`
	DeltaType      string          `json:"delta_type,omitempty"`
	Text           string          `json:"text,omitempty"`
	Raw            json.RawMessage `json:"raw,omitempty"`
}

type MessageSender struct {
	ID          string `json:"id,omitempty"`
	Username    string `json:"username,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
}

type MessageStartPatch struct {
	Deny       bool    `json:"deny,omitempty"`
	DenyReason string  `json:"deny_reason,omitempty"`
	Role       *string `json:"role,omitempty"`
	DeltaType  *string `json:"delta_type,omitempty"`
	Text       *string `json:"text,omitempty"`
}

type MessageStartPayload struct {
	Event          HookEvent       `json:"event"`
	Timestamp      time.Time       `json:"timestamp"`
	ProfileID      string          `json:"profile_id,omitempty"`
	SessionID      string          `json:"session_id,omitempty"`
	SessionName    string          `json:"session_name,omitempty"`
	SessionType    string          `json:"session_type,omitempty"`
	AgentName      string          `json:"agent_name,omitempty"`
	WorkspaceID    string          `json:"workspace_id,omitempty"`
	Workspace      string          `json:"workspace,omitempty"`
	WorktreeID     string          `json:"worktree_id,omitempty"`
	ACPSessionID   string          `json:"acp_session_id,omitempty"`
	State          string          `json:"state,omitempty"`
	SoulSnapshotID string          `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string          `json:"soul_digest,omitempty"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	TurnID         string          `json:"turn_id,omitempty"`
	MessageID      string          `json:"message_id,omitempty"`
	Role           string          `json:"role,omitempty"`
	DeltaType      string          `json:"delta_type,omitempty"`
	Text           string          `json:"text,omitempty"`
	Raw            json.RawMessage `json:"raw,omitempty"`
}

type MetaField struct {
	Label    string            `json:"label"`
	Value    string            `json:"value"`
	Requires map[string]string `json:"requires,omitempty"`
	Fallback string            `json:"fallback,omitempty"`
}

type Mode string

type ModelCatalogCostPayload struct {
	InputPerMillion      *float64 `json:"input_per_million,omitempty"`
	OutputPerMillion     *float64 `json:"output_per_million,omitempty"`
	CacheReadPerMillion  *float64 `json:"cache_read_per_million,omitempty"`
	CacheWritePerMillion *float64 `json:"cache_write_per_million,omitempty"`
	ReasoningPerMillion  *float64 `json:"reasoning_per_million,omitempty"`
}

type ModelCatalogSourceRefPayload struct {
	SourceID    string `json:"source_id"`
	SourceKind  string `json:"source_kind"`
	Priority    int    `json:"priority"`
	RefreshedAt string `json:"refreshed_at,omitempty"`
	Stale       bool   `json:"stale"`
	LastError   string `json:"last_error,omitempty"`
}

type ModelCatalogSourceStatusPayload struct {
	SourceID     string `json:"source_id"`
	SourceKind   string `json:"source_kind"`
	ProviderID   string `json:"provider_id"`
	Priority     int    `json:"priority"`
	LastRefresh  string `json:"last_refresh,omitempty"`
	NextRefresh  string `json:"next_refresh,omitempty"`
	LastSuccess  string `json:"last_success,omitempty"`
	LastError    string `json:"last_error,omitempty"`
	RefreshState string `json:"refresh_state"`
	RowCount     int    `json:"row_count"`
	Stale        bool   `json:"stale"`
}

type ModelSourceListParams struct {
	ProviderID   string `json:"provider_id,omitempty"`
	Refresh      bool   `json:"refresh,omitempty"`
	IncludeStale bool   `json:"include_stale,omitempty"`
}

type ModelSourceListResponse struct {
	Rows []ModelSourceRow `json:"rows"`
}

type ModelSourceOptionDescriptor struct {
	ID             string                   `json:"id"`
	Label          string                   `json:"label,omitempty"`
	Description    string                   `json:"description,omitempty"`
	Category       string                   `json:"category,omitempty"`
	Kind           ModelSourceOptionKind    `json:"kind"`
	CurrentValueID string                   `json:"current_value_id,omitempty"`
	CurrentBool    *bool                    `json:"current_bool,omitempty"`
	Values         []ModelSourceOptionValue `json:"values,omitempty"`
}

type ModelSourceOptionKind string

type ModelSourceOptionSelection struct {
	ID        string `json:"id"`
	ValueID   string `json:"value_id,omitempty"`
	BoolValue *bool  `json:"bool_value,omitempty"`
}

type ModelSourceOptionValue struct {
	ValueID     string `json:"value_id"`
	Label       string `json:"label,omitempty"`
	Description string `json:"description,omitempty"`
	GroupID     string `json:"group_id,omitempty"`
	GroupLabel  string `json:"group_label,omitempty"`
	Order       int    `json:"order,omitempty"`
}
