// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
)

type CallOwnerPayload struct {
	Kind string `json:"kind"`
	ID   string `json:"id"`
}

type CallPayload struct {
	Event            HookEvent `json:"event"`
	Timestamp        time.Time `json:"timestamp"`
	ProfileID        string    `json:"profile_id"`
	Scope            string    `json:"scope"`
	WorkspaceID      string    `json:"workspace_id,omitempty"`
	CallID           string    `json:"call_id,omitempty"`
	MessageID        string    `json:"message_id,omitempty"`
	ParentSessionID  string    `json:"parent_session_id,omitempty"`
	ChildSessionID   string    `json:"child_session_id,omitempty"`
	RootSessionID    string    `json:"root_session_id,omitempty"`
	AgentName        string    `json:"agent_name,omitempty"`
	State            string    `json:"state,omitempty"`
	Verdict          string    `json:"verdict,omitempty"`
	ActorKind        string    `json:"actor_kind,omitempty"`
	ActorID          string    `json:"actor_id,omitempty"`
	Channel          string    `json:"channel,omitempty"`
	ThreadID         string    `json:"thread_id,omitempty"`
	NetworkMessageID string    `json:"network_message_id,omitempty"`
	Delivery         string    `json:"delivery,omitempty"`
	StoppedChildren  int       `json:"stopped_children,omitempty"`
	ClosedCalls      int       `json:"closed_calls,omitempty"`
	PreservedResults int       `json:"preserved_results,omitempty"`
}

type CallProvenancePayload struct {
	ProducedBy string `json:"produced_by,omitempty"`
	SessionID  string `json:"session_id,omitempty"`
	Admitted   string `json:"admitted,omitempty"`
}

type CallResult struct {
	CallID string          `json:"call_id"`
	Result json.RawMessage `json:"result"`
}

type CallTargetParams struct {
	CallID      string `json:"call_id"`
	Scope       string `json:"scope,omitempty"`
	WorkspaceID string `json:"workspace_id,omitempty"`
}

type CallsListParams struct {
	Scope       string   `json:"scope,omitempty"`
	WorkspaceID string   `json:"workspace_id,omitempty"`
	State       []string `json:"state,omitempty"`
	Caller      string   `json:"caller,omitempty"`
	Cursor      string   `json:"cursor,omitempty"`
	Limit       int      `json:"limit,omitempty"`
}

type CallsResponse struct {
	Items      []Call `json:"items"`
	NextCursor string `json:"next_cursor,omitempty"`
}

type CatalogScope string

type CatalogSort string

type ChannelStrategy string

type Chip struct {
	ID       string            `json:"id"`
	Label    string            `json:"label"`
	Count    *int              `json:"count,omitempty"`
	Requires map[string]string `json:"requires,omitempty"`
	Fallback string            `json:"fallback,omitempty"`
}

type ClarifyAnswer struct {
	Choice   *int   `json:"choice"`
	Text     string `json:"text"`
	Fallback bool   `json:"fallback"`
}

type ClarifyAskParams struct {
	InvocationID string   `json:"invocation_id"`
	Question     string   `json:"question"`
	Choices      []string `json:"choices,omitempty"`
}

type ClientID string

type CmdPaletteAction struct {
	Kind string         `json:"kind"`
	Tool string         `json:"tool,omitempty"`
	View string         `json:"view,omitempty"`
	App  string         `json:"app,omitempty"`
	URL  string         `json:"url,omitempty"`
	Args map[string]any `json:"args,omitempty"`
}

type CmdPaletteArgument struct {
	Name        string   `json:"name"`
	Type        string   `json:"type"`
	Placeholder string   `json:"placeholder,omitempty"`
	Required    bool     `json:"required,omitempty"`
	Options     []string `json:"options,omitempty"`
}

type CmdPaletteCommand struct {
	ID              string                     `json:"id"`
	Title           string                     `json:"title"`
	Section         string                     `json:"section,omitempty"`
	Icon            string                     `json:"icon"`
	Profile         string                     `json:"profile,omitempty"`
	Keywords        []string                   `json:"keywords,omitempty"`
	Arguments       []CmdPaletteArgument       `json:"arguments,omitempty"`
	Action          CmdPaletteAction           `json:"action"`
	Destructive     bool                       `json:"destructive,omitempty"`
	Confirmation    *CmdPaletteConfirmation    `json:"confirmation,omitempty"`
	DefaultShortcut string                     `json:"default_shortcut,omitempty"`
	Execution       *CmdPaletteExecutionPolicy `json:"execution,omitempty"`
}

type CmdPaletteConfig struct {
	Commands []CmdPaletteCommand `json:"commands,omitempty"`
	Views    []CmdPaletteView    `json:"views,omitempty"`
}

type CmdPaletteConfirmation struct {
	Title   string `json:"title"`
	Body    string `json:"body,omitempty"`
	Confirm string `json:"confirm"`
}

type CmdPaletteExecutionPolicy struct {
	SingleFlight *bool `json:"single_flight,omitempty"`
	RetrySafe    *bool `json:"retry_safe,omitempty"`
}

type CmdPaletteView struct {
	ID      string                `json:"id"`
	Title   string                `json:"title"`
	Kind    string                `json:"kind"`
	Profile string                `json:"profile,omitempty"`
	Source  *CmdPaletteViewSource `json:"source,omitempty"`
	Program bool                  `json:"program,omitempty"`
}

type CmdPaletteViewSource struct {
	Tool string `json:"tool"`
}

type CommandFlag struct {
	Name       string          `json:"name"`
	Field      string          `json:"field"`
	Type       CommandFlagType `json:"type"`
	Repeatable bool            `json:"repeatable"`
	Required   bool            `json:"required"`
	Nullable   bool            `json:"nullable"`
	Enum       []string        `json:"enum,omitempty"`
	Default    json.RawMessage `json:"default,omitempty"`
	Minimum    *float64        `json:"minimum,omitempty"`
	Maximum    *float64        `json:"maximum,omitempty"`
}

type CommandFlagType string

const (
	CommandFlagTypeString  CommandFlagType = "string"
	CommandFlagTypeBoolean CommandFlagType = "boolean"
	CommandFlagTypeInteger CommandFlagType = "integer"
	CommandFlagTypeNumber  CommandFlagType = "number"
)
