// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

import "time"

type SandboxObservationPatch struct{}

type SandboxPreparePatch struct {
	Deny         bool              `json:"deny,omitempty"`
	DenyReason   string            `json:"deny_reason,omitempty"`
	EnvOverrides map[string]string `json:"env_overrides,omitempty"`
}

type SandboxPreparePayload struct {
	Event               HookEvent             `json:"event"`
	Timestamp           time.Time             `json:"timestamp"`
	SessionID           string                `json:"session_id,omitempty"`
	SessionName         string                `json:"session_name,omitempty"`
	SessionType         string                `json:"session_type,omitempty"`
	AgentName           string                `json:"agent_name,omitempty"`
	WorkspaceID         string                `json:"workspace_id,omitempty"`
	Workspace           string                `json:"workspace,omitempty"`
	WorktreeID          string                `json:"worktree_id,omitempty"`
	ACPSessionID        string                `json:"acp_session_id,omitempty"`
	State               string                `json:"state,omitempty"`
	SoulSnapshotID      string                `json:"soul_snapshot_id,omitempty"`
	SoulDigest          string                `json:"soul_digest,omitempty"`
	CreatedAt           time.Time             `json:"created_at"`
	UpdatedAt           time.Time             `json:"updated_at"`
	SandboxID           string                `json:"sandbox_id,omitempty"`
	Backend             string                `json:"backend,omitempty"`
	Profile             SandboxProfilePayload `json:"profile"`
	LocalRootDir        string                `json:"local_root,omitempty"`
	LocalAdditionalDirs []string              `json:"local_additional_dirs,omitempty"`
	AgentCommand        string                `json:"agent_command,omitempty"`
	AgentEnv            []string              `json:"agent_env,omitempty"`
	Permissions         string                `json:"permissions,omitempty"`
	ResumeACPState      string                `json:"resume_acp_state,omitempty"`
	EnvOverrides        map[string]string     `json:"env_overrides,omitempty"`
	Denied              bool                  `json:"denied,omitempty"`
	DenyReason          string                `json:"deny_reason,omitempty"`
}

type SandboxProfilePayload struct {
	Profile        string            `json:"profile,omitempty"`
	Backend        string            `json:"backend,omitempty"`
	SyncMode       string            `json:"sync_mode,omitempty"`
	Persistence    string            `json:"persistence,omitempty"`
	RuntimeRootDir string            `json:"runtime_root,omitempty"`
	DestroyOnStop  bool              `json:"destroy_on_stop,omitempty"`
	Env            map[string]string `json:"env,omitempty"`
	SecretEnv      map[string]string `json:"secret_env,omitempty"`
}

type SandboxReadyPatch struct{}

type SandboxReadyPayload struct {
	Event                 HookEvent `json:"event"`
	Timestamp             time.Time `json:"timestamp"`
	SessionID             string    `json:"session_id,omitempty"`
	SessionName           string    `json:"session_name,omitempty"`
	SessionType           string    `json:"session_type,omitempty"`
	AgentName             string    `json:"agent_name,omitempty"`
	WorkspaceID           string    `json:"workspace_id,omitempty"`
	Workspace             string    `json:"workspace,omitempty"`
	WorktreeID            string    `json:"worktree_id,omitempty"`
	ACPSessionID          string    `json:"acp_session_id,omitempty"`
	State                 string    `json:"state,omitempty"`
	SoulSnapshotID        string    `json:"soul_snapshot_id,omitempty"`
	SoulDigest            string    `json:"soul_digest,omitempty"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	SandboxID             string    `json:"sandbox_id,omitempty"`
	Backend               string    `json:"backend,omitempty"`
	Profile               string    `json:"profile,omitempty"`
	InstanceID            string    `json:"instance_id,omitempty"`
	RuntimeRootDir        string    `json:"runtime_root,omitempty"`
	RuntimeAdditionalDirs []string  `json:"runtime_additional_dirs,omitempty"`
}

type SandboxStopPatch struct {
	Deny       bool   `json:"deny,omitempty"`
	DenyReason string `json:"deny_reason,omitempty"`
}

type SandboxStopPayload struct {
	Event          HookEvent `json:"event"`
	Timestamp      time.Time `json:"timestamp"`
	SessionID      string    `json:"session_id,omitempty"`
	SessionName    string    `json:"session_name,omitempty"`
	SessionType    string    `json:"session_type,omitempty"`
	AgentName      string    `json:"agent_name,omitempty"`
	WorkspaceID    string    `json:"workspace_id,omitempty"`
	Workspace      string    `json:"workspace,omitempty"`
	WorktreeID     string    `json:"worktree_id,omitempty"`
	ACPSessionID   string    `json:"acp_session_id,omitempty"`
	State          string    `json:"state,omitempty"`
	SoulSnapshotID string    `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string    `json:"soul_digest,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	SandboxID      string    `json:"sandbox_id,omitempty"`
	Backend        string    `json:"backend,omitempty"`
	Profile        string    `json:"profile,omitempty"`
	InstanceID     string    `json:"instance_id,omitempty"`
	RuntimeRootDir string    `json:"runtime_root,omitempty"`
	StopReason     string    `json:"stop_reason,omitempty"`
	WillDestroy    bool      `json:"will_destroy,omitempty"`
	Denied         bool      `json:"denied,omitempty"`
	DenyReason     string    `json:"deny_reason,omitempty"`
}

type SandboxSummary struct {
	SessionID  string `json:"session_id"`
	SandboxID  string `json:"sandbox_id"`
	Backend    string `json:"backend"`
	Profile    string `json:"profile,omitempty"`
	InstanceID string `json:"instance_id,omitempty"`
	State      string `json:"state"`
	SyncState  string `json:"sync_state,omitempty"`
}

type SandboxSyncAfterPatch struct{}

type SandboxSyncAfterPayload struct {
	Event            HookEvent `json:"event"`
	Timestamp        time.Time `json:"timestamp"`
	SessionID        string    `json:"session_id,omitempty"`
	SessionName      string    `json:"session_name,omitempty"`
	SessionType      string    `json:"session_type,omitempty"`
	AgentName        string    `json:"agent_name,omitempty"`
	WorkspaceID      string    `json:"workspace_id,omitempty"`
	Workspace        string    `json:"workspace,omitempty"`
	WorktreeID       string    `json:"worktree_id,omitempty"`
	ACPSessionID     string    `json:"acp_session_id,omitempty"`
	State            string    `json:"state,omitempty"`
	SoulSnapshotID   string    `json:"soul_snapshot_id,omitempty"`
	SoulDigest       string    `json:"soul_digest,omitempty"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	SandboxID        string    `json:"sandbox_id,omitempty"`
	Backend          string    `json:"backend,omitempty"`
	Profile          string    `json:"profile,omitempty"`
	InstanceID       string    `json:"instance_id,omitempty"`
	RuntimeRootDir   string    `json:"runtime_root,omitempty"`
	Direction        string    `json:"direction,omitempty"`
	Reason           string    `json:"reason,omitempty"`
	FilesSynced      int       `json:"files_synced,omitempty"`
	BytesTransferred int64     `json:"bytes_transferred,omitempty"`
	DurationMS       int64     `json:"duration_ms,omitempty"`
	Errors           []string  `json:"errors,omitempty"`
}

type SandboxSyncBeforePatch struct {
	Deny            bool     `json:"deny,omitempty"`
	DenyReason      string   `json:"deny_reason,omitempty"`
	ExcludePatterns []string `json:"exclude_patterns,omitempty"`
}

type SandboxSyncBeforePayload struct {
	Event           HookEvent `json:"event"`
	Timestamp       time.Time `json:"timestamp"`
	SessionID       string    `json:"session_id,omitempty"`
	SessionName     string    `json:"session_name,omitempty"`
	SessionType     string    `json:"session_type,omitempty"`
	AgentName       string    `json:"agent_name,omitempty"`
	WorkspaceID     string    `json:"workspace_id,omitempty"`
	Workspace       string    `json:"workspace,omitempty"`
	WorktreeID      string    `json:"worktree_id,omitempty"`
	ACPSessionID    string    `json:"acp_session_id,omitempty"`
	State           string    `json:"state,omitempty"`
	SoulSnapshotID  string    `json:"soul_snapshot_id,omitempty"`
	SoulDigest      string    `json:"soul_digest,omitempty"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	SandboxID       string    `json:"sandbox_id,omitempty"`
	Backend         string    `json:"backend,omitempty"`
	Profile         string    `json:"profile,omitempty"`
	InstanceID      string    `json:"instance_id,omitempty"`
	RuntimeRootDir  string    `json:"runtime_root,omitempty"`
	Direction       string    `json:"direction,omitempty"`
	Reason          string    `json:"reason,omitempty"`
	ExcludePatterns []string  `json:"exclude_patterns,omitempty"`
	Denied          bool      `json:"denied,omitempty"`
	DenyReason      string    `json:"deny_reason,omitempty"`
}

type ScheduleMode string

type ScheduleSpec struct {
	Mode                ScheduleMode           `json:"mode"`
	Expr                string                 `json:"expr,omitempty"`
	Interval            string                 `json:"interval,omitempty"`
	Time                string                 `json:"time,omitempty"`
	CatchUpPolicy       SchedulerCatchUpPolicy `json:"catch_up_policy,omitempty"`
	MisfireGraceSeconds int                    `json:"misfire_grace_seconds,omitempty"`
}

type SchedulerCatchUpPolicy string

type Scope string

type SessionActivityHealth struct {
	SessionID          string     `json:"session_id"`
	TurnID             string     `json:"turn_id,omitempty"`
	TurnSource         string     `json:"turn_source,omitempty"`
	TurnStartedAt      *time.Time `json:"turn_started_at,omitempty"`
	LastActivityAt     *time.Time `json:"last_activity_at,omitempty"`
	LastActivityKind   string     `json:"last_activity_kind,omitempty"`
	LastActivityDetail string     `json:"last_activity_detail,omitempty"`
	CurrentTool        string     `json:"current_tool,omitempty"`
	ToolCallID         string     `json:"tool_call_id,omitempty"`
	LastProgressAt     *time.Time `json:"last_progress_at,omitempty"`
	IterationCurrent   int        `json:"iteration_current,omitempty"`
	IterationMax       int        `json:"iteration_max,omitempty"`
	IdleSeconds        int64      `json:"idle_seconds,omitempty"`
	ElapsedSeconds     int64      `json:"elapsed_seconds,omitempty"`
	Status             string     `json:"status"`
	StallState         string     `json:"stall_state,omitempty"`
	StallReason        string     `json:"stall_reason,omitempty"`
}

type SessionConfigOptionPayload struct {
	ID          string                            `json:"id"`
	Label       string                            `json:"label,omitempty"`
	Description string                            `json:"description,omitempty"`
	Kind        string                            `json:"kind"`
	Current     string                            `json:"current,omitempty"`
	Values      []SessionConfigOptionValuePayload `json:"values,omitempty"`
}

type SessionConfigOptionValuePayload struct {
	Value       string `json:"value"`
	Label       string `json:"label,omitempty"`
	Description string `json:"description,omitempty"`
}

type SessionContext struct {
	SessionID      string    `json:"session_id,omitempty"`
	SessionName    string    `json:"session_name,omitempty"`
	SessionType    string    `json:"session_type,omitempty"`
	AgentName      string    `json:"agent_name,omitempty"`
	WorkspaceID    string    `json:"workspace_id,omitempty"`
	Workspace      string    `json:"workspace,omitempty"`
	WorktreeID     string    `json:"worktree_id,omitempty"`
	ACPSessionID   string    `json:"acp_session_id,omitempty"`
	State          string    `json:"state,omitempty"`
	SoulSnapshotID string    `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string    `json:"soul_digest,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type SessionCreatePatch struct {
	Deny        bool    `json:"deny,omitempty"`
	DenyReason  string  `json:"deny_reason,omitempty"`
	SessionName *string `json:"session_name,omitempty"`
	SessionType *string `json:"session_type,omitempty"`
	AgentName   *string `json:"agent_name,omitempty"`
	WorkspaceID *string `json:"workspace_id,omitempty"`
	Workspace   *string `json:"workspace,omitempty"`
}

type SessionCreateResult struct {
	SessionID string `json:"session_id"`
}

type SessionEvent struct {
	Type      string    `json:"type"`
	Timestamp time.Time `json:"timestamp"`
	Data      any       `json:"data,omitempty"`
}
