// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
)

type CoordinatorObservationPatch struct {
	Labels map[string]string `json:"labels,omitempty"`
}

type CoordinatorPreSpawnPayload struct {
	Event                        HookEvent `json:"event"`
	Timestamp                    time.Time `json:"timestamp"`
	ProfileID                    string    `json:"profile_id,omitempty"`
	WorkspaceID                  string    `json:"workspace_id,omitempty"`
	Workspace                    string    `json:"workspace,omitempty"`
	AgentName                    string    `json:"agent_name,omitempty"`
	CoordinatorSessionID         string    `json:"coordinator_session_id,omitempty"`
	TaskID                       string    `json:"task_id,omitempty"`
	RunID                        string    `json:"run_id,omitempty"`
	WorkflowID                   string    `json:"workflow_id,omitempty"`
	ResolvedNetworkParticipation *Spec     `json:"resolved_network_participation,omitempty"`
	Provider                     string    `json:"provider,omitempty"`
	Model                        string    `json:"model,omitempty"`
	Reason                       string    `json:"reason,omitempty"`
	Denied                       bool      `json:"denied,omitempty"`
	DenyReason                   string    `json:"deny_reason,omitempty"`
}

type CoordinatorSpawnPatch struct {
	Deny       bool    `json:"deny,omitempty"`
	DenyReason string  `json:"deny_reason,omitempty"`
	AgentName  *string `json:"agent_name,omitempty"`
	Provider   *string `json:"provider,omitempty"`
	Model      *string `json:"model,omitempty"`
}

type CoordinatorSpawnedPayload struct {
	Event                        HookEvent `json:"event"`
	Timestamp                    time.Time `json:"timestamp"`
	ProfileID                    string    `json:"profile_id,omitempty"`
	WorkspaceID                  string    `json:"workspace_id,omitempty"`
	Workspace                    string    `json:"workspace,omitempty"`
	AgentName                    string    `json:"agent_name,omitempty"`
	CoordinatorSessionID         string    `json:"coordinator_session_id,omitempty"`
	TaskID                       string    `json:"task_id,omitempty"`
	RunID                        string    `json:"run_id,omitempty"`
	WorkflowID                   string    `json:"workflow_id,omitempty"`
	ResolvedNetworkParticipation *Spec     `json:"resolved_network_participation,omitempty"`
	Provider                     string    `json:"provider,omitempty"`
	Model                        string    `json:"model,omitempty"`
	DecisionKind                 string    `json:"decision_kind,omitempty"`
	Decision                     string    `json:"decision,omitempty"`
	StopReason                   string    `json:"stop_reason,omitempty"`
	Error                        string    `json:"error,omitempty"`
}

type CoordinatorStoppedPayload struct {
	Event                        HookEvent `json:"event"`
	Timestamp                    time.Time `json:"timestamp"`
	ProfileID                    string    `json:"profile_id,omitempty"`
	WorkspaceID                  string    `json:"workspace_id,omitempty"`
	Workspace                    string    `json:"workspace,omitempty"`
	AgentName                    string    `json:"agent_name,omitempty"`
	CoordinatorSessionID         string    `json:"coordinator_session_id,omitempty"`
	TaskID                       string    `json:"task_id,omitempty"`
	RunID                        string    `json:"run_id,omitempty"`
	WorkflowID                   string    `json:"workflow_id,omitempty"`
	ResolvedNetworkParticipation *Spec     `json:"resolved_network_participation,omitempty"`
	Provider                     string    `json:"provider,omitempty"`
	Model                        string    `json:"model,omitempty"`
	DecisionKind                 string    `json:"decision_kind,omitempty"`
	Decision                     string    `json:"decision,omitempty"`
	StopReason                   string    `json:"stop_reason,omitempty"`
	Error                        string    `json:"error,omitempty"`
}

type CopyEffect struct {
	Content string `json:"content"`
}

type CostSource string

type CostStatus string

type CountedCursorPagePayload struct {
	NextCursor string `json:"next_cursor,omitempty"`
	HasMore    bool   `json:"has_more"`
	Total      int    `json:"total"`
	Limit      int    `json:"limit"`
}

type CursorPagePayload struct {
	NextCursor string `json:"next_cursor,omitempty"`
	HasMore    bool   `json:"has_more"`
	Limit      int    `json:"limit"`
}

type DeliveryAck struct {
	DeliveryID             string               `json:"delivery_id"`
	Seq                    int64                `json:"seq"`
	RemoteMessageID        string               `json:"remote_message_id,omitempty"`
	ReplaceRemoteMessageID string               `json:"replace_remote_message_id,omitempty"`
	Outcome                DeliveryAckOutcome   `json:"outcome,omitempty"`
	Error                  *DeliveryErrorDetail `json:"error,omitempty"`
}

type DeliveryAckOutcome string

type DeliveryErrorDetail struct {
	Message string `json:"message"`
}

type DeliveryEvent struct {
	DeliveryID       string                    `json:"delivery_id"`
	BridgeInstanceID string                    `json:"bridge_instance_id"`
	RoutingKey       RoutingKey                `json:"routing_key"`
	DeliveryTarget   DeliveryTarget            `json:"delivery_target"`
	Seq              int64                     `json:"seq"`
	EventType        DeliveryEventType         `json:"event_type"`
	Content          MessageContent            `json:"content"`
	Final            bool                      `json:"final"`
	Operation        DeliveryOperation         `json:"operation,omitempty"`
	Reference        *DeliveryMessageReference `json:"reference,omitempty"`
	Error            *DeliveryErrorDetail      `json:"error,omitempty"`
	Resume           *DeliveryResumeState      `json:"resume,omitempty"`
	Progress         *ToolProgress             `json:"progress,omitempty"`
	ProviderMetadata json.RawMessage           `json:"provider_metadata,omitempty"`
}

type DeliveryEventType string

type DeliveryMessageReference struct {
	DeliveryID      string `json:"delivery_id,omitempty"`
	RemoteMessageID string `json:"remote_message_id,omitempty"`
}

type DeliveryMode string

type DeliveryOperation string

type DeliveryRequest struct {
	Event    DeliveryEvent     `json:"event"`
	Snapshot *DeliverySnapshot `json:"snapshot,omitempty"`
}

type DeliveryResumeState struct {
	LatestEventType DeliveryEventType `json:"latest_event_type"`
}

type DeliverySnapshot struct {
	DeliveryID             string                    `json:"delivery_id"`
	SessionID              string                    `json:"session_id"`
	TurnID                 string                    `json:"turn_id"`
	BridgeInstanceID       string                    `json:"bridge_instance_id"`
	RoutingKey             RoutingKey                `json:"routing_key"`
	DeliveryTarget         DeliveryTarget            `json:"delivery_target"`
	LatestSeq              int64                     `json:"latest_seq"`
	LatestEventType        DeliveryEventType         `json:"latest_event_type"`
	CurrentContent         MessageContent            `json:"current_content"`
	Operation              DeliveryOperation         `json:"operation,omitempty"`
	Reference              *DeliveryMessageReference `json:"reference,omitempty"`
	ProviderMetadata       json.RawMessage           `json:"provider_metadata,omitempty"`
	LastSentSeq            int64                     `json:"last_sent_seq,omitempty"`
	LastAckedSeq           int64                     `json:"last_acked_seq,omitempty"`
	RemoteMessageID        string                    `json:"remote_message_id,omitempty"`
	ReplaceRemoteMessageID string                    `json:"replace_remote_message_id,omitempty"`
	Final                  bool                      `json:"final"`
	Error                  string                    `json:"error,omitempty"`
	UpdatedAt              time.Time                 `json:"updated_at"`
}

type DeliveryTarget struct {
	BridgeInstanceID string       `json:"bridge_instance_id"`
	PeerID           string       `json:"peer_id,omitempty"`
	ThreadID         string       `json:"thread_id,omitempty"`
	GroupID          string       `json:"group_id,omitempty"`
	Mode             DeliveryMode `json:"mode,omitempty"`
}

type DependencyKind string

type DescribeHookEvent struct {
	Event   HookEvent `json:"event"`
	Profile string    `json:"profile,omitempty"`
}
