// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
)

type ModelSourceListResponse struct {
	Rows []ModelSourceRow `json:"rows"`
}

type ModelSourceRow struct {
	SourceID               string                   `json:"source_id"`
	ProviderID             string                   `json:"provider_id"`
	ModelID                string                   `json:"model_id"`
	DisplayName            string                   `json:"display_name,omitempty"`
	Priority               int                      `json:"priority,omitempty"`
	Available              *bool                    `json:"available,omitempty"`
	Stale                  bool                     `json:"stale,omitempty"`
	RefreshedAt            time.Time                `json:"refreshed_at"`
	ExpiresAt              time.Time                `json:"expires_at"`
	ContextWindow          *int64                   `json:"context_window,omitempty"`
	MaxInputTokens         *int64                   `json:"max_input_tokens,omitempty"`
	MaxOutputTokens        *int64                   `json:"max_output_tokens,omitempty"`
	SupportsTools          *bool                    `json:"supports_tools,omitempty"`
	SupportsReasoning      *bool                    `json:"supports_reasoning,omitempty"`
	ReasoningEfforts       []Effort                 `json:"reasoning_efforts,omitempty"`
	DefaultReasoningEffort *Effort                  `json:"default_reasoning_effort,omitempty"`
	Cost                   *ModelCatalogCostPayload `json:"cost,omitempty"`
	Deprecated             *bool                    `json:"deprecated,omitempty"`
	Hidden                 *bool                    `json:"hidden,omitempty"`
	Featured               *bool                    `json:"featured,omitempty"`
	ReleaseDate            *string                  `json:"release_date,omitempty"`
	LastError              string                   `json:"last_error,omitempty"`
}

type ModelsListParams struct {
	ProviderID   string `json:"provider_id,omitempty"`
	SourceID     string `json:"source_id,omitempty"`
	Refresh      bool   `json:"refresh,omitempty"`
	IncludeStale bool   `json:"include_stale,omitempty"`
}

type ModelsRefreshParams struct {
	ProviderID string `json:"provider_id,omitempty"`
	SourceID   string `json:"source_id,omitempty"`
	Force      bool   `json:"force,omitempty"`
	RequestID  string `json:"request_id,omitempty"`
}

type ModelsStatusParams struct {
	ProviderID string `json:"provider_id,omitempty"`
}

type NetworkBudgetUsagePayload struct {
	ParticipationStatus ParticipationStatus `json:"participation_status"`
	WakesUsed           int                 `json:"wakes_used"`
	WallTimeUsed        string              `json:"wall_time_used"`
	InputTokensUsed     int64               `json:"input_tokens_used"`
	OutputTokensUsed    int64               `json:"output_tokens_used"`
	ExhaustedReason     string              `json:"exhausted_reason,omitempty"`
	UpdatedAt           time.Time           `json:"updated_at"`
}

type NetworkCapabilityBriefPayload struct {
	ID      string `json:"id"`
	Summary string `json:"summary"`
}

type NetworkChannelPayload struct {
	Channel                    string     `json:"channel"`
	WorkspaceID                string     `json:"workspace_id,omitempty"`
	Purpose                    string     `json:"purpose,omitempty"`
	FanoutPolicy               string     `json:"fanout_policy,omitempty"`
	CoordinatorPeerID          string     `json:"coordinator_peer_id,omitempty"`
	CreatedBy                  string     `json:"created_by,omitempty"`
	CreatedAt                  *time.Time `json:"created_at,omitempty"`
	PeerCount                  int        `json:"peer_count"`
	LocalPeerCount             int        `json:"local_peer_count,omitempty"`
	SessionCount               int        `json:"session_count,omitempty"`
	MessageCount               int        `json:"message_count,omitempty"`
	PresenceCount              int        `json:"presence_count,omitempty"`
	HistoricalParticipantCount int        `json:"historical_participant_count,omitempty"`
	LastActivityAt             *time.Time `json:"last_activity_at,omitempty"`
	LastPresenceAt             *time.Time `json:"last_presence_at,omitempty"`
	LastMessagePreview         string     `json:"last_message_preview,omitempty"`
}

type NetworkChannelsParams struct {
	WorkspaceID string `json:"workspace_id"`
}

type NetworkConversationMessagePayload struct {
	MessageID   string          `json:"message_id"`
	WorkspaceID string          `json:"workspace_id,omitempty"`
	Channel     string          `json:"channel"`
	Surface     string          `json:"surface,omitempty"`
	ThreadID    string          `json:"thread_id,omitempty"`
	DirectID    string          `json:"direct_id,omitempty"`
	Kind        string          `json:"kind"`
	Direction   string          `json:"direction"`
	PeerFrom    string          `json:"peer_from"`
	PeerTo      string          `json:"peer_to,omitempty"`
	Mentions    []string        `json:"mentions,omitempty"`
	DisplayName string          `json:"display_name,omitempty"`
	SessionID   string          `json:"session_id,omitempty"`
	Local       bool            `json:"local,omitempty"`
	WorkID      string          `json:"work_id,omitempty"`
	ReplyTo     string          `json:"reply_to,omitempty"`
	TraceID     string          `json:"trace_id,omitempty"`
	CausationID string          `json:"causation_id,omitempty"`
	Intent      string          `json:"intent,omitempty"`
	Text        string          `json:"text,omitempty"`
	PreviewText string          `json:"preview_text,omitempty"`
	SizeBytes   int64           `json:"size_bytes,omitempty"`
	Body        json.RawMessage `json:"body"`
	Timestamp   time.Time       `json:"timestamp"`
}

type NetworkConversationRef struct {
	Channel     string                     `json:"channel"`
	Surface     NetworkConversationSurface `json:"surface"`
	ThreadID    string                     `json:"thread_id,omitempty"`
	DirectID    string                     `json:"direct_id,omitempty"`
	WorkID      string                     `json:"work_id,omitempty"`
	ReplyTo     string                     `json:"reply_to,omitempty"`
	TraceID     string                     `json:"trace_id,omitempty"`
	CausationID string                     `json:"causation_id,omitempty"`
}

type NetworkConversationSurface string

type NetworkCoordinationCostPayload struct {
	DeliveredCount        int64 `json:"delivered_count,omitempty"`
	PromptSizeBytes       int64 `json:"prompt_size_bytes,omitempty"`
	EstimatedPromptTokens int64 `json:"estimated_prompt_tokens,omitempty"`
}

type NetworkDirectMessagesParams struct {
	WorkspaceID string `json:"workspace_id"`
	Channel     string `json:"channel"`
	DirectID    string `json:"direct_id"`
	Before      string `json:"before,omitempty"`
	After       string `json:"after,omitempty"`
	Kind        string `json:"kind,omitempty"`
	WorkID      string `json:"work_id,omitempty"`
	Limit       int    `json:"limit,omitempty"`
}

type NetworkDirectResolveParams struct {
	WorkspaceID string `json:"workspace_id"`
	Channel     string `json:"channel"`
	SessionID   string `json:"session_id"`
	PeerID      string `json:"peer_id"`
}

type NetworkDirectRoomMessagesResponse struct {
	Messages []NetworkConversationMessagePayload `json:"messages"`
	Page     CursorPagePayload                   `json:"page"`
}

type NetworkDirectRoomOpenedPayload struct {
	Event       HookEvent  `json:"event"`
	Timestamp   time.Time  `json:"timestamp"`
	WorkspaceID string     `json:"workspace_id,omitempty"`
	SessionID   string     `json:"session_id,omitempty"`
	Channel     string     `json:"channel,omitempty"`
	Surface     string     `json:"surface,omitempty"`
	ThreadID    string     `json:"thread_id,omitempty"`
	DirectID    string     `json:"direct_id,omitempty"`
	MessageID   string     `json:"message_id,omitempty"`
	Kind        string     `json:"kind,omitempty"`
	Direction   string     `json:"direction,omitempty"`
	WorkID      string     `json:"work_id,omitempty"`
	WorkState   string     `json:"work_state,omitempty"`
	PeerID      string     `json:"peer_id,omitempty"`
	PeerFrom    string     `json:"peer_from,omitempty"`
	PeerTo      string     `json:"peer_to,omitempty"`
	LastSeenAt  *time.Time `json:"last_seen_at,omitempty"`
	TraceID     string     `json:"trace_id,omitempty"`
	CausationID string     `json:"causation_id,omitempty"`
}

type NetworkDirectRoomPayload struct {
	WorkspaceID        string     `json:"workspace_id,omitempty"`
	Channel            string     `json:"channel"`
	DirectID           string     `json:"direct_id"`
	SessionA           string     `json:"session_a"`
	SessionB           string     `json:"session_b"`
	OpenedAt           *time.Time `json:"opened_at,omitempty"`
	LastActivityAt     *time.Time `json:"last_activity_at,omitempty"`
	MessageCount       int        `json:"message_count"`
	OpenWorkCount      int        `json:"open_work_count"`
	LastMessagePreview string     `json:"last_message_preview,omitempty"`
}

type NetworkDirectRoomsResponse struct {
	Directs []NetworkDirectRoomPayload `json:"directs"`
	Page    CountedCursorPagePayload   `json:"page"`
}

type NetworkDirectsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Channel     string `json:"channel"`
	Query       string `json:"query,omitempty"`
	PeerID      string `json:"peer_id,omitempty"`
	Sort        string `json:"sort,omitempty"`
	HasWork     *bool  `json:"has_work,omitempty"`
	Limit       int    `json:"limit,omitempty"`
	After       string `json:"after,omitempty"`
}

type NetworkKindMetricPayload struct {
	Kind      string `json:"kind"`
	Sent      int64  `json:"sent"`
	Received  int64  `json:"received"`
	Rejected  int64  `json:"rejected"`
	Delivered int64  `json:"delivered"`
}

type NetworkMatcher struct {
	Channel             string `json:"channel,omitempty"`
	Surface             string `json:"surface,omitempty"`
	Kind                string `json:"kind,omitempty"`
	Direction           string `json:"direction,omitempty"`
	WorkState           string `json:"work_state,omitempty"`
	ParticipationMode   string `json:"participation_mode,omitempty"`
	ParticipationSource string `json:"participation_source,omitempty"`
}

type NetworkMessagePersistedPayload struct {
	Event       HookEvent  `json:"event"`
	Timestamp   time.Time  `json:"timestamp"`
	WorkspaceID string     `json:"workspace_id,omitempty"`
	SessionID   string     `json:"session_id,omitempty"`
	Channel     string     `json:"channel,omitempty"`
	Surface     string     `json:"surface,omitempty"`
	ThreadID    string     `json:"thread_id,omitempty"`
	DirectID    string     `json:"direct_id,omitempty"`
	MessageID   string     `json:"message_id,omitempty"`
	Kind        string     `json:"kind,omitempty"`
	Direction   string     `json:"direction,omitempty"`
	WorkID      string     `json:"work_id,omitempty"`
	WorkState   string     `json:"work_state,omitempty"`
	PeerID      string     `json:"peer_id,omitempty"`
	PeerFrom    string     `json:"peer_from,omitempty"`
	PeerTo      string     `json:"peer_to,omitempty"`
	LastSeenAt  *time.Time `json:"last_seen_at,omitempty"`
	TraceID     string     `json:"trace_id,omitempty"`
	CausationID string     `json:"causation_id,omitempty"`
}

type NetworkObservationPatch struct {
	Labels map[string]string `json:"labels,omitempty"`
}
