import {
  Activity,
  AppWindow,
  ArrowRightLeft,
  Award,
  BadgeCheck,
  Bell,
  Book,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Clock,
  Compass,
  Database,
  FileCode,
  FileText,
  FlaskConical,
  Folder,
  FolderTree,
  Gauge,
  Key,
  Layers,
  LifeBuoy,
  List,
  Mail,
  MessageSquare,
  Network,
  Package,
  Play,
  Plug,
  Puzzle,
  Repeat,
  Rocket,
  Route,
  ScrollText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  Terminal,
  Users,
  Waypoints,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Canonical icon registry for every docs surface — the sidebar plus the MDX
 * blocks that take an icon by name (`PathLink`). `icon:` frontmatter, meta.json
 * `icon` values, and MDX `icon` props all resolve against this one map: a name
 * missing here renders no icon, so every icon referenced by content must be
 * registered. Keeping a single registry is what stops the sidebar and the page
 * body from drifting onto different glyphs for the same idea.
 */
export const DOCS_ICONS: Record<string, LucideIcon> = {
  Activity,
  AppWindow,
  ArrowRightLeft,
  Award,
  BadgeCheck,
  Bell,
  Book,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Clock,
  Compass,
  Database,
  FileCode,
  FileText,
  FlaskConical,
  Folder,
  FolderTree,
  Gauge,
  Key,
  Layers,
  LifeBuoy,
  List,
  Mail,
  MessageSquare,
  Network,
  Package,
  Play,
  Plug,
  Puzzle,
  Repeat,
  Rocket,
  Route,
  ScrollText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  Terminal,
  Users,
  Waypoints,
  Workflow,
  Wrench,
  Zap,
};

/**
 * OpenAPI tag slug → DOCS_ICONS name, written into generated api-reference
 * frontmatter. Tags sharing a concept with a CompozyOS sidebar section reuse
 * that section's glyph (marketplace=Store, loops=Repeat, tools=Plug, …) so the
 * same idea reads the same across tabs. Every tag used by openapi/compozy.json
 * must have an entry — enforced by runtime-api-reference.test.ts.
 */
export const API_TAG_ICONS: Record<string, string> = {
  agent: "MessageSquare",
  agents: "FileText",
  automation: "Activity",
  bridges: "Layers",
  bundles: "Package",
  daemon: "Activity",
  diagnostics: "Gauge",
  extensions: "Puzzle",
  filesystem: "Folder",
  hooks: "Waypoints",
  logs: "ScrollText",
  loops: "Repeat",
  marketplace: "Store",
  memory: "Brain",
  network: "Network",
  notifications: "Bell",
  observe: "Compass",
  onboarding: "Rocket",
  openai: "Sparkles",
  providers: "Bot",
  resources: "Database",
  roles: "Users",
  sessions: "Send",
  settings: "Settings",
  skills: "FileCode",
  support: "LifeBuoy",
  tasks: "Workflow",
  tools: "Plug",
  toolsets: "Boxes",
  vault: "Key",
  workspaces: "FolderTree",
};
