import {
  Activity,
  Award,
  Bell,
  Book,
  Bot,
  Boxes,
  Brain,
  Compass,
  Database,
  FileCode,
  FileText,
  Folder,
  FolderTree,
  Gauge,
  Key,
  Layers,
  LifeBuoy,
  MessageSquare,
  Network,
  Package,
  Plug,
  Repeat,
  Rocket,
  Route,
  ScrollText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  Terminal,
  Users,
  Waypoints,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Canonical icon registry for the docs sidebar. `icon:` frontmatter and
 * meta.json `icon` values resolve against this map — a name missing here
 * renders no icon, so every icon referenced by content must be registered.
 */
export const DOCS_ICONS: Record<string, LucideIcon> = {
  Activity,
  Award,
  Bell,
  Book,
  Bot,
  Boxes,
  Brain,
  Compass,
  Database,
  FileCode,
  FileText,
  Folder,
  FolderTree,
  Gauge,
  Key,
  Layers,
  LifeBuoy,
  MessageSquare,
  Network,
  Package,
  Plug,
  Repeat,
  Rocket,
  Route,
  ScrollText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  Terminal,
  Users,
  Waypoints,
  Workflow,
  Zap,
};

/**
 * OpenAPI tag slug → DOCS_ICONS name, written into generated api-reference
 * frontmatter. Tags sharing a concept with a CompozyOS sidebar section reuse
 * that section's glyph (marketplace=Store, loops=Repeat, tools=Plug, …) so the
 * same idea reads the same across tabs. Every tag used by openapi/compozy.json
 * must have an entry — enforced by runtime-api-reference.test.ts.
 */
export const API_TAG_ICONS: Record<string, string> = {
  agent: "MessageSquare",
  agents: "FileText",
  automation: "Activity",
  bridges: "Layers",
  bundles: "Package",
  daemon: "Activity",
  diagnostics: "Gauge",
  extensions: "Plug",
  filesystem: "Folder",
  hooks: "Waypoints",
  logs: "ScrollText",
  loops: "Repeat",
  marketplace: "Store",
  memory: "Brain",
  network: "Network",
  notifications: "Bell",
  observe: "Compass",
  onboarding: "Rocket",
  openai: "Sparkles",
  providers: "Bot",
  resources: "Database",
  roles: "Users",
  sessions: "Send",
  settings: "Settings",
  skills: "FileCode",
  support: "LifeBuoy",
  tasks: "Workflow",
  tools: "Plug",
  toolsets: "Boxes",
  vault: "Key",
  workspaces: "FolderTree",
};
