id: quotes

config:
  input:
    type: object
    properties:
      to_language:
        type: string
        description: The language to translate to

tasks:
  - $ref: ./tasks/get_quote.yaml
    on_success:
      next: translate_quote

  - $ref: ./tasks/translate_quote.yaml
    with:
      quote: "{{ .tasks.get_quote.output.quote }}"
    on_success:
      next: save_results

  - id: save_results
    type: basic
    executor:
      type: tool
      $ref: ./tools/save_data.yaml
    with:
      message: "{{ .tasks.translate_quote.output.message }}"
    final: true
