FROM golang:1.25 as build
WORKDIR /src
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH:-amd64} go build -ldflags "-s -w" -o /out/compozy ./

FROM gcr.io/distroless/static:nonroot
USER nonroot
COPY --from=build /out/compozy /usr/local/bin/compozy
ENTRYPOINT ["/usr/local/bin/compozy"]

