import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  ChevronLeft,
  ChevronRight,
  Clock3,
  Columns2,
  Combine,
  Command as CommandGlyph,
  Cpu,
  Folder,
  History,
  Home,
  Keyboard,
  KeyRound,
  LayoutGrid,
  List,
  ListChecks,
  Maximize2,
  MinusSquare,
  Monitor,
  Network,
  NotebookPen,
  Palette,
  PanelLeft,
  PanelsTopLeft,
  PanelTop,
  PictureInPicture,
  Pin,
  PinOff,
  Plus,
  Puzzle,
  Radio,
  RedoDot,
  Repeat2,
  RotateCcw,
  Route,
  Scale,
  Settings,
  SlidersHorizontal,
  SquareStack,
  SquareTerminal,
  Store,
  TextCursorInput,
  Trash2,
  UndoDot,
  Waypoints,
  Webhook,
  Wrench,
  XSquare,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Lucide tokens the daemon serves on command descriptors → the glyph that
 * renders them.
 *
 * Icons cross the wire as tokens, never as code (BR-2), so this is the client's
 * half of that contract. An unlisted token falls back rather than breaking the
 * row: extensions may ship any lucide name, and a missing glyph must never cost
 * the operator the command.
 */
export const CMD_PALETTE_ICON_FALLBACK: LucideIcon = CommandGlyph;

export const cmdPaletteIconRegistry: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  bell: Bell,
  "book-open": BookOpen,
  bot: Bot,
  boxes: Boxes,
  brain: Brain,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "clock-3": Clock3,
  "columns-2": Columns2,
  combine: Combine,
  command: CommandGlyph,
  cpu: Cpu,
  folder: Folder,
  globe: Network,
  history: History,
  home: Home,
  keyboard: Keyboard,
  "key-round": KeyRound,
  "layout-grid": LayoutGrid,
  list: List,
  "list-checks": ListChecks,
  "maximize-2": Maximize2,
  "minus-square": MinusSquare,
  monitor: Monitor,
  network: Network,
  "notebook-pen": NotebookPen,
  palette: Palette,
  "panel-left": PanelLeft,
  "panel-top": PanelTop,
  "panels-top-left": PanelsTopLeft,
  "picture-in-picture": PictureInPicture,
  pin: Pin,
  "pin-off": PinOff,
  plus: Plus,
  puzzle: Puzzle,
  radio: Radio,
  "redo-2": RedoDot,
  "repeat-2": Repeat2,
  "rotate-ccw": RotateCcw,
  route: Route,
  scale: Scale,
  settings: Settings,
  "sliders-horizontal": SlidersHorizontal,
  "square-stack": SquareStack,
  "square-terminal": SquareTerminal,
  store: Store,
  "text-cursor-input": TextCursorInput,
  "trash-2": Trash2,
  "undo-2": UndoDot,
  waypoints: Waypoints,
  webhook: Webhook,
  wrench: Wrench,
  "x-square": XSquare,
  zap: Zap,
};

/**
 * A descriptor may carry a single emoji grapheme instead of a token. Anything
 * outside the ASCII token grammar is treated as that grapheme.
 */
export function isEmojiIcon(icon: string): boolean {
  const trimmed = icon.trim();
  return trimmed !== "" && !/^[a-z0-9-]+$/u.test(trimmed);
}
