package daemon

import (
	core "github.com/compozy/agh/internal/api/core"
	"github.com/compozy/agh/internal/api/httpapi"
	"github.com/compozy/agh/internal/api/udsapi"
	workspacepkg "github.com/compozy/agh/internal/workspace"
)

func httpServerOptions(deps *RuntimeDeps) []httpapi.Option {
	return []httpapi.Option{
		httpapi.WithHomePaths(deps.HomePaths),
		httpapi.WithConfig(&deps.Config),
		httpapi.WithLogger(deps.Logger),
		httpapi.WithStartedAt(deps.StartedAt),
		httpapi.WithSessionManager(deps.Sessions),
		httpapi.WithDaemonDrainController(deps.DrainController),
		httpapi.WithSessionCatalog(deps.Registry),
		httpapi.WithTaskService(deps.Tasks),
		httpapi.WithNetworkService(deps.Network),
		httpapi.WithNetworkStore(deps.Registry),
		httpapi.WithNetworkUsageStore(deps.Registry),
		httpapi.WithCoordinationService(workspacepkg.NewCoordinationService(deps.Registry)),
		httpapi.WithOnboardingStore(deps.Registry),
		httpapi.WithObserver(deps.Observer),
		httpapi.WithSchemaStreamStatusReader(deps.SchemaStreams),
		httpapi.WithAutomation(deps.Automation),
		httpapi.WithLoopService(deps.Loops),
		httpapi.WithBridgeService(deps.Bridges),
		httpapi.WithNotificationPresetService(notificationPresetServiceFromDeps(deps)),
		httpapi.WithBundleService(deps.Bundles),
		httpapi.WithToolRegistry(deps.ToolRegistry),
		httpapi.WithToolsetRegistry(deps.Toolsets),
		httpapi.WithToolArtifactStore(deps.ToolArtifacts),
		httpapi.WithToolApprovalIssuer(deps.ToolApprovals),
		httpapi.WithToolApprovalGrantService(deps.ApprovalGrants),
		httpapi.WithClarifyBroker(deps.Clarify),
		httpapi.WithSettingsService(deps.Settings),
		httpapi.WithSettingsRestartController(deps.SettingsRestart),
		httpapi.WithSettingsUpdateController(deps.SettingsUpdate),
		httpapi.WithSupportBundleService(deps.SupportBundles),
		httpapi.WithVaultService(deps.Vault),
		httpapi.WithResourceService(deps.Resources),
		httpapi.WithWorkspaceResolver(deps.WorkspaceService),
		httpapi.WithWindowManagerService(deps.WindowManager),
		httpapi.WithAgentCatalog(deps.AgentCatalog),
		httpapi.WithAgentDefinitionSync(deps.AgentDefinitionSync),
		httpapi.WithAgentHistoryPurgers(deps.SoulHistoryPurger, deps.HeartbeatPurger),
		httpapi.WithModelCatalogService(deps.ModelCatalog),
		httpapi.WithMarketplaceCatalogService(deps.MarketplaceCatalog),
		httpapi.WithAgentContext(deps.AgentContext),
		httpapi.WithCoordinatorRole(deps.CoordinatorRole),
		httpapi.WithRolesStatusProvider(deps.Roles),
		httpapi.WithSoulAuthoring(deps.SoulAuthoring),
		httpapi.WithSoulRefresher(deps.SoulRefresher),
		httpapi.WithHeartbeatAuthoring(deps.HeartbeatAuthor),
		httpapi.WithHeartbeatStatus(deps.HeartbeatStatus),
		httpapi.WithHeartbeatWake(deps.HeartbeatWake),
		httpapi.WithSessionHealthReader(deps.SessionHealth),
		httpapi.WithHeartbeatWakeEventReader(deps.WakeEvents),
		httpapi.WithSkillsRegistry(deps.SkillsRegistry),
		httpapi.WithSkillResourceSyncer(deps.SkillResources),
		httpapi.WithMemoryStore(deps.MemoryStore),
		httpapi.WithDreamTrigger(deps.DreamTrigger),
		httpapi.WithMemoryExtractorService(deps.MemoryExtractor),
		httpapi.WithMemoryProviderService(deps.MemoryProviders),
		httpapi.WithMemorySessionLedgerService(deps.MemorySessionLedger),
		httpapi.WithRuntimeMemorySnapshotSource(deps.RuntimeMemory),
		httpapi.WithDeadEntitySource(deps.DeadEntities),
		httpapi.WithExtensionService(deps.Extensions),
	}
}

func notificationPresetServiceFromDeps(deps *RuntimeDeps) core.NotificationPresetService {
	if deps == nil {
		return nil
	}
	return deps.Notifications
}

func udsServerOptions(deps *RuntimeDeps) []udsapi.Option {
	return []udsapi.Option{
		udsapi.WithHomePaths(deps.HomePaths),
		udsapi.WithConfig(&deps.Config),
		udsapi.WithLogger(deps.Logger),
		udsapi.WithStartedAt(deps.StartedAt),
		udsapi.WithSessionManager(deps.Sessions),
		udsapi.WithDaemonDrainController(deps.DrainController),
		udsapi.WithSessionCatalog(deps.Registry),
		udsapi.WithTaskService(deps.Tasks),
		udsapi.WithNetworkService(deps.Network),
		udsapi.WithNetworkStore(deps.Registry),
		udsapi.WithNetworkUsageStore(deps.Registry),
		udsapi.WithCoordinationService(workspacepkg.NewCoordinationService(deps.Registry)),
		udsapi.WithOnboardingStore(deps.Registry),
		udsapi.WithObserver(deps.Observer),
		udsapi.WithSchemaStreamStatusReader(deps.SchemaStreams),
		udsapi.WithAutomation(deps.Automation),
		udsapi.WithLoopService(deps.Loops),
		udsapi.WithBridgeService(deps.Bridges),
		udsapi.WithNotificationPresetService(notificationPresetServiceFromDeps(deps)),
		udsapi.WithBundleService(deps.Bundles),
		udsapi.WithToolRegistry(deps.ToolRegistry),
		udsapi.WithToolsetRegistry(deps.Toolsets),
		udsapi.WithToolArtifactStore(deps.ToolArtifacts),
		udsapi.WithToolApprovalIssuer(deps.ToolApprovals),
		udsapi.WithToolApprovalGrantService(deps.ApprovalGrants),
		udsapi.WithClarifyBroker(deps.Clarify),
		udsapi.WithSettingsService(deps.Settings),
		udsapi.WithSettingsRestartController(deps.SettingsRestart),
		udsapi.WithSettingsUpdateController(deps.SettingsUpdate),
		udsapi.WithSupportBundleService(deps.SupportBundles),
		udsapi.WithVaultService(deps.Vault),
		udsapi.WithResourceService(deps.Resources),
		udsapi.WithWorkspaceResolver(deps.WorkspaceService),
		udsapi.WithWindowManagerService(deps.WindowManager),
		udsapi.WithAgentCatalog(deps.AgentCatalog),
		udsapi.WithAgentDefinitionSync(deps.AgentDefinitionSync),
		udsapi.WithAgentHistoryPurgers(deps.SoulHistoryPurger, deps.HeartbeatPurger),
		udsapi.WithModelCatalogService(deps.ModelCatalog),
		udsapi.WithMarketplaceCatalogService(deps.MarketplaceCatalog),
		udsapi.WithAgentContext(deps.AgentContext),
		udsapi.WithSoulAuthoring(deps.SoulAuthoring),
		udsapi.WithSoulRefresher(deps.SoulRefresher),
		udsapi.WithHeartbeatAuthoring(deps.HeartbeatAuthor),
		udsapi.WithHeartbeatStatus(deps.HeartbeatStatus),
		udsapi.WithHeartbeatWake(deps.HeartbeatWake),
		udsapi.WithSessionHealthReader(deps.SessionHealth),
		udsapi.WithHeartbeatWakeEventReader(deps.WakeEvents),
		udsapi.WithCoordinatorRole(deps.CoordinatorRole),
		udsapi.WithRolesStatusProvider(deps.Roles),
		udsapi.WithSkillsRegistry(deps.SkillsRegistry),
		udsapi.WithSkillResourceSyncer(deps.SkillResources),
		udsapi.WithMemoryStore(deps.MemoryStore),
		udsapi.WithDreamTrigger(deps.DreamTrigger),
		udsapi.WithMemoryExtractorService(deps.MemoryExtractor),
		udsapi.WithMemoryProviderService(deps.MemoryProviders),
		udsapi.WithMemorySessionLedgerService(deps.MemorySessionLedger),
		udsapi.WithRuntimeMemorySnapshotSource(deps.RuntimeMemory),
		udsapi.WithDeadEntitySource(deps.DeadEntities),
		udsapi.WithExtensionService(deps.Extensions),
		udsapi.WithHostedMCP(deps.HostedMCP),
		udsapi.WithMCPHostAPI(deps.MCPHostAPI),
	}
}
