name: Code Quality & Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.25.1"
  CGO_ENABLED: 1

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go with caching
        uses: ./.github/actions/setup-go
        with:
          go-version: ${{ env.GO_VERSION }}
          install-tools: "true"

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup git-cliff for release tests
        uses: ./.github/actions/setup-git-cliff

      - name: Validate Codecov config
        run: |
          curl -X POST --data-binary @codecov.yml https://codecov.io/validate || echo "Codecov validation failed, continuing..."

      - name: Run tests with coverage
        run: |
          make test-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          override_branch: ${{ github.head_ref || github.ref_name }}
          override_commit: ${{ github.event.pull_request.head.sha || github.sha }}
          env_vars: OS,GO_VERSION
        env:
          OS: ${{ runner.os }}
          GO_VERSION: ${{ env.GO_VERSION }}
