name: Code Quality & Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CGO_ENABLED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go with caching
        uses: ./.github/actions/setup-go
        with:
          go-version: "1.24.x"
          install-tools: "true"

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Validate Codecov config
        run: |
          curl -X POST --data-binary @codecov.yml https://codecov.io/validate || echo "Codecov validation failed, continuing..."

      - name: Run tests with coverage
        run: |
          make test-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          override_branch: ${{ github.head_ref || github.ref_name }}
          override_commit: ${{ github.event.pull_request.head.sha || github.sha }}
          env_vars: OS,GO_VERSION
        env:
          OS: ${{ runner.os }}
          GO_VERSION: "1.24.x"

      - name: Coverage Badge
        uses: tj-actions/coverage-badge-go@v2
        if: github.ref == 'refs/heads/main'
        with:
          filename: coverage.out

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: README.md

      - name: Commit changes
        if: steps.verify-changed-files.outputs.files_changed == 'true' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: update coverage badge"

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true' && github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go with caching
        uses: ./.github/actions/setup-go
        with:
          go-version: "1.24.x"
          install-tools: "true"

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Run quality checks
        run: |-
          # Static analysis
          make lint

          # Cyclomatic complexity check
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          gocyclo -over 15 . || echo "High complexity detected"

          # Dead code detection
          go install golang.org/x/tools/cmd/deadcode@latest
          deadcode ./... || echo "Dead code detected"
