import { storyAgentNames, storySessionIds } from "./fintech-scenario";
import type { RouteStoryRegistryEntry } from "./route-story-types";

const storyTaskId = "task_001";
const storyTaskRunId = "run_001";
const storyLoopName = "implement-tasks";
const storyLoopRunId = "looprun_running";
const storyLoopDiffRunId = "looprun_release_train";

export const appRouteStories = [
  {
    system: "design-system",
    routePath: "/design-system",
    storybookPath: "/design-system",
    title: "systems/design-system/routes/DesignSystem",
    storyName: "Default",
  },
  {
    system: "runtime",
    routePath: "/",
    storybookPath: "/",
    title: "systems/runtime/routes/Home",
    storyName: "Default",
  },
  {
    system: "vault",
    routePath: "/vault",
    storybookPath: "/vault",
    title: "systems/vault/routes/Vault",
    storyName: "Default",
  },
  {
    system: "marketplace",
    routePath: "/marketplace",
    storybookPath: "/marketplace",
    title: "systems/marketplace/routes/Marketplace",
    storyName: "Default",
  },
  {
    system: "marketplace",
    routePath: "/marketplace/",
    storybookPath: "/marketplace/",
    title: "systems/marketplace/routes/Marketplace",
    storyName: "Default",
  },
  {
    system: "marketplace",
    routePath: "/marketplace/installed",
    storybookPath: "/marketplace/installed",
    title: "systems/marketplace/routes/Marketplace",
    storyName: "Installed",
  },
  {
    system: "marketplace",
    routePath: "/marketplace/$entryId",
    storybookPath: "/marketplace/slack-notify",
    title: "systems/marketplace/routes/MarketplaceDetail",
    storyName: "DetailExtensionBrowse",
  },
  {
    system: "tasks",
    routePath: "/tasks",
    storybookPath: "/tasks",
    title: "systems/tasks/routes/Tasks",
    storyName: "DefaultList",
  },
  {
    system: "loops",
    routePath: "/loops",
    storybookPath: "/loops",
    title: "systems/loops/routes/Loops",
    storyName: "Catalog",
  },
  {
    system: "loops",
    routePath: "/loop-runs",
    storybookPath: "/loop-runs",
    title: "systems/loops/routes/LoopRuns",
    storyName: "RunsList",
  },
  {
    system: "automation",
    routePath: "/automations",
    storybookPath: "/automations",
    title: "systems/automation/routes/Automations",
    storyName: "Default",
  },
  {
    system: "automation",
    routePath: "/automations/jobs/$jobId",
    storybookPath: "/automations/jobs/job_launch_command_digest",
    title: "systems/automation/routes/AutomationDetail",
    storyName: "JobDetail",
  },
  {
    system: "automation",
    routePath: "/automations/triggers/$triggerId",
    storybookPath: "/automations/triggers/trg_summarize_failures",
    title: "systems/automation/routes/AutomationDetail",
    storyName: "TriggerDetail",
  },
  // Shim: the four legacy redirect stories go with the `/jobs*` and `/triggers*` stubs in v0.5.0.
  {
    system: "automation",
    routePath: "/jobs",
    storybookPath: "/jobs?enabled=true",
    title: "systems/automation/routes/Automations",
    storyName: "LegacyJobsRedirect",
  },
  {
    system: "automation",
    routePath: "/jobs/$jobId",
    storybookPath: "/jobs/morning-digest",
    title: "systems/automation/routes/Automations",
    storyName: "LegacyJobDetailRedirect",
  },
  {
    system: "automation",
    routePath: "/triggers",
    storybookPath: "/triggers?event=session.stopped",
    title: "systems/automation/routes/Automations",
    storyName: "LegacyTriggersRedirect",
  },
  {
    system: "automation",
    routePath: "/triggers/$triggerId",
    storybookPath: "/triggers/rerun-delivery",
    title: "systems/automation/routes/Automations",
    storyName: "LegacyTriggerDetailRedirect",
  },
  {
    system: "tasks",
    routePath: "/tasks/new",
    storybookPath: "/tasks/new",
    title: "systems/tasks/routes/TaskCreate",
    storyName: "Default",
  },
  {
    system: "tasks",
    routePath: "/tasks/$id",
    storybookPath: `/tasks/${storyTaskId}`,
    title: "systems/tasks/routes/TaskDetail",
    storyName: "Overview",
  },
  {
    system: "session",
    routePath: "/session/$id",
    storybookPath: `/session/${storySessionIds.frontend}`,
    title: "systems/session/routes/SessionPermalink",
    storyName: "RedirectsToCanonicalSession",
  },
  {
    system: "loops",
    routePath: "/loops/$name",
    storybookPath: `/loops/${storyLoopName}`,
    title: "systems/loops/routes/Loops",
    storyName: "Detail",
  },
  {
    system: "loops",
    routePath: "/loop-runs/$runId",
    storybookPath: `/loop-runs/${storyLoopRunId}`,
    title: "systems/loops/routes/LoopRuns",
    storyName: "RunDetail",
  },
  {
    system: "loops",
    routePath: "/loop-runs/$runId/diff",
    storybookPath: `/loop-runs/${storyLoopDiffRunId}/diff`,
    title: "systems/loops/routes/LoopRuns",
    storyName: "Diff",
  },
  {
    system: "agent",
    routePath: "/agents",
    storybookPath: "/agents",
    title: "systems/agent/routes/AgentsFleet",
    storyName: "Loaded",
  },
  {
    system: "agent",
    routePath: "/agents/",
    storybookPath: "/agents/",
    title: "systems/agent/routes/AgentsFleet",
    storyName: "Loaded",
  },
  {
    system: "agent",
    routePath: "/agents/$name",
    storybookPath: `/agents/${storyAgentNames.fraud}`,
    title: "systems/agent/routes/AgentDetail",
    storyName: "Default",
  },
  {
    system: "agent",
    routePath: "/agents/$name/",
    storybookPath: `/agents/${storyAgentNames.fraud}/`,
    title: "systems/agent/routes/AgentDetail",
    storyName: "Default",
  },
  {
    system: "agent",
    routePath: "/agents/$name/settings",
    storybookPath: `/agents/${storyAgentNames.fraud}/settings`,
    title: "systems/agent/routes/AgentSettings",
    storyName: "Basics",
  },
  {
    system: "tasks",
    routePath: "/tasks/$id/edit",
    storybookPath: `/tasks/${storyTaskId}/edit`,
    title: "systems/tasks/routes/TaskEdit",
    storyName: "Default",
  },
  {
    system: "loops",
    routePath: "/loops/$name/run",
    storybookPath: `/loops/${storyLoopName}/run`,
    title: "systems/loops/routes/Loops",
    storyName: "RunForm",
  },
  {
    system: "loops",
    routePath: "/loops/$name/editor",
    storybookPath: `/loops/${storyLoopName}/editor`,
    title: "systems/loops/routes/Loops",
    storyName: "Editor",
  },
  {
    system: "loops",
    routePath: "/loops/$name/configure",
    storybookPath: `/loops/${storyLoopName}/configure`,
    title: "systems/loops/routes/Loops",
    storyName: "Configure",
  },
  {
    system: "tasks",
    routePath: "/tasks/$id/runs/$runId",
    storybookPath: `/tasks/${storyTaskId}/runs/${storyTaskRunId}`,
    title: "systems/tasks/routes/TaskRunDetail",
    storyName: "Running",
  },
  {
    system: "session",
    routePath: "/agents/$name/sessions/$id",
    storybookPath: `/agents/${storyAgentNames.fraud}/sessions/${storySessionIds.fraud}`,
    title: "systems/session/routes/AgentSession",
    storyName: "Default",
  },
  {
    system: "session",
    routePath: "/sessions",
    storybookPath: "/sessions",
    title: "systems/session/routes/Sessions",
    storyName: "Default",
  },
  {
    system: "os",
    routePath: "/new-tab",
    storybookPath: "/new-tab",
    title: "systems/os/routes/NewTab",
    storyName: "Default",
  },
] as const satisfies RouteStoryRegistryEntry[];
