import type { RouteStoryRegistryEntry } from "./route-story-types";

export const settingsRouteStories = [
  {
    system: "settings",
    routePath: "/settings",
    storybookPath: "/settings",
    title: "systems/settings/routes/SettingsShell",
    storyName: "Shell",
  },
  {
    system: "settings",
    routePath: "/settings/",
    storybookPath: "/settings/",
    title: "systems/settings/routes/SettingsShell",
    storyName: "IndexRedirect",
  },
  {
    system: "settings",
    routePath: "/sandbox",
    storybookPath: "/sandbox",
    title: "systems/settings/routes/Sandbox",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/skills",
    storybookPath: "/settings/skills",
    title: "systems/settings/routes/SettingsSkills",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/providers",
    storybookPath: "/settings/providers",
    title: "systems/settings/routes/SettingsProviders",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/attention",
    storybookPath: "/settings/attention",
    title: "systems/settings/routes/SettingsAttention",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/observability",
    storybookPath: "/settings/observability",
    title: "systems/settings/routes/SettingsObservability",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/network",
    storybookPath: "/settings/network",
    title: "systems/settings/routes/SettingsNetwork",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/gateway",
    storybookPath: "/settings/gateway",
    title: "systems/settings/routes/SettingsGateway",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/memory",
    storybookPath: "/settings/memory",
    title: "systems/settings/routes/SettingsMemory",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/roles",
    storybookPath: "/settings/roles",
    title: "systems/settings/routes/SettingsRoles",
    storyName: "Populated",
  },
  {
    system: "settings",
    routePath: "/settings/hooks",
    storybookPath: "/settings/hooks",
    title: "systems/settings/routes/SettingsHooks",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/extensions",
    storybookPath: "/settings/extensions",
    title: "systems/settings/routes/SettingsExtensions",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/general",
    storybookPath: "/settings/general",
    title: "systems/settings/routes/SettingsGeneral",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/terminal",
    storybookPath: "/settings/terminal",
    title: "systems/settings/routes/SettingsTerminal",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/defaults",
    storybookPath: "/settings/defaults",
    title: "systems/settings/routes/SettingsDefaults",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/appearance",
    storybookPath: "/settings/appearance",
    title: "systems/settings/routes/SettingsAppearance",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/layouts",
    storybookPath: "/settings/layouts",
    title: "systems/settings/routes/SettingsLayouts",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/profiles",
    storybookPath: "/settings/profiles",
    title: "systems/settings/routes/SettingsProfiles",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/palette",
    storybookPath: "/settings/palette",
    title: "systems/settings/routes/SettingsPalette",
    storyName: "Default",
  },
  {
    system: "settings",
    routePath: "/settings/automation",
    storybookPath: "/settings/automation",
    title: "systems/settings/routes/SettingsAutomation",
    storyName: "Default",
  },
] as const satisfies RouteStoryRegistryEntry[];
