import type { ShortcutMap } from "@/systems/os";

/** Story-only daemon keymap used by Settings and the live shortcuts sheet. */
export const STORY_SHORTCUT_DEFAULTS: ShortcutMap = {
  "palette.open": ["meta+KeyK"],
  "palette.view.sessions": ["meta+shift+KeyK"],
  "session.new": ["meta+KeyN"],
  "scope.global.toggle": ["meta+shift+KeyG"],
  "window.nav.back": ["meta+alt+BracketLeft"],
  "sidebar.toggle": ["meta+KeyB"],
  "shortcuts.cheatsheet": ["meta+Slash"],
  "window.close": ["meta+KeyW"],
  "window.minimize": ["meta+KeyM"],
  "window.zoom": ["meta+shift+KeyM"],
  "window.toggle_floating": ["meta+shift+KeyF"],
  "window.focus.left": ["control+ArrowLeft", "alt+KeyH"],
  "window.focus.right": ["control+ArrowRight", "alt+KeyL"],
  "window.focus.up": ["control+ArrowUp", "alt+KeyK"],
  "window.focus.down": ["control+ArrowDown", "alt+KeyJ"],
  "window.focus.last": ["control+alt+KeyO"],
  "window.tile.left": ["control+alt+ArrowLeft"],
  "window.tile.right": ["control+alt+ArrowRight"],
  "window.tile.bottom-left": ["control+alt+shift+KeyJ"],
  "window.tile.bottom-right": ["control+alt+shift+KeyK"],
  "window.tab.new": ["meta+KeyT"],
  "window.tab.next": ["control+Tab", "meta+BracketRight"],
  "window.tab.previous": ["control+shift+Tab", "meta+BracketLeft"],
  "window.tab.last": ["meta+Digit9"],
  "window.tab.reopen": ["meta+shift+KeyT"],
  "window.tab.jump.1": ["meta+Digit1"],
  "window.tab.jump.2": ["meta+Digit2"],
  "window.tab.jump.3": ["meta+Digit3"],
  "window.tab.jump.4": ["meta+Digit4"],
  "window.tab.jump.5": ["meta+Digit5"],
  "window.tab.jump.6": ["meta+Digit6"],
  "window.tab.jump.7": ["meta+Digit7"],
  "window.tab.jump.8": ["meta+Digit8"],
  "session.cycle.previous": ["control+shift+ArrowUp"],
  "session.cycle.next": ["control+shift+ArrowDown"],
  "session.focus.attention": ["control+alt+KeyA"],
  "desktop.switch.previous": ["control+BracketLeft"],
  "desktop.switch.next": ["control+BracketRight"],
  "desktop.create": ["meta+shift+KeyN"],
  "desktop.overview": ["control+shift+KeyO"],
  "desktop.switch.1": ["control+Digit1"],
  "desktop.switch.2": ["control+Digit2"],
  "desktop.switch.3": ["control+Digit3"],
  "desktop.switch.4": ["control+Digit4"],
  "desktop.switch.5": ["control+Digit5"],
  "desktop.switch.6": ["control+Digit6"],
  "desktop.switch.7": ["control+Digit7"],
  "desktop.switch.8": ["control+Digit8"],
  "desktop.switch.9": ["control+Digit9"],
  "workspace.picker": ["meta+shift+KeyO"],
  "workspace.cycle.previous": ["meta+shift+BracketLeft"],
  "workspace.cycle.next": ["meta+shift+BracketRight"],
  "layout.arrange.two-up": ["control+alt+KeyU"],
  "layout.arrange.grid": ["control+alt+KeyG"],
  "layout.balance": ["control+alt+KeyB"],
  "layout.undo": ["meta+KeyZ"],
  "layout.redo": ["meta+shift+KeyZ"],
};

export const STORY_SHORTCUT_DIAGNOSTIC_OVERRIDES: ShortcutMap = {
  "window.tab.new": ["meta+Digit3"],
  "window.tab.jump.4": ["alt+Digit4"],
  "sidebar.toggle": ["meta+KeyB"],
};

export const STORY_SHORTCUT_REBOUND_OVERRIDES: ShortcutMap = {
  "palette.open": ["meta+shift+KeyP"],
  "session.focus.attention": ["meta+shift+KeyA"],
  "window.tab.jump.4": ["alt+Digit4"],
};
